<?php
define('ttAccountActivation' , "Kontoaktivierung");
define('ttActive' , "Aktiv");
define('ttActivate' , "Aktivieren");
define('ttAdd' , "Hinzufügen");
define('ttAddSelectedStudents' , "Ausgewählte Studenten hinzufügen");
define('ttAdministration' , "Administration");
define('ttAdministrator' , "Administrator");
define('ttAdminWelcome' , "Willkommen zur Administrationsoberfläche.<br/>Dieses System beinhaltet:");
define('ttAlias' , "ISO 639-1 Code");
define('ttAndExit' , "und schliessen");
define('ttAnswer' , "Antwort");
define('ttAnswers' , "Antworten");
define('ttArchive' , "Archivieren");
define('ttArchived' , "Archiviert");
define('ttAssignSubject' , "Subject zuordnen");
define('ttAutomatic' , "Automatisch");
define('ttAImportComplete' , "Fragen-Import wurde erfolgreich abgeschlossen");
define('ttBasedOn' , "Basiert auf");
define('ttBlocked' , "Geblockt");
define('ttBlock' , "Blocken");
define('ttUnblock' , "Blockierung aufheben");
define('ttBonus' , "Bonus");
define('ttCancel' , "Abbrechen");
define('ttChangeLanguage' , "Sprache ändern");
define('ttChangeVersion' , "Test Version ändern");
define('ttCheck' , "Testen...");
define('ttClose' , "Schliessen");
define('ttClosed' , "Geschlossen");
define('ttCorrect' , "Korrekt");
define('ttConfiguration' , "Konfiguration");
define('ttConfirm' , "Bestätigen");
define('ttConfirmEmail' , "Email bestätigen");
define('ttConfirmPassword' , "Passwort bestätigen");
define('ttCreate' , "Anlegen");
define('ttCArchiveExam' , "Wollen sie das Exam archivieren?<br/>Alle gestarteten Tests können nicht mehr beendet werden and all questions to correct of already submitted tests sum total of 0 points.<br/>Die Operation kann nicht rückgängig gemacht werden! Fortsetzen?");
define('ttCBlockTest' , "Wollen sie diesen Test wirklich blockieren?");
define('ttCChangeStatus' , "Wollen sie den Status der Frage wirklich ändern auf _STATUS_?");
define('ttCConfirmTest' , "Wollen sie das Testergebnis bestätigen?<br/>Dieser Test wird archiviert!<br/>Fortsetzen?");
define('ttCDeleteAnswer' , "Wollen sie diese Antwort und ihre Übersetzungen wirklich löschen?<br/>Dieser Schritt kann nicht rückgängig gemacht werden!<br/>Fortsetzen?");
define('ttCDeleteExam' , "Wollen sie dieses Exam wirklich löschen?<br/>Alle laufenden, beendeten und archivierten Tests werden gelöscht.<br/>Dieser Schritt kann nicht rückgängig gemacht werden!<br/>Fortsetzen?");
define('ttCDeleteQuestion' , "Wollen sie diese Frage und deren Übersetzungen löschen?<br/>Dieser Schritt kann nicht rückgängig gemacht werden!<br/>Fortsetzen?");
define('ttCDeleteRoom' , "Wollen sie diesen Raum löschen?<br/>Dieser Schritt kann nicht rückgängig gemacht werden!<br/>Fortsetzen?");
define('ttCDeleteSubject' , "Wollen sie dieses Subjekt löschen?<br/>Die folgenden Elemente werden PERMANENT entfernt:<br/> - Subjekt<br/> - Alle Kapitel<br/> - Alle Fragen und Antworten mit ihren Übersetzungen<br/> - Alle Einstellungen<br/> - Alle aktiven und archivierten Exams und Tests<br/>Dieser Schritt kann nicht rückgängig gemacht werden! Fortsetzen?");
define('ttCDeleteSettings' , "Wollen sie diese Test-Einstellungen löschen? Dieser Schritt kann nicht rückgängig gemacht werden.<br/>Fortsetzen?");
define('ttCDeleteTopic' , "Wollen sie dieses Kapitel löschen?<br/>Die folgenden Elemente werden PEMANENT entfernt:<br/> - Kapitel<br/> - Alle Fragen mit ihren Übersetzungen<br/> - Alle Antworten mit ihren Übersetzungen<br/>Dieser Schritt kann nicht rückgängig gemacht werden! Fortsetzen?");
define('ttCDiscardEdits' , "Ihre Änderungen gehen verloren.<br/>Exit?");
define('ttCDiscardNew' , "Das erzeugte Element geht verloren.<br/>Exit?");
define('ttCRegister' , "Wollen sie sich wirklich zu diesem Exam registrieren?");
define('ttCRegisterStudents' , "Wollen sie die ausgewählten Studierenden wirklich für das Exam registrieren?");
define('ttCRenewPassword' , "Das Passwort des Exams wird geändert.<br/>Dieser Schritt kann nicht rückgängig gemacht werden.<br/>Fortsetzen?");
define('ttCStartExam' , "Wollen sie das ausgewählte Exam aktivieren?");
define('ttCStartTest' , "Wollen sie das Exam nun starten?<br/>Ein Exam Passwort wird benötigt.");
define('ttCStopExam' , "Wollen sie das ausgewählte Exam deaktivieren?");
define('ttCSubmitTest' , "Wollen sie den Test absenden?<br/>Dieser Schritt kann nicht rückgängig gemacht werden!<br/>Fortsetzen?");
define('ttCTest' , "Das Passwort ist richtig. Ihr Test ist nun vorbereitet und startet nach dem Klick!");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Wollen sie die Blockade des Tests aufheben?");
define('ttCUpdateConfigurations' , "Wollen sie die neuen Systemeinstellungen speichern?");
define('ttCUpdateLanguage' , "Wollen sie die Spach-Dateien aktualisieren?<br/>Dieser Schritt kann nicht rückgängig gemacht werden. Fortsetzen?");
define('ttD1' , "Einfach");
define('ttD2' , "Mittel");
define('ttD3' , "Schwer");
define('ttDatabaseConfiguration' , "Datenbank Einstellungen");
define('ttDay' , "Tag");
define('ttDelete' , "Löschen");
define('ttDescription' , "Beschreibung");
define('ttDifficulty' , "Schwierigkeitsgrad");
define('ttDifficultyQuestions' , "Fragen pro Schwierigkeitsgrad");
define('ttDistribution' , "Verteilung");
define('ttDo' , "Exam durchführen");
define('ttDTAnswerInfo' , "Zeige _TOTAL_ Antworten");
define('ttDTAnswerFiltered' , "(gefiltert von _MAX_ Antworten insgesamt)");
define('ttDTAnswerEmpty' , "Keine Antworten vorhanden");
define('ttDTExamInfo' , "_TOTAL_ Exams im Laufen");
define('ttDTExamFiltered' , "(gefiltert von _MAX_ laufenden Exams insgesamt)");
define('ttDTExamEmpty' , "Keine Exams vorhanden");
define('ttDTQuestionInfo' , "Zeige _TOTAL_ Fragen");
define('ttDTQuestionFiltered' , "(gefiltert von _MAX_ Fragen insgesamt)");
define('ttDTQuestionEmpty' , "Keine Fragen vorhanden");
define('ttDTRegisteredStudentInfo' , "Zeige _TOTAL_ registrierte Studierende");
define('ttDTRegisteredStudentFiltered' , "(gefiltert von _MAX_ registerten Studierenden insgesamt)");
define('ttDTRegisteredStudentEmpty' , "Keine registrierten Studierenden vorhanden");
define('ttDTStudentsInfo' , "Zeige _TOTAL_ Studierende");
define('ttDTStudentsFiltered' , "(gefiltert von _MAX_ Studierenden insgesamt)");
define('ttDTStudentsEmpty' , "Keine Studenten vorhanden");
define('ttDTTestInfo' , "Zeige _TOTAL_ Tests");
define('ttDTTeacherInfo' , "Zeige _TOTAL_ Lehrer");
define('ttDTTeacherFiltered' , "(gefiltert von _MAX_ Lehrern insgesamt)");
define('ttDTTeacherEmpty' , "Kein Lehrer vorhanden");
define('ttDTTestFiltered' , "(gefiltert von _MAX_ Tests insgesamt)");
define('ttDTTestEmpty' , "Keine Tests vorhanden");
define('ttDone' , "Exam dürchgeführt");
define('ttDuration' , "Dauer");
define('ttEdit' , "Editieren");
define('ttEditableScore' , "Editable Score");
define('ttError' , "Fehler");
define('ttEmail' , "E-mail");
define('ttEnd' , "Ende");
define('ttEverywhere' , "Überall");
define('ttExam' , "Exam");
define('ttExams' , "Exams");
define('ttExit' , "Exit");
define('ttExport', "Export");
define('ttExtra' , "Extra");
define('ttExamsArchive' , "Archive");
define('ttExamsInProgress' , "Exams im laufen");
define('ttETeachers' , "Examinator");
define('ttErrorquestion' , "Report Fehler");
define('ttEActivationFails' , "Aktivierung fehlgeschlagen!");
define('ttEAlreadyRegistered' , "Der Studiernde ist bereits für dieses Exam registriert!");
define('ttEAnswerInSet' , "Dieser Schritt kann nicht abgeschlossen werden. Die Antwort wird in Tests verwendet!");
define('ttEAnswerNotFound' , "Antwort nicht gefunden");
define('ttEAnswers' , "Ein Problem mit den Antworten ist aufgetreten.<br/>Bitte kontaktieren die den Lehrer oder Administrator.");
define('ttEDatabase' , "Datenbank Fehler!");
define('ttEDates' , "Termine sind nicht richtig!");
define('ttEEditRoomAll' , "Der Raum 'All' kann nicht editiert werden!");
define('ttEEmailAlreadyRegistered' , "E-mail bereits registriert!");
define('ttEEmailNotRegistered' , "E-mail nicht registriert!");
define('ttEEmailNotValid' , "Die eingetippte email ist nicht gültig! Bitte geben sie eine korrekte E-mail-Adresse ein");
define('ttEEmailsNotMatch' , "Die beiden E-mail-Adressen stimmen nicht überein!");
define('ttEEmptyFields' , "Ein oder mehrere Felder sind leer!");
define('ttEExamArchived' , "Dieser Schritt kann nicht abgeschlossen werden. Das Exam ist bereits archiviert!");
define('ttEExamNotFound' , "Exam nicht gefunden!");
define('ttEExamNotStarted' , "Sie können das Exam nicht starten. Es ist noch nicht aktiv!");
define('ttEExamStarted' , "Dieser Schritt kann nicht abgeschlossen werden weil das Exam bereits gestartet ist!");
define('ttEExamWaiting' , "Dieser Schritt kann nicht abgeschlossen werden weil das Exam noch nie gestartet wurde!");
define('ttEExamsNotArchivedDeleteTopic' , "Dieser Schritt kann nicht abgeschlossen werden weil zumindest ein nicht archiviertes Exam Fragen aus diesem Kapitel beinhaltet!");
define('ttEExamsNotArchivedEditTestSettings' , "Dieser Schritt kann nicht abgeschlossen werden weil diese Einstellungen bei zumindest einem nicht archivierten Exam verwendet werden.<br/>Nur der Name und die Beschreibung werden aktualisiert. Fortsetzen?");
define('ttEExamsNotArchivedDeleteTestSettings' , "Dieser Schritt kann nicht abgeschlossen werden weil diese Einstellungen zumindest bei einem nicht archivierten Exam verwendet werden!");
define('ttEExport', "Die Exportanfrage wurde nicht gesendet!");
define('ttEIncorrectField' , "Ein oder mehrere Felder sind nicht korrekt!");
define('ttELogin' , "E-mail und/oder Passwort sind nicht korrekt!");
define('ttEMainLanguageEmpty' , "Subject's Hauptsprache kann nicht leer sein!");
define('ttEMandatoryQuestion' , "Dies ist eine verpflichtende Frage von '_TESTSETTING_' Test's Einstellung: sie können diese nicht löschen oder den Schwierigkeitsgrad ändern.");
define('ttENotAuthorized' , "Ihr Browser ist nicht authorisiert.<br/>Bitte kontaktieren sie den Lehrer oder den Administrator.");
define('ttENoStudentsToRegister' , "Keine Studierenden zu registrieren!");
define('ttENoTopicsForSubject' , "Kein Kapitel für dieses Subjekt!<br/>Um eine neue Frage anzulegen müssen sie zuerst zumindest ein Kapitel anlegen.");
define('ttEOldPasswordWrong' , "Das Passwort ist nicht korrekt!");
define('ttEPassword' , "Falsches Passwort!");
define('ttEPasswordShort' , "Das Passwort ist zu kurz. Es muss zumindest 8 Zeichen lang sein!");
define('ttEPasswordsNotMatch' , "Die beiden Passwörter stimmen nicht überein!");
define('ttEQuestAnswPicker' , "Error during questions and answers picking.<br/>Please contact your teacher!");
define('ttEQuestionInSet' , "Dieser Schritt kann nicht abgeschlossen werden. Die Frage wird in manchen Tests verwendet!");
define('ttEQuestionNotFound' , "Frage nicht gefunden!");
define('ttEQuestionType' , "Typ der Frage ist nicht korrekt!");
define('ttERegFailedQuestions' , "Registrierung fehlgeschlagen: zu wenige Fragen! Bitte kontaktieren sie den Lehrer.");
define('ttERoomAllDelete' , "Der Raum 'All' kann nicht gelöscht werden!");
define('ttERoomUsed' , "Dieser Schritt kann nicht abgeschlossen werden. Der Raum wird in manchen Exams verwendet!");
define('ttESaveBeforeNew' , "Vor dem Anlegen eines neuen Items speichern sie bitte das gerade erzeugte.");
define('ttESelectQuestionType' , "Sie müssen eine der verfügbaren Fragentypen auswählen!");
define('ttESelectSubject' , "Sie müssen einers der Subjekte auswählen!");
define('ttESelectTestSettings' , "Sie müssen eine Test-Einstellung auswählen!");
define('ttESetNotFound' , "Fragen-Set nicht gefunden!");
define('ttETestAlreadyArchived' , "Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde bereits korrigiert und archiviert!");
define('ttETestAlreadySubmitted' , "Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde bereits abgesendet und/oder archiviert.");
define('ttETestBlockedSubmitted' , "Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde geblockt or wurde bereits abgesendet!");
define('ttETestNotArchived' , "Dieser Schritt kann nicht abgeschlossen werden. Dieser Test wurde noch nicht archiviert!");
define('ttETestNotFound' , "Test nicht gefunden!");
define('ttETestsNotArchived' , "Einige Tests wurden nicht archiviert! Bitte korrigieren sie zuerst alle Tests.");
define('ttETestSettingDeleteQuestion' , "Dieser Schritt kann nicht abgeschlossen werden. Diese Frage ist verpflichtend in den folgenden Test-Einstellungens:");
define('ttETestSettingDeleteTopic' , "Dieser Schritt kann nicht abgeschlossen werden. Einige Fragen dieses Kapitels werden in den folgenden Test-Einstellungen verwendet:");
define('ttETimeExpired' , "Die verfügbare Zeit ist abgelaufen!");
define('ttETranslationExists' , "Die Übersetzung der gewählten Sprache existiert bereits!");
define('ttEUserNotFound' , "Benutzer nicht gefunden!");
define('ttEValues' , "Einige Werte sind nicht korrekt!");
define('ttFalse' , "Falsch");
define('ttFinalScore' , "Endgültiges Ergebnis");
define('ttGeneralInformations' , "Allgemeine Informationen");
define('ttHours' , "Stunden");
define('ttHome' , "Home");
define('ttHomepage' , "Startseite");
define('ttHost' , "Host");
define('ttHAnswPanel' , "Doppelklick um die ausgewählte Antwort zu bearbeiten");
define('ttHQuestLanguagesPanel' , "Klicken um die Ünersetzung<br/>der ausgewählten Frage anzuzeigen");
define('ttHQuestPanel' , "Einfacher Klick um die Frage auszuwählen und anzuzeigen, und Doppelklick um die Frage und Antworten zu bearbeiten. Doppelklick auf die Flagge um die Frage zu aktivieren oder deaktivieren");
define('ttHQuestPreviewPanel' , "Die Antworten mit orangem Hintergrund sind nicht in die gewählte Sprache übersetzt");
define('ttHQuestTopicPanel' , "Einfacher Klick um Fragen zu filtern und<br/>Doppelklick um das Kapitel zu bearbeiten");
define('ttInfo' , "Info");
define('ttIPEnd' , "IPv4 Ende");
define('ttIPStart' , "IPv4 Anfang");
define('ttInactive' , "Inaktiv");
define('ttImportQM' , "Import");
define('ttImport' , "Import QM");
define('ttImportComplete' , "Import der Fragen wurde erfolgreich abgeschlossen");
define('ttJoin' , "Beitreten");
define('ttLanguage' , "Sprache");
define('ttLanguages' , "Sprachen");
define('ttLogin' , "Login");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Erfolgreich eingeloggt!");
define('ttLogout' , "LOGOUT");
define('ttMailLostPassword' , "Um ihr Zugangspasswort zurückzusetzen klicken sie bitte auf folgenden Link:\n\n_LINK_\n\nWenn sie keine Rücksetzung des Passwortes angefordert haben ignorieren sie bitte diese email.");
define('ttMailCredentials' , "Lieber _USERNAME_,\nIhr Passwort für Konto _USEREMAIL_ wurde auf Ihre Anfrage zurückgesetzt\nDas LibreEOL Team.");
define('ttMailNewTeacher' , "Willkommen zu _SYSTEMNAME_.\nUm ihren Zugang zu aktivieren klicken sie bitte auf folgenden Link und setzen sie ihr Zugangspasswort:");
define('ttMainLanguage' , "Hauptsprache");
define('ttManage' , "Manage");
define('ttMandatory' , "Verpflichtend");
define('ttManual' , "Manual");
define('ttMinutes' , "Minuten");
define('ttMyExams' , "Meine Exams");
define('ttMySettings' , "Meine Einstellungen");
define('ttMySubjects' , "Wähle Subjekt");
define('ttMActivation' , "Passwort erfolgreich gesetzt.<br/>Sie werden nun zur Startseite weitergeleitet");
define('ttMAnswerDeleted' , "Antwort erfolgreich gelöscht");
define('ttMConfigurationsUpdated' , "System-Einstellungen erfolgreich aktualisiert");
define('ttMConfirm' , "Test erfolgreich bestätigt und archiviert");
define('ttMUserCreated' , "Benutzer angelegt: eine email mit einem Link zum Abschliessen ihrer Registrierung wurde ihnen zugesendet.<br/>Bitte kontrollieren sie auch ihren SPAM-Folder!");
define('ttMEdit' , "Änderungen erfolgreich gespeichert");
define('ttMExamArchived' , "Exam erfolgreich archiviert");
define('ttMExamDeleted' , "Exam erfolgreich gelöscht");
define('ttMExamStarted' , "Exam erfolgreich gestartet");
define('ttMExamStopped' , "Exam erfolgreich gestoppt");
define('ttMExportRequestSent',"Exportanfrage erfolgreich gesendet, überprüfen sie thre E-Mail");
define('ttMLanguageCreated' , "Übersetzung erfolgreich angelegt");
define('ttMLanguageSaved' , "Übersetzung erfolgreich gespeichert");
define('ttMLanguageUpdated' , "Übersetzung erfolgreich aktualisiert");
define('ttMNewAnswer' , "Antwort erfolgreich angelegt");
define('ttMNewQuestion' , "Frage erfolgreich angelegt");
define('ttMNewRoom' , "Raum erfolgreich angelegt");
define('ttMNewSettings' , "Test-Einstellungen erfolgreich angelegt");
define('ttMNewSubject' , "Sujekt erfolgreich angelegt");
define('ttMNewTopic' , "Kapitel erfolgreich angelegt");
define('ttMPasswordRenewed' , "Passwort des Exams erfolgreich neu erstellt");
define('ttMQuestionDeleted' , "Frage erfolgreich gelöscht");
define('ttMRegistration' , "Sie haben sich erfolgreich zu diesem Exam registriert");
define('ttMResetConfirmed' , "Request completed: eine Email wurde ihnen zugesendet um das Passwort neu zu setzen.<br/>Bitte kontrollieren sie auch ihren Spam-Ordner");
define('ttMRoomDeleted' , "Raum erfolgreich gelöscht");
define('ttMSelectLanguage' , "Wählen sie die Sprache welche sie bearbeiten möchten");
define('ttMSettingsDeleted' , "Test-Einstellungen erfolgreich gelöscht");
define('ttMStudentsRegistered' , "Studierenden erfolgreich zum Exam registriert");
define('ttMSubjectDeleted' , "Subjekt erfolgreich gelöscht");
define('ttMSubjectQuestions' , "Um Kapitel und Fragen zu bearbeiten wählen sie bitte ein Subjekt");
define('ttMSubjectSettings' , "Um Exam-Einstellungen zu bearbeiten wählen sie bitte ein Subjekt");
define('ttMTestBlocked' , "Test erfolgreich geblockt");
define('ttMTestSubmitted' , "Test erfolgreich abgesendet");
define('ttMTestUnblocked' , "Test erfolgreich freigeschalten");
define('ttMTopicDeleted' , "Kapitel erfolgreich gelöscht");
define('ttName' , "Name");
define('ttNumberError' , "Der Wert soll ein Integer oder eine Dezimalzahl sein (zB: 12.5)");
define('ttNegativeScores' , "Negative Wertung");
define('ttNew' , "Neu");
define('ttNext' , "Next");
define('ttNewAnswer' , "Neue Antwort");
define('ttNewCredentials' , "Neue Zugangsdaten");
define('ttNewLanguage' , "Neue Sprache");
define('ttNewPassword' , "Neues Passwort");
define('ttNewQuestion' , "Neue Frage");
define('ttNewRegistration' , "Neue Registrierung");
define('ttNewRoom' , "Neuer Raum");
define('ttNewTeacher' , "Neuer Lehrer");
define('ttNewTestSettings' , "Neue Einstellungen");
define('ttNewSubject' , "Neues Subjekt");
define('ttNewStudent' , "Neuer Studierender");
define('ttNewTopic' , "Neues Kapitel");
define('ttNewUser' , "Neuer Benutzer");
define('ttNo' , "Nein");
define('ttNoAnswers' , "Keine Antworten verfügbar für diese Frage");
define('ttNoExams' , "Kein Exam verfügbar für dieses Subjekt");
define('ttNoExamInProgress' , "Kein Exam im laufen");
define('ttNoInfo' , "Es gibt keine Informationen für dieses Exam");
define('ttNoQuestions' , "Keine Fragen verfügbar für dieses Kapitel");
define('ttNoRooms' , "Kein Raum angelegt: nur 'All' verfügbar");
define('ttNoSettings' , "Keine Einstellungen verfügbar für dieses Subjekt");
define('ttNoSubjects' , "Keine Subjekts verfügbar");
define('ttNoTestToCorrect' , "Keine Tests zu korrigieren");
define('ttNoUserRegistered' , "Keine registrierten Benutzer für dieses Exam verfügbar");
define('ttOldPassword' , "Altes Passwort");
define('ttEssayQuestion' , "Aufsatz-Frage");
define('ttPassword' , "Passwort");
define('ttPasswordLost' , "Passwort vergessen??");
define('ttPort' , "Port");
define('ttProfile' , "Profil");
define('ttPrepareImportQM' , "Vorschau");
define('ttQuestion' , "Frage");
define('ttQuestionPreview' , "Vorschau der Frage");
define('ttQuestions' , "Fragen");
define('ttQEc' , "Rechner");
define('ttQEp' , "Periodensystem");
define('ttQTMC' , "Multiple Choice");
define('ttQTMCDescription' , "Bei einer Multiple Choice-Frage wählt der Teilnehmer eine Antwort aus mehreren vorgegebenen Möglichkeiten aus um die Frage zu beantworten.");
define('ttQTMR' , "Multiple Response");
define('ttQTMRDescription' , "Eine Multiple Response-Frage ist ähnlich einer Multiple Choice-Frage, mit dem Unterschied dass mehr als eine der möglichen Antworten ausgewählt werden können.");
define('ttQTES' , "Essay Question");
define('ttQTESDescription' , "Eine Essay-Frage ermöglicht dem Teilnehmer einen längeren freien Text einzugeben um die Frage zu beantworten. Dieser Fragen-Typ kann auch dazu verwendet werden um Meinungen und Vorschläge zu einem beliebigen Thema abzufragen.");
define('ttQTYN' , "Yes/No");
define('ttQTYNDescription' , "Eine Yes/No-Frage ist eine Multiple Choice-Frage die der Teilnehmer mit \"Ja\" oder \"Nein\" beantworten muss.");
define('ttQTTF' , "True/False");
define('ttQTTFDescription' , "Eine True/False-Frage ist eine Multiple Choice-Frage die der Teilnehmer mit \"Wahr\" oder \"Falsch\" beantowrten muss.");
define('ttQTNM' , "Numerc");
define('ttQTNMDescription' , "Bei einer Numeric-Frage muss der Teilnehmer einen Zahlenwert als Antwort eingeben.");
define('ttQTTM' , "Text Match");
define('ttQTTMDescription' , "Bei einer Text Match-Frage gibt der Teilnehmer ein einzelnes Wort oder mehrere Wörter ein um die Frage zu beantworten. Sie bestimmen richtige oder falsche Wörter (oder Phrasen) durch Eingabe einer Liste von akzeptierten Antworten.");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Eine Hotspot-Frage ist eine Drag and Drop-Frage mit nur einem richtigen Bereich. Der Teilnehmer plaziert einen Marker auf das Bild um seine Antwort anzugeben.");
define('ttQTPL' , "Pull Down List");
define('ttQTPLDescription' , "descrizione Pull Down");
define('ttQuestionsubPL' , "Unterfrage");
define('ttQuesionid' , "Fragen ID");
define('ttQuestionNotes' , "Beschreibung");
define('ttQuestionsend' , "Sende Report");
define('ttQuestionreporting' , "To report more questions you need to leave the id field blank");
define('ttRandom' , "Zufall");
define('ttRefresh' , "Aktualisieren");
define('ttRegister' , "Registrieren");
define('ttRegistrations' , "Registrierungen");
define('ttRegEnd' , "Registrierungsende");
define('ttRenewPassword' , "Passwort erneuern");
define('ttReset' , "Zurücksetzen");
define('ttResetPassword' , "Passwort zurücksetzen");
define('ttRole' , "Rolle");
define('ttRooms' , "Räume");
define('ttSave' , "Speichern");
define('ttSaveAnswerInfo' , "Save Answer Info");
define('ttSaveLanguageFiles' , "Speichere Sprach-Dateien");
define('ttSaveLanguageXML' , "Speichere XML-Sprach-Dateien");
define('ttSaveQuestionInfo' , "Speichere Frageninformation");
define('ttScore' , "Wertung");
define('ttScoreFinal' , "Endgültige Wertung");
define('ttScoreTest' , "Test-Wertung");
define('ttScoreType' , "Score Type");
define('ttScoreMin' , "minimale Wertung");
define('ttSelectSubject' , "wähle Subjekt");
define('ttSelectSubjectBefore' , "wähle zuerst ein Subjekt");
define('ttSet' , "Set");
define('ttSetPassword' , "Bitte setzen sie ihr Passwort");
define('ttSettings' , "Einstellungen");
define('ttShowHide' , "Anzeigen/Verstecken");
define('ttSelectSubQuestion' , "Wählen sie eine Unterfrage");
define('ttSkin' , "Skin");
define('ttStart' , "Start");
define('ttStarted' , "Gestartet");
define('ttStop' , "Stopp");
define('ttStopped' , "Gestoppt");
define('ttStartTest' , "Test starten");
define('ttStatus' , "Status");
define('ttStats' , "Stats");
define('ttStudent' , "Student");
define('ttStudents' , "Studenten");
define('ttST10' , "Tenths");
define('ttST30' , "Thirtieths");
define('ttST100' , "Hundredth");
define('ttSubject' , "Subjekt");
define('ttSubjects' , "Subjekte");
define('ttSubmit' , "Absenden");
define('ttSurname' , "Familienname");
define('ttSystem' , "System");
define('ttSystemConfiguration' , "System Einstellungen");
define('ttSbjVers' , "Version");
define('ttTeacher' , "Lehrer");
define('ttTeachers' , "Lehrer");
define('ttTest' , "Test");
define('ttTests' , "Tests");
define('ttTestToCorrect' , "Tests zu korrigieren");
define('ttText' , "Text");
define('ttTime' , "Zeit");
define('ttTimeEnd' , "Zeit Ende");
define('ttTimeStart' , "Zeit Start");
define('ttTimeUsed' , "Zeit verwendet");
define('ttTimeZone' , "Zeitzone");
define('ttTitle' , "Titel");
define('ttTopic' , "Kapitel");
define('ttTopics' , "Kapitel");
define('ttTopicsAndQuestions' , "Kapitel und Fragen");
define('ttTopicsQuestions' , "Fragen je Kapitel");
define('ttTranslations' , "Übersetzungen");
define('ttTrue' , "Wahr");
define('ttType' , "Typ");
define('ttUser' , "Benutzer");
define('ttUsers' , "Benutzer");
define('ttView' , "Ansicht");
define('ttWelcome' , "Willkommen");
define('ttWaiting' , "Waiting");
define('ttWarning' , "Warnung");
define('ttYes' , "Ja");
define('ttDTsubquestionInfo' , "Unterfrage");
define('ttAssesmentOverview' , "Assesment Übersichts Report");
define('ttDeselectAll' , "alle abwählen");
define('ttErrorUserParameter' , "Wählen sie die Details des Teilnehmers um fortzusetzen!");
define('ttQuestionerror' , "Fragen ID");
define('ttRemove' , "Entfernen");
define('ttReport' , "Report");
define('ttReportAOWelcome' , "Wählen sie ein Assessment und verwenden sie die Tabs des Wizards um Daten zu filtern");
define('ttReportAOSelectAssesment' , "Wählen sie ein Assessment um einen Report zu erstellen");
define('ttReportCoachingError' , "Wählen sie ein Assessment und einen Teilnehmer um forzusetzen");
define('ttReportCoachingError2' , "Wählen sie ein Assessment um fortzusetzen");
define('ttReportErrorStudent' , "Der ausgewählte Studierende hat nicht am gewählten Test teilgenommen");
define('ttReportMainAO' , "Main");
define('ttReportTemplateDeleteFailed' , "Löschen fehlgeschlagen");
define('ttReportTemplateDelet' , "Template gelöscht");
define('ttReportTemplateLoaded' , "Template caricato correttamente");
define('ttReportTemplateSaveError' , "Geben sie einen Templatenamen ohne Leerzeichen ein!");
define('ttReportTemplateSaved' , "Template korrekt gespeichert");
define('ttReportTemplateDuplicateError' , "Templatename existiert bereits!");
define('ttReportScoreFilter' , "Wenn sie bereits einen Teilnehmer ausgewählt haben wählen sie bitte nun einen neuen.");
define('ttSelectAll' , "Alles auswählen");
define('ttQTFB' , "Füllen sie die Lücken aus");
define('ttQTFB_TEXT' , "Ergänzen sie den folgenedn Text mit den passenden Wörtern");
define('ttQTFBDescription' , "Bei einer Lückentext-Frage muss der Teilnehmer einen Text mit den richtigen Wörten ergänzen");
define('ttPosterImageVideo' , "Lade Logo");
define('ttWidthVideo' , "Breite");
define('ttHeightVideo' , "Höhe");
define('ttIdVideo' , "Identification Code");
define('ttVideoTypeVideo' , "Videoformat");
define('ttNumberOfPlaysVideo' , "Max number of plays");
define('ttToolbarVideo' , "Video");
define('ttDialogTitleVideo' , "Videoeigenschaft");
define('ttFakeObjectVideo' , "Video");
define('ttPropertiesVideo' , "Video bearbeiten");
define('ttWidthRequiredVideo' , "Die Breite muss gesetzt werden");
define('ttHeightRequiredVideo' , "Die Höhe muss gesetzt werden");
define('ttNumberOfPlayRequiredVideo' , "The Max number of plays should be set");
define('ttFallbackTemplateVideo' , "Ihr Browser unterstützt keine HTML5-Videos");
define('ttBrowseVideo' , "Browse server");
define('ttsourceVideo' , "Source video");
define('ttNumberOfPlayAlertVideo' , "You have reached the maximum number of plays your video");
define('ttHelpDefault' , "Information Panel");
define('ttHelpDefaultDescription' , "Press this button to get a description of what you can do");
define('ttHelpQuestion' , "Wählen sie eine Frage um den Inhalt anzugeigen oder bearbeiten sie diese mit einem Doppelklick");
define('ttHelpADMINNewTeacherDescription' , "Define the account of a new administrator, teacher or examiner");
define('ttHelpADMINNewStudentDescription' , "Define the account of a new student");
define('ttHelpADMINSelLanguageDescription' , "Select a language to manage");
define('ttHelpADMINLanguageDescription' , "Hier können sie die Sprache des Systems verändern");
define('ttHelpADMINSystemConf' , "Hier können sie die Einstellungen von EOL verändern, bitte seien sie vorsichtig");
define('ttHelpADMINRoom' , "Bestimmen sie Räume wo die Tests ausgeführt werden können");
define('ttHelpADMINImport' , "Dieses Fenster erlaubt ihnen neue Fragen nach Question Mark zu importieren");
define('ttHelpADMINProfile' , "Dieses Fenster erlaubt ihnen ihr Profil zu bearbeiten");
define('ttHelpReportAreport' , "Dieses Fenster erlaubt ihnen einen Report zu erstellen, sie müssen zuerst mindestens ein Subject auswählen");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "Dieses Fenster erlaubt ihnen einen Report zu erstellen, sie müssen dazu einen Teilnehmer auswählen");
define('ttHelpReportCreportlist' , "Wählen sie das Exam für den Report");
define('ttHelpStudent' , "Links finden sie die verfügbaren Tests, rechts die Prüfungsdetails");
define('ttHelpStudentTest' , "You are in the exam screen, answer the questions and submit the test");
define('ttHelpAdminErrorQuestion' , "Wenn sie auf ein Problem stossen dann können sie uns über dieses Fenster darüber informieren.");
define('ttHelpExamsCorrect' , "Here you receive an examination done by a student, check that the correction has been made correctly, and then confirm the vote.");
define('ttHelpExamsSettings' , "In this screen you can define or change the settings to use in future examinations.");
define('ttErrorSent' , "La segnalazioe è stata inviata con Successo!");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttGroup' , "Group");
define('ttSubgroup' , "Subgroup");
define('ttAOreportSaved' , "All the generated report will be saved on server. You can see them in the specific section");
define('ttReportAllFinished' , "All finished");
define('ttReportAODescription' , "If you not select specific assessments, all the assessment will be analyzed");
define('ttReportAssesmentAuthor' , "Assessment author");
define('ttReportAssessmentInformation' , "Assessment information");
define('ttReportAssesmentID' , "Assessment ID");
define('ttReportAssesmentDateTimeFirst' , "Date/Time first taken");
define('ttReportAssesmentDateTimeLast' , "Date/Time last taken");
define('ttReportAssesmentLeastTimeFinished' , "Least time taken for those finished");
define('ttReportAssesmentName' , "Assessment name");
define('ttReportAssesmentNumberStarted' , "Num. of times started");
define('ttReportAssesmentNumberNotFinished' , "Num. of times not finished");
define('ttReportAssesmentNumberFinished' , "Num. of times finished");
define('ttReportAssesmentMinscoreFinished' , "Minimum score of those finished");
define('ttReportAssesmentMaxcoreFinished' , "Maximum score of those finished");
define('ttReportAssesmentMediumFinished' , "Medium score of those finished");
define('ttReportAssesmentMediumTimeFinished' , "Medium time taken for those finished");
define('ttReportAssesmentMostTimeFinished' , "Most time taken for those finished");
define('ttReportAssesmentScore' , "Filter by assessments score");
define('ttReportAssesmentStdDeviation' , "Standard deviation for those finished");
define('ttReportChecked' , "Selected");
define('ttReportCoaching' , "Coaching Report");
define('ttReportCWelcome' , "Choose an assessment and a participant");
define('ttReportCDescription' , "You have to filter data by dates and, if you want, also by score");
define('ttReportCoachingDescription' , "See detailed results for one participant taking one assessment");
define('ttReportCoachingInformation' , "Select one test to see detailed information");
define('ttReportCustomize' , "Customize your report");
define('ttReportDateInterval' , "Dates interval");
define('ttReportDateFrom' , "From");
define('ttReportDateTaken' , "Date taken");
define('ttReportDateTo' , "to");
define('ttReportErrorDetail' , "Please select a participant to show details");
define('ttReportField' , "Field name");
define('ttReportGraphicalDsiplays' , "Graphical displays");
define('ttReportGraphicHistogram' , "Histogram of assessment scores");
define('ttReportGraphicTopicScore' , "Histogram of topic scores");
define('ttReportGroup' , "Groups");
define('ttReportGroupNotPresent' , "There aren't groups");
define('ttReportMinimumScore' , "Filter by minimum score");
define('ttReportMaximumScore' , "Filter by maximum score");
define('ttReportNotFilter' , "Do not use filter");
define('ttReportOrder' , "Order");
define('ttReportPartecipants' , "Participants");
define('ttReportPartecipant' , "Participant");
define('ttReportScheduled' , "Schedule");
define('ttReportScoreBand' , "Filter by score band");
define('ttReportSearch' , "Search...");
define('ttReportSearched' , "Search result");
define('ttReportSelectDetail' , "Select user ID or email of participant selected before");
define('ttReportSelectFilter' , "Select filter");
define('ttReportSelectGroup' , "Select groups filter on");
define('ttReportSelectLetter' , "Letter");
define('ttReportAOSelectPartecipant' , "Select participant");
define('ttReportSelected' , "Selected assessments");
define('ttReportSelectTemplate' , "Select a template");
define('ttReportSelectedGroup' , "Selected groups");
define('ttReportSearchByLetter' , "Search by letter");
define('ttReportStudent' , "Filter on participant");
define('ttReportStudentNotPresent' , "There aren't students");
define('ttReportStudentDetail' , "Filter on participant detail");
define('ttReportTemplateLoad' , "Select a template to load");
define('ttReportTemplateSave' , "Save template as");
define('ttReportTemplateName' , "Insert name");
define('ttReportTimedOut' , "Timed out");
define('ttReportTopicAverageScore' , "Average score");
define('ttReportTopicInformation' , "Topic information");
define('ttReportTopicMaximumScore' , "Maximum score");
define('ttReportTopicMinimumScore' , "Minimum score");
define('ttReportTopicName' , "Topic name");
define('ttReportTopicStandardDeviation' , "Standard Deviation");
define('ttReportTyping' , "Search by typing");
define('ttReportQuestionType' , "Question type");
define('ttReportViewer' , "Report viewer");
define('ttReportViewerDescription' , "View all generated report and manage them");
define('ttStudentDetailCreport' , "Student detail");
define('ttCertificates' , "Certificates");
define('ttNewGroup' , "Add group");
define('ttEditGroup' , "Edit group");
define('ttEditTeacher' , "Edit Teacher");
define('ttEditStudent' , "New Teacher");
define('tteTeacher' , "Examiner");
define('ttCertificate' , "Certificate");
define('tttotals' , "Total");
define('ttD1s' , "Easy");
define('ttD2s' , "Medium");
define('ttD3s' , "Hard");
define('ttSelectStudent' , "Students list");
define('ttSelectTeacher' , "Teacher list");
define('ttCoord' , "Coordinates");
define('ttHelpExams' , "The list of exams is displayed here. You can create a new exam, change the exam settings, or view student votes.");
define('ttHelpSubject' , "Here you will see a list of the courses you are teaching. Select one to view the questions contained therein.");
define('ttNotAvailable' , "The selected settings do not allow you to generate a test.");
define('ttSelectGroup' , "Edit groups or subgroups");
define('ttConfirmProcedure' , "Do you really want to do this?");
define('ttUserDeleted' , "User deleted correctly");
define('ttMGroupCreated' , "Group successfully created");
define('ttMSubgroupCreated' , "Subgroup successfully created");
define('ttTeacherSubmitStudentExam' , "If you click the yes button, the student exam will automatically be delivered to the system in its current state. If the student is still doing the exam, any further modification will not be considered.");
define('ttNewSubgroup' , "Add subgroup");
define('ttErrorTopic' , "Too much topic questions selected");
define('ttAvailable' , "questions available of");
define('ttThereAreNot' , "There aren't");
define('ttErrorMax' , "This field can't be lesser than the number of selected mandatory questions");
define('ttField' , "The field");
define('ttHard' , "Hard");
define('ttMedium' , "Medium");
define('ttEasy' , "Easy");
define('ttMustBeaNumber' , "Must be a number");
define('ttMaxHardReached' , "Maximum number of hard questions already reached");
define('ttMaxMediumReached' , "Maximum number of medium questions already reached");
define('ttMaxEasyReached' , "Maximum number of easy questions already reached");
define('ttProfCert' , "Proficiency Certificate");
define('ttCertify' , "This is to certify that");
define('ttSuccess' , "has successfully passed");
define('ttEvaluation' , "with evaluation");
define('ttAccreditedTestSite' , "in the Accredited Test Site of the");
define('ttOn' , "on");
define('ttNumQuestionsTopic' , "Number of questions for each topic");
define('ttParamNotSet' , "Missing parameters");
define('ttNotEnoughQuestions' , "Not enough questions");
define('ttExamArchivedCertNot' , "The exam is archived but certificates have not been generated");
define('ttSendCertificate' , "Download certificate");
define('ttCertificateAlert' , "Are you sure you want to generate and download the exam certificate to the student? The operation can not be canceled in any way!");
define('ttCertificateScore' , "The student does not have the minimum score to receive a certificate");
define('ttCertificateGenerated' , "The certificate was generated correctly");
define('ttBut' , "but");
define('ttAnd' , "and");
define('ttCertificateEmailSended' , "the email was successfully sent");
define('ttCertificateGeneratedProblem' , "The certificate was not generated!");
define('ttCertificatePoint' , "The student score is too low and can not be issued a certificate.");
define('ttPrivacy1' , "I read and accept the");
define('ttPrivacy2' , "ECTN Privacy Policy");
define('ttPrivacy3' , "I wish to be informed on the possibility of obtaining an Individual Proficiency Certificate");
define('ttDemoTest' , "Demo test");
