<?php
define('ttAccountActivation' , "Ενεργοποίηση Λογαριασμού");
define('ttActive' , "Ενεργός");
define('ttActivate' , "Θέτω εις ενέργειαν");
define('ttAdd' , "Προσθέτω");
define('ttAddSelectedStudents' , "Προσθέστε επιλεγμένους μαθητές");
define('ttAdministration' , "Διαχείριση");
define('ttAdministrator' , "Διαχειριστής");
define('ttAdminWelcome' , "Καλώς ήλθατε στον πίνακα διαχείρισης.");
define('ttAlias' , "Κωδικός ISO 639-1");
define('ttAndExit' , "και Έξοδος");
define('ttAnswer' , "Απάντηση");
define('ttAnswers' , "Απαντήσεις");
define('ttArchive' , "Αρχείο");
define('ttArchived' , "Αρχειοθετημένα");
define('ttAssignSubject' , "Αντιστοίχιση θέματος");
define('ttAutomatic' , "Αυτόματο");
define('ttAImportComplete' , "Ερωτήσεις Η εισαγωγή ολοκληρώθηκε με επιτυχία");
define('ttBasedOn' , "Βασισμένο στο");
define('ttBlocked' , "Αποκλεισμένος");
define('ttBlock' , "ΟΙΚΟΔΟΜΙΚΟ ΤΕΤΡΑΓΩΝΟ");
define('ttUnblock' , "Ξεβουλώνω");
define('ttBonus' , "Δώρο");
define('ttCancel' , "Ματαίωση");
define('ttChangeLanguage' , "Αλλαξε γλώσσα");
define('ttChangeVersion' , "Αλλαγή δοκιμαστικής έκδοσης");
define('ttCheck' , "Ελεγχος...");
define('ttClose' , "Κοντά");
define('ttClosed' , "Κλειστό");
define('ttCorrect' , "Σωστός");
define('ttConfiguration' , "Διαμόρφωση");
define('ttConfirm' , "Επιβεβαιώνω");
define('ttConfirmEmail' , "Επιβεβαίωση διεύθυνσης ηλεκτρονικού ταχυδρομείου");
define('ttConfirmPassword' , "Επιβεβαίωση Κωδικού");
define('ttCreate' , "Δημιουργώ");
define('ttCArchiveExam' , "Είστε βέβαιοι να αρχειοθετήσετε την εξέταση;");
define('ttCBlockTest' , "Είστε βέβαιοι ότι θα εμποδίσετε αυτό το τεστ;");
define('ttCChangeStatus' , "Είστε σίγουροι ότι αλλάζετε την κατάσταση της ερώτησης στο _STATUS_;");
define('ttCConfirmTest' , "Θέλετε να επιβεβαιώσετε τη βαθμολογία της δοκιμής;");
define('ttCDeleteAnswer' , "Είστε σίγουροι ότι θα διαγράψετε αυτήν την απάντηση και τις μεταφράσεις της;");
define('ttCDeleteExam' , "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την εξέταση;");
define('ttCDeleteQuestion' , "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτή την ερώτηση και τις μεταφράσεις της;");
define('ttCDeleteRoom' , "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το δωμάτιο;");
define('ttCDeleteSubject' , "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το θέμα;");
define('ttCDeleteSettings' , "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτές τις ρυθμίσεις ελέγχου;");
define('ttCDeleteTopic' , "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το θέμα;");
define('ttCDiscardEdits' , "Οι αλλαγές σας θα χαθούν.");
define('ttCDiscardNew' , "Το δημιουργούμενο στοιχείο θα χαθεί.");
define('ttCRegister' , "Είστε σίγουροι ότι θα εγγραφείτε σε αυτή την εξέταση;");
define('ttCRegisterStudents' , "Είστε σίγουροι ότι θα καταχωρήσετε αυτούς τους επιλεγμένους μαθητές στην εξέταση;");
define('ttCRenewPassword' , "Ο κωδικός της εξέτασης θα αλλάξει.");
define('ttCStartExam' , "Θέλετε να ενεργοποιήσετε την επιλεγμένη εξέταση;");
define('ttCStartTest' , "Θέλετε να ξεκινήσετε τώρα τις εξετάσεις;");
define('ttCStopExam' , "Θέλετε να απενεργοποιήσετε την επιλεγμένη εξέταση;");
define('ttCSubmitTest' , "Θέλετε να υποβάλετε τη δοκιμή σας;");
define('ttCTest' , "Ο κωδικός είναι σωστός.");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Είστε σίγουροι ότι θα ξεκλειδώσετε αυτή τη δοκιμή;");
define('ttCUpdateConfigurations' , "Είστε σίγουροι ότι θα αποθηκεύσετε τις νέες διαμορφώσεις του συστήματος;");
define('ttCUpdateLanguage' , "Είστε σίγουροι ότι θα ενημερώσετε τα αρχεία γλώσσας;");
define('ttD1' , "Εύκολος");
define('ttD2' , "Μεσαίο");
define('ttD3' , "Σκληρά");
define('ttDatabaseConfiguration' , "Διαμόρφωση βάσης δεδομένων");
define('ttDay' , "Ημέρα");
define('ttDelete' , "Διαγράφω");
define('ttDescription' , "Περιγραφή");
define('ttDifficulty' , "Δυσκολία");
define('ttDifficultyQuestions' , "Ερωτήσεις ανά δυσκολία");
define('ttDistribution' , "Κατανομή");
define('ttDo' , "Κάνετε την εξέταση");
define('ttDTAnswerInfo' , "Εμφανίζονται _TOTAL_ απαντήσεις");
define('ttDTAnswerFiltered' , "(φιλτράρεται από τις συνολικές απαντήσεις _MAX_)");
define('ttDTAnswerEmpty' , "Δεν υπάρχουν απαντήσεις για εμφάνιση");
define('ttDTExamInfo' , "Παρουσιάζονται _TOTAL_ εξετάσεις σε εξέλιξη");
define('ttDTExamFiltered' , "(διηθήθηκε από τις συνολικές εξετάσεις _MAX_ που βρίσκονται σε εξέλιξη)");
define('ttDTExamEmpty' , "Δεν υπάρχουν εξετάσεις για εμφάνιση");
define('ttDTQuestionInfo' , "Εμφανίζονται _TOTAL_ ερωτήσεις");
define('ttDTQuestionFiltered' , "(φιλτραρισμένο από _MAX_ συνολικά ερωτήματα)");
define('ttDTQuestionEmpty' , "Δεν υπάρχουν ερωτήσεις για εμφάνιση");
define('ttDTRegisteredStudentInfo' , "Εμφανίζονται _TOTAL_ εγγεγραμμένοι φοιτητές");
define('ttDTRegisteredStudentFiltered' , "(φιλτραρισμένο από _MAX_ σύνολο εγγεγραμμένων φοιτητών)");
define('ttDTRegisteredStudentEmpty' , "Δεν υπάρχουν εγγεγραμμένοι μαθητές να δείξουν");
define('ttDTStudentsInfo' , "Εμφανίζονται _TOTAL_ φοιτητές");
define('ttDTStudentsFiltered' , "(φιλτραρισμένο από _MAX_ σύνολο φοιτητών)");
define('ttDTStudentsEmpty' , "Κανένας σπουδαστής δεν θα δείξει");
define('ttDTTestInfo' , "Εμφάνιση δοκιμής _TOTAL_");
define('ttDTTeacherInfo' , "Εμφανίζονται _TOTAL_ καθηγητές");
define('ttDTTeacherFiltered' , "(φιλτραρισμένο από τους _MAX_ συνολικά εκπαιδευτικούς)");
define('ttDTTeacherEmpty' , "Δεν υπάρχει δάσκαλος για να δείξει");
define('ttDTTestFiltered' , "(φιλτράρεται από τις συνολικές δοκιμές _MAX_)");
define('ttDTTestEmpty' , "Δεν υπάρχουν δοκιμές για εμφάνιση");
define('ttDone' , "Η εξέταση έγινε");
define('ttDuration' , "Διάρκεια");
define('ttDTsubquestionInfo' , "Υπο ερωτήσεις");
define('ttEdit' , "Επεξεργασία");
define('ttEditableScore' , "Επεξεργάσιμη βαθμολογία");
define('ttError' , "Λάθος");
define('ttEmail' , "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ");
define('ttEnd' , "Τέλος");
define('ttEverywhere' , "Παντού");
define('ttExam' , "Εξέταση");
define('ttExams' , "Εξετάσεις");
define('ttExit' , "Εξοδος");
define('ttExport',"εξαγωγή");
define('ttExtra' , "Επιπλέον");
define('ttExamsArchive' , "Αρχείο");
define('ttExamsInProgress' , "Οι εξετάσεις βρίσκονται σε εξέλιξη");
define('ttETeachers' , "Εξεταστής");
define('ttErrorquestion' , "Αναφορά σφάλματος");
define('ttEActivationFails' , "Η ενεργοποίηση αποτυγχάνει!");
define('ttEAlreadyRegistered' , "Ο φοιτητής είναι ήδη εγγεγραμμένος για αυτή την εξέταση!");
define('ttEAnswerInSet' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttEAnswerNotFound' , "Η απάντηση δεν βρέθηκε");
define('ttEAnswers' , "Παρουσιάστηκε ένα πρόβλημα με απαντήσεις.");
define('ttEDatabase' , "Σφάλμα βάσης δεδομένων!");
define('ttEDates' , "Οι ημερομηνίες δεν είναι σωστές!");
define('ttEEditRoomAll' , "Δεν είναι δυνατή η επεξεργασία του \"ολόκληρου\" του δωματίου!");
define('ttEEmailAlreadyRegistered' , "E-mail έχει ήδη εγγραφεί!");
define('ttEEmailNotRegistered' , "Το ηλεκτρονικό ταχυδρομείο δεν έχει εγγραφεί!");
define('ttEEmailNotValid' , "Το δακτυλογραφημένο ηλεκτρονικό ταχυδρομείο δεν είναι έγκυρο!");
define('ttEEmailsNotMatch' , "Τα δύο μηνύματα ηλεκτρονικού ταχυδρομείου δεν ταιριάζουν!");
define('ttEEmptyFields' , "Ένα ή περισσότερα πεδία είναι κενά!");
define('ttEExamArchived' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttEExamNotFound' , "Η εξέταση δεν βρέθηκε!");
define('ttEExamNotStarted' , "Δεν μπορείτε να ξεκινήσετε την εξέταση.");
define('ttEExamStarted' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί επειδή η εξέταση έχει ήδη ξεκινήσει!");
define('ttEExamWaiting' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί επειδή η εξέταση δεν ξεκίνησε ποτέ!");
define('ttEExamsNotArchivedDeleteTopic' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή τουλάχιστον μία μη αρχειοθετημένη εξέταση περιέχει ερωτήσεις από αυτό το θέμα!");
define('ttEExamsNotArchivedEditTestSettings' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή αυτές οι ρυθμίσεις χρησιμοποιούνται από τουλάχιστον μία μη αρχειοθετημένη εξέταση.");
define('ttEExamsNotArchivedDeleteTestSettings' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί, επειδή αυτές οι ρυθμίσεις χρησιμοποιούνται από τουλάχιστον μία μη αρχειοθετημένη εξέταση!");
define('ttEExport',"Το αίτημα εξαγωγής δεν στάλθηκε!");
define('ttEIncorrectField' , "Ένα ή περισσότερα πεδία δεν είναι σωστά!");
define('ttELogin' , "Το ηλεκτρονικό ταχυδρομείο και / ή ο κωδικός πρόσβασης δεν είναι σωστά!");
define('ttEMainLanguageEmpty' , "Η κύρια γλώσσα του αντικειμένου δεν μπορεί να είναι κενή!");
define('ttEMandatoryQuestion' , "Αυτή είναι μια υποχρεωτική ερώτηση σχετικά με τη ρύθμιση δοκιμής '_TESTSETTING_': δεν μπορείτε να την διαγράψετε ή να επεξεργαστείτε τη δυσκολία ή το θέμα της.");
define('ttENotAuthorized' , "Ο πελάτης σας δεν είναι εξουσιοδοτημένος.");
define('ttENoStudentsToRegister' , "Κανένας φοιτητής να εγγραφεί");
define('ttENoTopicsForSubject' , "Δεν υπάρχει θέμα για αυτό το θέμα!");
define('ttEOldPasswordWrong' , "Ο παλιός κωδικός πρόσβασης δεν είναι σωστός!");
define('ttEPassword' , "Λάθος κωδικός!");
define('ttEPasswordShort' , "Ο κωδικός πρόσβασης είναι πολύ μικρός.");
define('ttEPasswordsNotMatch' , "Οι δύο κωδικοί πρόσβασης δεν ταιριάζουν!");
define('ttEQuestAnswPicker' , "Σφάλμα κατά την επιλογή των ερωτήσεων και των απαντήσεων.");
define('ttEQuestionInSet' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttEQuestionNotFound' , "Η ερώτηση δεν βρέθηκε!");
define('ttEQuestionType' , "Ο τύπος ερωτήματος δεν είναι σωστός!");
define('ttERegFailedQuestions' , "Η καταχώριση απέτυχε: πολύ λίγες ερωτήσεις!");
define('ttERoomAllDelete' , "Το 'Όλα' δεν μπορεί να διαγραφεί!");
define('ttERoomUsed' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttESaveBeforeNew' , "Πριν δημιουργήσετε ένα νέο στοιχείο, αποθηκεύστε ή ακυρώστε το ήδη δημιουργημένο στοιχείο.");
define('ttESelectQuestionType' , "Πρέπει να επιλέξετε έναν από τους διαθέσιμους τύπους ερωτήσεων!");
define('ttESelectSubject' , "Πρέπει να επιλέξετε ένα από τα θέματα σας!");
define('ttESelectTestSettings' , "Πρέπει να επιλέξετε μία από τις ρυθμίσεις ελέγχου!");
define('ttESetNotFound' , "Οι ερωτήσεις δεν βρέθηκαν!");
define('ttETestAlreadyArchived' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETestAlreadySubmitted' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETestBlockedSubmitted' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETestNotArchived' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETestNotFound' , "Η δοκιμή δεν βρέθηκε!");
define('ttETestsNotArchived' , "Ορισμένες δοκιμές δεν έχουν αρχειοθετηθεί!");
define('ttETestSettingDeleteQuestion' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETestSettingDeleteTopic' , "Η λειτουργία δεν μπορεί να ολοκληρωθεί.");
define('ttETimeExpired' , "Ο διαθέσιμος χρόνος έχει λήξει!");
define('ttETranslationExists' , "Η μετάφραση της επιλεγμένης γλώσσας υπάρχει ήδη!");
define('ttEUserNotFound' , "Ο χρήστης δεν βρέθηκε!");
define('ttEValues' , "Ορισμένες τιμές δεν είναι σωστές!");
define('ttFalse' , "Ψευδής");
define('ttFinalScore' , "Τελικό σκορ");
define('ttGeneralInformations' , "Γενικές πληροφορίες");
define('ttHours' , "ώρες");
define('ttHome' , "Σπίτι");
define('ttHomepage' , "Αρχική σελίδα");
define('ttHost' , "Πλήθος");
define('ttHAnswPanel' , "Κάντε διπλό κλικ για να επεξεργαστείτε την επιλεγμένη απάντηση");
define('ttHQuestLanguagesPanel' , "Κάντε κλικ για να εμφανιστεί η μετάφραση της επιλεγμένης ερώτησης");
define('ttHQuestPanel' , "Κάντε ένα κλικ για να επιλέξετε και να προβάλετε την προεπισκόπηση ερωτήσεων και κάντε διπλό κλικ για να επεξεργαστείτε τις ερωτήσεις και τις απαντήσεις.");
define('ttHQuestPreviewPanel' , "Οι απαντήσεις με πορτοκαλί φόντο δεν μεταφράζονται σε γλώσσα που ζητήσατε");
define('ttHQuestTopicPanel' , "Κάντε ένα κλικ για να φιλτράρετε ερωτήσεις και κάντε διπλό κλικ για να επεξεργαστείτε τις πληροφορίες σχετικά με το θέμα");
define('ttInfo' , "Πληροφορίες");
define('ttIPEnd' , "IPv4 Τέλος");
define('ttIPStart' , "IPv4 Έναρξη");
define('ttInactive' , "Αδρανής");
define('ttImportQM' , "Εισαγωγή");
define('ttImport' , "Εισαγωγή QM");
define('ttImportComplete' , "Ερωτήσεις Η εισαγωγή ολοκληρώθηκε με επιτυχία");
define('ttJoin' , "Συμμετοχή");
define('ttLanguage' , "Γλώσσα");
define('ttLanguages' , "Γλώσσες");
define('ttLogin' , "Σύνδεση");
define('ttLogo' , "Λογότυπο");
define('ttLoginOk' , "Η σύνδεση ολοκληρώθηκε!");
define('ttLogout' , "ΑΠΟΣΥΝΔΕΣΗ");
define('ttMailLostPassword' , "Για να επαναφέρετε τον κωδικό πρόσβασης του λογαριασμού σας, κάντε κλικ στον παρακάτω σύνδεσμο: _LINK_ Εάν δεν έχετε ζητήσει επαναφορά κωδικού πρόσβασης, αγνοήστε αυτό το μήνυμα ηλεκτρονικού ταχυδρομείου.");
define('ttMailCredentials' , "Αγαπητέ _USERNAME_, Ο κωδικός πρόσβασής σας που έχει συσχετιστεί με τον λογαριασμό _USEREMAIL_ έχει τροποποιηθεί σύμφωνα με το αίτημά σας.");
define('ttMailNewTeacher' , "Καλώς ήρθατε στο _SYSTEMNAME_.");
define('ttMainLanguage' , "Κύρια γλώσσα");
define('ttManage' , "Διαχειρίζονται");
define('ttMandatory' , "Επιτακτικός");
define('ttManual' , "Εγχειρίδιο");
define('ttMinutes' , "λεπτά");
define('ttMyExams' , "Οι εξετάσεις μου");
define('ttMySettings' , "Οι ρυθμίσεις μου");
define('ttMySubjects' , "Επιλέξτε θέμα");
define('ttMActivation' , "Ο κωδικός πρόσβασης έχει ρυθμιστεί με επιτυχία.");
define('ttMAnswerDeleted' , "Η απάντηση διαγράφηκε με επιτυχία");
define('ttMConfigurationsUpdated' , "Οι διαμορφώσεις συστημάτων ενημερώθηκαν με επιτυχία");
define('ttMConfirm' , "Η δοκιμή επιβεβαιώθηκε με επιτυχία και αρχειοθετείται");
define('ttMUserCreated' , "Η δημιουργία ολοκληρώθηκε: ένα μήνυμα ηλεκτρονικού ταχυδρομείου σας έχει σταλεί για να ολοκληρώσετε την εγγραφή.");
define('ttMEdit' , "Οι επεξεργασίες αποθηκεύτηκαν με επιτυχία");
define('ttMExamArchived' , "Η εξέταση ολοκληρώθηκε με επιτυχία");
define('ttMExamDeleted' , "Η εξέταση διαγράφηκε με επιτυχία");
define('ttMExamStarted' , "Η εξέταση ξεκίνησε με επιτυχία");
define('ttMExamStopped' , "Η εξέταση έπαψε επιτυχώς");
define('ttMExportRequestSent',"Το αίτημα εξαγωγής εστάλη, ελέγξτε το email σας");
define('ttMLanguageCreated' , "Η μετάφραση δημιουργήθηκε με επιτυχία");
define('ttMLanguageSaved' , "Η μετάφραση αποθηκεύτηκε με επιτυχία");
define('ttMLanguageUpdated' , "Η μετάφραση ενημερώθηκε με επιτυχία");
define('ttMNewAnswer' , "Η απάντηση δημιουργήθηκε με επιτυχία");
define('ttMNewQuestion' , "Η ερώτηση δημιουργήθηκε με επιτυχία");
define('ttMNewRoom' , "Η αίθουσα δημιουργήθηκε με επιτυχία");
define('ttMNewSettings' , "Οι ρυθμίσεις δοκιμής δημιουργήθηκαν με επιτυχία");
define('ttMNewSubject' , "Το θέμα δημιουργήθηκε με επιτυχία");
define('ttMNewTopic' , "Το θέμα δημιουργήθηκε με επιτυχία");
define('ttMPasswordRenewed' , "Ο κωδικός της εξέτασης ολοκληρώθηκε με επιτυχία");
define('ttMQuestionDeleted' , "Η ερώτηση διαγράφεται με επιτυχία");
define('ttMRegistration' , "Έχετε εγγραφεί επιτυχώς σε αυτήν την εξέταση");
define('ttMResetConfirmed' , "Η αίτηση ολοκληρώθηκε: έχει σταλεί ένα μήνυμα ηλεκτρονικού ταχυδρομείου σε εσάς για να επαναφέρετε τον κωδικό πρόσβασης.");
define('ttMRoomDeleted' , "Το δωμάτιο διαγράφηκε με επιτυχία");
define('ttMSelectLanguage' , "Επιλέξτε τη γλώσσα που θέλετε να διαχειριστείτε");
define('ttMSettingsDeleted' , "Οι ρυθμίσεις δοκιμής διαγράφηκαν με επιτυχία");
define('ttMStudentsRegistered' , "Οι φοιτητές έχουν εγγραφεί επιτυχώς στην εξέταση");
define('ttMSubjectDeleted' , "Το θέμα διαγράφηκε με επιτυχία");
define('ttMSubjectQuestions' , "Για να διαχειριστείτε θέματα και ερωτήσεις, επιλέξτε το θέμα");
define('ttMSubjectSettings' , "Για να διαχειριστείτε τις ρυθμίσεις των εξετάσεων, επιλέξτε το θέμα");
define('ttMTestBlocked' , "Η δοκιμή ολοκληρώθηκε με επιτυχία");
define('ttMTestSubmitted' , "Η δοκιμή υποβλήθηκε με επιτυχία");
define('ttMTestUnblocked' , "Η δοκιμή ξεκλειδώθηκε με επιτυχία");
define('ttMTopicDeleted' , "Το θέμα διαγράφηκε με επιτυχία");
define('ttName' , "Ονομα");
define('ttNumberError' , "Η τιμή πρέπει να είναι ακέραιος ή δεκαδικός (ES: 12,5)");
define('ttNegativeScores' , "Αρνητικές βαθμολογίες");
define('ttNew' , "Νέος");
define('ttNext' , "Επόμενο");
define('ttNewAnswer' , "Νέα απάντηση");
define('ttNewCredentials' , "Νέα διαπιστευτήρια");
define('ttNewLanguage' , "Νέα Γλώσσα");
define('ttNewPassword' , "νέος κωδικός πρόσβασης");
define('ttNewQuestion' , "Νέα ερώτηση");
define('ttNewRegistration' , "Νέα καταχώρηση");
define('ttNewRoom' , "Νέο Δωμάτιο");
define('ttNewTeacher' , "Νέος δάσκαλος");
define('ttNewTestSettings' , "Νέες ρυθμίσεις");
define('ttNewSubject' , "Νέο θέμα");
define('ttNewStudent' , "Νέος μαθητής");
define('ttNewTopic' , "Νέο θέμα");
define('ttNewUser' , "Νέος χρήστης");
define('ttNo' , "Οχι");
define('ttNoAnswers' , "Δεν υπάρχουν διαθέσιμες απαντήσεις για αυτήν την ερώτηση");
define('ttNoExams' , "Δεν υπάρχουν διαθέσιμες εξετάσεις για αυτό το θέμα");
define('ttNoExamInProgress' , "Δεν υπάρχουν εξετάσεις σε εξέλιξη");
define('ttNoInfo' , "Δεν υπάρχουν πληροφορίες σχετικά με αυτήν την εξέταση");
define('ttNoQuestions' , "Δεν υπάρχουν διαθέσιμες ερωτήσεις για αυτό το θέμα");
define('ttNoRooms' , "Δεν δημιουργήθηκαν δωμάτια: \"Όλα\" μόνο διαθέσιμα");
define('ttNoSettings' , "Δεν υπάρχουν διαθέσιμες ρυθμίσεις για αυτό το θέμα");
define('ttNoSubjects' , "Δεν υπάρχουν διαθέσιμα θέματα");
define('ttNoTestToCorrect' , "Δεν υπάρχουν δοκιμές για να διορθωθούν");
define('ttNoUserRegistered' , "Δεν υπάρχουν εγγεγραμμένοι χρήστες για αυτήν την εξέταση");
define('ttOldPassword' , "ΠΑΛΙΟΣ ΚΩΔΙΚΟΣ");
define('ttEssayQuestion' , "Ερώτηση για το δοκίμιο");
define('ttPassword' , "Κωδικός πρόσβασης");
define('ttPasswordLost' , "Ο κωδικός πρόσβασης χάθηκε;");
define('ttPort' , "Λιμάνι");
define('ttProfile' , "Προφίλ");
define('ttPrepareImportQM' , "Προεπισκόπηση");
define('ttQuestion' , "Ερώτηση");
define('ttQuestionPreview' , "Προεπισκόπηση ερωτήματος");
define('ttQuestions' , "Ερωτήσεις");
define('ttQEc' , "Αριθμομηχανή");
define('ttQEp' , "Περιοδικός Πίνακας");
define('ttQTMC' , "Πολλαπλή επιλογή");
define('ttQTMCDescription' , "Σε μια ερώτηση πολλαπλής επιλογής ο συμμετέχων επιλέγει μία μόνο επιλογή από μια σειρά επιλογών για να απαντήσει στην ερώτηση.");
define('ttQTMR' , "Πολλαπλή απάντηση");
define('ttQTMRDescription' , "Μια ερώτηση πολλαπλής απάντησης είναι σαν μια πολλαπλή επιλογή, εκτός από το ότι αντί να απαιτείται να κάνετε το πολύ μία επιλογή, ο χρήστης μπορεί να κάνει μία ή περισσότερες από μία επιλογές.");
define('ttQTES' , "Ερώτηση για το δοκίμιο");
define('ttQTESDescription' , "Μια ερώτηση για το δοκίμιο επιτρέπει στον συμμετέχοντα να εισαγάγει μια μακρά απάντηση κειμένου ελεύθερου εύρους σε μια ερώτηση.");
define('ttQTYN' , "Ναι όχι");
define('ttQTYNDescription' , "Η ερώτηση Ναι / Όχι είναι μια ερώτηση πολλαπλής επιλογής που ζητά από τον συμμετέχοντα να δώσει μια απάντηση \"Ναι\" ή \"Όχι\" σε μια ερώτηση.");
define('ttQTTF' , "Σωστό Λάθος");
define('ttQTTFDescription' , "Μια αληθινή / ψεύτικη ερώτηση είναι μια ερώτηση πολλαπλής επιλογής που ζητά από τον συμμετέχοντα να δώσει μια \"αληθινή\" ή \"ψευδή\" απάντηση σε μια ερώτηση.");
define('ttQTNM' , "Αριθμητικός");
define('ttQTNMDescription' , "Σε μια Αριθμητική Ερώτηση, ο συμμετέχων απαντά πληκτρολογώντας είτε έναν ολόκληρο αριθμό είτε έναν πραγματικό αριθμό.");
define('ttQTTM' , "Ταίριασμα κειμένου");
define('ttQTTMDescription' , "Σε μια ερώτηση για την αντιστοίχιση κειμένου, ο συμμετέχων πληκτρολογεί με μία λέξη ή μερικές λέξεις για να δείξει την απάντησή του.");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Μια ερώτηση Hotspot είναι μια ερώτηση drag-and-drop μόνο με μία σωστή περιοχή.");
define('ttQTPL' , "Τραβήξτε τον κατάλογο");
define('ttQuesionid' , "Αναγνωριστικό ερωτήματος");
define('ttQuestionNotes' , "Περιγραφή");
define('ttQuestionsend' , "Αποστολή αναφοράς");
define('ttQuestionreporting' , "Για να αναφέρετε περισσότερες ερωτήσεις, πρέπει να αφήσετε το πεδίο id κενό");
define('ttRandom' , "Τυχαίος");
define('ttRefresh' , "Φρεσκάρω");
define('ttRegister' , "Κανω ΕΓΓΡΑΦΗ");
define('ttRegistrations' , "Εγγραφές");
define('ttRegEnd' , "Κατάργηση καταχώρισης");
define('ttRenewPassword' , "Ανανέωση κωδικού πρόσβασης");
define('ttReset' , "Επαναφορά");
define('ttResetPassword' , "Επαναφέρετε τον κωδικό πρόσβασης");
define('ttRole' , "Ρόλος");
define('ttRooms' , "Δωμάτια");
define('ttSave' , "Αποθηκεύσετε");
define('ttSaveAnswerInfo' , "Αποθήκευση πληροφοριών απάντησης");
define('ttSaveLanguageFiles' , "Αποθήκευση αρχείων γλώσσας");
define('ttSaveLanguageXML' , "Αποθήκευση αρχείων γλώσσας XML");
define('ttSaveQuestionInfo' , "Αποθήκευση πληροφοριών ερωτήσεων");
define('ttScore' , "Σκορ");
define('ttScoreFinal' , "Τελικό σκορ");
define('ttScoreTest' , "Αποτέλεσμα δοκιμής");
define('ttScoreType' , "Τύπος βαθμολογίας");
define('ttScoreMin' , "Ελάχιστη βαθμολογία");
define('ttSelectSubject' , "Επιλέξτε Θέμα");
define('ttSelectSubjectBefore' , "Επιλέξτε ένα θέμα πριν");
define('ttSet' , "Σειρά");
define('ttSetPassword' , "Ορίστε τον κωδικό πρόσβασής σας");
define('ttSettings' , "Ρυθμίσεις");
define('ttShowHide' , "Εμφάνιση απόκρυψη");
define('ttSelectSubQuestion' , "Επιλέξτε μια υποQuestion");
define('ttSkin' , "Δέρμα");
define('ttStart' , "Αρχή");
define('ttStarted' , "Ξεκίνησε");
define('ttStop' , "Να σταματήσει");
define('ttStopped' , "Σταμάτησε");
define('ttStartTest' , "Ξεκινήστε τη δοκιμή");
define('ttStatus' , "Κατάσταση");
define('ttStats' , "Στατιστικά στοιχεία");
define('ttStudent' , "Μαθητης σχολειου");
define('ttStudents' , "Φοιτητές");
define('ttST10' , "Δέκατα");
define('ttST30' , "Τριάντα");
define('ttST100' , "Εκατοστός");
define('ttSubject' , "Θέμα");
define('ttSubjects' , "μαθήματα");
define('ttSubmit' , "υποβάλλουν");
define('ttSurname' , "Επώνυμο");
define('ttSystem' , "Σύστημα");
define('ttSystemConfiguration' , "Διαμόρφωση συστήματος");
define('ttSbjVers' , "Εκδοχή");
define('ttTeacher' , "Δάσκαλος");
define('ttTeachers' , "Δάσκαλοι");
define('ttTest' , "Δοκιμή");
define('ttTests' , "Δοκιμές");
define('ttTestToCorrect' , "Δοκιμές για διόρθωση");
define('ttText' , "Κείμενο");
define('ttTime' , "χρόνος");
define('ttTimeEnd' , "Τέλος χρόνου");
define('ttTimeStart' , "Ώρα έναρξης");
define('ttTimeUsed' , "Χρόνος που χρησιμοποιήθηκε");
define('ttTimeZone' , "Ζώνη ώρας");
define('ttTitle' , "Τίτλος");
define('ttTopic' , "Θέμα");
define('ttTopics' , "Θέματα");
define('ttTopicsAndQuestions' , "Θέματα και Ερωτήσεις");
define('ttTopicsQuestions' , "Ερωτήσεις ανά Θέματα");
define('ttTranslations' , "Μεταφράσεις");
define('ttTrue' , "Αληθής");
define('ttType' , "Τύπος");
define('ttUser' , "Χρήστης");
define('ttUsers' , "Χρήστες");
define('ttView' , "Θέα");
define('ttWelcome' , "καλως ΗΡΘΑΤΕ");
define('ttWaiting' , "Αναμονή");
define('ttWarning' , "Προειδοποίηση");
define('ttYes' , "Ναί");
define('ttAssesmentOverview' , "Αναφορά επισκόπησης αξιολόγησης");
define('ttDeselectAll' , "Αποεπιλογή όλων");
define('ttErrorUserParameter' , "Επιλέξτε μια λεπτομέρεια συμμετέχοντα για να συνεχίσετε!");
define('ttQuestionerror' , "Αναγνωριστικό ερωτήματος");
define('ttRemove' , "Αφαιρώ");
define('ttReportCoachingError' , "Επιλέξτε μια αξιολόγηση και έναν συμμετέχοντα για να συνεχίσετε");
define('ttReportCoachingError2' , "Επιλέξτε αξιολόγηση για να συνεχίσετε");
define('ttReportErrorStudent' , "Ο επιλεγμένος φοιτητής δεν συμμετείχε σε επιλεγμένες εξετάσεις");
define('ttReportMainAO' , "Κύριος");
define('ttReportTemplateDeleteFailed' , "Η διαγραφή απέτυχε");
define('ttReportTemplateDelet' , "Το πρότυπο διαγράφηκε");
define('ttReportTemplateLoaded' , "Πρότυπο caricato correttamente");
define('ttReportTemplateSaveError' , "Εισαγάγετε ένα όνομα προτύπου χωρίς χώρο!");
define('ttReportTemplateSaved' , "Το πρότυπο αποθηκεύτηκε σωστά");
define('ttReportTemplateDuplicateError' , "Το όνομα προτύπου υπάρχει ήδη!");
define('ttReportScoreFilter' , "Αν έχετε ήδη επιλέξει έναν συμμετέχοντα, τώρα επιλέξτε ξανά ένα νέο");
define('ttSelectAll' , "Επιλογή όλων");
define('ttQTFB' , "Συμπλήρωσε τα κενά");
define('ttQTFB_TEXT' , "Συμπληρώστε το ακόλουθο κείμενο με τις κατάλληλες λέξεις");
define('ttQTFBDescription' , "Σε μια συμπλήρωση κενών ερωτήσεων ο συμμετέχων πρέπει να συμπληρώσει το κείμενο με τη σωστή απάντηση στο πεδίο κειμένου");
define('ttPosterImageVideo' , "Φόρτωση λογοτύπου");
define('ttWidthVideo' , "Πλάτος");
define('ttHeightVideo' , "Υψος");
define('ttIdVideo' , "Κωδικός αναγνώρισης");
define('ttVideoTypeVideo' , "Βίντεο μορφή");
define('ttNumberOfPlaysVideo' , "Μέγιστος αριθμός αναπαραστάσεων");
define('ttToolbarVideo' , "βίντεο");
define('ttDialogTitleVideo' , "Ιδιότητα βίντεο");
define('ttFakeObjectVideo' , "βίντεο");
define('ttPropertiesVideo' , "Επεξεργασία βίντεο");
define('ttWidthRequiredVideo' , "Το πλάτος πρέπει να ρυθμιστεί");
define('ttHeightRequiredVideo' , "Το ύψος πρέπει να ρυθμιστεί");
define('ttNumberOfPlayRequiredVideo' , "Πρέπει να οριστεί ο μέγιστος αριθμός αναπαραγωγών");
define('ttFallbackTemplateVideo' , "Το πρόγραμμα περιήγησής σας δεν υποστηρίζει βίντεο HTML5");
define('ttBrowseVideo' , "Αναζήτηση διακομιστή");
define('ttsourceVideo' , "Πηγή βίντεο");
define('ttNumberOfPlayAlertVideo' , "Έχετε φτάσει στον μέγιστο αριθμό αναπαραγωγών του βίντεό σας");
define('ttHelpDefault' , "Πίνακας πληροφοριών");
define('ttHelpDefaultDescription' , "Πατήστε αυτό το κουμπί για να δείτε μια περιγραφή του τι μπορείτε να κάνετε");
define('ttHelpQuestion' , "Επιλέξτε μια ερώτηση για να διαβάσετε τα περιεχόμενά της ή κάντε διπλό κλικ για επεξεργασία");
define('ttHelpADMINNewTeacherDescription' , "Καθορίστε το λογαριασμό ενός νέου διαχειριστή, εκπαιδευτή ή εξεταστή");
define('ttHelpADMINNewStudentDescription' , "Καθορίστε το λογαριασμό ενός νέου φοιτητή");
define('ttHelpADMINSelLanguageDescription' , "Επιλέξτε μια γλώσσα που θέλετε να διαχειριστείτε");
define('ttHelpADMINLanguageDescription' , "Εδώ μπορείτε να αλλάξετε τις τοποθεσίες των λέξεων που χρησιμοποιούνται από το σύστημα");
define('ttHelpADMINSystemConf' , "Εδώ μπορείτε να αλλάξετε τις ρυθμίσεις EOL, προσέξτε");
define('ttHelpADMINRoom' , "Ορίστε τους χώρους όπου θα διεξαχθούν οι δοκιμές");
define('ttHelpADMINImport' , "Αυτή η οθόνη σάς επιτρέπει να εισάγετε νέες ερωτήσεις στο ερωτηματικό");
define('ttHelpADMINProfile' , "Αυτή η οθόνη σάς επιτρέπει να επεξεργαστείτε το προφίλ σας");
define('ttHelpReportAreport' , "Αυτή η οθόνη σας επιτρέπει να δημιουργήσετε ένα Areport, είναι υποχρεωτικό να επιλέξετε τουλάχιστον ένα θέμα");
define('ttHelpReportAreportTemplate' , "Επιλέξτε ποιες πληροφορίες μπορείτε να βρείτε στην Αναφορά");
define('ttHelpReportCreport' , "Αυτή η οθόνη σας επιτρέπει να δημιουργήσετε ένα Creport, είναι υποχρεωτικό να επιλέξετε έναν συμμετέχοντα");
define('ttHelpReportCreportlist' , "Επιλέξτε την εξέταση για να δημιουργήσετε την αναφορά");
define('ttHelpStudent' , "Αριστερά είναι οι διαθέσιμες δοκιμές, στα δεξιά οι επιλεγμένες λεπτομέρειες εξέτασης");
define('ttHelpStudentTest' , "Βρίσκεστε στην οθόνη εξετάσεων, απαντήστε στις ερωτήσεις και υποβάλετε τη δοκιμή");
define('ttHelpAdminErrorQuestion' , "Εάν εντοπίσετε προβλήματα που μπορείτε να αναφέρετε από αυτήν τη σελίδα.");
define('ttHelpExamsCorrect' , "Εδώ λαμβάνετε μια εξέταση από έναν φοιτητή, ελέγχετε ότι η διόρθωση έγινε σωστά και, στη συνέχεια, επιβεβαιώστε την ψηφοφορία.");
define('ttHelpExamsSettings' , "Σε αυτή την οθόνη μπορείτε να ορίσετε ή να αλλάξετε τις ρυθμίσεις που θα χρησιμοποιηθούν σε μελλοντικές εξετάσεις.");
define('ttQTPLDescription' , "Το Dropdown είναι μια ερώτηση κλειστού τύπου που επιτρέπει στους ερωτώμενους να επιλέξουν μία επιλογή απαντήσεων από μια λίστα επιλογών που παρουσιάζονται σε ένα αναπτυσσόμενο μενού. Εάν θέλετε να εμφανίσετε τις επιλογές απάντησης ως κουμπιά επιλογής ή κουτάκια επιλογής, χρησιμοποιήστε την ερώτηση πολλαπλής επιλογής");
define('ttQuestionsubPL' , "Υποερωτήσεις");
define('ttHelpLog' , "Ένα αρχείο καταγραφής θα δημιουργηθεί αυτόματα μετά την αλλαγή μιας ερώτησης που έχει ήδη αντιστοιχιστεί σε μια δοκιμή.");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Ομάδα");
define('ttSubgroup' , "Υποομάδα");
define('ttAOreportSaved' , "Όλες οι αναφορές που δημιουργούνται θα αποθηκευτούν στο διακομιστή.");
define('ttReport' , "Κανω ΑΝΑΦΟΡΑ");
define('ttReportAllFinished' , "Ολα τελειωσαν");
define('ttReportAODescription' , "Αν δεν επιλέξετε συγκεκριμένες αξιολογήσεις, θα αναλυθεί ολόκληρη η αξιολόγηση");
define('ttReportAOWelcome' , "Επιλέξτε μια καρτέλα οδηγιών αξιολόγησης και χρήσης για να φιλτράρετε δεδομένα");
define('ttReportAOSelectAssesment' , "Επιλέξτε αξιολογήσεις για την αναφορά");
define('ttReportAssesmentAuthor' , "Συγγραφέας αξιολόγησης");
define('ttReportAssessmentInformation' , "Πληροφορίες αξιολόγησης");
define('ttReportAssesmentID' , "Αναγνωριστικό αξιολόγησης");
define('ttReportAssesmentDateTimeFirst' , "Ημερομηνία / Ώρα που έχετε πάρει για πρώτη φορά");
define('ttReportAssesmentDateTimeLast' , "Ημερομηνία / ώρα που λήφθηκε τελευταία");
define('ttReportAssesmentLeastTimeFinished' , "Λιγότερος χρόνος για τους τελειωμένους");
define('ttReportAssesmentName' , "Όνομα αξιολόγησης");
define('ttReportAssesmentNumberStarted' , "Αριθ.");
define('ttReportAssesmentNumberNotFinished' , "Αριθ.");
define('ttReportAssesmentNumberFinished' , "Αριθ.");
define('ttReportAssesmentMinscoreFinished' , "Ελάχιστο σκορ από αυτά που έχουν τελειώσει");
define('ttReportAssesmentMaxcoreFinished' , "Μέγιστο σκορ από αυτά που έχουν τελειώσει");
define('ttReportAssesmentMediumFinished' , "Μεσαίο σκορ από αυτά που έχουν τελειώσει");
define('ttReportAssesmentMediumTimeFinished' , "Μεσοπρόθεσμος χρόνος για τους τελειωμένους");
define('ttReportAssesmentMostTimeFinished' , "Ο περισσότερος χρόνος για τους τελειωμένους");
define('ttReportAssesmentScore' , "Φιλτράρετε με βάση βαθμολογίες");
define('ttReportAssesmentStdDeviation' , "Τυπική απόκλιση για τα τελειωμένα");
define('ttReportChecked' , "Επιλεγμένο");
define('ttReportCoaching' , "Έκθεση καθοδήγησης");
define('ttReportCWelcome' , "Επιλέξτε μια αξιολόγηση και έναν συμμετέχοντα");
define('ttReportCDescription' , "Θα πρέπει να φιλτράρετε τα δεδομένα κατά ημερομηνίες και, αν θέλετε, επίσης με σκορ");
define('ttReportCoachingDescription' , "Δείτε αναλυτικά αποτελέσματα για έναν συμμετέχοντα λαμβάνοντας μια αξιολόγηση");
define('ttReportCoachingInformation' , "Επιλέξτε μια δοκιμή για να δείτε λεπτομερείς πληροφορίες");
define('ttReportCustomize' , "Προσαρμόστε την αναφορά σας");
define('ttReportDateInterval' , "Ημερομηνίες διάστημα");
define('ttReportDateFrom' , "Από");
define('ttReportDateTaken' , "Ημερομηνία λήψης");
define('ttReportDateTo' , "προς το");
define('ttReportErrorDetail' , "Επιλέξτε έναν συμμετέχοντα για να δείτε λεπτομέρειες");
define('ttReportField' , "Ονομα πεδίου");
define('ttReportGraphicalDsiplays' , "Γραφικές απεικονίσεις");
define('ttReportGraphicHistogram' , "Ιστορικό βαθμολογίας αξιολόγησης");
define('ttReportGraphicTopicScore' , "Ιστορικό βαθμολογίας θεμάτων");
define('ttReportGroup' , "Ομάδες");
define('ttReportGroupNotPresent' , "Δεν υπάρχουν ομάδες");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Φιλτράρετε με ελάχιστο σκορ");
define('ttReportMaximumScore' , "Φιλτράρετε κατά μέγιστο σκορ");
define('ttReportNotFilter' , "Μην χρησιμοποιείτε φίλτρο");
define('ttReportOrder' , "Σειρά");
define('ttReportPartecipants' , "Συμμετέχοντες");
define('ttReportPartecipant' , "Συμμέτοχος");
define('ttReportScheduled' , "Πρόγραμμα");
define('ttReportScoreBand' , "Φιλτράρετε με βάση τη βαθμολογία");
define('ttReportSearch' , "Ψάξιμο...");
define('ttReportSearched' , "Αποτέλεσμα αναζήτησης");
define('ttReportSelectDetail' , "Επιλέξτε το αναγνωριστικό χρήστη ή το ηλεκτρονικό ταχυδρομείο του συμμετέχοντα που επιλέξατε πριν");
define('ttReportSelectFilter' , "Επιλέξτε φίλτρο");
define('ttReportSelectGroup' , "Επιλέξτε ομάδες φιλτραρίσματος");
define('ttReportSelectLetter' , "Γράμμα");
define('ttReportAOSelectPartecipant' , "Επιλέξτε συμμετέχοντα");
define('ttReportSelected' , "Επιλεγμένες αξιολογήσεις");
define('ttReportSelectTemplate' , "Επιλέξτε ένα πρότυπο");
define('ttReportSelectedGroup' , "Επιλεγμένες ομάδες");
define('ttReportSearchByLetter' , "Αναζήτηση με επιστολή");
define('ttReportStudent' , "Φιλτράρετε στο συμμετέχοντα");
define('ttReportStudentNotPresent' , "Δεν υπάρχουν μαθητές");
define('ttReportStudentDetail' , "Φιλτράρετε στις λεπτομέρειες του συμμετέχοντα");
define('ttReportTemplateLoad' , "Επιλέξτε ένα πρότυπο για φόρτωση");
define('ttReportTemplateSave' , "Αποθηκεύστε το πρότυπο ως");
define('ttReportTemplateName' , "Εισαγάγετε το όνομα");
define('ttReportTimedOut' , "Ο χρόνος εξαντλήθηκε");
define('ttReportTopicAverageScore' , "Μέσος όρος");
define('ttReportTopicInformation' , "Πληροφορίες για το θέμα");
define('ttReportTopicMaximumScore' , "Μέγιστη βαθμολογία");
define('ttReportTopicMinimumScore' , "Ελάχιστη βαθμολογία");
define('ttReportTopicName' , "Όνομα θεμάτων");
define('ttReportTopicStandardDeviation' , "Τυπική απόκλιση");
define('ttReportTyping' , "Αναζήτηση με πληκτρολόγηση");
define('ttReportQuestionType' , "ΕΙΔΟΣ ΕΡΩΤΗΣΗΣ");
define('ttReportViewer' , "Αναφορά προβολής");
define('ttReportViewerDescription' , "Δείτε όλες τις αναφορές που δημιουργούνται και τις διαχειριστείτε");
define('ttStudentDetailCreport' , "Στοιχεία σπουδαστών");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Πιστοποιητικά");
define('ttCertificate' , "Πιστοποιητικό");
define('ttNewGroup' , "Προσθήκη ομάδας");
define('ttEditGroup' , "Επεξεργασία ομάδας");
define('ttEditTeacher' , "Επεξεργασία καθηγητή");
define('ttEditStudent' , "Επεξεργασία φοιτητή");
define('tteTeacher' , "Εξεταστής");
define('tttotals' , "Σύνολο");
define('ttD1s' , "Εύκολος");
define('ttD2s' , "Μεσαίο");
define('ttD3s' , "Σκληρά");
define('ttSelectStudent' , "Λίστα σπουδαστών");
define('ttSelectTeacher' , "Λίστα καθηγητών");
define('ttCoord' , "Συντεταγμένες");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "Η λίστα των εξετάσεων εμφανίζεται εδώ.");
define('ttHelpSubject' , "Εδώ θα δείτε μια λίστα με τα μαθήματα που διδάσκετε.");
define('ttNotAvailable' , "Οι επιλεγμένες ρυθμίσεις δεν σας επιτρέπουν να δημιουργήσετε μια δοκιμή.");
define('ttSelectGroup' , "Επεξεργαστείτε ομάδες ή υποομάδες");
define('ttConfirmProcedure' , "Θέλετε πραγματικά να το κάνετε αυτό;");
define('ttUserDeleted' , "Ο χρήστης διαγράφηκε σωστά");
define('ttMGroupCreated' , "Η ομάδα δημιουργήθηκε με επιτυχία");
define('ttMSubgroupCreated' , "Η υποομάδα δημιουργήθηκε με επιτυχία");
define('ttNewSubgroup' , "Προσθήκη υποομάδας");
define('ttErrorTopic' , "Έχουν επιλεγεί υπερβολικά πολλά ερωτήματα για θέματα");
define('ttAvailable' , "διαθέσιμα ερωτήματα");
define('ttThereAreNot' , "Δεν υπάρχουν");
define('ttErrorMax' , "Αυτό το πεδίο δεν μπορεί να είναι μικρότερο από τον αριθμό των επιλεγμένων υποχρεωτικών ερωτήσεων");
define('ttField' , "Το πεδίο");
define('ttHard' , "Σκληρά");
define('ttMedium' , "Μεσαίο");
define('ttEasy' , "Εύκολος");
define('ttMustBeaNumber' , "Πρέπει να είναι ένας αριθμός");
define('ttMaxHardReached' , "Μέγιστος αριθμός σκληρών ερωτήσεων που έχουν ήδη επιτευχθεί");
define('ttMaxMediumReached' , "Μέγιστος αριθμός μέσων ερωτήσεων που έχουν ήδη επιτευχθεί");
define('ttMaxEasyReached' , "Μέγιστος αριθμός εύκολων ερωτήσεων που έχουν ήδη επιτευχθεί");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Εάν κάνετε κλικ στο κουμπί ναι, η εξέταση μαθημάτων θα μεταφερθεί αυτόματα στο σύστημα στην τρέχουσα κατάσταση.");
define('ttProfCert' , "Πιστοποιητικό ικανότητας");
define('ttCertify' , "Αυτό γίνεται για να επιβεβαιωθεί ότι");
define('ttSuccess' , "έχει περάσει επιτυχώς");
define('ttEvaluation' , "με αξιολόγηση");
define('ttAccreditedTestSite' , "στο διαπιστευμένο site δοκιμών του");
define('ttOn' , "επί");
define('ttNumQuestionsTopic' , "Αριθμός ερωτήσεων για κάθε θέμα");
define('ttParamNotSet' , "Λείπουν παραμέτρους");
define('ttNotEnoughQuestions' , "Δεν υπάρχουν αρκετές ερωτήσεις");
define('ttExamArchivedCertNot' , "Η εξέταση αρχειοθετείται, αλλά δεν έχουν δημιουργηθεί πιστοποιητικά");
define('ttSendCertificate' , "Λήψη πιστοποιητικού");
define('ttCertificateAlert' , "Είστε βέβαιοι ότι θέλετε να δημιουργήσετε και να λάβετε το πιστοποιητικό εξέτασης στον σπουδαστή;");
define('ttCertificateScore' , "Ο φοιτητής δεν έχει το ελάχιστο σκορ για να λάβει πιστοποιητικό");
define('ttCertificateGenerated' , "Το πιστοποιητικό δημιουργήθηκε σωστά");
define('ttBut' , "αλλά");
define('ttAnd' , "και");
define('ttCertificateEmailSended' , "το email αποστέλλεται με επιτυχία");
define('ttCertificateGeneratedProblem' , "Το πιστοποιητικό δεν δημιουργήθηκε!");
define('ttCertificatePoint' , "Η βαθμολογία φοιτητών είναι πολύ χαμηλή και δεν μπορεί να εκδοθεί πιστοποιητικό.");
define('ttPrivacy1' , "Διάβασα και δέχτηκα το");
define('ttPrivacy2' , "Πολιτική Απορρήτου του ECTN");
define('ttPrivacy3' , "Επιθυμώ να ενημερώνομαι για τη δυνατότητα απόκτησης πιστοποιητικού ατομικής επάρκειας");
define('ttDemoTest' , "Demo test");
define('ttEExportEmptySub', "το θέμα είναι κενό.");
define('ttEExportNoAnswers', "υπάρχει μια ερώτηση χωρίς δοκιμές χωρίς απαντήσεις.");
define('ttEExportNotEnAnswers', "δεν υπάρχουν αρκετές απαντήσεις για ορισμένες ερωτήσεις");