<?php
define('ttAccountActivation' , "Aktywacja konta");
define('ttActive' , "Aktywny");
define('ttActivate' , "Aktywuj");
define('ttAdd' , "Dodaj");
define('ttAddSelectedStudents' , "Dodaj wybranych uczniów");
define('ttAdministration' , "Podawanie");
define('ttAdministrator' , "Administrator");
define('ttAdminWelcome' , "Witamy w panelu administracyjnym.");
define('ttAlias' , "Kod ISO 639-1");
define('ttAndExit' , "i Wyjdź");
define('ttAnswer' , "Odpowiedź");
define('ttAnswers' , "Odpowiedzi");
define('ttArchive' , "Archiwum");
define('ttArchived' , "Zarchiwizowane");
define('ttAssignSubject' , "Przypisz podmiot");
define('ttAutomatic' , "Automatyczny");
define('ttAImportComplete' , "Pytania Import już zakończony");
define('ttBasedOn' , "Oparte na");
define('ttBlocked' , "Zablokowany");
define('ttBlock' , "Blok");
define('ttUnblock' , "Odblokować");
define('ttBonus' , "Premia");
define('ttCancel' , "Anuluj");
define('ttChangeLanguage' , "Zmień język");
define('ttChangeVersion' , "Zmień wersję testową");
define('ttCheck' , "Czek...");
define('ttClose' , "Blisko");
define('ttClosed' , "Zamknięte");
define('ttCorrect' , "Poprawny");
define('ttConfiguration' , "Konfiguracja");
define('ttConfirm' , "Potwierdzać");
define('ttConfirmEmail' , "Potwierdź email");
define('ttConfirmPassword' , "Potwierdź hasło");
define('ttCreate' , "Stwórz");
define('ttCArchiveExam' , "Czy na pewno zarchiwizujesz egzamin?");
define('ttCBlockTest' , "Czy na pewno chcesz zablokować ten test?");
define('ttCChangeStatus' , "Czy na pewno zmienisz status pytania na _STATUS_?");
define('ttCConfirmTest' , "Czy chcesz potwierdzić wynik testu?");
define('ttCDeleteAnswer' , "Czy na pewno chcesz usunąć tę odpowiedź i jej tłumaczenia?");
define('ttCDeleteExam' , "Czy na pewno chcesz usunąć ten egzamin?");
define('ttCDeleteQuestion' , "Czy na pewno chcesz usunąć to pytanie i jego tłumaczenia?");
define('ttCDeleteRoom' , "Czy na pewno chcesz usunąć ten pokój?");
define('ttCDeleteSubject' , "Czy na pewno chcesz usunąć ten temat?");
define('ttCDeleteSettings' , "Czy na pewno chcesz usunąć te ustawienia testowe?");
define('ttCDeleteTopic' , "Czy na pewno chcesz usunąć ten temat?");
define('ttCDiscardEdits' , "Twoje zmiany zostaną utracone.");
define('ttCDiscardNew' , "Utworzony element zostanie utracony.");
define('ttCRegister' , "Czy na pewno chcesz zarejestrować się na tym egzaminie?");
define('ttCRegisterStudents' , "Czy na pewno chcesz zarejestrować tych wybranych uczniów na egzaminie?");
define('ttCRenewPassword' , "Hasło egzaminu zostanie zmienione.");
define('ttCStartExam' , "Czy chcesz aktywować wybrany egzamin?");
define('ttCStartTest' , "Czy chcesz teraz rozpocząć egzamin?");
define('ttCStopExam' , "Czy chcesz dezaktywować wybrany egzamin?");
define('ttCSubmitTest' , "Czy chcesz przesłać test?");
define('ttCTest' , "Hasło jest poprawne.");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Czy na pewno chcesz odblokować ten test?");
define('ttCUpdateConfigurations' , "Czy na pewno chcesz zapisać nowe konfiguracje systemu?");
define('ttCUpdateLanguage' , "Czy na pewno chcesz zaktualizować pliki językowe?");
define('ttD1' , "Łatwy");
define('ttD2' , "Średni");
define('ttD3' , "Ciężko");
define('ttDatabaseConfiguration' , "Konfiguracja bazy danych");
define('ttDay' , "Dzień");
define('ttDelete' , "Kasować");
define('ttDescription' , "Opis");
define('ttDifficulty' , "Trudność");
define('ttDifficultyQuestions' , "Pytania na poziom trudności");
define('ttDistribution' , "Dystrybucja");
define('ttDo' , "Zrób egzamin");
define('ttDTAnswerInfo' , "Pokazuje _TOTAL_ odpowiedzi");
define('ttDTAnswerFiltered' , "(przefiltrowane z odpowiedzi całkowitych _MAX_)");
define('ttDTAnswerEmpty' , "Brak odpowiedzi do pokazania");
define('ttDTExamInfo' , "Pokazywanie _TOTAL_ egzaminów w toku");
define('ttDTExamFiltered' , "(odfiltrowane z łącznej liczby egzaminów _MAX_ w toku)");
define('ttDTExamEmpty' , "Brak egzaminów do pokazania");
define('ttDTQuestionInfo' , "Pokazuje _TOTAL_ pytania");
define('ttDTQuestionFiltered' , "(przefiltrowane z pytań całkowitych _MAX_)");
define('ttDTQuestionEmpty' , "Brak pytań do pokazania");
define('ttDTRegisteredStudentInfo' , "Pokazywanie _TOTAL_ zarejestrowanych studentów");
define('ttDTRegisteredStudentFiltered' , "(odfiltrowane z _MAX_ ogółem zarejestrowanych studentów)");
define('ttDTRegisteredStudentEmpty' , "Brak zarejestrowanych studentów do pokazania");
define('ttDTStudentsInfo' , "Pokazuje _TOTAL_ studentów");
define('ttDTStudentsFiltered' , "(odfiltrowane z ogółu studentów _MAX_)");
define('ttDTStudentsEmpty' , "Brak uczniów do pokazania");
define('ttDTTestInfo' , "Pokazuje test _TOTAL_");
define('ttDTTeacherInfo' , "Pokazuje _TOTAL_ nauczycieli");
define('ttDTTeacherFiltered' , "(odfiltrowane z nauczycieli ogółem _MAX_)");
define('ttDTTeacherEmpty' , "Brak nauczyciela do pokazania");
define('ttDTTestFiltered' , "(przefiltrowane z testów ogółem _MAX_)");
define('ttDTTestEmpty' , "Brak testów do pokazania");
define('ttDone' , "Egzamin wykonany");
define('ttDuration' , "Trwanie");
define('ttDTsubquestionInfo' , "Sub pytania");
define('ttEdit' , "Edytować");
define('ttEditableScore' , "Wynik do edycji");
define('ttError' , "Błąd");
define('ttEmail' , "E-mail");
define('ttEnd' , "Koniec");
define('ttEverywhere' , "Wszędzie");
define('ttExam' , "Egzamin");
define('ttExams' , "Egzaminy");
define('ttExit' , "Wyjście");
define('ttExtra' , "Dodatkowy");
define('ttExamsArchive' , "Archiwum");
define('ttExamsInProgress' , "Egzaminy w toku");
define('ttETeachers' , "Egzaminator");
define('ttErrorquestion' , "Zgłoś błąd");
define('ttEActivationFails' , "Aktywacja kończy się niepowodzeniem!");
define('ttEAlreadyRegistered' , "Student jest już zarejestrowany na ten egzamin!");
define('ttEAnswerInSet' , "Operacja nie może zostać zakończona.");
define('ttEAnswerNotFound' , "Nie znaleziono odpowiedzi");
define('ttEAnswers' , "Wystąpił problem z odpowiedziami.");
define('ttEDatabase' , "Błąd bazy danych!");
define('ttEDates' , "Daty są nieprawidłowe!");
define('ttEEditRoomAll' , "Nie można edytować pokoju „All”!");
define('ttEEmailAlreadyRegistered' , "Email już zarejestrowany!");
define('ttEEmailNotRegistered' , "E-mail nie jest zarejestrowany!");
define('ttEEmailNotValid' , "Wpisany e-mail jest nieprawidłowy!");
define('ttEEmailsNotMatch' , "Dwa e-maile się nie zgadzają!");
define('ttEEmptyFields' , "Jedno lub więcej pól jest pustych!");
define('ttEExamArchived' , "Operacja nie może zostać zakończona.");
define('ttEExamNotFound' , "Nie znaleziono egzaminu!");
define('ttEExamNotStarted' , "Nie możesz rozpocząć egzaminu.");
define('ttEExamStarted' , "Operacja nie może zostać zakończona, ponieważ egzamin już się rozpoczął!");
define('ttEExamWaiting' , "Operacja nie może zostać zakończona, ponieważ egzamin nigdy się nie rozpoczął!");
define('ttEExamsNotArchivedDeleteTopic' , "Operacja nie może zostać zakończona, ponieważ co najmniej jeden nie zarchiwizowany egzamin zawiera pytania z tego tematu!");
define('ttEExamsNotArchivedEditTestSettings' , "Operacja nie może zostać zakończona, ponieważ te ustawienia są używane przez co najmniej jeden niezarchiwizowany egzamin.");
define('ttEExamsNotArchivedDeleteTestSettings' , "Operacja nie może zostać zakończona, ponieważ te ustawienia są używane przez co najmniej jeden nie zarchiwizowany egzamin!");
define('ttEIncorrectField' , "Jedno lub więcej pól jest niepoprawnych!");
define('ttELogin' , "E-mail i / lub hasło są nieprawidłowe!");
define('ttEMainLanguageEmpty' , "Główny język tematu nie może być pusty!");
define('ttEMandatoryQuestion' , "Jest to obowiązkowe pytanie dotyczące ustawienia testu „_TESTSETTING_”: nie można go usunąć ani edytować jego trudności lub tematu.");
define('ttENotAuthorized' , "Twój klient nie jest autoryzowany.");
define('ttENoStudentsToRegister' , "Żaden student nie może się zarejestrować!");
define('ttENoTopicsForSubject' , "Brak tematu na ten temat!");
define('ttEOldPasswordWrong' , "Stare hasło jest nieprawidłowe!");
define('ttEPassword' , "Złe hasło!");
define('ttEPasswordShort' , "Hasło jest za krótkie.");
define('ttEPasswordsNotMatch' , "Dwa hasła nie pasują!");
define('ttEQuestAnswPicker' , "Błąd podczas wybierania pytań i odpowiedzi.");
define('ttEQuestionInSet' , "Operacja nie może zostać zakończona.");
define('ttEQuestionNotFound' , "Nie znaleziono pytania!");
define('ttEQuestionType' , "Nieprawidłowy typ pytania!");
define('ttERegFailedQuestions' , "Rejestracja nie powiodła się: zbyt mało pytań!");
define('ttERoomAllDelete' , "Nie można usunąć pokoju „All”!");
define('ttERoomUsed' , "Operacja nie może zostać zakończona.");
define('ttESaveBeforeNew' , "Przed utworzeniem nowego przedmiotu zapisz lub anuluj już utworzony.");
define('ttESelectQuestionType' , "Musisz wybrać jeden z dostępnych typów pytań!");
define('ttESelectSubject' , "Musisz wybrać jeden ze swoich przedmiotów!");
define('ttESelectTestSettings' , "Musisz wybrać jedno z ustawień testowych!");
define('ttESetNotFound' , "Nie znaleziono zestawu pytań!");
define('ttETestAlreadyArchived' , "Operacja nie może zostać zakończona.");
define('ttETestAlreadySubmitted' , "Operacja nie może zostać zakończona.");
define('ttETestBlockedSubmitted' , "Operacja nie może zostać zakończona.");
define('ttETestNotArchived' , "Operacja nie może zostać zakończona.");
define('ttETestNotFound' , "Nie znaleziono testu!");
define('ttETestsNotArchived' , "Niektóre testy nie zostały zarchiwizowane!");
define('ttETestSettingDeleteQuestion' , "Operacja nie może zostać zakończona.");
define('ttETestSettingDeleteTopic' , "Operacja nie może zostać zakończona.");
define('ttETimeExpired' , "Dostępny czas upłynął!");
define('ttETranslationExists' , "Tłumaczenie wybranego języka już istnieje!");
define('ttEUserNotFound' , "Użytkownik nie znaleziony!");
define('ttEValues' , "Niektóre wartości są nieprawidłowe!");
define('ttFalse' , "Fałszywy");
define('ttFinalScore' , "Wynik końcowy");
define('ttGeneralInformations' , "Informacje ogólne");
define('ttHours' , "godziny");
define('ttHome' , "Dom");
define('ttHomepage' , "Strona główna");
define('ttHost' , "Gospodarz");
define('ttHAnswPanel' , "Kliknij dwukrotnie, aby edytować wybraną odpowiedź");
define('ttHQuestLanguagesPanel' , "Kliknij, aby pokazać tłumaczenie wybranego pytania");
define('ttHQuestPanel' , "Jedno kliknięcie umożliwia wybranie i wyświetlenie podglądu pytania oraz dwukrotne kliknięcie w celu edycji pytania i udzielenia odpowiedzi.");
define('ttHQuestPreviewPanel' , "Odpowiedzi z pomarańczowym tłem nie są tłumaczone na żądany język");
define('ttHQuestTopicPanel' , "Pojedyncze kliknięcie, aby filtrować pytania i podwójnie kliknąć, aby edytować informacje o temacie");
define('ttInfo' , "Informacje");
define('ttIPEnd' , "Koniec IPv4");
define('ttIPStart' , "IPv4 Start");
define('ttInactive' , "Nieaktywny");
define('ttImportQM' , "Import");
define('ttImport' , "Importuj QM");
define('ttImportComplete' , "Import zakończony pomyślnie");
define('ttJoin' , "Przystąpić");
define('ttLanguage' , "Język");
define('ttLanguages' , "Języki");
define('ttLogin' , "Zaloguj Się");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Logowanie zakończone!");
define('ttLogout' , "WYLOGUJ");
define('ttMailLostPassword' , "Aby zresetować hasło do konta, kliknij poniższy link: _LINK_ Jeśli nie zażądałeś zresetowania hasła, zignoruj ​​ten e-mail.");
define('ttMailCredentials' , "Drogi _USERNAME_, Twoje hasło powiązane z kontem _USEREMAIL_ zostało zmodyfikowane zgodnie z twoją prośbą.");
define('ttMailNewTeacher' , "Witaj w _SYSTEMNAME_.");
define('ttMainLanguage' , "Główny język");
define('ttManage' , "Zarządzanie");
define('ttMandatory' , "Obowiązkowy");
define('ttManual' , "podręcznik");
define('ttMinutes' , "minuty");
define('ttMyExams' , "Moje egzaminy");
define('ttMySettings' , "Moje ustawienia");
define('ttMySubjects' , "Wybierz temat");
define('ttMActivation' , "Hasło zostało pomyślnie ustawione.");
define('ttMAnswerDeleted' , "Odpowiedź została pomyślnie usunięta");
define('ttMConfigurationsUpdated' , "Konfiguracja systemu została pomyślnie zaktualizowana");
define('ttMConfirm' , "Test został pomyślnie potwierdzony i zarchiwizowany");
define('ttMUserCreated' , "Tworzenie zakończone: wysłano do Ciebie wiadomość e-mail, aby dokończyć rejestrację.");
define('ttMEdit' , "Zmiany zostały pomyślnie zapisane");
define('ttMExamArchived' , "Egzamin pomyślnie zarchiwizowany");
define('ttMExamDeleted' , "Egzamin został pomyślnie usunięty");
define('ttMExamStarted' , "Egzamin został pomyślnie rozpoczęty");
define('ttMExamStopped' , "Egzamin został pomyślnie zatrzymany");
define('ttMLanguageCreated' , "Tłumaczenie zostało pomyślnie utworzone");
define('ttMLanguageSaved' , "Tłumaczenie zostało pomyślnie zapisane");
define('ttMLanguageUpdated' , "Tłumaczenie zostało pomyślnie zaktualizowane");
define('ttMNewAnswer' , "Odpowiedź została pomyślnie utworzona");
define('ttMNewQuestion' , "Pytanie zostało pomyślnie utworzone");
define('ttMNewRoom' , "Pomyślnie utworzono pokój");
define('ttMNewSettings' , "Pomyślnie utworzono ustawienia testowe");
define('ttMNewSubject' , "Temat pomyślnie utworzony");
define('ttMNewTopic' , "Temat pomyślnie utworzony");
define('ttMPasswordRenewed' , "Hasło egzaminu zostało pomyślnie odnowione");
define('ttMQuestionDeleted' , "Pytanie zostało pomyślnie usunięte");
define('ttMRegistration' , "Udało Ci się zarejestrować na tym egzaminie");
define('ttMResetConfirmed' , "Żądanie zakończone: wysłano wiadomość e-mail, aby zresetować hasło.");
define('ttMRoomDeleted' , "Pokój został pomyślnie usunięty");
define('ttMSelectLanguage' , "Wybierz język, którym chcesz zarządzać");
define('ttMSettingsDeleted' , "Testowe ustawienia zostały pomyślnie usunięte");
define('ttMStudentsRegistered' , "Studenci pomyślnie zarejestrowali się na egzaminie");
define('ttMSubjectDeleted' , "Temat został pomyślnie usunięty");
define('ttMSubjectQuestions' , "Aby zarządzać tematami i pytaniami, wybierz temat");
define('ttMSubjectSettings' , "Aby zarządzać ustawieniami egzaminu, wybierz temat");
define('ttMTestBlocked' , "Test został pomyślnie zablokowany");
define('ttMTestSubmitted' , "Test został pomyślnie przesłany");
define('ttMTestUnblocked' , "Przetestuj pomyślnie odblokowany");
define('ttMTopicDeleted' , "Temat został pomyślnie usunięty");
define('ttName' , "Imię");
define('ttNumberError' , "Wartość powinna być liczbą całkowitą lub dziesiętną (ES: 12,5)");
define('ttNegativeScores' , "Wyniki negatywne");
define('ttNew' , "Nowy");
define('ttNext' , "Kolejny");
define('ttNewAnswer' , "Nowa odpowiedź");
define('ttNewCredentials' , "Nowe poświadczenia");
define('ttNewLanguage' , "Nowy język");
define('ttNewPassword' , "nowe hasło");
define('ttNewQuestion' , "Nowe pytanie");
define('ttNewRegistration' , "Nowa rejestracja");
define('ttNewRoom' , "Nowy pokój");
define('ttNewTeacher' , "Nowy nauczyciel");
define('ttNewTestSettings' , "Nowe ustawienia");
define('ttNewSubject' , "Nowy przedmiot");
define('ttNewStudent' , "Nowy uczeń");
define('ttNewTopic' , "Nowy temat");
define('ttNewUser' , "Nowy użytkownik");
define('ttNo' , "Nie");
define('ttNoAnswers' , "Brak odpowiedzi na to pytanie");
define('ttNoExams' , "Brak dostępnych egzaminów dla tego przedmiotu");
define('ttNoExamInProgress' , "Brak egzaminu w toku");
define('ttNoInfo' , "Nie ma informacji o tym egzaminie");
define('ttNoQuestions' , "Brak dostępnych pytań na ten temat");
define('ttNoRooms' , "Nie utworzono pokoi: dostępne tylko „Wszystkie”");
define('ttNoSettings' , "Brak ustawień dla tego tematu");
define('ttNoSubjects' , "Brak dostępnych tematów");
define('ttNoTestToCorrect' , "Brak testów do poprawienia");
define('ttNoUserRegistered' , "Brak zarejestrowanych użytkowników do tego egzaminu");
define('ttOldPassword' , "Stare hasło");
define('ttEssayQuestion' , "Pytanie esejowe");
define('ttPassword' , "Hasło");
define('ttPasswordLost' , "Zgubiłeś hasło?");
define('ttPort' , "Port");
define('ttProfile' , "Profil");
define('ttPrepareImportQM' , "Zapowiedź");
define('ttQuestion' , "Pytanie");
define('ttQuestionPreview' , "Podgląd pytania");
define('ttQuestions' , "pytania");
define('ttQEc' , "Kalkulator");
define('ttQEp' , "Układ okresowy");
define('ttQTMC' , "Wielokrotny wybór");
define('ttQTMCDescription' , "W pytaniu wielokrotnego wyboru uczestnik wybiera jeden wybór spośród wielu opcji, aby odpowiedzieć na pytanie.");
define('ttQTMR' , "Odpowiedź wielokrotna");
define('ttQTMRDescription' , "Pytanie z wieloma odpowiedziami jest jak wielokrotny wybór, z tym wyjątkiem, że zamiast wymagać od siebie co najwyżej jednego wyboru, użytkownik może dokonać jednego lub więcej niż jednego wyboru.");
define('ttQTES' , "Esej Pytanie");
define('ttQTESDescription' , "Pytanie esej pozwala uczestnikowi wprowadzić długą, swobodną odpowiedź tekstową na pytanie.");
define('ttQTYN' , "Tak nie");
define('ttQTYNDescription' , "Pytanie Tak / Nie jest pytaniem wielokrotnego wyboru, które prosi uczestnika o udzielenie odpowiedzi „Tak” lub „Nie” na pytanie.");
define('ttQTTF' , "Prawda fałsz");
define('ttQTTFDescription' , "Pytanie Prawda / Fałsz to pytanie wielokrotnego wyboru, które prosi uczestnika o udzielenie odpowiedzi „prawda” lub „fałsz” na pytanie.");
define('ttQTNM' , "Numeryczny");
define('ttQTNMDescription' , "W pytaniu numerycznym uczestnik odpowiada, wpisując liczbę całkowitą lub liczbę rzeczywistą.");
define('ttQTTM' , "Dopasowanie tekstu");
define('ttQTTMDescription' , "W pytaniu Dopasowanie tekstu uczestnik wpisuje jedno słowo lub kilka słów, aby wskazać swoją odpowiedź.");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Pytanie Hotspot to pytanie typu „przeciągnij i upuść” zawierające tylko jeden właściwy obszar.");
define('ttQTPL' , "Pull Down List");
define('ttQuesionid' , "Identyfikator pytania");
define('ttQuestionNotes' , "Opis");
define('ttQuestionsend' , "Wyślij raport");
define('ttQuestionreporting' , "Aby zgłosić więcej pytań, musisz pozostawić pole id puste");
define('ttRandom' , "Losowy");
define('ttRefresh' , "Odświeżać");
define('ttRegister' , "Zarejestrować");
define('ttRegistrations' , "Rejestracje");
define('ttRegEnd' , "Zamknięcie rejestracji");
define('ttRenewPassword' , "Odnów hasło");
define('ttReset' , "Nastawić");
define('ttResetPassword' , "Zresetuj hasło");
define('ttRole' , "Rola");
define('ttRooms' , "Pokoje");
define('ttSave' , "Zapisać");
define('ttSaveAnswerInfo' , "Zapisz informacje o odpowiedzi");
define('ttSaveLanguageFiles' , "Zapisz pliki językowe");
define('ttSaveLanguageXML' , "Zapisz pliki językowe XML");
define('ttSaveQuestionInfo' , "Zapisz informacje o pytaniu");
define('ttScore' , "Wynik");
define('ttScoreFinal' , "Wynik końcowy");
define('ttScoreTest' , "Wynik testu");
define('ttScoreType' , "Rodzaj wyniku");
define('ttScoreMin' , "Minimalny wynik");
define('ttSelectSubject' , "Wybierz Temat");
define('ttSelectSubjectBefore' , "Wybierz temat wcześniej");
define('ttSet' , "Zestaw");
define('ttSetPassword' , "Ustaw swoje hasło");
define('ttSettings' , "Ustawienia");
define('ttShowHide' , "Pokaż ukryj");
define('ttSelectSubQuestion' , "Wybierz pytanie");
define('ttSkin' , "Skóra");
define('ttStart' , "Początek");
define('ttStarted' , "Zaczęło się");
define('ttStop' , "Zatrzymać");
define('ttStopped' , "Zatrzymany");
define('ttStartTest' , "Rozpocznij test");
define('ttStatus' , "Status");
define('ttStats' , "Statystyki");
define('ttStudent' , "Student");
define('ttStudents' , "Uczniowie");
define('ttST10' , "Dziesiąte");
define('ttST30' , "Trzydzieste");
define('ttST100' , "Setny");
define('ttSubject' , "Przedmiot");
define('ttSubjects' , "Przedmioty");
define('ttSubmit' , "Zatwierdź");
define('ttSurname' , "Nazwisko");
define('ttSystem' , "System");
define('ttSystemConfiguration' , "Konfiguracja systemu");
define('ttSbjVers' , "Wersja");
define('ttTeacher' , "Nauczyciel");
define('ttTeachers' , "Nauczyciele");
define('ttTest' , "Test");
define('ttTests' , "Testy");
define('ttTestToCorrect' , "Testy do poprawienia");
define('ttText' , "Tekst");
define('ttTime' , "Czas");
define('ttTimeEnd' , "Koniec czasu");
define('ttTimeStart' , "Czas rozpoczęcia");
define('ttTimeUsed' , "Wykorzystany czas");
define('ttTimeZone' , "Strefa czasowa");
define('ttTitle' , "Tytuł");
define('ttTopic' , "Temat");
define('ttTopics' , "Tematy");
define('ttTopicsAndQuestions' , "Tematy i pytania");
define('ttTopicsQuestions' , "Pytania na tematy");
define('ttTranslations' , "Tłumaczenia");
define('ttTrue' , "Prawdziwe");
define('ttType' , "Rodzaj");
define('ttUser' , "Użytkownik");
define('ttUsers' , "Użytkownicy");
define('ttView' , "Widok");
define('ttWelcome' , "Witamy");
define('ttWaiting' , "Czekanie");
define('ttWarning' , "Ostrzeżenie");
define('ttYes' , "tak");
define('ttAssesmentOverview' , "Raport z przeglądu oceny");
define('ttDeselectAll' , "Odznacz wszystkie");
define('ttErrorUserParameter' , "Wybierz szczegół uczestnika, aby kontynuować!");
define('ttQuestionerror' , "Identyfikator pytania");
define('ttRemove' , "Usunąć");
define('ttReportCoachingError' , "Wybierz ocenę i kontynuuj uczestnika");
define('ttReportCoachingError2' , "Wybierz ocenę, aby kontynuować");
define('ttReportErrorStudent' , "Wybrany student nie brał udziału w wybranych testach");
define('ttReportMainAO' , "Główny");
define('ttReportTemplateDeleteFailed' , "Usuwanie nie powiodło się");
define('ttReportTemplateDelet' , "Szablon usunięty");
define('ttReportTemplateLoaded' , "Szablon caricato correttamente");
define('ttReportTemplateSaveError' , "Wstaw nazwę szablonu bez spacji!");
define('ttReportTemplateSaved' , "Szablon zapisany poprawnie");
define('ttReportTemplateDuplicateError' , "Nazwa szablonu już istnieje!");
define('ttReportScoreFilter' , "Jeśli wybrałeś już uczestnika, teraz wybierz go ponownie");
define('ttSelectAll' , "Zaznacz wszystko");
define('ttQTFB' , "Wypełnij puste miejsca");
define('ttQTFB_TEXT' , "Wypełnij poniższy tekst odpowiednimi słowami");
define('ttQTFBDescription' , "W wypełnieniu pustych pól uczestnik musi wypełnić tekst poprawną odpowiedzią w polu tekstowym");
define('ttPosterImageVideo' , "Ładowanie logo");
define('ttWidthVideo' , "Szerokość");
define('ttHeightVideo' , "Wysokość");
define('ttIdVideo' , "Kod identyfikacyjny");
define('ttVideoTypeVideo' , "Format wideo");
define('ttNumberOfPlaysVideo' , "Maksymalna liczba odtworzeń");
define('ttToolbarVideo' , "Wideo");
define('ttDialogTitleVideo' , "Właściwość wideo");
define('ttFakeObjectVideo' , "Wideo");
define('ttPropertiesVideo' , "Edytuj wideo");
define('ttWidthRequiredVideo' , "Szerokość powinna być ustawiona");
define('ttHeightRequiredVideo' , "Wysokość należy ustawić");
define('ttNumberOfPlayRequiredVideo' , "Należy ustawić maksymalną liczbę odtworzeń");
define('ttFallbackTemplateVideo' , "Twoja przeglądarka nie obsługuje wideo HTML5");
define('ttBrowseVideo' , "Przeglądaj serwer");
define('ttsourceVideo' , "Źródło wideo");
define('ttNumberOfPlayAlertVideo' , "Osiągnąłeś maksymalną liczbę odtwarzanych filmów");
define('ttHelpDefault' , "Panel informacyjny");
define('ttHelpDefaultDescription' , "Naciśnij ten przycisk, aby uzyskać opis tego, co możesz zrobić");
define('ttHelpQuestion' , "Wybierz pytanie, aby przeczytać jego zawartość lub kliknij dwukrotnie, aby edytować");
define('ttHelpADMINNewTeacherDescription' , "Zdefiniuj konto nowego administratora, nauczyciela lub egzaminatora");
define('ttHelpADMINNewStudentDescription' , "Zdefiniuj konto nowego ucznia");
define('ttHelpADMINSelLanguageDescription' , "Wybierz język do zarządzania");
define('ttHelpADMINLanguageDescription' , "Tutaj możesz zmienić lokalizacje słów używanych przez system");
define('ttHelpADMINSystemConf' , "Tutaj możesz zmienić ustawienia EOL, bądź ostrożny");
define('ttHelpADMINRoom' , "Zdefiniuj pomieszczenia, w których będą przeprowadzane testy");
define('ttHelpADMINImport' , "This screen allows you to import new questions to Question Mark");
define('ttHelpADMINProfile' , "This screen allows you to edit your profile");
define('ttHelpReportAreport' , "Ten ekran umożliwia utworzenie Areportu, obowiązkowe jest wybranie co najmniej jednego przedmiotu");
define('ttHelpReportAreportTemplate' , "Wybierz, jakie informacje możesz uzyskać w raporcie");
define('ttHelpReportCreport' , "Ten ekran pozwala utworzyć Creport, obowiązkowe jest wybranie uczestnika");
define('ttHelpReportCreportlist' , "Wybierz egzamin, aby utworzyć raport");
define('ttHelpStudent' , "To the left are the available tests, to the right the selected examination details");
define('ttHelpStudentTest' , "You are in the exam screen, answer the questions and submit the test");
define('ttHelpAdminErrorQuestion' , "If you find problems you can report from this page.");
define('ttHelpExamsCorrect' , "Tutaj otrzymasz egzamin wykonany przez studenta, sprawdź, czy poprawka została wykonana poprawnie, a następnie potwierdź głosowanie.");
define('ttHelpExamsSettings' , "Na tym ekranie można zdefiniować lub zmienić ustawienia, które będą używane w przyszłych badaniach.");
define('ttQTPLDescription' , "Lista rozwijana to pytanie zamknięte, które pozwala respondentom wybrać jeden wybór odpowiedzi z listy opcji przedstawionych w menu rozwijanym. Jeśli chcesz wyświetlić opcje odpowiedzi jako przyciski opcji lub pola wyboru, użyj pytania wielokrotnego wyboru");
define('ttQuestionsubPL' , "Podpytania");
define('ttHelpLog' , "Plik dziennika zostanie automatycznie utworzony po zmianie pytania już przypisanego do testu.");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Grupa");
define('ttSubgroup' , "Podgrupa");
define('ttAOreportSaved' , "Cały wygenerowany raport zostanie zapisany na serwerze.");
define('ttReport' , "Raport");
define('ttReportAllFinished' , "Wszystko skończone");
define('ttReportAODescription' , "Jeśli nie wybierzesz konkretnych ocen, cała ocena zostanie przeanalizowana");
define('ttReportAOWelcome' , "Wybierz karty oceny i użyj kreatora, aby filtrować dane");
define('ttReportAOSelectAssesment' , "Wybierz oceny, które chcesz zgłosić");
define('ttReportAssesmentAuthor' , "Autor oceny");
define('ttReportAssessmentInformation' , "Informacje dotyczące oceny");
define('ttReportAssesmentID' , "Identyfikator oceny");
define('ttReportAssesmentDateTimeFirst' , "Data / godzina po raz pierwszy");
define('ttReportAssesmentDateTimeLast' , "Data / godzina ostatnio wykorzystana");
define('ttReportAssesmentLeastTimeFinished' , "Najmniej czasu zajęło się tym, którzy skończyli");
define('ttReportAssesmentName' , "Nazwa oceny");
define('ttReportAssesmentNumberStarted' , "Num.");
define('ttReportAssesmentNumberNotFinished' , "Num.");
define('ttReportAssesmentNumberFinished' , "Num.");
define('ttReportAssesmentMinscoreFinished' , "Minimalny wynik ukończonych");
define('ttReportAssesmentMaxcoreFinished' , "Maksymalna liczba ukończonych");
define('ttReportAssesmentMediumFinished' , "Średni wynik ukończonych");
define('ttReportAssesmentMediumTimeFinished' , "Średni czas potrzebny na ukończenie");
define('ttReportAssesmentMostTimeFinished' , "Najwięcej czasu zajęli ci skończeni");
define('ttReportAssesmentScore' , "Filtruj według ocen");
define('ttReportAssesmentStdDeviation' , "Odchylenie standardowe dla tych zakończonych");
define('ttReportChecked' , "Wybrany");
define('ttReportCoaching' , "Coaching Report");
define('ttReportCWelcome' , "Wybierz ocenę i uczestnika");
define('ttReportCDescription' , "Musisz filtrować dane według dat i, jeśli chcesz, również według wyniku");
define('ttReportCoachingDescription' , "Zobacz szczegółowe wyniki dla jednego uczestnika biorącego jedną ocenę");
define('ttReportCoachingInformation' , "Wybierz jeden test, aby zobaczyć szczegółowe informacje");
define('ttReportCustomize' , "Dostosuj swój raport");
define('ttReportDateInterval' , "Interwał dat");
define('ttReportDateFrom' , "Z");
define('ttReportDateTaken' , "Data wykonania");
define('ttReportDateTo' , "do");
define('ttReportErrorDetail' , "Please select a participant to show details");
define('ttReportField' , "Field name");
define('ttReportGraphicalDsiplays' , "Graphical displays");
define('ttReportGraphicHistogram' , "Histogram of assessment scores");
define('ttReportGraphicTopicScore' , "Histogram of topic scores");
define('ttReportGroup' , "Groups");
define('ttReportGroupNotPresent' , "There aren't groups");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filter by minimum score");
define('ttReportMaximumScore' , "Filter by maximum score");
define('ttReportNotFilter' , "Do not use filter");
define('ttReportOrder' , "Order");
define('ttReportPartecipants' , "Participants");
define('ttReportPartecipant' , "Participant");
define('ttReportScheduled' , "Schedule");
define('ttReportScoreBand' , "Filter by score band");
define('ttReportSearch' , "Search...");
define('ttReportSearched' , "Search result");
define('ttReportSelectDetail' , "Select user ID or email of participant selected before");
define('ttReportSelectFilter' , "Select filter");
define('ttReportSelectGroup' , "Select groups filter on");
define('ttReportSelectLetter' , "Letter");
define('ttReportAOSelectPartecipant' , "Select participant");
define('ttReportSelected' , "Wybrane oceny");
define('ttReportSelectTemplate' , "Wybierz szablon");
define('ttReportSelectedGroup' , "Wybrane grupy");
define('ttReportSearchByLetter' , "Szukaj według listu");
define('ttReportStudent' , "Filtruj na uczestniku");
define('ttReportStudentNotPresent' , "Nie ma studentów");
define('ttReportStudentDetail' , "Filtruj szczegóły uczestnika");
define('ttReportTemplateLoad' , "Wybierz szablon do załadowania");
define('ttReportTemplateSave' , "Zapisz szablon jako");
define('ttReportTemplateName' , "Wprowadź imię");
define('ttReportTimedOut' , "Przekroczono limit czasu");
define('ttReportTopicAverageScore' , "Średni wynik");
define('ttReportTopicInformation' , "Informacje tematyczne");
define('ttReportTopicMaximumScore' , "Maksymalny wynik");
define('ttReportTopicMinimumScore' , "Minimalny wynik");
define('ttReportTopicName' , "Nazwa tematu");
define('ttReportTopicStandardDeviation' , "Odchylenie standardowe");
define('ttReportTyping' , "Wyszukaj, wpisując");
define('ttReportQuestionType' , "Typ pytania");
define('ttReportViewer' , "Przeglądarka raportów");
define('ttReportViewerDescription' , "Wyświetl wszystkie wygenerowane raporty i zarządzaj nimi");
define('ttStudentDetailCreport' , "Szczegół ucznia");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Certyfikaty");
define('ttCertificate' , "Certyfikat");
define('ttNewGroup' , "Dodaj grupę");
define('ttEditGroup' , "Edytuj grupę");
define('ttEditTeacher' , "Edytuj nauczyciela");
define('ttEditStudent' , "Edytuj ucznia");
define('tteTeacher' , "Egzaminator");
define('tttotals' , "Całkowity");
define('ttD1s' , "Łatwy");
define('ttD2s' , "Średni");
define('ttD3s' , "Ciężko");
define('ttSelectStudent' , "Lista studentów");
define('ttSelectTeacher' , "Lista nauczycieli");
define('ttCoord' , "Współrzędne");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "The list of exams is displayed here. You can create a new exam, change the exam settings, or view student votes.");
define('ttHelpSubject' , "Here you will see a list of the courses you are teaching. Select one to view the questions contained therein.");
define('ttNotAvailable' , "The selected settings do not allow you to generate a test.");
define('ttSelectGroup' , "Edit groups or subgroups");
define('ttConfirmProcedure' , "Do you really want to do this?");
define('ttUserDeleted' , "User deleted correctly");
define('ttMGroupCreated' , "Group successfully created");
define('ttMSubgroupCreated' , "Utworzono podgrupę");
define('ttNewSubgroup' , "Add subgroup");
define('ttErrorTopic' , "Too much topic questions selected");
define('ttAvailable' , "questions available of");
define('ttThereAreNot' , "There aren't");
define('ttErrorMax' , "This field can't be lesser than the number of selected mandatory questions");
define('ttField' , "The field");
define('ttHard' , "Hard");
define('ttMedium' , "Medium");
define('ttEasy' , "Easy");
define('ttMustBeaNumber' , "Must be a number");
define('ttMaxHardReached' , "Osiągnięto maksymalną liczbę trudnych pytań");
define('ttMaxMediumReached' , "Osiągnięto maksymalną liczbę średnich pytań");
define('ttMaxEasyReached' , "Osiągnięto maksymalną liczbę łatwych pytań");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Jeśli klikniesz przycisk Tak, egzamin studenta zostanie automatycznie dostarczony do systemu w jego aktualnym stanie.");
define('ttProfCert' , "Certyfikat biegłości");
define('ttCertify' , "To zaświadcza");
define('ttSuccess' , "pomyślnie przeszedł");
define('ttEvaluation' , "z oceną");
define('ttAccreditedTestSite' , "w akredytowanej witrynie testowej");
define('ttOn' , "na");
define('ttNumQuestionsTopic' , "Liczba pytań do każdego tematu");
define('ttParamNotSet' , "Brakujące parametry");
define('ttNotEnoughQuestions' , "Za mało pytań");
define('ttExamArchivedCertNot' , "Egzamin jest archiwizowany, ale certyfikaty nie zostały wygenerowane");
define('ttSendCertificate' , "Pobierz certyfikat");
define('ttCertificateAlert' , "Czy na pewno chcesz wygenerować i pobrać certyfikat egzaminu do ucznia?");
define('ttCertificateScore' , "Student nie ma minimalnego wyniku, aby otrzymać certyfikat");
define('ttCertificateGenerated' , "Certyfikat został wygenerowany poprawnie");
define('ttBut' , "ale");
define('ttAnd' , "i");
define('ttCertificateEmailSended' , "wiadomość została pomyślnie wysłana");
define('ttCertificateGeneratedProblem' , "Certyfikat nie został wygenerowany!");
define('ttCertificatePoint' , "Wynik studenta jest zbyt niski i nie można wydać certyfikatu.");
define('ttPrivacy1' , "Czytam i akceptuję");
define('ttPrivacy2' , "Polityka prywatności ECTN");
define('ttPrivacy3' , "Chcę być informowany o możliwości uzyskania Indywidualnego Certyfikatu Biegłości");
define('ttDemoTest' , "Demo test");
