<?php
define('ttAccountActivation' , "Account Activation");
define('ttActive' , "Active");
define('ttActivate' , "Activate");
define('ttAdd' , "Add");
define('ttAddSelectedStudents' , "Add Selected Students");
define('ttAdministration' , "Administration");
define('ttAdministrator' , "Administrator");
define('ttAdminWelcome' , "Welcome to the administation panel.<br/>This system includes:");
define('ttAlias' , "ISO 639-1 Code");
define('ttAndExit' , "and Exit");
define('ttAnswer' , "Answer");
define('ttAnswers' , "Answers");
define('ttArchive' , "Archive");
define('ttArchived' , "Archived");
define('ttAssignSubject' , "Assign Subject");
define('ttAutomatic' , "Automatic");
define('ttAImportComplete' , "Questions Import already successfully completed");
define('ttBasedOn' , "Based on");
define('ttBlocked' , "Blocked");
define('ttBlock' , "Block");
define('ttUnblock' , "Unblock");
define('ttBonus' , "Bonus");
define('ttCancel' , "Cancel");
define('ttChangeLanguage' , "Change Language");
define('ttChangeVersion' , "Change Test Version");
define('ttCheck' , "Check...");
define('ttClose' , "Close");
define('ttClosed' , "Closed");
define('ttCorrect' , "Correct");
define('ttConfiguration' , "Configuration");
define('ttConfirm' , "Confirm");
define('ttConfirmEmail' , "Confirm Email");
define('ttConfirmPassword' , "Confirm Password");
define('ttCreate' , "Create");
define('ttCArchiveExam' , "Are you sure to archive the exam?<br/>All started tests can not be submitted anymore and all questions to correct of already submitted tests sum total of 0 points.<br/>The operation can not be undone! Continue?");
define('ttCBlockTest' , "Are you sure to block this test?");
define('ttCChangeStatus' , "Are you sure to change question's status to _STATUS_?");
define('ttCConfirmTest' , "Do you want to confirm the test score?<br/>This test will be archived! Continue?");
define('ttCDeleteAnswer' , "Are you sure to delete this answer and its translations?<br/>This operation can not be undone! Continue?");
define('ttCDeleteExam' , "Are you sure to delete this exam?<br/>All running, ended and archived tests will be deleted.<br/>The operation can not be undone! Continue?");
define('ttCDeleteQuestion' , "Are you sure to delete this question and its translations?<br/>This operation can not be undone! Continue?");
define('ttCDeleteRoom' , "Are you sure to delete this room?<br/>This operation can not be undone!<br/>Continue?");
define('ttCDeleteSubject' , "Are you sure to delete this subject?<br/>The following items will be PERMANENTLY deleted:<br/> - Subject<br/> - All Topics<br/> - All Questions and answers with their translations<br/> - All Settings<br/> - All active and archived exams and tests<br/>The operation can not be undone! Continue?");
define('ttCDeleteSettings' , "Are you sure to delete this test settings? The operation can not be undone.<br/>Continue?");
define('ttCDeleteTopic' , "Are you sure to delete this topic?<br/>The following items will be PERMANENTLY deleted:<br/> - Topic<br/> - All Questions with their translations<br/> - All Answers with their translations<br/>The operation can not be undone! Continue?");
define('ttCDiscardEdits' , "Your changes will be lost.<br/>Exit?");
define('ttCDiscardNew' , "The created item will be lost.<br/>Exit?");
define('ttCRegister' , "Are you sure to register on this exam?");
define('ttCRegisterStudents' , "Are you sure to register these selected students on the exam?");
define('ttCRenewPassword' , "The exam's password will be changed.<br/>This operation can not be undone.<br/>Continue?");
define('ttCStartExam' , "Do you want activate the selected exam?");
define('ttCStartTest' , "Do you want to start the exam now?<br/>Exam password will be required.");
define('ttCStopExam' , "Do you want to deactivate the selected exam?");
define('ttCSubmitTest' , "Do you want to submit your test?<br/>This operation can not be undone! Continue?");
define('ttCTest' , "Password is correct. Your test is ready and will start after your click!");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Are you sure to unblock this test?");
define('ttCUpdateConfigurations' , "Are you sure to save the new system configurations?");
define('ttCUpdateLanguage' , "Are you sure to update language files?<br/>This operation can not be undone. Continue?");
define('ttD1' , "Easy");
define('ttD2' , "Medium");
define('ttD3' , "Hard");
define('ttDatabaseConfiguration' , "Database Configuration");
define('ttDay' , "Day");
define('ttDelete' , "Delete");
define('ttDescription' , "Description");
define('ttDifficulty' , "Difficulty");
define('ttDifficultyQuestions' , "Questions per Difficulty");
define('ttDistribution' , "Distribution");
define('ttDo' , "Do Exam");
define('ttDTAnswerInfo' , "Showing _TOTAL_ answers");
define('ttDTAnswerFiltered' , "(filtered from _MAX_ total answers)");
define('ttDTAnswerEmpty' , "No answers to show");
define('ttDTExamInfo' , "Showing _TOTAL_ exams in progress");
define('ttDTExamFiltered' , "(filtered from _MAX_ total exams in progress)");
define('ttDTExamEmpty' , "No exams to show");
define('ttDTQuestionInfo' , "Showing _TOTAL_ questions");
define('ttDTQuestionFiltered' , "(filtered from _MAX_ total questions)");
define('ttDTQuestionEmpty' , "No questions to show");
define('ttDTRegisteredStudentInfo' , "Showing _TOTAL_ registered students");
define('ttDTRegisteredStudentFiltered' , "(filtered from _MAX_ total registered students)");
define('ttDTRegisteredStudentEmpty' , "No registered students to show");
define('ttDTStudentsInfo' , "Showing _TOTAL_ students");
define('ttDTStudentsFiltered' , "(filtered from _MAX_ total students)");
define('ttDTStudentsEmpty' , "No students to show");
define('ttDTTestInfo' , "Showing _TOTAL_ test");
define('ttDTTeacherInfo' , "Showing _TOTAL_ teachers");
define('ttDTTeacherFiltered' , "(filtered from _MAX_ total teachers)");
define('ttDTTeacherEmpty' , "No teacher to show");
define('ttDTTestFiltered' , "(filtered from _MAX_ total tests)");
define('ttDTTestEmpty' , "No tests to show");
define('ttDone' , "Exam done");
define('ttDuration' , "Duration");
define('ttDTsubquestionInfo' , "Sub Questions");
define('ttEdit' , "Edit");
define('ttEditableScore' , "Editable Score");
define('ttError' , "Error");
define('ttEmail' , "E-mail");
define('ttEnd' , "End");
define('ttEverywhere' , "Everywhere");
define('ttExam' , "Exam");
define('ttExams' , "Exams");
define('ttExit' , "Exit");
define('ttExtra' , "Extra");
define('ttExamsArchive' , "Archive");
define('ttExamsInProgress' , "Exams in progress");
define('ttETeachers' , "Examinator");
define('ttErrorquestion' , "Report Error");
define('ttEActivationFails' , "Activation fails!");
define('ttEAlreadyRegistered' , "The student is already registered for this exam!");
define('ttEAnswerInSet' , "The operation can not be completed. The answer is used in some tests!");
define('ttEAnswerNotFound' , "Answer not found");
define('ttEAnswers' , "A problem with answers occurred.<br/>Please contact the teacher or the admin.");
define('ttEDatabase' , "Database Error!");
define('ttEDates' , "Dates are not correct!");
define('ttEEditRoomAll' , "'All' room can not be edited!");
define('ttEEmailAlreadyRegistered' , "E-mail already registered!");
define('ttEEmailNotRegistered' , "E-mail not registered!");
define('ttEEmailNotValid' , "The typed email is not valid! Plase type a valid e-mail address");
define('ttEEmailsNotMatch' , "The two emails does not match!");
define('ttEEmptyFields' , "One or more fields are empty!");
define('ttEExamArchived' , "The operation can not be completed. The exam has already been archived!");
define('ttEExamNotFound' , "Exam not found!");
define('ttEExamNotStarted' , "You can not start the exam. It is not active yet!");
define('ttEExamStarted' , "The operation can not be completed because the exam is already started!");
define('ttEExamWaiting' , "The operation can not be completed because the exam is never started!");
define('ttEExamsNotArchivedDeleteTopic' , "The operation can not be completed, because at least one not archived exam contains questions from this topic!");
define('ttEExamsNotArchivedEditTestSettings' , "The operation can not be completed, because these settings are used by at least one not archived exam.<br/>Only name and description will be updated. Continue?");
define('ttEExamsNotArchivedDeleteTestSettings' , "The operation can not be completed, because these settings are used by at least one not archived exam!");
define('ttEIncorrectField' , "One or more field are not correct!");
define('ttELogin' , "E-mail and/or Password are not correct!");
define('ttEMainLanguageEmpty' , "Subject's main language can not be empty!");
define('ttEMandatoryQuestion' , "This is a mandatory question of '_TESTSETTING_' test's setting: you can't delete it or edit its difficulty or topic.");
define('ttENotAuthorized' , "Your client is not authorized.<br/>Please contact the teacher or the admin.");
define('ttENoStudentsToRegister' , "No student to register!");
define('ttENoTopicsForSubject' , "No topic for this subject!<br/>To create a new question you must first create at least one topic.");
define('ttEOldPasswordWrong' , "The old password is not correct!");
define('ttEPassword' , "Wrong password!");
define('ttEPasswordShort' , "The password is too short. It must be at least 8 characters long!");
define('ttEPasswordsNotMatch' , "The two passwords does not match!");
define('ttEQuestAnswPicker' , "Error during questions and answers picking.<br/>Please contact your teacher!");
define('ttEQuestionInSet' , "The operation can not be completed. The question is used some tests!");
define('ttEQuestionNotFound' , "Question not found!");
define('ttEQuestionType' , "Question type not correct!");
define('ttERegFailedQuestions' , "Registration failed: too few questions! Please contact the teacher.");
define('ttERoomAllDelete' , "'All' room can not be deleted!");
define('ttERoomUsed' , "The operation can not be completed. The room is used in some exams!");
define('ttESaveBeforeNew' , "Before creating a new item please save or cancel the one already created.");
define('ttESelectQuestionType' , "You must select one of available question type!");
define('ttESelectSubject' , "You must select one of your subject!");
define('ttESelectTestSettings' , "You must select one of the test settings!");
define('ttESetNotFound' , "Questions set not found!");
define('ttETestAlreadyArchived' , "The operation can not be completed. This test has already been corrected and archived!");
define('ttETestAlreadySubmitted' , "The operation can not be completed. This test has already been submitted and/or archived.");
define('ttETestBlockedSubmitted' , "The operation can not be completed. This test has been blocked or has already been submitted!");
define('ttETestNotArchived' , "The operation can not be completed. This test has not been archived!");
define('ttETestNotFound' , "Test not found!");
define('ttETestsNotArchived' , "Some tests have not been archived! Please correct all the tests before.");
define('ttETestSettingDeleteQuestion' , "The operation can not be completed. This question is mandatory in the following test's settings:");
define('ttETestSettingDeleteTopic' , "The operation can not ben completed. Some questions of this topic are used in the following test's settings:");
define('ttETimeExpired' , "The available time is expired!");
define('ttETranslationExists' , "The translation of the selected language already exists!");
define('ttEUserNotFound' , "User not found!");
define('ttEValues' , "Some values are not correct!");
define('ttFalse' , "False");
define('ttFinalScore' , "Final Score");
define('ttGeneralInformations' , "General Informations");
define('ttHours' , "hours");
define('ttHome' , "Home");
define('ttHomepage' , "Homepage");
define('ttHost' , "Host");
define('ttHAnswPanel' , "Double click to edit selected answer");
define('ttHQuestLanguagesPanel' , "Click to show translation<br/>of selected question");
define('ttHQuestPanel' , "Single click to select and view question preview, and double click to edit question and answers info. Double click on flags to activate and deactivate question in test");
define('ttHQuestPreviewPanel' , "The answers with orange background are not translated in requested language");
define('ttHQuestTopicPanel' , "Single click to filter questions and<br/>double click to edit topic info");
define('ttInfo' , "Info");
define('ttIPEnd' , "IPv4 End");
define('ttIPStart' , "IPv4 Start");
define('ttInactive' , "Inactive");
define('ttImportQM' , "Import");
define('ttImport' , "Import QM");
define('ttImportComplete' , "Questions Import successfully completed");
define('ttJoin' , "Join");
define('ttLanguage' , "Language");
define('ttLanguages' , "Languages");
define('ttLogin' , "Login");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Login complete!");
define('ttLogout' , "LOGOUT");
define('ttMailLostPassword' , "To reset your account password please click the following link:\n\n_LINK_\n\nIf you have not request a password reset ignore this email.");
define('ttMailCredentials' , "Hi _USERNAME_,\nBelow are shown your personal access credentials:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_");
define('ttMailNewTeacher' , "Welcome to _SYSTEMNAME_.\nTo activate your accunt please click the following link and set your personal account's password:");
define('ttMainLanguage' , "Main Language");
define('ttManage' , "Manage");
define('ttMandatory' , "Mandatory");
define('ttManual' , "Manual");
define('ttMinutes' , "minutes");
define('ttMyExams' , "My Exams");
define('ttMySettings' , "My Settings");
define('ttMySubjects' , "Select subject");
define('ttMActivation' , "Password successfully setted.<br/>You will be redirect to your Homepage");
define('ttMAnswerDeleted' , "Answer successfully deleted");
define('ttMConfigurationsUpdated' , "System configurations successfully updated");
define('ttMConfirm' , "Test successfully confirmed and archived");
define('ttMUserCreated' , "Creation completed: an email has been sent to you to complete the registration.<br/>Also check in spam folder too");
define('ttMEdit' , "Edits saved successfully");
define('ttMExamArchived' , "Exam successfully archived");
define('ttMExamDeleted' , "Exam successfully deleted");
define('ttMExamStarted' , "Exam successfully started");
define('ttMExamStopped' , "Exam successfully stopped");
define('ttMLanguageCreated' , "Translation successfully created");
define('ttMLanguageSaved' , "Translation successfully saved");
define('ttMLanguageUpdated' , "Translation successfully updated");
define('ttMNewAnswer' , "Answer successfully created");
define('ttMNewQuestion' , "Question successfully created");
define('ttMNewRoom' , "Room successfully created");
define('ttMNewSettings' , "Test Settings successfully created");
define('ttMNewSubject' , "Subject successfully created");
define('ttMNewTopic' , "Topic successfully created");
define('ttMPasswordRenewed' , "Exam's password successfully renewed");
define('ttMQuestionDeleted' , "Question successfully deleted");
define('ttMRegistration' , "You successfully registered on this exam");
define('ttMResetConfirmed' , "Request completed: an email has been sent to you reset your password.<br/>Also check in spam folder too");
define('ttMRoomDeleted' , "Room successfully deleted");
define('ttMSelectLanguage' , "Select the language you want manage");
define('ttMSettingsDeleted' , "Test Settings successfully deleted");
define('ttMStudentsRegistered' , "Students successfully registered on the exam");
define('ttMSubjectDeleted' , "Subject successfully deleted");
define('ttMSubjectQuestions' , "To manage topics and questions, plase select the subject");
define('ttMSubjectSettings' , "To manage exam's settings, please select the subject");
define('ttMTestBlocked' , "Test successfully blocked");
define('ttMTestSubmitted' , "Test successfully submitted");
define('ttMTestUnblocked' , "Test successfully unblocked");
define('ttMTopicDeleted' , "Topic successfully deleted");
define('ttName' , "Name");
define('ttNumberError' , "The value should be an integer or a decimal (ES: 12.5)");
define('ttNegativeScores' , "Negative scores");
define('ttNew' , "New");
define('ttNext' , "Next");
define('ttNewAnswer' , "New Answer");
define('ttNewCredentials' , "New Credentials");
define('ttNewLanguage' , "New Language");
define('ttNewPassword' , "New Password");
define('ttNewQuestion' , "New Question");
define('ttNewRegistration' , "New Registration");
define('ttNewRoom' , "New Room");
define('ttNewTeacher' , "New Teacher");
define('ttNewTestSettings' , "New Settings");
define('ttNewSubject' , "New Subject");
define('ttNewStudent' , "New Student");
define('ttNewTopic' , "New Topic");
define('ttNewUser' , "New User");
define('ttNo' , "No");
define('ttNoAnswers' , "No answers available for this question");
define('ttNoExams' , "No exams available for this subject");
define('ttNoExamInProgress' , "No exam in progress");
define('ttNoInfo' , "There aren't informations about this exam");
define('ttNoQuestions' , "No questions available for this topic");
define('ttNoRooms' , "No rooms created: 'All' only available");
define('ttNoSettings' , "No settings available for this subject");
define('ttNoSubjects' , "No subjects available");
define('ttNoTestToCorrect' , "No tests to correct");
define('ttNoUserRegistered' , "No registered users for this exam");
define('ttOldPassword' , "Old Password");
define('ttEssayQuestion' , "Essay question");
define('ttPassword' , "Password");
define('ttPasswordLost' , "Password Lost?");
define('ttPort' , "Port");
define('ttProfile' , "Profile");
define('ttPrepareImportQM' , "Preview");
define('ttQuestion' , "Question");
define('ttQuestionPreview' , "Question Preview");
define('ttQuestions' , "Questions");
define('ttQEc' , "Calculator");
define('ttQEp' , "Periodic Table");
define('ttQTMC' , "Multiple Choice");
define('ttQTMCDescription' , "In a Multiple Choice question the participant selects a single choice from a number of choices to answer the question.");
define('ttQTMR' , "Multiple Response");
define('ttQTMRDescription' , "A Multiple Response question is like a multiple choice, except that instead of being required to make at most one choice, the user is allowed to make one or more than one choice.");
define('ttQTES' , "Essay Question");
define('ttQTESDescription' , "An Essay question lets the participant enter a long, free-range text answer to a question. It's also possible to use this question type to solicit opinions or suggestions on a particular subject.");
define('ttQTYN' , "Yes / No");
define('ttQTYNDescription' , "A Yes/No question is a multiple choice question that asks the participant to give a \"Yes\" or \"No\" answer to a question.");
define('ttQTTF' , "True / False");
define('ttQTTFDescription' , "A True/False question is a Multiple Choice question that asks the participant to give a \"True\" or \"False\" answer to a question.");
define('ttQTNM' , "Numeric");
define('ttQTNMDescription' , "In a Numeric Question, the participant answers by typing in either a whole number or a real number.");
define('ttQTTM' , "Text Match");
define('ttQTTMDescription' , "In a Text Match question, the participant types in a single word, or a few words to indicate their answer. You define right or wrong words or phrases in advance by entering a list of acceptable answers.");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "A Hotspot question is a drag and drop question with only one right area. The participant places a single marker on an image to indicate the answer.");
define('ttQTPL' , "Pull Down List");
define('ttQuesionid' , "Question ID");
define('ttQuestionNotes' , "Description");
define('ttQuestionsend' , "Send Report");
define('ttQuestionreporting' , "To report more questions you need to leave the id field blank");
define('ttRandom' , "Random");
define('ttRefresh' , "Refresh");
define('ttRegister' , "Register");
define('ttRegistrations' , "Registrations");
define('ttRegEnd' , "Registation closure");
define('ttRenewPassword' , "Renew Password");
define('ttReset' , "Reset");
define('ttResetPassword' , "Reset Password");
define('ttRole' , "Role");
define('ttRooms' , "Rooms");
define('ttSave' , "Save");
define('ttSaveAnswerInfo' , "Save Answer Info");
define('ttSaveLanguageFiles' , "Save Language Files");
define('ttSaveLanguageXML' , "Save XML Language Files");
define('ttSaveQuestionInfo' , "Save Question Info");
define('ttScore' , "Score");
define('ttScoreFinal' , "Final Score");
define('ttScoreTest' , "Test Score");
define('ttScoreType' , "Score Type");
define('ttScoreMin' , "Minimum Score");
define('ttSelectSubject' , "Select Subject");
define('ttSelectSubjectBefore' , "Select a Subject before");
define('ttSet' , "Set");
define('ttSetPassword' , "Please set your password");
define('ttSettings' , "Settings");
define('ttShowHide' , "Show/Hide");
define('ttSelectSubQuestion' , "Select a subQuestion");
define('ttSkin' , "Skin");
define('ttStart' , "Start");
define('ttStarted' , "Started");
define('ttStop' , "Stop");
define('ttStopped' , "Stopped");
define('ttStartTest' , "Start Test");
define('ttStatus' , "Status");
define('ttStats' , "Stats");
define('ttStudent' , "Student");
define('ttStudents' , "Students");
define('ttST10' , "Tenths");
define('ttST30' , "Thirtieths");
define('ttST100' , "Hundredth");
define('ttSubject' , "Subject");
define('ttSubjects' , "Subjects");
define('ttSubmit' , "Submit");
define('ttSurname' , "Surname");
define('ttSystem' , "System");
define('ttSystemConfiguration' , "System Configuration");
define('ttSbjVers' , "Version");
define('ttTeacher' , "Teacher");
define('ttTeachers' , "Teachers");
define('ttTest' , "Test");
define('ttTests' , "Tests");
define('ttTestToCorrect' , "Tests to correct");
define('ttText' , "Text");
define('ttTime' , "Time");
define('ttTimeEnd' , "Time End");
define('ttTimeStart' , "Time Start");
define('ttTimeUsed' , "Time Used");
define('ttTimeZone' , "Time zone");
define('ttTitle' , "Title");
define('ttTopic' , "Topic");
define('ttTopics' , "Topics");
define('ttTopicsAndQuestions' , "Topics and Questions");
define('ttTopicsQuestions' , "Questions per Topics");
define('ttTranslations' , "Translations");
define('ttTrue' , "True");
define('ttType' , "Type");
define('ttUser' , "User");
define('ttUsers' , "Users");
define('ttView' , "View");
define('ttWelcome' , "Welcome");
define('ttWaiting' , "Waiting");
define('ttWarning' , "Warning");
define('ttYes' , "Yes");
define('ttAssesmentOverview' , "Assesment Overview Report");
define('ttDeselectAll' , "Deselect all");
define('ttErrorUserParameter' , "Select a participant detail to continue!");
define('ttQuestionerror' , "Question ID");
define('ttRemove' , "Remove");
define('ttReportCoachingError' , "Select an assessment and a participant to continue");
define('ttReportCoachingError2' , "Select an assessment to continue");
define('ttReportErrorStudent' , "The selected student did not participate in chosen tests");
define('ttReportMainAO' , "Main");
define('ttReportTemplateDeleteFailed' , "Delete failed");
define('ttReportTemplateDelet' , "Template deleted");
define('ttReportTemplateLoaded' , "Template caricato correttamente");
define('ttReportTemplateSaveError' , "Insert a template name without space!");
define('ttReportTemplateSaved' , "Template Saved correctly");
define('ttReportTemplateDuplicateError' , "Template name already exist!");
define('ttReportScoreFilter' , "If you have already selected a participant, now please re-select new one");
define('ttSelectAll' , "Select all");
define('ttQTFB' , "Fill in the blanks");
define('ttQTFB_TEXT' , "Complete the following text with the appropriate words");
define('ttQTFBDescription' , "In a fill in blanks question the participant have to complete the text with the correct answer in the text-field");
define('ttPosterImageVideo' , "Loading Logo");
define('ttWidthVideo' , "Width");
define('ttHeightVideo' , "Height");
define('ttIdVideo' , "Identification Code");
define('ttVideoTypeVideo' , "Video format");
define('ttNumberOfPlaysVideo' , "Max number of plays");
define('ttToolbarVideo' , "Video");
define('ttDialogTitleVideo' , "Video property");
define('ttFakeObjectVideo' , "Video");
define('ttPropertiesVideo' , "Edit video");
define('ttWidthRequiredVideo' , "The width should be set");
define('ttHeightRequiredVideo' , "The height should be set");
define('ttNumberOfPlayRequiredVideo' , "The Max number of plays should be set");
define('ttFallbackTemplateVideo' , "Your browser does not support HTML5 video");
define('ttBrowseVideo' , "Browse server");
define('ttsourceVideo' , "Source video");
define('ttNumberOfPlayAlertVideo' , "You have reached the maximum number of plays your video");
define('ttHelpDefault' , "Information Panel");
define('ttHelpDefaultDescription' , "Press this button to get a description of what you can do");
define('ttHelpQuestion' , "Select a question to read its contents, or double-click to edit");
define('ttHelpADMINNewTeacherDescription' , "Define the account of a new administrator, teacher or examiner");
define('ttHelpADMINNewStudentDescription' , "Define the account of a new student");
define('ttHelpADMINSelLanguageDescription' , "Select a language to manage");
define('ttHelpADMINLanguageDescription' , "Here you can change the localizations of the words used by the system");
define('ttHelpADMINSystemConf' , "Here you can change the EOL settings, be careful");
define('ttHelpADMINRoom' , "Define the rooms where the tests will be carried out");
define('ttHelpADMINImport' , "This screen allows you to import new questions to Question Mark");
define('ttHelpADMINProfile' , "This screen allows you to edit your profile");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttHelpStudent' , "To the left are the available tests, to the right the selected examination details");
define('ttHelpStudentTest' , "You are in the exam screen, answer the questions and submit the test");
define('ttHelpAdminErrorQuestion' , "If you find problems you can report from this page.");
define('ttHelpExamsCorrect' , "Here you receive an examination done by a student, check that the correction has been made correctly, and then confirm the vote.");
define('ttHelpExamsSettings' , "In this screen you can define or change the settings to use in future examinations.");
define('ttQTPLDescription' , "Dropdown is a closed-ended question that allows respondents to choose one answer choice from a list of choices presented in a dropdown menu.If you want to display answer choices as radio buttons or checkboxes, use the Multiple Choice question");
define('ttQuestionsubPL' , "Subquestions");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Group");
define('ttSubgroup' , "Subgroup");
define('ttAOreportSaved' , "All the generated report will be saved on server. You can see them in the specific section");
define('ttReport' , "Report");
define('ttReportAllFinished' , "All finished");
define('ttReportAODescription' , "If you not select specific assessments, all the assessment will be analyzed");
define('ttReportAOWelcome' , "Choose an assessment and use wizard tabs to filter data");
define('ttReportAOSelectAssesment' , "Select assessments to report on");
define('ttReportAssesmentAuthor' , "Assessment author");
define('ttReportAssessmentInformation' , "Assessment information");
define('ttReportAssesmentID' , "Assessment ID");
define('ttReportAssesmentDateTimeFirst' , "Date/Time first taken");
define('ttReportAssesmentDateTimeLast' , "Date/Time last taken");
define('ttReportAssesmentLeastTimeFinished' , "Least time taken for those finished");
define('ttReportAssesmentName' , "Assessment name");
define('ttReportAssesmentNumberStarted' , "Num. of times started");
define('ttReportAssesmentNumberNotFinished' , "Num. of times not finished");
define('ttReportAssesmentNumberFinished' , "Num. of times finished");
define('ttReportAssesmentMinscoreFinished' , "Minimum score of those finished");
define('ttReportAssesmentMaxcoreFinished' , "Maximum score of those finished");
define('ttReportAssesmentMediumFinished' , "Medium score of those finished");
define('ttReportAssesmentMediumTimeFinished' , "Medium time taken for those finished");
define('ttReportAssesmentMostTimeFinished' , "Most time taken for those finished");
define('ttReportAssesmentScore' , "Filter by assessments score");
define('ttReportAssesmentStdDeviation' , "Standard deviation for those finished");
define('ttReportChecked' , "Selected");
define('ttReportCoaching' , "Coaching Report");
define('ttReportCWelcome' , "Choose an assessment and a participant");
define('ttReportCDescription' , "You have to filter data by dates and, if you want, also by score");
define('ttReportCoachingDescription' , "See detailed results for one participant taking one assessment");
define('ttReportCoachingInformation' , "Select one test to see detailed information");
define('ttReportCustomize' , "Customize your report");
define('ttReportDateInterval' , "Dates interval");
define('ttReportDateFrom' , "From");
define('ttReportDateTaken' , "Date taken");
define('ttReportDateTo' , "to");
define('ttReportErrorDetail' , "Please select a participant to show details");
define('ttReportField' , "Field name");
define('ttReportGraphicalDsiplays' , "Graphical displays");
define('ttReportGraphicHistogram' , "Histogram of assessment scores");
define('ttReportGraphicTopicScore' , "Histogram of topic scores");
define('ttReportGroup' , "Groups");
define('ttReportGroupNotPresent' , "There aren't groups");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filter by minimum score");
define('ttReportMaximumScore' , "Filter by maximum score");
define('ttReportNotFilter' , "Do not use filter");
define('ttReportOrder' , "Order");
define('ttReportPartecipants' , "Participants");
define('ttReportPartecipant' , "Participant");
define('ttReportScheduled' , "Schedule");
define('ttReportScoreBand' , "Filter by score band");
define('ttReportSearch' , "Search...");
define('ttReportSearched' , "Search result");
define('ttReportSelectDetail' , "Select user ID or email of participant selected before");
define('ttReportSelectFilter' , "Select filter");
define('ttReportSelectGroup' , "Select groups filter on");
define('ttReportSelectLetter' , "Letter");
define('ttReportAOSelectPartecipant' , "Select participant");
define('ttReportSelected' , "Selected assessments");
define('ttReportSelectTemplate' , "Select a template");
define('ttReportSelectedGroup' , "Selected groups");
define('ttReportSearchByLetter' , "Search by letter");
define('ttReportStudent' , "Filter on participant");
define('ttReportStudentNotPresent' , "There aren't students");
define('ttReportStudentDetail' , "Filter on participant detail");
define('ttReportTemplateLoad' , "Select a template to load");
define('ttReportTemplateSave' , "Save template as");
define('ttReportTemplateName' , "Insert name");
define('ttReportTimedOut' , "Timed out");
define('ttReportTopicAverageScore' , "Average score");
define('ttReportTopicInformation' , "Topic information");
define('ttReportTopicMaximumScore' , "Maximum score");
define('ttReportTopicMinimumScore' , "Minimum score");
define('ttReportTopicName' , "Topic name");
define('ttReportTopicStandardDeviation' , "Standard Deviation");
define('ttReportTyping' , "Search by typing");
define('ttReportQuestionType' , "Question type");
define('ttReportViewer' , "Report viewer");
define('ttReportViewerDescription' , "View all generated report and manage them");
define('ttStudentDetailCreport' , "Student detail");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Certificates");
define('ttCertificate' , "Certificate");
define('ttNewGroup' , "Add group");
define('ttEditGroup' , "Edit group");
define('ttEditTeacher' , "Edit Teacher");
define('ttEditStudent' , "Edit Student");
define('tteTeacher' , "Examiner");
define('tttotals' , "Total");
define('ttD1s' , "Easy");
define('ttD2s' , "Medium");
define('ttD3s' , "Hard");
define('ttSelectStudent' , "Students list");
define('ttSelectTeacher' , "Teacher list");
define('ttCoord' , "Coordinates");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "The list of exams is displayed here. You can create a new exam, change the exam settings, or view student votes.");
define('ttHelpSubject' , "Here you will see a list of the courses you are teaching. Select one to view the questions contained therein.");
define('ttNotAvailable' , "The selected settings do not allow you to generate a test.");
define('ttSelectGroup' , "Edit groups or subgroups");
define('ttConfirmProcedure' , "Do you really want to do this?");
define('ttUserDeleted' , "User deleted correctly");
define('ttMGroupCreated' , "Group successfully created");
define('ttMSubgroupCreated' , "Subgroup successfully created");
define('ttNewSubgroup' , "Add subgroup");
define('ttTeacherSubmitStudentExam' , "If you click the yes button, the student exam will automatically be delivered to the system in its current state. If the student is still doing the exam, any further modification will not be considered.");
define('ttErrorTopic' , "Troppe domande selezionate nei topics");
define('ttAvailable' , "questions available of");
define('ttThereAreNot' , "Non ci sono");
define('ttErrorMax' , "Questo campo non deve essere minore del numero di domande obbligatorie selezionate");
define('ttField' , "Il campo");
define('ttHard' , "Difficile");
define('ttMedium' , "Intermedio");
define('ttEasy' , "Facile");
define('ttMustBeaNumber' , "Deve essere un numero");
define('ttMaxHardReached' , "Numero massimo di domande difficili già raggiunto");
define('ttMaxMediumReached' , "Numero massimo di domande intermedie già raggiunto");
define('ttMaxEasyReached' , "Numero massimo di domande facili già raggiunto");
