<?php
define('ttAccountActivation' , "Activation de compte");
define('ttActive' , "actif");
define('ttActivate' , "Activer");
define('ttAdd' , "Ajouter");
define('ttAddSelectedStudents' , "Ajouter des étudiants sélectionnés");
define('ttAdministration' , "Administration");
define('ttAdministrator' , "Administrateur");
define('ttAdminWelcome' , "Bienvenue dans le panneau d'administration. ");
define('ttAlias' , "Code ISO 639-1");
define('ttAndExit' , "et sortie");
define('ttAnswer' , "Réponse");
define('ttAnswers' , "Réponses");
define('ttArchive' , "Archiver");
define('ttArchived' , "Archivé");
define('ttAssignSubject' , "Attribuer un sujet");
define('ttAutomatic' , "Automatique");
define('ttAImportComplete' , "Questions Import déjà terminé avec succès");
define('ttBasedOn' , "Basé sur");
define('ttBlocked' , "Bloqué");
define('ttBlock' , "Bloc");
define('ttUnblock' , "Débloquer");
define('ttBonus' , "Prime");
define('ttCancel' , "Annuler");
define('ttChangeLanguage' , "Changer de langue");
define('ttChangeVersion' , "Changer la version de test");
define('ttCheck' , "Vérifier...");
define('ttClose' , "Fermer");
define('ttClosed' , "Fermé");
define('ttCorrect' , "Correct");
define('ttConfiguration' , "Configuration");
define('ttConfirm' , "Confirmer");
define('ttConfirmEmail' , "Confirmez votre e-mail");
define('ttConfirmPassword' , "Confirmez le mot de passe");
define('ttCreate' , "Créer");
define('ttCArchiveExam' , "Êtes-vous sûr de vouloir archiver l'examen? ");
define('ttCBlockTest' , "Êtes-vous sûr de bloquer ce test?");
define('ttCChangeStatus' , "Etes-vous sûr de changer le statut de la question en _STATUS_?");
define('ttCConfirmTest' , "Voulez-vous confirmer le résultat du test? ");
define('ttCDeleteAnswer' , "Etes-vous sûr de vouloir supprimer cette réponse et ses traductions? ");
define('ttCDeleteExam' , "Êtes-vous sûr de vouloir supprimer cet examen? ");
define('ttCDeleteQuestion' , "Êtes-vous sûr de vouloir supprimer cette question et ses traductions? ");
define('ttCDeleteRoom' , "Êtes-vous sûr de vouloir supprimer cette pièce? ");
define('ttCDeleteSubject' , "Êtes-vous sûr de vouloir supprimer ce sujet? ");
define('ttCDeleteSettings' , "Êtes-vous sûr de vouloir supprimer ces paramètres de test? ");
define('ttCDeleteTopic' , "Êtes-vous sûr de vouloir supprimer ce sujet? ");
define('ttCDiscardEdits' , "Vos modifications seront perdues. ");
define('ttCDiscardNew' , "L'élément créé sera perdu. ");
define('ttCRegister' , "Êtes-vous sûr de vous inscrire à cet examen?");
define('ttCRegisterStudents' , "Êtes-vous sûr d’inscrire ces étudiants sélectionnés à l’examen?");
define('ttCRenewPassword' , "Le mot de passe de l'examen sera changé. ");
define('ttCStartExam' , "Voulez-vous activer l'examen sélectionné?");
define('ttCStartTest' , "Voulez-vous commencer l'examen maintenant? ");
define('ttCStopExam' , "Voulez-vous désactiver l'examen sélectionné?");
define('ttCSubmitTest' , "Voulez-vous soumettre votre test? ");
define('ttCTest' , "Le mot de passe est correct. ");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Êtes-vous sûr de débloquer ce test?");
define('ttCUpdateConfigurations' , "Etes-vous sûr de sauvegarder les nouvelles configurations du système?");
define('ttCUpdateLanguage' , "Êtes-vous sûr de mettre à jour les fichiers de langue? ");
define('ttD1' , "Facile");
define('ttD2' , "Moyen");
define('ttD3' , "Difficile");
define('ttDatabaseConfiguration' , "Configuration de la base de données");
define('ttDay' , "journée");
define('ttDelete' , "Effacer");
define('ttDescription' , "La description");
define('ttDifficulty' , "Difficulté");
define('ttDifficultyQuestions' , "Questions par difficulté");
define('ttDistribution' , "Distribution");
define('ttDo' , "Faire l'examen");
define('ttDTAnswerInfo' , "Affichage de _TOTAL_ réponses");
define('ttDTAnswerFiltered' , "(filtré de _MAX_ réponses totales)");
define('ttDTAnswerEmpty' , "Pas de réponse à montrer");
define('ttDTExamInfo' , "Affichage des examens _TOTAL_ en cours");
define('ttDTExamFiltered' , "(filtré de _MAX_ total des examens en cours)");
define('ttDTExamEmpty' , "Aucun examen à afficher");
define('ttDTQuestionInfo' , "Affichage de _TOTAL_ questions");
define('ttDTQuestionFiltered' , "(filtré à partir de _MAX_ total de questions)");
define('ttDTQuestionEmpty' , "Aucune question à afficher");
define('ttDTRegisteredStudentInfo' , "Affichage de _TOTAL_ étudiants inscrits");
define('ttDTRegisteredStudentFiltered' , "(filtré de _MAX_ total des étudiants inscrits)");
define('ttDTRegisteredStudentEmpty' , "Aucun étudiant inscrit à montrer");
define('ttDTStudentsInfo' , "Affichage de _TOTAL_ étudiants");
define('ttDTStudentsFiltered' , "(filtré de _MAX_ total des étudiants)");
define('ttDTStudentsEmpty' , "Aucun étudiant à montrer");
define('ttDTTestInfo' , "Affichage de _TOTAL_ test");
define('ttDTTeacherInfo' , "Affichage des enseignants _TOTAL_");
define('ttDTTeacherFiltered' , "(filtré de _MAX_ total d'enseignants)");
define('ttDTTeacherEmpty' , "Aucun enseignant à montrer");
define('ttDTTestFiltered' , "(filtré à partir des tests _MAX_ total)");
define('ttDTTestEmpty' , "Aucun test à montrer");
define('ttDone' , "Examen fait");
define('ttDuration' , "Durée");
define('ttDTsubquestionInfo' , "Sous questions");
define('ttEdit' , "modifier");
define('ttEditableScore' , "Partition éditable");
define('ttError' , "Erreur");
define('ttEmail' , "Email");
define('ttEnd' , "Fin");
define('ttEverywhere' , "Partout");
define('ttExam' , "Examen");
define('ttExams' , "Examens");
define('ttExit' , "Sortie");
define('ttExtra' , "Supplémentaire");
define('ttExamsArchive' , "Archiver");
define('ttExamsInProgress' , "Examens en cours");
define('ttETeachers' , "Examinateur");
define('ttErrorquestion' , "Signaler une erreur");
define('ttEActivationFails' , "L'activation échoue!");
define('ttEAlreadyRegistered' , "L'étudiant est déjà inscrit à cet examen!");
define('ttEAnswerInSet' , "L'opération ne peut pas être terminée. ");
define('ttEAnswerNotFound' , "Réponse non trouvée");
define('ttEAnswers' , "Un problème de réponses s'est produit. ");
define('ttEDatabase' , "Erreur de la base de données!");
define('ttEDates' , "Les dates ne sont pas correctes!");
define('ttEEditRoomAll' , "La salle 'Toutes' ne peut pas être modifiée!");
define('ttEEmailAlreadyRegistered' , "E-mail déjà enregistré!");
define('ttEEmailNotRegistered' , "E-mail non enregistré!");
define('ttEEmailNotValid' , "L'email tapé n'est pas valide! ");
define('ttEEmailsNotMatch' , "Les deux emails ne correspondent pas!");
define('ttEEmptyFields' , "Un ou plusieurs champs sont vides!");
define('ttEExamArchived' , "L'opération ne peut pas être terminée. ");
define('ttEExamNotFound' , "Examen non trouvé!");
define('ttEExamNotStarted' , "Vous ne pouvez pas commencer l'examen. ");
define('ttEExamStarted' , "L'opération ne peut pas être terminée car l'examen est déjà commencé!");
define('ttEExamWaiting' , "L'opération ne peut pas être terminée car l'examen n'est jamais commencé!");
define('ttEExamsNotArchivedDeleteTopic' , "L'opération ne peut pas être terminée, car au moins un examen non archivé contient des questions de ce sujet!");
define('ttEExamsNotArchivedEditTestSettings' , "L'opération ne peut pas être terminée car ces paramètres sont utilisés par au moins un examen non archivé.");
define('ttEExamsNotArchivedDeleteTestSettings' , "L'opération ne peut pas être terminée car ces paramètres sont utilisés par au moins un examen non archivé!");
define('ttEIncorrectField' , "Un ou plusieurs champs ne sont pas corrects!");
define('ttELogin' , "E-mail et / ou mot de passe ne sont pas corrects!");
define('ttEMainLanguageEmpty' , "La langue principale du sujet ne peut pas être vide!");
define('ttEMandatoryQuestion' , "Ceci est une question obligatoire du paramétrage du test '_TESTSETTING_': vous ne pouvez pas le supprimer, ni modifier sa difficulté ou son sujet.");
define('ttENotAuthorized' , "Votre client n'est pas autorisé. ");
define('ttENoStudentsToRegister' , "Aucun étudiant à s'inscrire!");
define('ttENoTopicsForSubject' , "Pas de sujet pour ce sujet! ");
define('ttEOldPasswordWrong' , "L'ancien mot de passe n'est pas correct!");
define('ttEPassword' , "Mauvais mot de passe!");
define('ttEPasswordShort' , "Le mot de passe est trop court. ");
define('ttEPasswordsNotMatch' , "Les deux mots de passe ne correspondent pas!");
define('ttEQuestAnswPicker' , "Erreur lors de la sélection des questions et réponses. ");
define('ttEQuestionInSet' , "L'opération ne peut pas être terminée. ");
define('ttEQuestionNotFound' , "Question non trouvée!");
define('ttEQuestionType' , "Le type de question n'est pas correct!");
define('ttERegFailedQuestions' , "L'inscription a échoué: trop peu de questions! ");
define('ttERoomAllDelete' , "La salle 'Toutes' ne peut pas être supprimée!");
define('ttERoomUsed' , "L'opération ne peut pas être terminée. ");
define('ttESaveBeforeNew' , "Avant de créer un nouvel élément, veuillez enregistrer ou annuler celui déjà créé.");
define('ttESelectQuestionType' , "Vous devez sélectionner l'un des types de questions disponibles!");
define('ttESelectSubject' , "Vous devez sélectionner l'un de vos sujets!");
define('ttESelectTestSettings' , "Vous devez sélectionner l'un des paramètres de test!");
define('ttESetNotFound' , "Ensemble de questions non trouvé!");
define('ttETestAlreadyArchived' , "L'opération ne peut pas être terminée. ");
define('ttETestAlreadySubmitted' , "L'opération ne peut pas être terminée. ");
define('ttETestBlockedSubmitted' , "L'opération ne peut pas être terminée. ");
define('ttETestNotArchived' , "L'opération ne peut pas être terminée. ");
define('ttETestNotFound' , "Test non trouvé!");
define('ttETestsNotArchived' , "Certains tests n'ont pas été archivés! ");
define('ttETestSettingDeleteQuestion' , "L'opération ne peut pas être terminée. ");
define('ttETestSettingDeleteTopic' , "L'opération ne peut pas être terminée. ");
define('ttETimeExpired' , "Le temps disponible est expiré!");
define('ttETranslationExists' , "La traduction de la langue sélectionnée existe déjà!");
define('ttEUserNotFound' , "Utilisateur non trouvé!");
define('ttEValues' , "Certaines valeurs ne sont pas correctes!");
define('ttFalse' , "Faux");
define('ttFinalScore' , "Score final");
define('ttGeneralInformations' , "Informations générales");
define('ttHours' , "heures");
define('ttHome' , "Accueil");
define('ttHomepage' , "Page d'accueil");
define('ttHost' , "Hôte");
define('ttHAnswPanel' , "Double-cliquez pour éditer la réponse sélectionnée");
define('ttHQuestLanguagesPanel' , "Cliquez pour afficher la traduction de la question sélectionnée");
define('ttHQuestPanel' , "Un simple clic pour sélectionner et afficher l'aperçu de la question, et double-cliquer pour modifier les informations sur la question et les réponses. ");
define('ttHQuestPreviewPanel' , "Les réponses sur fond orange ne sont pas traduites dans la langue demandée");
define('ttHQuestTopicPanel' , "Un simple clic pour filtrer les questions et double-cliquer pour modifier les informations sur le sujet");
define('ttInfo' , "Info");
define('ttIPEnd' , "Fin IPv4");
define('ttIPStart' , "Début IPv4");
define('ttInactive' , "Inactif");
define('ttImportQM' , "Importation");
define('ttImport' , "Importer QM");
define('ttImportComplete' , "Questions importées avec succès");
define('ttJoin' , "Joindre");
define('ttLanguage' , "La langue");
define('ttLanguages' , "Les langues");
define('ttLogin' , "S'identifier");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Connexion terminée!");
define('ttLogout' , "CONNECTEZ - OUT");
define('ttMailLostPassword' , "Pour réinitialiser le mot de passe de votre compte, cliquez sur le lien suivant: _LINK_ Si vous n'avez pas encore demandé de réinitialisation de mot de passe, ignorez cet e-mail.");
define('ttMailCredentials' , "Cher _USERNAME_, Votre mot de passe associé au compte _USEREMAIL_ a été modifié en fonction de votre demande. ");
define('ttMailNewTeacher' , "Bienvenue sur _SYSTEMNAME_. ");
define('ttMainLanguage' , "Langage principal");
define('ttManage' , "Gérer");
define('ttMandatory' , "Obligatoire");
define('ttManual' , "Manuel");
define('ttMinutes' , "minutes");
define('ttMyExams' , "Mes examens");
define('ttMySettings' , "Mes paramètres");
define('ttMySubjects' , "Sélectionnez un sujet");
define('ttMActivation' , "Mot de passe défini avec succès. ");
define('ttMAnswerDeleted' , "Réponse supprimée avec succès");
define('ttMConfigurationsUpdated' , "Configurations système mises à jour avec succès");
define('ttMConfirm' , "Test confirmé et archivé avec succès");
define('ttMUserCreated' , "Création terminée: un email vous a été envoyé pour compléter l'inscription. ");
define('ttMEdit' , "Edits sauvegardés avec succès");
define('ttMExamArchived' , "Examen archivé avec succès");
define('ttMExamDeleted' , "Examen supprimé avec succès");
define('ttMExamStarted' , "Examen commencé avec succès");
define('ttMExamStopped' , "Examen arrêté avec succès");
define('ttMLanguageCreated' , "Traduction créée avec succès");
define('ttMLanguageSaved' , "Traduction enregistrée avec succès");
define('ttMLanguageUpdated' , "Traduction mise à jour avec succès");
define('ttMNewAnswer' , "Réponse créée avec succès");
define('ttMNewQuestion' , "Question créée avec succès");
define('ttMNewRoom' , "Chambre créée avec succès");
define('ttMNewSettings' , "Paramètres de test créés avec succès");
define('ttMNewSubject' , "Sujet créé avec succès");
define('ttMNewTopic' , "Sujet créé avec succès");
define('ttMPasswordRenewed' , "Mot de passe de l'examen renouvelé avec succès");
define('ttMQuestionDeleted' , "Question supprimée avec succès");
define('ttMRegistration' , "Vous avez réussi votre inscription à cet examen");
define('ttMResetConfirmed' , "Requête complétée: un email vous a été envoyé pour réinitialiser votre mot de passe. ");
define('ttMRoomDeleted' , "Chambre supprimée avec succès");
define('ttMSelectLanguage' , "Sélectionnez la langue que vous souhaitez gérer");
define('ttMSettingsDeleted' , "Paramètres de test supprimés avec succès");
define('ttMStudentsRegistered' , "Etudiants inscrits à l'examen avec succès");
define('ttMSubjectDeleted' , "Sujet supprimé avec succès");
define('ttMSubjectQuestions' , "Pour gérer les sujets et les questions, sélectionnez le sujet.");
define('ttMSubjectSettings' , "Pour gérer les paramètres de l'examen, veuillez sélectionner le sujet.");
define('ttMTestBlocked' , "Test bloqué avec succès");
define('ttMTestSubmitted' , "Test soumis avec succès");
define('ttMTestUnblocked' , "Test débloqué avec succès");
define('ttMTopicDeleted' , "Sujet supprimé avec succès");
define('ttName' , "prénom");
define('ttNumberError' , "La valeur doit être un entier ou un nombre décimal (ES: 12.5)");
define('ttNegativeScores' , "Scores négatifs");
define('ttNew' , "Nouveau");
define('ttNext' , "Suivant");
define('ttNewAnswer' , "Nouvelle réponse");
define('ttNewCredentials' , "Nouveaux pouvoirs");
define('ttNewLanguage' , "Nouveau langage");
define('ttNewPassword' , "nouveau mot de passe");
define('ttNewQuestion' , "Nouvelle question");
define('ttNewRegistration' , "Nouvelle inscription");
define('ttNewRoom' , "Nouvelle pièce");
define('ttNewTeacher' , "Nouveau professeur");
define('ttNewTestSettings' , "Nouveaux paramètres");
define('ttNewSubject' , "Nouveau sujet");
define('ttNewStudent' , "Nouvel étudiant");
define('ttNewTopic' , "Nouveau sujet");
define('ttNewUser' , "Nouvel utilisateur");
define('ttNo' , "Non");
define('ttNoAnswers' , "Aucune réponse disponible pour cette question");
define('ttNoExams' , "Aucun examen disponible pour ce sujet");
define('ttNoExamInProgress' , "Aucun examen en cours");
define('ttNoInfo' , "Il n'y a pas d'informations sur cet examen");
define('ttNoQuestions' , "Aucune question disponible pour ce sujet");
define('ttNoRooms' , "Aucune chambre créée: 'Tous' uniquement disponible");
define('ttNoSettings' , "Aucun paramètre disponible pour ce sujet");
define('ttNoSubjects' , "Aucun sujet disponible");
define('ttNoTestToCorrect' , "Aucun test à corriger");
define('ttNoUserRegistered' , "Aucun utilisateur enregistré pour cet examen");
define('ttOldPassword' , "ancien mot de passe");
define('ttEssayQuestion' , "Question d'essai");
define('ttPassword' , "Mot de passe");
define('ttPasswordLost' , "Mot de passe perdu?");
define('ttPort' , "Port");
define('ttProfile' , "Profil");
define('ttPrepareImportQM' , "Aperçu");
define('ttQuestion' , "Question");
define('ttQuestionPreview' , "Aperçu de la question");
define('ttQuestions' , "Des questions");
define('ttQEc' , "Calculatrice");
define('ttQEp' , "Tableau périodique");
define('ttQTMC' , "Choix multiple");
define('ttQTMCDescription' , "Dans une question à choix multiples, le participant sélectionne un seul choix parmi plusieurs choix pour répondre à la question.");
define('ttQTMR' , "Réponse multiple");
define('ttQTMRDescription' , "Une question à réponses multiples ressemble à un choix multiple, sauf qu'au lieu de devoir faire au plus un choix, l'utilisateur est autorisé à faire un ou plusieurs choix.");
define('ttQTES' , "Question d'essai");
define('ttQTESDescription' , "Une question de rédaction permet au participant de saisir une réponse textuelle longue et libre à une question. ");
define('ttQTYN' , "Oui Non");
define('ttQTYNDescription' , "Une question Oui / Non est une question à choix multiples qui demande au participant de donner une réponse \"Oui\" ou \"Non\" à une question.");
define('ttQTTF' , "Vrai faux");
define('ttQTTFDescription' , "Une question Vrai / Faux est une question à choix multiples qui demande au participant de donner une réponse \"Vrai\" ou \"Faux\" à une question.");
define('ttQTNM' , "Numérique");
define('ttQTNMDescription' , "Dans une question numérique, le participant répond en saisissant un nombre entier ou un nombre réel.");
define('ttQTTM' , "Correspondance de texte");
define('ttQTTMDescription' , "Dans une question de correspondance de texte, le participant tape un ou plusieurs mots pour indiquer sa réponse. ");
define('ttQTHS' , "Point chaud");
define('ttQTHSDescription' , "Une question Hotspot est une question à glisser et déposer comportant une seule zone droite. ");
define('ttQTPL' , "Liste déroulante");
define('ttQuesionid' , "ID de la question");
define('ttQuestionNotes' , "La description");
define('ttQuestionsend' , "Envoyer un rapport");
define('ttQuestionreporting' , "Pour signaler plus de questions, vous devez laisser le champ id vide.");
define('ttRandom' , "au hasard");
define('ttRefresh' , "Rafraîchir");
define('ttRegister' , "registre");
define('ttRegistrations' , "Inscriptions");
define('ttRegEnd' , "Fermeture de l'enregistrement");
define('ttRenewPassword' , "Renouveler le mot de passe");
define('ttReset' , "Réinitialiser");
define('ttResetPassword' , "réinitialiser le mot de passe");
define('ttRole' , "Rôle");
define('ttRooms' , "Pièces");
define('ttSave' , "sauvegarder");
define('ttSaveAnswerInfo' , "Enregistrer les informations de réponse");
define('ttSaveLanguageFiles' , "Enregistrer les fichiers de langue");
define('ttSaveLanguageXML' , "Enregistrer les fichiers de langue XML");
define('ttSaveQuestionInfo' , "Enregistrer les informations sur la question");
define('ttScore' , "But");
define('ttScoreFinal' , "Score final");
define('ttScoreTest' , "Score du test");
define('ttScoreType' , "Type de score");
define('ttScoreMin' , "Score minimum");
define('ttSelectSubject' , "Sélectionnez un sujet");
define('ttSelectSubjectBefore' , "Sélectionnez un sujet avant");
define('ttSet' , "Ensemble");
define('ttSetPassword' , "Veuillez définir votre mot de passe");
define('ttSettings' , "Réglages");
define('ttShowHide' , "Afficher / Masquer");
define('ttSelectSubQuestion' , "Sélectionnez une sous-question");
define('ttSkin' , "Peau");
define('ttStart' , "Début");
define('ttStarted' , "Commencé");
define('ttStop' , "Arrêtez");
define('ttStopped' , "Arrêté");
define('ttStartTest' , "Lancer le test");
define('ttStatus' , "Statut");
define('ttStats' , "Statistiques");
define('ttStudent' , "Étudiant");
define('ttStudents' , "Étudiants");
define('ttST10' , "Dixièmes");
define('ttST30' , "Trentième");
define('ttST100' , "Centième");
define('ttSubject' , "Assujettir");
define('ttSubjects' , "Sujets");
define('ttSubmit' , "Soumettre");
define('ttSurname' , "Nom de famille");
define('ttSystem' , "Système");
define('ttSystemConfiguration' , "Configuration du système");
define('ttSbjVers' , "Version");
define('ttTeacher' , "Prof");
define('ttTeachers' , "Enseignants");
define('ttTest' , "Tester");
define('ttTests' , "Des tests");
define('ttTestToCorrect' , "Tests pour corriger");
define('ttText' , "Texte");
define('ttTime' , "Temps");
define('ttTimeEnd' , "Fin du temps");
define('ttTimeStart' , "Heure de début");
define('ttTimeUsed' , "Temps utilisé");
define('ttTimeZone' , "Fuseau horaire");
define('ttTitle' , "Titre");
define('ttTopic' , "Sujet");
define('ttTopics' , "Les sujets");
define('ttTopicsAndQuestions' , "Sujets et questions");
define('ttTopicsQuestions' , "Questions par sujets");
define('ttTranslations' , "Traductions");
define('ttTrue' , "Vrai");
define('ttType' , "Type");
define('ttUser' , "Utilisateur");
define('ttUsers' , "Utilisateurs");
define('ttView' , "Vue");
define('ttWelcome' , "Bienvenue");
define('ttWaiting' , "Attendre");
define('ttWarning' , "Attention");
define('ttYes' , "Oui");
define('ttAssesmentOverview' , "Rapport de synthèse d'évaluation");
define('ttDeselectAll' , "Tout déselectionner");
define('ttErrorUserParameter' , "Sélectionnez un détail de participant pour continuer!");
define('ttQuestionerror' , "ID de la question");
define('ttRemove' , "Retirer");
define('ttReportCoachingError' , "Sélectionnez une évaluation et un participant pour continuer");
define('ttReportCoachingError2' , "Sélectionnez une évaluation pour continuer");
define('ttReportErrorStudent' , "L'élève sélectionné n'a pas participé aux tests choisis");
define('ttReportMainAO' , "Principale");
define('ttReportTemplateDeleteFailed' , "La suppression a échoué");
define('ttReportTemplateDelet' , "Modèle supprimé");
define('ttReportTemplateLoaded' , "Modèle caricato correttamente");
define('ttReportTemplateSaveError' , "Insérer un nom de modèle sans espace!");
define('ttReportTemplateSaved' , "Modèle enregistré correctement");
define('ttReportTemplateDuplicateError' , "Le nom du modèle existe déjà!");
define('ttReportScoreFilter' , "Si vous avez déjà sélectionné un participant, veuillez sélectionner à nouveau un nouveau participant.");
define('ttSelectAll' , "Tout sélectionner");
define('ttQTFB' , "Remplir les espaces vides");
define('ttQTFB_TEXT' , "Complétez le texte suivant avec les mots appropriés");
define('ttQTFBDescription' , "Dans une question remplie de blancs, le participant doit compléter le texte avec la bonne réponse dans le champ de texte");
define('ttPosterImageVideo' , "Chargement du logo");
define('ttWidthVideo' , "Largeur");
define('ttHeightVideo' , "la taille");
define('ttIdVideo' , "Code d'identification");
define('ttVideoTypeVideo' , "Format vidéo");
define('ttNumberOfPlaysVideo' , "Nombre maximum de lectures");
define('ttToolbarVideo' , "Vidéo");
define('ttDialogTitleVideo' , "Propriété vidéo");
define('ttFakeObjectVideo' , "Vidéo");
define('ttPropertiesVideo' , "Éditer vidéo");
define('ttWidthRequiredVideo' , "La largeur doit être définie");
define('ttHeightRequiredVideo' , "La hauteur doit être définie");
define('ttNumberOfPlayRequiredVideo' , "Le nombre maximum de lectures doit être défini");
define('ttFallbackTemplateVideo' , "Votre navigateur ne supporte pas la vidéo HTML5");
define('ttBrowseVideo' , "Parcourir le serveur");
define('ttsourceVideo' , "Vidéo source");
define('ttNumberOfPlayAlertVideo' , "Vous avez atteint le nombre maximum de lectures de votre vidéo");
define('ttHelpDefault' , "Panneau d'information");
define('ttHelpDefaultDescription' , "Appuyez sur ce bouton pour obtenir une description de ce que vous pouvez faire.");
define('ttHelpQuestion' , "Sélectionnez une question pour lire son contenu ou double-cliquez pour la modifier.");
define('ttHelpADMINNewTeacherDescription' , "Définir le compte d'un nouvel administrateur, enseignant ou examinateur");
define('ttHelpADMINNewStudentDescription' , "Définir le compte d'un nouvel étudiant");
define('ttHelpADMINSelLanguageDescription' , "Sélectionnez une langue à gérer");
define('ttHelpADMINLanguageDescription' , "Ici vous pouvez changer les localisations des mots utilisés par le système");
define('ttHelpADMINSystemConf' , "Ici, vous pouvez modifier les paramètres EOL, soyez prudent");
define('ttHelpADMINRoom' , "Définir les salles où les tests seront effectués");
define('ttHelpADMINImport' , "Cet écran vous permet d'importer de nouvelles questions dans un point d'interrogation.");
define('ttHelpADMINProfile' , "Cet écran vous permet de modifier votre profil.");
define('ttHelpReportAreport' , "Cet écran vous permet de créer un Areport, il est obligatoire de sélectionner au moins un sujet.");
define('ttHelpReportAreportTemplate' , "Sélectionnez les informations que vous pouvez obtenir dans le rapport.");
define('ttHelpReportCreport' , "Cet écran vous permet de créer un Creport, il est obligatoire de sélectionner un participant.");
define('ttHelpReportCreportlist' , "Sélectionnez l'examen pour créer le rapport");
define('ttHelpStudent' , "A gauche se trouvent les tests disponibles, à droite les détails de l'examen sélectionné");
define('ttHelpStudentTest' , "Vous êtes à l'écran d'examen, répondez aux questions et soumettez le test.");
define('ttHelpAdminErrorQuestion' , "Si vous rencontrez des problèmes, vous pouvez les signaler à partir de cette page.");
define('ttHelpExamsCorrect' , "Ici, vous recevez un examen effectué par un étudiant, vérifiez que la correction a été effectuée correctement, puis confirmez le vote.");
define('ttHelpExamsSettings' , "Dans cet écran, vous pouvez définir ou modifier les paramètres à utiliser lors des prochains examens.");
define('ttQTPLDescription' , "La liste déroulante est une question fermée qui permet aux répondants de choisir un choix de réponse parmi une liste de choix présentée dans un menu déroulant.Si vous souhaitez afficher les choix de réponse sous forme de boutons radio ou de cases à cocher, utilisez la question à choix multiples.");
define('ttQuestionsubPL' , "Sous-questions");
define('ttHelpLog' , "Un fichier journal sera automatiquement créé après la modification d'une question déjà attribuée à un test. ");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Groupe");
define('ttSubgroup' , "Sous-groupe");
define('ttAOreportSaved' , "Tout le rapport généré sera sauvegardé sur le serveur. ");
define('ttReport' , "rapport");
define('ttReportAllFinished' , "Tout fini");
define('ttReportAODescription' , "Si vous ne sélectionnez pas d’évaluations spécifiques, toutes les évaluations seront analysées.");
define('ttReportAOWelcome' , "Choisissez une évaluation et utilisez les onglets de l'assistant pour filtrer les données");
define('ttReportAOSelectAssesment' , "Sélectionner les évaluations à rapporter");
define('ttReportAssesmentAuthor' , "Auteur de l'évaluation");
define('ttReportAssessmentInformation' , "Information d'évaluation");
define('ttReportAssesmentID' , "ID d'évaluation");
define('ttReportAssesmentDateTimeFirst' , "Date / heure de la première prise");
define('ttReportAssesmentDateTimeLast' , "Date / heure de la dernière prise");
define('ttReportAssesmentLeastTimeFinished' , "Moins de temps pris pour ceux qui ont fini");
define('ttReportAssesmentName' , "Nom de l'évaluation");
define('ttReportAssesmentNumberStarted' , "Num. ");
define('ttReportAssesmentNumberNotFinished' , "Num. ");
define('ttReportAssesmentNumberFinished' , "Num. ");
define('ttReportAssesmentMinscoreFinished' , "Score minimum de ceux finis");
define('ttReportAssesmentMaxcoreFinished' , "Score maximum de ceux finis");
define('ttReportAssesmentMediumFinished' , "Score moyen des finis");
define('ttReportAssesmentMediumTimeFinished' , "Temps moyen pris pour ceux qui ont fini");
define('ttReportAssesmentMostTimeFinished' , "La plupart du temps pris pour ceux qui ont fini");
define('ttReportAssesmentScore' , "Filtrer par score d'évaluation");
define('ttReportAssesmentStdDeviation' , "Écart type pour ceux qui ont fini");
define('ttReportChecked' , "Choisi");
define('ttReportCoaching' , "Rapport de coaching");
define('ttReportCWelcome' , "Choisissez une évaluation et un participant");
define('ttReportCDescription' , "Vous devez filtrer les données par date et, si vous le souhaitez, également par score");
define('ttReportCoachingDescription' , "Voir les résultats détaillés pour un participant prenant une évaluation");
define('ttReportCoachingInformation' , "Sélectionnez un test pour voir des informations détaillées");
define('ttReportCustomize' , "Personnalisez votre rapport");
define('ttReportDateInterval' , "Intervalle de dates");
define('ttReportDateFrom' , "De");
define('ttReportDateTaken' , "Date prise");
define('ttReportDateTo' , "à");
define('ttReportErrorDetail' , "Veuillez sélectionner un participant pour afficher les détails.");
define('ttReportField' , "Nom de domaine");
define('ttReportGraphicalDsiplays' , "Affichages graphiques");
define('ttReportGraphicHistogram' , "Histogramme des scores d'évaluation");
define('ttReportGraphicTopicScore' , "Histogramme des notes du sujet");
define('ttReportGroup' , "Groupes");
define('ttReportGroupNotPresent' , "Il n'y a pas de groupes");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filtrer par score minimum");
define('ttReportMaximumScore' , "Filtrer par score maximum");
define('ttReportNotFilter' , "Ne pas utiliser le filtre");
define('ttReportOrder' , "Ordre");
define('ttReportPartecipants' , "Participants");
define('ttReportPartecipant' , "Participant");
define('ttReportScheduled' , "Programme");
define('ttReportScoreBand' , "Filtrer par bande de score");
define('ttReportSearch' , "Chercher...");
define('ttReportSearched' , "Résultat de la recherche");
define('ttReportSelectDetail' , "Sélectionnez l'ID utilisateur ou l'e-mail du participant sélectionné avant");
define('ttReportSelectFilter' , "Sélectionnez le filtre");
define('ttReportSelectGroup' , "Sélectionner les groupes filtrer sur");
define('ttReportSelectLetter' , "Lettre");
define('ttReportAOSelectPartecipant' , "Sélectionnez un participant");
define('ttReportSelected' , "Évaluations sélectionnées");
define('ttReportSelectTemplate' , "Sélectionnez un modèle");
define('ttReportSelectedGroup' , "Groupes sélectionnés");
define('ttReportSearchByLetter' , "Recherche par lettre");
define('ttReportStudent' , "Filtrer sur le participant");
define('ttReportStudentNotPresent' , "Il n'y a pas d'étudiants");
define('ttReportStudentDetail' , "Filtrer sur les détails du participant");
define('ttReportTemplateLoad' , "Sélectionnez un modèle à charger");
define('ttReportTemplateSave' , "Enregistrer le modèle sous");
define('ttReportTemplateName' , "Insérer le nom");
define('ttReportTimedOut' , "Fin du temps");
define('ttReportTopicAverageScore' , "Score moyen");
define('ttReportTopicInformation' , "Informations sur le sujet");
define('ttReportTopicMaximumScore' , "Score maximum");
define('ttReportTopicMinimumScore' , "Note minimale");
define('ttReportTopicName' , "Nom du sujet");
define('ttReportTopicStandardDeviation' , "Déviation standard");
define('ttReportTyping' , "Rechercher en tapant");
define('ttReportQuestionType' , "Type de question");
define('ttReportViewer' , "Visionneuse de rapports");
define('ttReportViewerDescription' , "Voir tous les rapports générés et les gérer");
define('ttStudentDetailCreport' , "Détail étudiant");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Certificats");
define('ttCertificate' , "Certificat");
define('ttNewGroup' , "Ajouter un groupe");
define('ttEditGroup' , "Editer le groupe");
define('ttEditTeacher' , "Editer le professeur");
define('ttEditStudent' , "Editer un étudiant");
define('tteTeacher' , "Examinateur");
define('tttotals' , "Total");
define('ttD1s' , "Facile");
define('ttD2s' , "Moyen");
define('ttD3s' , "Difficile");
define('ttSelectStudent' , "Liste des étudiants");
define('ttSelectTeacher' , "Liste des enseignants");
define('ttCoord' , "Les coordonnées");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "La liste des examens est affichée ici. ");
define('ttHelpSubject' , "Ici, vous verrez une liste des cours que vous enseignez. ");
define('ttNotAvailable' , "Les paramètres sélectionnés ne vous permettent pas de générer un test.");
define('ttSelectGroup' , "Editer des groupes ou des sous-groupes");
define('ttConfirmProcedure' , "Tu veux vraiment faire ça?");
define('ttUserDeleted' , "Utilisateur supprimé correctement");
define('ttMGroupCreated' , "Groupe créé avec succès");
define('ttMSubgroupCreated' , "Sous-groupe créé avec succès");
define('ttNewSubgroup' , "Ajouter un sous-groupe");
define('ttErrorTopic' , "Trop de questions de sujet sélectionnées");
define('ttAvailable' , "questions disponibles de");
define('ttThereAreNot' , "Il n'y a pas");
define('ttErrorMax' , "Ce champ ne peut pas être inférieur au nombre de questions obligatoires sélectionnées");
define('ttField' , "Le champ");
define('ttHard' , "Difficile");
define('ttMedium' , "Moyen");
define('ttEasy' , "Facile");
define('ttMustBeaNumber' , "Doit être un nombre");
define('ttMaxHardReached' , "Nombre maximum de questions difficiles déjà atteint");
define('ttMaxMediumReached' , "Nombre maximum de questions moyennes déjà atteintes");
define('ttMaxEasyReached' , "Nombre maximum de questions faciles déjà atteint");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Si vous cliquez sur le bouton Oui, l'examen de l'étudiant sera automatiquement transmis au système dans son état actuel. ");
define('ttProfCert' , "Certificat de compétence");
define('ttCertify' , "Ceci est pour certifier que");
define('ttSuccess' , "a passé avec succès");
define('ttEvaluation' , "avec évaluation");
define('ttAccreditedTestSite' , "sur le site d’essai accrédité du");
define('ttOn' , "sur");
define('ttNumQuestionsTopic' , "Nombre de questions pour chaque sujet");
define('ttParamNotSet' , "Paramètres manquants");
define('ttNotEnoughQuestions' , "Pas assez de questions");
define('ttExamArchivedCertNot' , "L'examen est archivé mais les certificats n'ont pas été générés");
define('ttSendCertificate' , "Télécharger le certificat");
define('ttCertificateAlert' , "Êtes-vous sûr de vouloir générer et télécharger le certificat d'examen pour l'étudiant? ");
define('ttCertificateScore' , "L'étudiant n'a pas le score minimum pour recevoir un certificat");
define('ttCertificateGenerated' , "Le certificat a été généré correctement");
define('ttBut' , "mais");
define('ttAnd' , "et");
define('ttCertificateEmailSended' , "l'e-mail a été envoyé avec succès");
define('ttCertificateGeneratedProblem' , "Le certificat n'a pas été généré!");
define('ttCertificatePoint' , "Le score de l’étudiant est trop faible et ne peut être délivré de certificat.");
define('ttPrivacy1' , "Je lis et accepte le");
define('ttPrivacy2' , "Politique de confidentialité ECTN");
define('ttPrivacy3' , "Je souhaite être informé de la possibilité d'obtenir un certificat d'aptitude individuel");
