<?php
define('ttAccountActivation' , "активация аккаунта");
define('ttActive' , "активный");
define('ttActivate' , "активировать");
define('ttAdd' , "добавлять");
define('ttAddSelectedStudents' , "Добавить выбранных студентов");
define('ttAdministration' , "администрация");
define('ttAdministrator' , "администратор");
define('ttAdminWelcome' , "Добро пожаловать на панель администрирования. ");
define('ttAlias' , "Код ISO 639-1");
define('ttAndExit' , "и выход");
define('ttAnswer' , "Ответ");
define('ttAnswers' , "ответы");
define('ttArchive' , "Архив");
define('ttArchived' , "Архивировано");
define('ttAssignSubject' , "Назначить тему");
define('ttAutomatic' , "автоматическая");
define('ttAImportComplete' , "Импорт вопросов уже успешно завершен");
define('ttBasedOn' , "На основе");
define('ttBlocked' , "блокированный");
define('ttBlock' , "блок");
define('ttUnblock' , "открыть");
define('ttBonus' , "бонус");
define('ttCancel' , "отменить");
define('ttChangeLanguage' , "Изменить язык");
define('ttChangeVersion' , "Изменить тестовую версию");
define('ttCheck' , "Проверьте...");
define('ttClose' , "близко");
define('ttClosed' , "Закрыто");
define('ttCorrect' , "Правильный");
define('ttConfiguration' , "конфигурация");
define('ttConfirm' , "подтвердить");
define('ttConfirmEmail' , "Подтвердите адрес электронной почты");
define('ttConfirmPassword' , "Подтвердите Пароль");
define('ttCreate' , "Создайте");
define('ttCArchiveExam' , "Вы уверены, что заархивировали экзамен? ");
define('ttCBlockTest' , "Вы уверены, что заблокировали этот тест?");
define('ttCChangeStatus' , "Вы действительно хотите изменить статус вопроса на _STATUS_?");
define('ttCConfirmTest' , "Хотите подтвердить результаты теста? ");
define('ttCDeleteAnswer' , "Вы уверены, что хотите удалить этот ответ и его переводы? ");
define('ttCDeleteExam' , "Вы уверены, что хотите удалить этот экзамен? ");
define('ttCDeleteQuestion' , "Вы уверены, что хотите удалить этот вопрос и его переводы? ");
define('ttCDeleteRoom' , "Вы уверены, что хотите удалить эту комнату? ");
define('ttCDeleteSubject' , "Вы уверены, что хотите удалить эту тему? ");
define('ttCDeleteSettings' , "Вы уверены, что хотите удалить настройки этого теста? ");
define('ttCDeleteTopic' , "Вы уверены, что хотите удалить эту тему? ");
define('ttCDiscardEdits' , "Ваши изменения будут потеряны. ");
define('ttCDiscardNew' , "Созданный предмет будет потерян. ");
define('ttCRegister' , "Вы уверены, что хотите зарегистрироваться на этот экзамен?");
define('ttCRegisterStudents' , "Вы уверены, что зарегистрировали этих отобранных студентов на экзамене?");
define('ttCRenewPassword' , "Пароль экзамена будет изменен. ");
define('ttCStartExam' , "Вы хотите активировать выбранный экзамен?");
define('ttCStartTest' , "Вы хотите начать экзамен сейчас? ");
define('ttCStopExam' , "Вы хотите деактивировать выбранный экзамен?");
define('ttCSubmitTest' , "Хотите отправить свой тест? ");
define('ttCTest' , "Пароль правильный. ");
define('ttCumLaudae' , "с отличием");
define('ttCUnblockTest' , "Вы уверены, что разблокировать этот тест?");
define('ttCUpdateConfigurations' , "Вы уверены, что сохранили новые конфигурации системы?");
define('ttCUpdateLanguage' , "Вы уверены, что хотите обновить языковые файлы? ");
define('ttD1' , "Легко");
define('ttD2' , "Средняя");
define('ttD3' , "Жесткий");
define('ttDatabaseConfiguration' , "Конфигурация базы данных");
define('ttDay' , "День");
define('ttDelete' , "удалять");
define('ttDescription' , "Описание");
define('ttDifficulty' , "трудность");
define('ttDifficultyQuestions' , "Вопросов на сложность");
define('ttDistribution' , "распределение");
define('ttDo' , "Сделать экзамен");
define('ttDTAnswerInfo' , "Показаны _TOTAL_ ответы");
define('ttDTAnswerFiltered' , "(отфильтровано из _MAX_ всего ответов)");
define('ttDTAnswerEmpty' , "Нет ответов, чтобы показать");
define('ttDTExamInfo' , "Показаны итоговые _TOTAL_ экзамены");
define('ttDTExamFiltered' , "(отфильтровано по итоговым экзаменам _MAX_)");
define('ttDTExamEmpty' , "Нет экзаменов, чтобы показать");
define('ttDTQuestionInfo' , "Показаны _TOTAL_ вопросы");
define('ttDTQuestionFiltered' , "(отфильтровано из _MAX_ всего вопросов)");
define('ttDTQuestionEmpty' , "Нет вопросов для показа");
define('ttDTRegisteredStudentInfo' , "Показаны _TOTAL_ зарегистрированные студенты");
define('ttDTRegisteredStudentFiltered' , "(отфильтровано из _MAX_ всего зарегистрированных студентов)");
define('ttDTRegisteredStudentEmpty' , "Нет зарегистрированных студентов, чтобы показать");
define('ttDTStudentsInfo' , "Показаны _TOTAL_ студенты");
define('ttDTStudentsFiltered' , "(отфильтровано от _MAX_ всего студентов)");
define('ttDTStudentsEmpty' , "Нет студентов, чтобы показать");
define('ttDTTestInfo' , "Показывает _TOTAL_ тест");
define('ttDTTeacherInfo' , "Показаны _TOTAL_ учителя");
define('ttDTTeacherFiltered' , "(отфильтровано из _MAX_ всего учителей)");
define('ttDTTeacherEmpty' , "Нет учителя, чтобы показать");
define('ttDTTestFiltered' , "(отфильтровано по итоговым тестам _MAX_)");
define('ttDTTestEmpty' , "Нет тестов, чтобы показать");
define('ttDone' , "Экзамен готов");
define('ttDuration' , "продолжительность");
define('ttDTsubquestionInfo' , "Под Вопросы");
define('ttEdit' , "редактировать");
define('ttEditableScore' , "Редактируемый счет");
define('ttError' , "ошибка");
define('ttEmail' , "Эл. почта");
define('ttEnd' , "Конец");
define('ttEverywhere' , "Везде");
define('ttExam' , "Экзамен");
define('ttExams' , "Экзамены");
define('ttExit' , "Выход");
define('ttExtra' , "дополнительный");
define('ttExamsArchive' , "Архив");
define('ttExamsInProgress' , "Экзамены в процессе");
define('ttETeachers' , "Экзаменатор");
define('ttErrorquestion' , "Сообщить об ошибке");
define('ttEActivationFails' , "Активация не удалась!");
define('ttEAlreadyRegistered' , "Студент уже зарегистрирован на этот экзамен!");
define('ttEAnswerInSet' , "Операция не может быть завершена. ");
define('ttEAnswerNotFound' , "Ответ не найден");
define('ttEAnswers' , "Возникла проблема с ответами. ");
define('ttEDatabase' , "Ошибка базы данных!");
define('ttEDates' , "Даты не верны!");
define('ttEEditRoomAll' , "Комната «Все» не редактируется!");
define('ttEEmailAlreadyRegistered' , "E-mail уже зарегистрирован!");
define('ttEEmailNotRegistered' , "Электронная почта не зарегистрирована!");
define('ttEEmailNotValid' , "Напечатанный адрес электронной почты недействителен! ");
define('ttEEmailsNotMatch' , "Два электронных письма не совпадают!");
define('ttEEmptyFields' , "Одно или несколько полей пусты!");
define('ttEExamArchived' , "Операция не может быть завершена. ");
define('ttEExamNotFound' , "Экзамен не найден!");
define('ttEExamNotStarted' , "Вы не можете начать экзамен. ");
define('ttEExamStarted' , "Операция не может быть завершена, потому что экзамен уже начался!");
define('ttEExamWaiting' , "Операция не может быть завершена, потому что экзамен никогда не начинается!");
define('ttEExamsNotArchivedDeleteTopic' , "Операция не может быть завершена, потому что хотя бы один неархивированный экзамен содержит вопросы из этой темы!");
define('ttEExamsNotArchivedEditTestSettings' , "Операция не может быть завершена, поскольку эти настройки используются как минимум одним неархивированным экзаменом.");
define('ttEExamsNotArchivedDeleteTestSettings' , "Операция не может быть завершена, поскольку эти настройки используются как минимум одним неархивированным экзаменом!");
define('ttEIncorrectField' , "Одно или несколько полей не верны!");
define('ttELogin' , "E-mail и / или пароль не верны!");
define('ttEMainLanguageEmpty' , "Основной язык субъекта не может быть пустым!");
define('ttEMandatoryQuestion' , "Это обязательный вопрос настройки теста «_TESTSETTING_»: вы не можете удалить его или изменить его сложность или тему.");
define('ttENotAuthorized' , "Ваш клиент не авторизован. ");
define('ttENoStudentsToRegister' , "Нет студента для регистрации!");
define('ttENoTopicsForSubject' , "Нет темы для этой темы! ");
define('ttEOldPasswordWrong' , "Старый пароль не верный!");
define('ttEPassword' , "Неправильный пароль!");
define('ttEPasswordShort' , "Пароль слишком короткий. ");
define('ttEPasswordsNotMatch' , "Два пароля не совпадают!");
define('ttEQuestAnswPicker' , "Ошибка при выборе вопросов и ответов. ");
define('ttEQuestionInSet' , "Операция не может быть завершена. ");
define('ttEQuestionNotFound' , "Вопрос не найден!");
define('ttEQuestionType' , "Тип вопроса не правильный!");
define('ttERegFailedQuestions' , "Регистрация не удалась: слишком мало вопросов! ");
define('ttERoomAllDelete' , "Комната «Все» не может быть удалена!");
define('ttERoomUsed' , "Операция не может быть завершена. ");
define('ttESaveBeforeNew' , "Перед созданием нового элемента, пожалуйста, сохраните или отмените уже созданный.");
define('ttESelectQuestionType' , "Вы должны выбрать один из доступных типов вопросов!");
define('ttESelectSubject' , "Вы должны выбрать один из ваших предметов!");
define('ttESelectTestSettings' , "Вы должны выбрать одну из настроек теста!");
define('ttESetNotFound' , "Вопросы не найдены!");
define('ttETestAlreadyArchived' , "Операция не может быть завершена. ");
define('ttETestAlreadySubmitted' , "Операция не может быть завершена. ");
define('ttETestBlockedSubmitted' , "Операция не может быть завершена. ");
define('ttETestNotArchived' , "Операция не может быть завершена. ");
define('ttETestNotFound' , "Тест не найден!");
define('ttETestsNotArchived' , "Некоторые тесты не были заархивированы! ");
define('ttETestSettingDeleteQuestion' , "Операция не может быть завершена. ");
define('ttETestSettingDeleteTopic' , "Операция не может быть завершена. ");
define('ttETimeExpired' , "Доступное время истекло!");
define('ttETranslationExists' , "Перевод выбранного языка уже существует!");
define('ttEUserNotFound' , "Пользователь не найден!");
define('ttEValues' , "Некоторые значения не верны!");
define('ttFalse' , "Ложь");
define('ttFinalScore' , "Финальный счет");
define('ttGeneralInformations' , "Основная информация");
define('ttHours' , "часов");
define('ttHome' , "Главная");
define('ttHomepage' , "домашняя страница");
define('ttHost' , "хозяин");
define('ttHAnswPanel' , "Двойной щелчок для редактирования выбранного ответа");
define('ttHQuestLanguagesPanel' , "Нажмите, чтобы показать перевод выбранного вопроса");
define('ttHQuestPanel' , "Один щелчок, чтобы выбрать и просмотреть предварительный просмотр вопроса, и двойной щелчок, чтобы изменить информацию о вопросе и ответах. ");
define('ttHQuestPreviewPanel' , "Ответы с оранжевым фоном не переведены на требуемый язык");
define('ttHQuestTopicPanel' , "Один клик для фильтрации вопросов и двойной клик для редактирования информации о теме");
define('ttInfo' , "Информация");
define('ttIPEnd' , "IPv4 End");
define('ttIPStart' , "IPv4 Start");
define('ttInactive' , "Неактивный");
define('ttImportQM' , "Импортировать");
define('ttImport' , "Импорт QM");
define('ttImportComplete' , "Импорт вопросов успешно завершен");
define('ttJoin' , "Присоединиться");
define('ttLanguage' , "язык");
define('ttLanguages' , "Языки");
define('ttLogin' , "Авторизоваться");
define('ttLogo' , "логотип");
define('ttLoginOk' , "Авторизация завершена!");
define('ttLogout' , "ВЫЙТИ");
define('ttMailLostPassword' , "Чтобы сбросить пароль учетной записи, перейдите по следующей ссылке: _LINK_ Если вы не запрашивали сброс пароля, игнорируйте это письмо.");
define('ttMailCredentials' , "Уважаемый _USERNAME_, Ваш пароль, связанный с учетной записью _USEREMAIL_, был изменен в соответствии с вашим запросом. ");
define('ttMailNewTeacher' , "Добро пожаловать в _SYSTEMNAME_. ");
define('ttMainLanguage' , "Главный язык");
define('ttManage' , "управлять");
define('ttMandatory' , "Обязательный");
define('ttManual' , "Руководство");
define('ttMinutes' , "минут");
define('ttMyExams' , "Мои экзамены");
define('ttMySettings' , "Мои настройки");
define('ttMySubjects' , "Выберите тему");
define('ttMActivation' , "Пароль успешно установлен. ");
define('ttMAnswerDeleted' , "Ответ успешно удален");
define('ttMConfigurationsUpdated' , "Конфигурации системы успешно обновлены");
define('ttMConfirm' , "Тест успешно подтвержден и заархивирован");
define('ttMUserCreated' , "Создание завершено: вам было отправлено электронное письмо для завершения регистрации. ");
define('ttMEdit' , "Изменения успешно сохранены");
define('ttMExamArchived' , "Экзамен успешно заархивирован");
define('ttMExamDeleted' , "Экзамен успешно удален");
define('ttMExamStarted' , "Экзамен успешно начался");
define('ttMExamStopped' , "Экзамен успешно остановлен");
define('ttMLanguageCreated' , "Перевод успешно создан");
define('ttMLanguageSaved' , "Перевод успешно сохранен");
define('ttMLanguageUpdated' , "Перевод успешно обновлен");
define('ttMNewAnswer' , "Ответ успешно создан");
define('ttMNewQuestion' , "Вопрос успешно создан");
define('ttMNewRoom' , "Комната успешно создана");
define('ttMNewSettings' , "Настройки теста успешно созданы");
define('ttMNewSubject' , "Тема успешно создана");
define('ttMNewTopic' , "Тема успешно создана");
define('ttMPasswordRenewed' , "Пароль экзамена успешно обновлен");
define('ttMQuestionDeleted' , "Вопрос успешно удален");
define('ttMRegistration' , "Вы успешно зарегистрированы на этом экзамене");
define('ttMResetConfirmed' , "Запрос выполнен: вам было отправлено электронное письмо для сброса пароля. ");
define('ttMRoomDeleted' , "Номер успешно удален");
define('ttMSelectLanguage' , "Выберите язык, которым хотите управлять");
define('ttMSettingsDeleted' , "Настройки теста успешно удалены");
define('ttMStudentsRegistered' , "Студенты успешно зарегистрировались на экзамене");
define('ttMSubjectDeleted' , "Тема успешно удалена");
define('ttMSubjectQuestions' , "Для управления темами и вопросами, пожалуйста, выберите тему");
define('ttMSubjectSettings' , "Чтобы управлять настройками экзамена, выберите тему");
define('ttMTestBlocked' , "Тест успешно заблокирован");
define('ttMTestSubmitted' , "Тест успешно отправлен");
define('ttMTestUnblocked' , "Тест успешно разблокирован");
define('ttMTopicDeleted' , "Тема успешно удалена");
define('ttName' , "название");
define('ttNumberError' , "Значение должно быть целым или десятичным (ES: 12,5)");
define('ttNegativeScores' , "Отрицательные оценки");
define('ttNew' , "новый");
define('ttNext' , "следующий");
define('ttNewAnswer' , "Новый ответ");
define('ttNewCredentials' , "Новые полномочия");
define('ttNewLanguage' , "Новый язык");
define('ttNewPassword' , "новый пароль");
define('ttNewQuestion' , "Новый вопрос");
define('ttNewRegistration' , "Новая регистрация");
define('ttNewRoom' , "Новая комната");
define('ttNewTeacher' , "Новый учитель");
define('ttNewTestSettings' , "Новые настройки");
define('ttNewSubject' , "Новая тема");
define('ttNewStudent' , "Новый студент");
define('ttNewTopic' , "Новая тема");
define('ttNewUser' , "Новый пользователь");
define('ttNo' , "нет");
define('ttNoAnswers' , "Нет ответов на этот вопрос");
define('ttNoExams' , "Нет доступных экзаменов по этому предмету");
define('ttNoExamInProgress' , "Экзамен не проводится");
define('ttNoInfo' , "Там нет информации об этом экзамене");
define('ttNoQuestions' , "Нет вопросов по этой теме");
define('ttNoRooms' , "Не создано ни одного номера: доступно только «Все»");
define('ttNoSettings' , "Нет доступных настроек для этой темы");
define('ttNoSubjects' , "Нет доступных предметов");
define('ttNoTestToCorrect' , "Нет тестов для исправления");
define('ttNoUserRegistered' , "Нет зарегистрированных пользователей для этого экзамена");
define('ttOldPassword' , "Прежний пароль");
define('ttEssayQuestion' , "Эссе вопрос");
define('ttPassword' , "пароль");
define('ttPasswordLost' , "Пароль Забыли?");
define('ttPort' , "порт");
define('ttProfile' , "Профиль");
define('ttPrepareImportQM' , "предварительный просмотр");
define('ttQuestion' , "Вопрос");
define('ttQuestionPreview' , "Предварительный просмотр вопроса");
define('ttQuestions' , "Вопросы");
define('ttQEc' , "Калькулятор");
define('ttQEp' , "Периодическая таблица");
define('ttQTMC' , "Большой выбор");
define('ttQTMCDescription' , "В вопросе с несколькими вариантами ответов участник выбирает один вариант из нескольких вариантов ответа на вопрос.");
define('ttQTMR' , "Множественный ответ");
define('ttQTMRDescription' , "Вопрос с несколькими ответами похож на множественный выбор, за исключением того, что вместо того, чтобы делать выбор не более одного выбора, пользователю разрешается сделать один или несколько вариантов.");
define('ttQTES' , "Эссе Вопрос");
define('ttQTESDescription' , "Вопрос к эссе позволяет участнику ввести длинный текстовый ответ в свободном диапазоне на вопрос. ");
define('ttQTYN' , "Да нет");
define('ttQTYNDescription' , "Вопрос «Да / Нет» - это вопрос с несколькими вариантами ответов, в котором участник просит дать ответ «Да» или «Нет» на вопрос.");
define('ttQTTF' , "True / False");
define('ttQTTFDescription' , "Правдивый / Ложный вопрос - это вопрос с множественным выбором, который просит участника дать «Верный» или «Ложный» ответ на вопрос.");
define('ttQTNM' , "числовой");
define('ttQTNMDescription' , "В числовом вопросе участник отвечает, набирая либо целое число, либо действительное число.");
define('ttQTTM' , "Совпадение текста");
define('ttQTTMDescription' , "В вопросе «Совпадение текста» участник вводит одно слово или несколько слов, чтобы указать свой ответ. ");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Вопрос Hotspot - это вопрос перетаскивания только с одной правой областью. ");
define('ttQTPL' , "Выпадающий список");
define('ttQuesionid' , "Идентификатор вопроса");
define('ttQuestionNotes' , "Описание");
define('ttQuestionsend' , "Отправить жалобу");
define('ttQuestionreporting' , "Чтобы сообщить больше вопросов, вам нужно оставить поле id пустым");
define('ttRandom' , "случайный");
define('ttRefresh' , "обновление");
define('ttRegister' , "регистр");
define('ttRegistrations' , "зарегистрирования");
define('ttRegEnd' , "Закрытие регистрации");
define('ttRenewPassword' , "Обновить пароль");
define('ttReset' , "Сброс");
define('ttResetPassword' , "Сброс пароля");
define('ttRole' , "Роль");
define('ttRooms' , "Номера");
define('ttSave' , "Сохранить");
define('ttSaveAnswerInfo' , "Сохранить информацию об ответе");
define('ttSaveLanguageFiles' , "Сохранить языковые файлы");
define('ttSaveLanguageXML' , "Сохраните языковые файлы XML");
define('ttSaveQuestionInfo' , "Сохранить информацию о вопросе");
define('ttScore' , "Гол");
define('ttScoreFinal' , "Финальный счет");
define('ttScoreTest' , "Оценка теста");
define('ttScoreType' , "Тип оценки");
define('ttScoreMin' , "Минимальная оценка");
define('ttSelectSubject' , "Выберите тему");
define('ttSelectSubjectBefore' , "Выберите тему перед");
define('ttSet' , "Задавать");
define('ttSetPassword' , "Пожалуйста, установите ваш пароль");
define('ttSettings' , "настройки");
define('ttShowHide' , "Показать спрятать");
define('ttSelectSubQuestion' , "Выберите подвопрос");
define('ttSkin' , "кожа");
define('ttStart' , "Начните");
define('ttStarted' , "Началось");
define('ttStop' , "Стоп");
define('ttStopped' , "Остановился");
define('ttStartTest' , "Начать тест");
define('ttStatus' , "Статус");
define('ttStats' , "Статистика");
define('ttStudent' , "Ученик");
define('ttStudents' , "Ученики");
define('ttST10' , "Десятые");
define('ttST30' , "Thirtieths");
define('ttST100' , "сотый");
define('ttSubject' , "Предмет");
define('ttSubjects' , "Предметы");
define('ttSubmit' , "Отправить");
define('ttSurname' , "Фамилия");
define('ttSystem' , "система");
define('ttSystemConfiguration' , "Конфигурация системы");
define('ttSbjVers' , "Версия");
define('ttTeacher' , "учитель");
define('ttTeachers' , "Учителя");
define('ttTest' , "Тестовое задание");
define('ttTests' , "тесты");
define('ttTestToCorrect' , "Тесты исправить");
define('ttText' , "Текст");
define('ttTime' , "Время");
define('ttTimeEnd' , "Конец времени");
define('ttTimeStart' , "Время начала");
define('ttTimeUsed' , "Используемое время");
define('ttTimeZone' , "Часовой пояс");
define('ttTitle' , "заглавие");
define('ttTopic' , "Тема");
define('ttTopics' , "темы");
define('ttTopicsAndQuestions' , "Темы и вопросы");
define('ttTopicsQuestions' , "Вопросы по темам");
define('ttTranslations' , "Переводы");
define('ttTrue' , "Правда");
define('ttType' , "Тип");
define('ttUser' , "пользователь");
define('ttUsers' , "пользователей");
define('ttView' , "Посмотреть");
define('ttWelcome' , "желанный");
define('ttWaiting' , "ждущий");
define('ttWarning' , "Предупреждение");
define('ttYes' , "да");
define('ttAssesmentOverview' , "Обзорный отчет по оценке");
define('ttDeselectAll' , "Убрать выделение со всего");
define('ttErrorUserParameter' , "Выберите участника, чтобы продолжить!");
define('ttQuestionerror' , "Идентификатор вопроса");
define('ttRemove' , "Удалить");
define('ttReportCoachingError' , "Выберите оценку и участника, чтобы продолжить");
define('ttReportCoachingError2' , "Выберите оценку, чтобы продолжить");
define('ttReportErrorStudent' , "Выбранный студент не участвовал в выбранных тестах");
define('ttReportMainAO' , "Главный");
define('ttReportTemplateDeleteFailed' , "Удалить не удалось");
define('ttReportTemplateDelet' , "Шаблон удален");
define('ttReportTemplateLoaded' , "Шаблон Caricato Correttamente");
define('ttReportTemplateSaveError' , "Вставьте имя шаблона без пробела!");
define('ttReportTemplateSaved' , "Шаблон сохранен правильно");
define('ttReportTemplateDuplicateError' , "Название шаблона уже существует!");
define('ttReportScoreFilter' , "Если вы уже выбрали участника, теперь, пожалуйста, повторно выберите нового");
define('ttSelectAll' , "Выбрать все");
define('ttQTFB' , "Заполнить бланки");
define('ttQTFB_TEXT' , "Заполните следующий текст соответствующими словами");
define('ttQTFBDescription' , "В вопросе для заполнения пробелов участник должен заполнить текст с правильным ответом в текстовом поле.");
define('ttPosterImageVideo' , "Загрузка логотипа");
define('ttWidthVideo' , "ширина");
define('ttHeightVideo' , "Рост");
define('ttIdVideo' , "Идентификационный код");
define('ttVideoTypeVideo' , "Видео формат");
define('ttNumberOfPlaysVideo' , "Максимальное количество игр");
define('ttToolbarVideo' , "видео");
define('ttDialogTitleVideo' , "Видео собственности");
define('ttFakeObjectVideo' , "видео");
define('ttPropertiesVideo' , "Редактировать видео");
define('ttWidthRequiredVideo' , "Ширина должна быть установлена");
define('ttHeightRequiredVideo' , "Высота должна быть установлена");
define('ttNumberOfPlayRequiredVideo' , "Максимальное количество игр должно быть установлено");
define('ttFallbackTemplateVideo' , "Ваш браузер не поддерживает видео HTML5");
define('ttBrowseVideo' , "Обзор сервера");
define('ttsourceVideo' , "Исходное видео");
define('ttNumberOfPlayAlertVideo' , "Вы достигли максимального количества просмотров вашего видео");
define('ttHelpDefault' , "Информационная панель");
define('ttHelpDefaultDescription' , "Нажмите эту кнопку, чтобы получить описание того, что вы можете сделать");
define('ttHelpQuestion' , "Выберите вопрос, чтобы прочитать его содержимое, или дважды щелкните, чтобы изменить");
define('ttHelpADMINNewTeacherDescription' , "Определите учетную запись нового администратора, учителя или экзаменатора");
define('ttHelpADMINNewStudentDescription' , "Определить учетную запись нового студента");
define('ttHelpADMINSelLanguageDescription' , "Выберите язык для управления");
define('ttHelpADMINLanguageDescription' , "Здесь вы можете изменить локализацию слов, используемых системой");
define('ttHelpADMINSystemConf' , "Здесь вы можете изменить настройки EOL, будьте осторожны");
define('ttHelpADMINRoom' , "Определите помещения, где будут проводиться испытания");
define('ttHelpADMINImport' , "Этот экран позволяет импортировать новые вопросы в знак вопроса");
define('ttHelpADMINProfile' , "Этот экран позволяет редактировать ваш профиль");
define('ttHelpReportAreport' , "Этот экран позволяет создать Арепорт, обязательно выбрать хотя бы один предмет");
define('ttHelpReportAreportTemplate' , "Выберите, какую информацию вы можете получить в отчете");
define('ttHelpReportCreport' , "На этом экране можно создать Creport, обязательно выбрать участника");
define('ttHelpReportCreportlist' , "Выберите экзамен для создания отчета");
define('ttHelpStudent' , "Слева находятся доступные тесты, справа выбранные детали экзамена");
define('ttHelpStudentTest' , "Вы находитесь на экране экзамена, отвечаете на вопросы и сдаете тест");
define('ttHelpAdminErrorQuestion' , "Если вы обнаружите проблемы, вы можете сообщить с этой страницы.");
define('ttHelpExamsCorrect' , "Здесь вы получите экзамен, проведенный студентом, убедитесь, что исправление было сделано правильно, и затем подтвердите голосование.");
define('ttHelpExamsSettings' , "На этом экране вы можете определить или изменить настройки для использования в будущих экзаменах.");
define('ttQTPLDescription' , "Раскрывающийся вопрос является закрытым вопросом, который позволяет респондентам выбрать один вариант ответа из списка вариантов, представленных в раскрывающемся меню. Если вы хотите отобразить варианты ответов в виде переключателей или флажков, используйте вопрос с несколькими вариантами ответов.");
define('ttQuestionsubPL' , "подвопросы");
define('ttHelpLog' , "Файл журнала будет создан автоматически после изменения вопроса, уже назначенного для теста. ");
define('ttErrorSent' , "ACK");
define('ttGroup' , "группа");
define('ttSubgroup' , "Подгруппа");
define('ttAOreportSaved' , "Весь сгенерированный отчет будет сохранен на сервере. ");
define('ttReport' , "отчет");
define('ttReportAllFinished' , "Все закончено");
define('ttReportAODescription' , "Если вы не выберете конкретные оценки, все оценки будут проанализированы");
define('ttReportAOWelcome' , "Выберите оценку и используйте вкладки мастера для фильтрации данных");
define('ttReportAOSelectAssesment' , "Выберите оценки для отчета");
define('ttReportAssesmentAuthor' , "Оценка автора");
define('ttReportAssessmentInformation' , "Информация об оценке");
define('ttReportAssesmentID' , "ID оценки");
define('ttReportAssesmentDateTimeFirst' , "Дата / Время впервые приняты");
define('ttReportAssesmentDateTimeLast' , "Дата / Время последнего использования");
define('ttReportAssesmentLeastTimeFinished' , "Наименьшее время, необходимое для тех, кто закончил");
define('ttReportAssesmentName' , "Название оценки");
define('ttReportAssesmentNumberStarted' , "Num. ");
define('ttReportAssesmentNumberNotFinished' , "Num. ");
define('ttReportAssesmentNumberFinished' , "Num. ");
define('ttReportAssesmentMinscoreFinished' , "Минимальная оценка законченных");
define('ttReportAssesmentMaxcoreFinished' , "Максимальная оценка законченных");
define('ttReportAssesmentMediumFinished' , "Средний балл законченных");
define('ttReportAssesmentMediumTimeFinished' , "Среднее время, необходимое для тех, кто закончил");
define('ttReportAssesmentMostTimeFinished' , "Большинство времени занято для тех, кто закончил");
define('ttReportAssesmentScore' , "Фильтр по оценкам");
define('ttReportAssesmentStdDeviation' , "Стандартное отклонение для тех, кто закончил");
define('ttReportChecked' , "выбранный");
define('ttReportCoaching' , "Тренерский отчет");
define('ttReportCWelcome' , "Выберите оценку и участника");
define('ttReportCDescription' , "Вы должны фильтровать данные по датам и, если хотите, также по баллам");
define('ttReportCoachingDescription' , "Посмотреть подробные результаты для одного участника, принимающего одну оценку");
define('ttReportCoachingInformation' , "Выберите один тест, чтобы увидеть подробную информацию");
define('ttReportCustomize' , "Настройте свой отчет");
define('ttReportDateInterval' , "Интервал дат");
define('ttReportDateFrom' , "От");
define('ttReportDateTaken' , "Выбранная дата");
define('ttReportDateTo' , "в");
define('ttReportErrorDetail' , "Пожалуйста, выберите участника, чтобы показать детали");
define('ttReportField' , "Имя поля");
define('ttReportGraphicalDsiplays' , "Графические дисплеи");
define('ttReportGraphicHistogram' , "Гистограмма оценочных баллов");
define('ttReportGraphicTopicScore' , "Гистограмма тематических баллов");
define('ttReportGroup' , "группы");
define('ttReportGroupNotPresent' , "Нет групп");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Фильтровать по минимальной оценке");
define('ttReportMaximumScore' , "Фильтровать по максимальному количеству баллов");
define('ttReportNotFilter' , "Не используйте фильтр");
define('ttReportOrder' , "порядок");
define('ttReportPartecipants' , "участники");
define('ttReportPartecipant' , "участник");
define('ttReportScheduled' , "График");
define('ttReportScoreBand' , "Фильтровать по диапазону баллов");
define('ttReportSearch' , "Поиск...");
define('ttReportSearched' , "Результат поиска");
define('ttReportSelectDetail' , "Выберите идентификатор пользователя или адрес электронной почты участника, выбранного ранее");
define('ttReportSelectFilter' , "Выберите фильтр");
define('ttReportSelectGroup' , "Фильтр выбора групп включен");
define('ttReportSelectLetter' , "Письмо");
define('ttReportAOSelectPartecipant' , "Выберите участника");
define('ttReportSelected' , "Избранные оценки");
define('ttReportSelectTemplate' , "Выберите шаблон");
define('ttReportSelectedGroup' , "Выбранные группы");
define('ttReportSearchByLetter' , "Поиск по букве");
define('ttReportStudent' , "Фильтр по участнику");
define('ttReportStudentNotPresent' , "Нет студентов");
define('ttReportStudentDetail' , "Фильтр на детали участника");
define('ttReportTemplateLoad' , "Выберите шаблон для загрузки");
define('ttReportTemplateSave' , "Сохранить шаблон как");
define('ttReportTemplateName' , "Введите имя");
define('ttReportTimedOut' , "Время вышло");
define('ttReportTopicAverageScore' , "Средний счет");
define('ttReportTopicInformation' , "Информация о теме");
define('ttReportTopicMaximumScore' , "Максимальная оценка");
define('ttReportTopicMinimumScore' , "Минимальная оценка");
define('ttReportTopicName' , "Название темы");
define('ttReportTopicStandardDeviation' , "Стандартное отклонение");
define('ttReportTyping' , "Поиск, набрав");
define('ttReportQuestionType' , "Тип вопроса");
define('ttReportViewer' , "Просмотрщик отчетов");
define('ttReportViewerDescription' , "Просмотр всех сгенерированных отчетов и управление ими");
define('ttStudentDetailCreport' , "Студенческая деталь");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Сертификаты");
define('ttCertificate' , "сертификат");
define('ttNewGroup' , "Добавить группу");
define('ttEditGroup' , "Редактировать группу");
define('ttEditTeacher' , "Редактировать Учителя");
define('ttEditStudent' , "Редактировать студента");
define('tteTeacher' , "экзаменатор");
define('tttotals' , "Всего");
define('ttD1s' , "Легко");
define('ttD2s' , "Средняя");
define('ttD3s' , "Жесткий");
define('ttSelectStudent' , "Список студентов");
define('ttSelectTeacher' , "Список учителей");
define('ttCoord' , "Координаты");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "Список экзаменов отображается здесь. ");
define('ttHelpSubject' , "Здесь вы увидите список курсов, которые вы преподаете. ");
define('ttNotAvailable' , "Выбранные настройки не позволяют генерировать тест.");
define('ttSelectGroup' , "Редактировать группы или подгруппы");
define('ttConfirmProcedure' , "Вы действительно хотите это сделать?");
define('ttUserDeleted' , "Пользователь удален правильно");
define('ttMGroupCreated' , "Группа успешно создана");
define('ttMSubgroupCreated' , "Подгруппа успешно создана");
define('ttNewSubgroup' , "Добавить подгруппу");
define('ttErrorTopic' , "Выбрано слишком много тематических вопросов");
define('ttAvailable' , "вопросы доступны из");
define('ttThereAreNot' , "Нет");
define('ttErrorMax' , "Это поле не может быть меньше количества выбранных обязательных вопросов");
define('ttField' , "Поле");
define('ttHard' , "Жесткий");
define('ttMedium' , "Средняя");
define('ttEasy' , "Легко");
define('ttMustBeaNumber' , "Должен быть числом");
define('ttMaxHardReached' , "Максимальное количество сложных вопросов уже достигнуто");
define('ttMaxMediumReached' , "Максимальное количество средних вопросов уже достигнуто");
define('ttMaxEasyReached' , "Максимальное количество простых вопросов уже достигнуто");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Если вы нажмете кнопку «Да», студенческий экзамен будет автоматически доставлен в систему в ее текущем состоянии. ");
define('ttProfCert' , "Сертификат квалификации");
define('ttCertify' , "Настоящим удостоверяется, что");
define('ttSuccess' , "успешно прошел");
define('ttEvaluation' , "с оценкой");
define('ttAccreditedTestSite' , "в Аккредитованном испытательном полигоне");
define('ttOn' , "на");
define('ttNumQuestionsTopic' , "Количество вопросов по каждой теме");
define('ttParamNotSet' , "Недостающие параметры");
define('ttNotEnoughQuestions' , "Не хватает вопросов");
define('ttExamArchivedCertNot' , "Экзамен заархивирован, но сертификаты не были созданы");
define('ttSendCertificate' , "Скачать сертификат");
define('ttCertificateAlert' , "Вы уверены, что хотите сгенерировать и загрузить экзаменационный сертификат студенту? ");
define('ttCertificateScore' , "Студент не имеет минимального балла для получения сертификата");
define('ttCertificateGenerated' , "Сертификат был сгенерирован правильно");
define('ttBut' , "но");
define('ttAnd' , "а также");
define('ttCertificateEmailSended' , "письмо было успешно отправлено");
define('ttCertificateGeneratedProblem' , "Сертификат не был сгенерирован!");
define('ttCertificatePoint' , "Оценка студента слишком низкая и не может быть выдан сертификат.");
define('ttPrivacy1' , "Я читаю и принимаю");
define('ttPrivacy2' , "Политика конфиденциальности ECTN");
define('ttPrivacy3' , "Я хочу быть проинформированным о возможности получения Индивидуального Свидетельства о квалификации");
