<?php
define('ttAccountActivation' , "Attivazione account");
define('ttActive' , "Attivo");
define('ttActivate' , "Attiva");
define('ttAdd' , "Aggiungi");
define('ttAddSelectedStudents' , "Aggiungi studenti selezionati");
define('ttAdministration' , "Amministrazione");
define('ttAdministrator' , "Amministratore");
define('ttAdminWelcome' , "Benvenuto nel pannello d'amministrazione<br/>Il sistema include:");
define('ttAlias' , "Codice ISO 639-1");
define('ttAndExit' , "ed Esci");
define('ttAnswer' , "Risposta");
define('ttAnswers' , "Risposte");
define('ttArchive' , "Archivia");
define('ttArchived' , "Archiviato");
define('ttAssignSubject' , "Assegna Materia");
define('ttAutomatic' , "Automatico");
define('ttAImportComplete' , "Import Domande già completato con successo");
define('ttBasedOn' , "Basato su");
define('ttBlocked' , "Bloccato");
define('ttBlock' , "Blocca");
define('ttUnblock' , "Sblocca");
define('ttBonus' , "Bonus");
define('ttCancel' , "Annulla");
define('ttChangeLanguage' , "Cambia lingua");
define('ttChangeVersion' , "Cambia versione");
define('ttCheck' , "Verifica...");
define('ttClose' , "Chiudi");
define('ttClosed' , "Chiuso");
define('ttCorrect' , "Correggi");
define('ttConfiguration' , "Configurazione");
define('ttConfirm' , "Conferma");
define('ttConfirmEmail' , "Conferma E-mail");
define('ttConfirmPassword' , "Conferma Password");
define('ttCreate' , "Crea");
define('ttCArchiveExam' , "Sei sicuro di voler archiviare l'esame?<br/>Non sarà possibile consegnare ulteriori test e tutte le domande da correggere dei test consegnati totalizzeranno 0 punti.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCBlockTest' , "Sei sicuro di voler bloccare questo test?");
define('ttCChangeStatus' , "Sei sicuro di voler impostare lo stato della domanda a _STATUS_?");
define('ttCConfirmTest' , "Vuoi confermare il punteggio finale?<br/>Questo test verrà archiviato! Continuare?");
define('ttCDeleteAnswer' , "Sei sicuro di voler eliminare questa risposta e le sue traduzioni?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteExam' , "Sei sicuro di voler eliminare questo esame?<br/>Tutti i test in corso, consegnati e archiviati verranno eliminati.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteQuestion' , "Sei sicuro di voler eliminare questa domanda e le sue traduzioni?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteRoom' , "Sei sicuro di voler eliminare questa stanza?<br/>L'operazione non potrà essere annullata!<br/>Continuare?");
define('ttCDeleteSubject' , "Sei sicuro di voler eliminare questa materia?<br/>I seguenti elementi verranno PERMANENTEMENTE eliminati:<br/> - Materia<br/> - Tutti gli argomenti<br/> - Tutte le domande e le risposte con le relative traduzioni<br/> - Tutte le impostazioni d'esame<br/> - Tutti gli esami e i test attivi e archiviati<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteSettings' , "Sei sicuro di voler eliminare queste impostazioni d'esame?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDeleteTopic' , "Sei sicuro di voler eliminare questo argomento?<br/>I seguenti elementi verranno PERMANENTEMENTE eliminati:<br/> - Argomento<br/> - Tutte le domande con le relative traduzioni<br/> - Tutte le risposte con le relative traduzioni<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCDiscardEdits' , "Le modifiche verranno perse.<br/>Uscire?");
define('ttCDiscardNew' , "L'elemento creato verrà perso.<br/>Uscire?");
define('ttCRegister' , "Sei sicuro di volerti registrare a questo esame?");
define('ttCRegisterStudents' , "Sei sicuro di voler registrare gli studenti selezionati all'esame?");
define('ttCRenewPassword' , "La password per l'esame verrà aggiornata.<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCStartExam' , "Vuoi attivare questo esame?");
define('ttCStartTest' , "Vuoi iniziare l'esame ora?<br/>Ti verrà richiesta la password d'accesso all'esame.");
define('ttCStopExam' , "Vuoi disattivare questo esame?");
define('ttCSubmitTest' , "Vuoi consegnare il test?<br/>L'operazione non potrà essere annullata! Continuare?");
define('ttCTest' , "La password è corretta. Il tuo test è pronto e inizierà dopo il tuo click!");
define('ttCumLaudae' , "e Lode");
define('ttCUnblockTest' , "Sei sicuro di voler sbloccare questo test?");
define('ttCUpdateConfigurations' , "Sei sicuro di voler salvare le nuove configurazioni di sistema?");
define('ttCUpdateLanguage' , "Sei sicuro di voler aggiornare i file di lingua?<br/>L'operazione non potrà essere annullata. Continuare?");
define('ttD1' , "Facile");
define('ttD2' , "Intermedio");
define('ttD3' , "Difficile");
define('ttDatabaseConfiguration' , "Configurazione del database");
define('ttDay' , "Giorno");
define('ttDelete' , "Elimina");
define('ttDescription' , "Descrizione");
define('ttDifficulty' , "Difficoltà");
define('ttDifficultyQuestions' , "Domande per difficoltà");
define('ttDistribution' , "Distribuzione");
define('ttDo' , "Esegui esame");
define('ttDTAnswerInfo' , "Visualizzate _TOTAL_ risposte");
define('ttDTAnswerFiltered' , "(filtrate da _MAX_ risposte totali)");
define('ttDTAnswerEmpty' , "Nessuna risposta da visualizzare");
define('ttDTExamInfo' , "Visualizzati _TOTAL_ esami in corso");
define('ttDTExamFiltered' , "(filtrati da _MAX_ esami in corso totali)");
define('ttDTExamEmpty' , "Nessun esame da visualizzare");
define('ttDTQuestionInfo' , "Visualizzate _TOTAL_ domande");
define('ttDTQuestionFiltered' , "(filtrate da _MAX_ domande totali)");
define('ttDTQuestionEmpty' , "Nessuna domanda da visualizzare");
define('ttDTRegisteredStudentInfo' , "Visualizzati _TOTAL_ studenti registrati");
define('ttDTRegisteredStudentFiltered' , "(filtrati da _MAX_ studenti registrati totali)");
define('ttDTRegisteredStudentEmpty' , "Nessuno studente registrato da visualizzare");
define('ttDTStudentsInfo' , "Visualizzati _TOTAL_ studenti");
define('ttDTStudentsFiltered' , "(filtrati da _MAX_ studenti totali)");
define('ttDTStudentsEmpty' , "Nessuno studente da visualizzare");
define('ttDTTeacherInfo' , "Visualizzati _TOTAL_ docenti");
define('ttDTTeacherFiltered' , "(filtrati da _MAX_ docenti totali)");
define('ttDTTeacherEmpty' , "Nessun docente da visualizzare");
define('ttDTTestInfo' , "Visualizzati _TOTAL_ test");
define('ttDTTestFiltered' , "(filtrati da _MAX_ test totali)");
define('ttDTTestEmpty' , "Nessun test da visualizzare");
define('ttDone' , "Esame completato");
define('ttDuration' , "Durata");
define('ttDTsubquestionInfo' , "Sottodomande");
define('ttEdit' , "Modifica");
define('ttEditableScore' , "Voto modificabile");
define('ttError' , "Errore");
define('ttErrorSent' , "La segnalazioe è stata inviata con Successo!");
define('ttEmail' , "E-mail");
define('ttEnd' , "Fine");
define('ttEverywhere' , "Ovunque");
define('ttExam' , "Esame");
define('ttExams' , "Esami");
define('ttExit' , "Uscita");
define('ttExtra' , "Extra");
define('ttExamsArchive' , "Archivia");
define('ttExamsInProgress' , "Esami in corso");
define('ttErrorquestion' , "Segnalazione Domanda Errata");
define('ttEActivationFails' , "Attivazione fallita!");
define('ttEAlreadyRegistered' , "Lo studente è già registrato a questo esame!");
define('ttEAnswerInSet' , "L'operazione non può essere completata. La risposta è usata in alcuni test!");
define('ttEAnswerNotFound' , "Risposta non trovata");
define('ttEAnswers' , "Si è verificato un problema con le risposte.<br/>Contattare il docente o l'amministratore.");
define('ttEDatabase' , "Errore nel database!");
define('ttEDates' , "Date non corrette!");
define('ttEEditRoomAll' , "'All' non pùò essere modificata!");
define('ttEEmailAlreadyRegistered' , "E-mail già registrata!");
define('ttEEmailNotRegistered' , "E-mail non registrata!");
define('ttEEmailNotValid' , "L'email inserita non è valida! Inserisci un'indirizzo email valido");
define('ttEEmailsNotMatch' , "Le due email non corrispondono!");
define('ttEEmptyFields' , "Uno o più campi sono vuoti!");
define('ttEExamArchived' , "L'operazione non può essere completata. L'esame è stato già archiviato!");
define('ttEExamNotFound' , "Esame non trovato!");
define('ttEExamNotStarted' , "Non puoi iniziare il test. L'esame non è ancora stato avviato!");
define('ttEExamStarted' , "L'operazione non può essere completata perché l'esame è già iniziato!");
define('ttEExamWaiting' , "L'operazione non può essere completata perché l'esame non è mai stato avviato!");
define('ttEExamsNotArchivedDeleteTopic' , "L'operazione non può essere completata perché uno o più esami non ancora archiviati contengono domande contenute in questo argomento!");
define('ttEExamsNotArchivedEditTestSettings' , "L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.");
define('ttEExamsNotArchivedDeleteTestSettings' , "L'operazione non può essere completata perché queste impostazioni sono utilizzate da almeno un esame non ancora archiviato.");
define('ttEIncorrectField' , "Uno o più campi non sono corretti!");
define('ttELogin' , "E-mail e/o Password non sono corretti!");
define('ttEMainLanguageEmpty' , "La lingua principale della materia non può essere vuota!");
define('ttEMandatoryQuestion' , "Questa è una domanda obbligatoria delle impostazioni d'esame '_TESTSETTING_': non è possibile cancellara o modificarne difficoltà e argomento.");
define('ttENotAuthorized' , "Il tuo client non è autorizzato.<br/>Contatta il docente o l'amministratore.");
define('ttENoStudentsToRegister' , "Nessun studente da registrare all'esame!");
define('ttENoTopicsForSubject' , "Nessun argomento esistente per questa materia!<br/>Prima di creare una nuova domanda occorre aver creato almeno un argomento.");
define('ttEOldPasswordWrong' , "La vecchia password non corrisponde!");
define('ttEPassword' , "Password errata!");
define('ttEPasswordShort' , "La password è troppo breve. Deve avere una lunghezza minima di 8 caratteri!");
define('ttEPasswordsNotMatch' , "Le due password non corrispondono!");
define('ttEQuestAnswPicker' , "Errore durante il recupero di domande e risposte.<br/>Contattare il docente!");
define('ttEQuestionInSet' , "L'operazione non può essere completata. La domanda è usata in alcuni test!");
define('ttEQuestionNotFound' , "Domanda non trovata!");
define('ttEQuestionType' , "Tipo di domanda non corretto!");
define('ttERegFailedQuestions' , "Registrazione fallita: poche domande! Contattare il docente.");
define('ttERoomAllDelete' , "'Tutte' non può essere eliminata!");
define('ttERoomUsed' , "L'operazione non può essere completata. La stanza è usata in alcuni esami!");
define('ttESaveBeforeNew' , "Prima di creare un nuovo elemento salva o cancella quello appena creato.");
define('ttESelectQuestionType' , "Selezionare uno dei tipi di domanda disponibili!");
define('ttESelectSubject' , "Selezionare uno dei propri corsi!");
define('ttESelectTestSettings' , "Selezionare una delle impostazioni d'esame!");
define('ttESetNotFound' , "Set di domande non trovato!");
define('ttETestBlockedSubmitted' , "L'operazione non può essere completata. Questo test è stato bloccato o è stato già consegnato!");
define('ttETestAlreadyArchived' , "L'operazione non può essere completata. Questo test è stato già corretto e archiviato!");
define('ttETestAlreadySubmitted' , "L'operazione non può essere completata. Il test è stato già consegnato o archiviato!");
define('ttETestNotArchived' , "L'operazione non può essere completata. Questo test non è stato archiviato!");
define('ttETestNotFound' , "Test non trovato!");
define('ttETestSettingDeleteQuestion' , "L'operazione non può essere completata perché la domanda è obbligatoria nelle seguenti impostazioni d'esame:");
define('ttETestSettingDeleteTopic' , "L'operazione non può essere completata perché alcune domande di questo argomento sono utilizzate nelle seguenti impostazioni d'esame:");
define('ttETestsNotArchived' , "Alcuni test non sono stati archiviati! Correggere prima tutti i test.");
define('ttETimeExpired' , "Il tempo disponibile è finito!");
define('ttETranslationExists' , "La traduzione nella lingua selezionata è già presente!");
define('ttEUserNotFound' , "Utente non trovato!");
define('ttEValues' , "Alcuni valori non sono corretti!");
define('ttFalse' , "Falso");
define('ttFinalScore' , "Punteggio finale");
define('ttGeneralInformations' , "Informazioni Generali");
define('ttHours' , "ore");
define('ttHome' , "Home");
define('ttHomepage' , "Homepage");
define('ttHost' , "Host");
define('ttHAnswPanel' , "Due click per modificare la risposta selezionata");
define('ttHQuestLanguagesPanel' , "Un click per la traduzione<br/>della domanda selezionata");
define('ttHQuestPanel' , "Un click per selezionare la domanda e vederne l'anteprima, due click per modificare domanda e risposte. Doppio click sulle bandierine per attivare e disattivare le domande nei test");
define('ttHQuestPreviewPanel' , "Le risposte con sfondo arancione non sono tradotte nella lingua richiesta");
define('ttHQuestTopicPanel' , "Un click per filtrare le domande,<br/>doppio per modificare l'argomento");
define('ttInfo' , "Informazioni");
define('ttIPEnd' , "IPv4 Fine");
define('ttIPStart' , "IPv4 Inizio");
define('ttInactive' , "Inattivo");
define('ttImportQM' , "Import");
define('ttImport' , "Import QM");
define('ttImportComplete' , "Import Domande completato con successo");
define('ttJoin' , "Iscriviti");
define('ttLanguage' , "Lingua");
define('ttLanguages' , "Lingue");
define('ttLogin' , "Entra");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Login completato!");
define('ttLogout' , "ESCI");
define('ttMailLostPassword' , "Per impostare una nuova password clicca il link seguente:\n\n_LINK_\n\nSe non hai richiesto il reset della password allora ignora questa email.");
define('ttMailCredentials' , "Ciao _USERNAME_,\nDi seguito sono riportate le tue credenziali di accesso:\n\nE-mail : _USEREMAIL_ \n Password : _USERPASSWORD_");
define('ttMailNewTeacher' , "Benvenuto in _SYSTEMNAME_.\n\nPer attivare il tuo account clicca il link seguente e imposta la tua password personale:");
define('ttMainLanguage' , "Lingua principale");
define('ttManage' , "Gestisci");
define('ttMandatory' , "Fisse");
define('ttManual' , "Manuale");
define('ttMinutes' , "minuti");
define('ttMyExams' , "I miei esami");
define('ttMySettings' , "Le mie impostazioni");
define('ttMySubjects' , "Seleziona un corso");
define('ttMActivation' , "Password impostata correttamente.<br/>Verrai portato alla tua Homepage");
define('ttMAnswerDeleted' , "Risposta eliminata con successo");
define('ttMConfigurationsUpdated' , "Configurazioni di sistema aggiornate con successo");
define('ttMConfirm' , "Test confermato e archiviato correttamente");
define('ttMUserCreated' , "Creazione completata: ti è stata inviata una e-mail per completare la registrazione.<br/>Controlla anche nella cartella Spam");
define('ttMEdit' , "Modifiche salvate correttamente");
define('ttMExamArchived' , "Esame archiviato con successo");
define('ttMExamDeleted' , "Esame eliminato con successo");
define('ttMExamStarted' , "Esame avviato con successo");
define('ttMExamStopped' , "Esame fermato con successo");
define('ttMLanguageCreated' , "Traduzione creata con successo");
define('ttMLanguageSaved' , "Traduzione salvata con successo");
define('ttMLanguageUpdated' , "Traduzione aggiornata con successo");
define('ttMNewAnswer' , "Risposta creata con successo");
define('ttMNewQuestion' , "Domanda creata con successo");
define('ttMNewRoom' , "Stanza creata con successo");
define('ttMNewSettings' , "Impostazioni d'esame create con successo");
define('ttMNewSubject' , "Materia creata con successo");
define('ttMNewTopic' , "Argomento creato con successo");
define('ttMPasswordRenewed' , "Password d'esame rinnovata con successo");
define('ttMQuestionDeleted' , "Domanda eliminata con successo");
define('ttMRegistration' , "Sei stato correttamente registrato all'esame");
define('ttMResetConfirmed' , "Richiesta completata: ti è stata inviata una e-mail per reimpostare la tua password. Controlla anche nella cartella Spam");
define('ttMRoomDeleted' , "Stanza eliminata con successo");
define('ttMSelectLanguage' , "Seleziona la lingua da gestire");
define('ttMSettingsDeleted' , "Impostazioni d'esame eliminate con successso");
define('ttMStudentsRegistered' , "Studenti registrati con successo all'esame");
define('ttMSubjectDeleted' , "Materia eliminata con successo");
define('ttMSubjectQuestions' , "Per gestire gli argomenti e le domande seleziona il corso");
define('ttMSubjectSettings' , "Per gestire le impostazioni d'esame seleziona il corso");
define('ttMTestBlocked' , "Test bloccato con successo");
define('ttMTestSubmitted' , "Test consegnato con successo");
define('ttMTestUnblocked' , "Test sbloccato con successo");
define('ttMTopicDeleted' , "Argomento eliminato con successo");
define('ttName' , "Nome");
define('ttNegativeScores' , "Punteggi negativi");
define('ttNew' , "Nuovo");
define('ttNext' , "Avanti");
define('ttNewAnswer' , "Nuova risposta");
define('ttNewCredentials' , "Nuove credenziali");
define('ttNewLanguage' , "Nuova lingua");
define('ttNewPassword' , "Nuova password");
define('ttNewQuestion' , "Nuova domanda");
define('ttNewRegistration' , "Nuova registrazione");
define('ttNewRoom' , "Nuova stanza");
define('ttNewTeacher' , "Nuovo docente");
define('ttNewTestSettings' , "Nuove impostazioni");
define('ttNewStudent' , "Nuovo studente");
define('ttNewSubject' , "Nuova materia");
define('ttNewTopic' , "Nuovo argomento");
define('ttNewUser' , "Nuovo utente");
define('ttNo' , "No");
define('ttNoAnswers' , "Nessuna risposta disponibile per questa domanda");
define('ttNoExams' , "Nessun esame disponibile per questa materia");
define('ttNoExamInProgress' , "Nessun esame in corso");
define('ttNoInfo' , "Non ci sono informazioni per questo esame");
define('ttNoQuestions' , "Nessuna domanda disponibile per questo argomento");
define('ttNoRooms' , "Nessuna stanza creata: 'Tutte' è l'unica disponibile");
define('ttNoSettings' , "Nessuna impostazione disponile per questa materia");
define('ttNoSubjects' , "Nessuna materia disponibile");
define('ttNoTestToCorrect' , "Nessun test da correggere");
define('ttNoUserRegistered' , "Nessuno studente registrato a questo esame");
define('ttNumberError' , "Il valore da inserire deve essere un numero intero o con la virgola (ES: 12.5)");
define('ttOldPassword' , "Vecchia Password");
define('ttEssayQuestion' , "Domanda a risposta aperta");
define('ttPassword' , "Password");
define('ttPasswordLost' , "Password persa?");
define('ttPort' , "Porta");
define('ttProfile' , "Profilo");
define('ttPrepareImportQM' , "Preview");
define('ttQuestion' , "Domanda");
define('ttQuestionPreview' , "Anteprima della domanda");
define('ttQuestions' , "Domande");
define('ttQEc' , "Calcolatrice");
define('ttQEp' , "Tavola Periodica");
define('ttQTMC' , "Risposta singola");
define('ttQTMCDescription' , "In una domanda a risposta singola il partecipante sceglie una singola risposta tra tutte quelle fornite.");
define('ttQTMR' , "Risposta multipla");
define('ttQTMRDescription' , "Una domanda a risposta multipla è simile a quella a Risposta Singola, con la differenza che il partecipante può rispondere scegliendo una o più risposte tra quelle fornite.");
define('ttQTES' , "Risposta aperta");
define('ttQTESDescription' , "Una domanda a risposta aperta permette al partecipante di rispondere inserendo un testo libero senza limiti di caratteri. È possibile usare questo tipo di domanda per chiedere opinioni o suggerimenti riguardo una particolare materia.");
define('ttQTYN' , "Si / No");
define('ttQTYNDescription' , "Una domanda Sì/No è una domanda a risposta singola che chiede al partecipante di rispondere con un \"Sì\" o un \"No\".");
define('ttQTTF' , "Vera / Falso");
define('ttQTTFDescription' , "Una domanda Vero/Falso è una domanda a risposta singola che chiede al partecipante di rispondere con un \"Vero\" o un \"Falso\".");
define('ttQTNM' , "Numerica");
define('ttQTNMDescription' , "In una domanda Numeric, i partecipanti rispondono digitando un numero intero o reale.");
define('ttQTTM' , "Testo");
define('ttQTTMDescription' , "In una domanda Testo, i partecipanti scelgono una sola parola, o poche parole per indicare la loro risposta. Si definiscono parole o frasi, giuste o sbagliate precedentemente inserendo un elenco di risposte accettabili.");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Una domanda Hotspot è una domanda drag and drop con una sola zona giusta. Il partecipante pone un singolo marcatore su un immagine per indicare la risposta.");
define('ttQTPL' , "Pull Down List");
define('ttQuesionid' , "ID");
define('ttQuestionNotes' , "Note aggiuntive");
define('ttQuestionsend' , "Invia Segnalazione");
define('ttQuestionreporting' , "To report more questions you need to leave the id field blank");
define('ttRandom' , "Casuali");
define('ttRefresh' , "Aggiorna");
define('ttRegister' , "Registrati");
define('ttRegistrations' , "Registrazione");
define('ttRegEnd' , "Chiusura registrazione");
define('ttRenewPassword' , "Rinnova Password");
define('ttReset' , "Reimposta");
define('ttResetPassword' , "Reimposta Password");
define('ttRole' , "Ruolo");
define('ttRooms' , "Stanze");
define('ttSave' , "Salva");
define('ttSaveAnswerInfo' , "Salva Informazioni Risposta");
define('ttSaveLanguageFiles' , "Salva file di lingua");
define('ttSaveLanguageXML' , "Salva file XML di lingua");
define('ttSaveQuestionInfo' , "Salva Informazioni Domanda");
define('ttScore' , "Punteggio");
define('ttScoreFinal' , "Punteggio finale");
define('ttScoreTest' , "Punteggio");
define('ttScoreType' , "Tipo di punteggio");
define('ttScoreMin' , "Punteggio minimo");
define('ttSelectSubject' , "Seleziona un corso");
define('ttSelectSubjectBefore' , "Selezionare prima un corso");
define('ttSet' , "Imposta");
define('ttSetPassword' , "Imposta la tua password");
define('ttSelectSubQuestion' , "Seleziona una sottodomanda");
define('ttShowHide' , "Mostra/Nascondi");
define('ttSkin' , "Skin");
define('ttSettings' , "Impostazioni");
define('ttStart' , "Inizia");
define('ttStarted' , "Iniziato");
define('ttStop' , "Ferma");
define('ttStopped' , "Fermato");
define('ttStartTest' , "Inizia test");
define('ttStatus' , "Stato");
define('ttStats' , "Statistiche");
define('ttStudent' , "Studente");
define('ttStudents' , "Studenti");
define('ttST10' , "Decimi");
define('ttST30' , "Trentesimi");
define('ttST100' , "Centesimi");
define('ttSubject' , "Materia");
define('ttSubjects' , "Materie");
define('ttSubmit' , "Consegna");
define('ttSurname' , "Cognome");
define('ttSystem' , "Sistema");
define('ttSystemConfiguration' , "Configurazione di Sistema");
define('ttSbjVers' , "Versione");
define('ttTeacher' , "Docente");
define('ttTeachers' , "Docenti");
define('ttETeachers' , "Esaminatori");
define('ttTest' , "Test");
define('ttTests' , "Test");
define('ttTestToCorrect' , "Tests da correggere");
define('ttText' , "Testo");
define('ttTime' , "Ora");
define('ttTimeEnd' , "Ora di fine");
define('ttTimeStart' , "Ora di inizio");
define('ttTimeUsed' , "Tempo usato");
define('ttTimeZone' , "Fuso orario");
define('ttTitle' , "Titolo");
define('ttTopic' , "Argomento");
define('ttTopics' , "Argomenti");
define('ttTopicsAndQuestions' , "Argomenti e Domande");
define('ttTopicsQuestions' , "Domande per argomenti");
define('ttTranslations' , "Traduzioni");
define('ttTrue' , "Vero");
define('ttType' , "Tipo");
define('ttUser' , "Utente");
define('ttUsers' , "Utenti");
define('ttView' , "Vedi");
define('ttWelcome' , "Benvenuto");
define('ttWaiting' , "Attesa");
define('ttWarning' , "Attenzione");
define('ttYes' , "Sì");
define('ttAssesmentOverview' , "Panoramica valutazioni report");
define('ttDeselectAll' , "Deseleziona tutti");
define('ttErrorUserParameter' , "Selezionare un dettaglio del  partecipante per continuare!");
define('ttQuestionerror' , "Question ID");
define('ttRemove' , "Rimuovi");
define('ttReportCoachingError' , "Seleziona una valutazione ed un partecipante per continuare");
define('ttReportCoachingError2' , "Seleziona una valutazione per continuare");
define('ttReportErrorStudent' , "Lo studente selezionato non ha mai partecipato ad un test");
define('ttReportMainAO' , "Main");
define('ttReportTemplateDeleteFailed' , "Eliminazione fallita");
define('ttReportTemplateDelet' , "Template cancellato");
define('ttReportTemplateLoaded' , "Template caricato correttamente");
define('ttReportTemplateSaveError' , "Inserisci un nome senza spazi!");
define('ttReportTemplateSaved' , "Template salvato correttamente");
define('ttReportTemplateDuplicateError' , "Il nome per il template è gia stato utilizzato");
define('ttReportScoreFilter' , "Se hai già selezionato un partecipante, perfavore riseleziona uno nuovo");
define('ttSelectAll' , "Seleziona tutto");
define('ttQTFB' , "Completamento Testo");
define('ttQTFB_TEXT' , "Completa il testo seguente con le opportune parole");
define('ttQTFBDescription' , "Una domanda completamento testo è una domanda che permette al partecipante di rispondere inserendo un testo libero senza limiti di caratteri.");
define('ttPosterImageVideo' , "Logo di caricamento del video");
define('ttWidthVideo' , "Larghezza");
define('ttHeightVideo' , "Altezza");
define('ttIdVideo' , "Codice Identificiativo");
define('ttVideoTypeVideo' , "Formato video");
define('ttNumberOfPlaysVideo' , "Numero massimo di riproduzioni");
define('ttToolbarVideo' , "Video");
define('ttDialogTitleVideo' , "Proprietà Video");
define('ttFakeObjectVideo' , "Video");
define('ttPropertiesVideo' , "Modifica video");
define('ttWidthRequiredVideo' , "La larghezza deve essere impostata");
define('ttHeightRequiredVideo' , "La altezza deve essere impostata");
define('ttNumberOfPlayRequiredVideo' , "Il numero di riproduzioni deve essere impostato");
define('ttFallbackTemplateVideo' , "Il tuo browser non supporta i video HTML5");
define('ttBrowseVideo' , "Cerca sul server");
define('ttsourceVideo' , "Source video");
define('ttNumberOfPlayAlertVideo' , "Hai raggiunto il massimo numero di riproduzioni del video");
define('ttHelpDefault' , "Pannello informativo");
define('ttHelpDefaultDescription' , "Premi questo bottone all'interno di una schermata per avere una descrizione su cosa puoi fare");
define('ttHelpQuestion' , "Seleziona una domanda per leggerne il contenuto, facci doppio click per modificarla");
define('ttHelpADMINNewTeacherDescription' , "Definisci l'account di un nuovo amministratore, insegnante o esaminatore");
define('ttHelpADMINNewStudentDescription' , "Definisci l'account di un nuovo studente");
define('ttHelpADMINSelLanguageDescription' , "Seleziona una lingua da gestire");
define('ttHelpADMINLanguageDescription' , "Qui puoi cambiare le localizzazioni delle parole usate dal sistema");
define('ttHelpADMINSystemConf' , "Qui puoi modificare le impostazioni di EOL, fai attenzione");
define('ttHelpADMINRoom' , "Definisci le stanze degli esami");
define('ttHelpADMINImport' , "Questa schermata ti permette di importare nuove domande da QuestionMark");
define('ttHelpADMINProfile' , "Questa schermata ti permette di modificare il tuo profilo");
define('ttHelpReportAreport' , "Questa schermata ti permette di creare un Areport,è obbligatorio selezionare almeno una materia");
define('ttHelpReportAreportTemplate' , "Seleziona quali informazioni vuoi ottenere nel Report");
define('ttHelpReportCreport' , "Questa schermata ti permette di creare un Creport,è obbligatorio selezionare un partecipante");
define('ttHelpReportCreportlist' , "Seleziona l'esame su cui creare il Report");
define('ttHelpStudent' , "A sinistra trovi gli esami disponibili, a destra il dettaglio dell'esame selezionato");
define('ttHelpStudentTest' , "Ti trovi nella schermata d'esame, rispondi alle domande e consegna il test");
define('ttHelpAdminErrorQuestion' , "Se hai trovato dei problemi puoi segnalarli da questa pagina.");
define('ttHelpExamsCorrect' , "Qui viene visualizzato l'esame svolto da uno studente, controlla che la correzione sia stata fatta correttamente e poi conferma il voto.");
define('ttHelpExamsSettings' , "In questa schermata potrai definire, o modificare, le impostazioni da usare nei futuri esami.");
define('ttQTPLDescription' , "Dropdown è una tipologia di domanda a risposta chiusa che consente ai partecipanti di scegliere una opzione di risposta da un elenco di scelte presentate in un menu a discesa.<br/>Se si desidera visualizzare opzioni di risposta come pulsanti di opzione o caselle di controllo, utilizzare la domanda a scelta multipla, (multiple choice).");
define('ttQuestionsubPL' , "Sottodomande");
define('ttHelpLog' , "Un file di Log verrà creato automaticamente dopo aver modificato una domanda già assegnata ad un test. Sposta il mouse sull'id di una domanda per vederne la history");
define('ttAOreportSaved' , "Tutti i report che verranno generati saranno salvati nel server e visibili nella sezione apposita");
define('ttReportAllFinished' , "Completati");
define('ttReportAODescription' , "Se non si seleziona una valutazione, verranno tutte analizzate");
define('ttReportAOWelcome' , "Scegli una valutazione e usa le tab guida per filtrare i dati");
define('ttReportAOSelectAssesment' , "Seleziona le valutazioni che vuoi analizzare");
define('ttReportAssesmentAuthor' , "Autore valutazione");
define('ttReportAssessmentInformation' , "Informazioni valutazione");
define('ttReportAssesmentID' , "ID Valutazione");
define('ttReportAssesmentDateTimeFirst' , "Data/Ora primo test");
define('ttReportAssesmentDateTimeLast' , "Data/Ora ultimo test");
define('ttReportAssesmentLeastTimeFinished' , "Minor tempo impiegato finiti");
define('ttReportAssesmentName' , "Nome valutazione");
define('ttReportAssesmentNumberStarted' , "Num. di volte iniziato");
define('ttReportAssesmentNumberNotFinished' , "Num. di volte non finito");
define('ttReportAssesmentNumberFinished' , "Num. di volte finito");
define('ttReportAssesmentMinscoreFinished' , "Punteggio minimo di quelli finiti");
define('ttReportAssesmentMaxcoreFinished' , "Punteggio massimo di quelli finiti");
define('ttReportAssesmentMediumFinished' , "Punteggio medio finiti");
define('ttReportAssesmentMediumTimeFinished' , "Tempo medio impiegato finiti");
define('ttReportAssesmentMostTimeFinished' , "Maggior tempo impiegato finiti");
define('ttReportAssesmentScore' , "Filtra per punteggio valutazione");
define('ttReportAssesmentStdDeviation' , "Deviazione standard finiti");
define('ttReportChecked' , "Selezionati");
define('ttReportCoaching' , "Coaching Report");
define('ttReportCWelcome' , "Scegli una valutazione ed un partecipante");
define('ttReportCDescription' , "Filtra i dati per date e, se vuoi, anche per punteggio");
define('ttReportCoachingDescription' , "Visualizza i risultati in dettaglio per un partecipante relativi ad una valutazione");
define('ttReportCoachingInformation' , "Seleziona un test per informazioni dettagliate");
define('ttReportCustomize' , "Personalizza report");
define('ttReportDateInterval' , "Intervallo date");
define('ttReportDateFrom' , "Da");
define('ttReportDateTaken' , "Data");
define('ttReportDateTo' , "a");
define('ttReportErrorDetail' , "Seleziona uno studente per poter scegliere il dettaglio");
define('ttReportField' , "Nome campo");
define('ttReportGraphicalDsiplays' , "Informazioni grafiche");
define('ttReportGraphicHistogram' , "Istogramma punteggio valutazioni");
define('ttReportGraphicTopicScore' , "Istogramma punteggio argomenti");
define('ttReportGroup' , "Gruppi");
define('ttReportGroupNotPresent' , "Nessun gruppo presente");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Punteggio minimo");
define('ttReportMaximumScore' , "Punteggio massimo");
define('ttReportOrder' , "Ordine");
define('ttReportNotFilter' , "Non usare filtri");
define('ttReportPartecipants' , "Partecipanti");
define('ttReportPartecipant' , "Partecipante");
define('ttReportScheduled' , "Schedati");
define('ttReportScoreBand' , "Filtra per banda di punteggio");
define('ttReportSearch' , "Cerca...");
define('ttReportSearched' , "Risultati ricerca");
define('ttReportSelectDetail' , "Seleziona ID utente o email del partecipante precedentemente selezionato");
define('ttReportSelectFilter' , "Seleziona filtro");
define('ttReportSelectGroup' , "Seleziona gruppi su cui filtrare i dati");
define('ttReportSelectLetter' , "Lettera");
define('ttReportAOSelectPartecipant' , "Seleziona partecipante");
define('ttReportSelected' , "Valutazioni selezionate");
define('ttReportSelectTemplate' , "Seleziona template");
define('ttReportSelectedGroup' , "Gruppi selezionati");
define('ttReportSearchByLetter' , "Cerca per lettera");
define('ttReportStudent' , "Filtra per partecipante");
define('ttReportStudentNotPresent' , "Nessuno studente presente");
define('ttReportStudentDetail' , "Filtra su dettaglio partecipante");
define('ttReportTemplateLoad' , "Seleziona un template da caricare");
define('ttReportTemplateSave' , "Salva template come");
define('ttReportTemplateName' , "Inserisci nome");
define('ttReportTimedOut' , "Scaduti");
define('ttReportTopicAverageScore' , "Punteggio medio");
define('ttReportTopicInformation' , "Informazioni sugli argomenti");
define('ttReportTopicMaximumScore' , "Punteggio massimo");
define('ttReportTopicMinimumScore' , "Punteggio minimo");
define('ttReportTopicName' , "Nome topic");
define('ttReportTopicStandardDeviation' , "Deviazione standard");
define('ttReportTyping' , "Cerca digitando");
define('ttReportQuestionType' , "Tipo domanda");
define('ttReportViewer' , "Visualizzatore Report");
define('ttReportViewerDescription' , "Guarda e gestisci i report generati");
define('ttGroup' , "Gruppo");
define('ttSubgroup' , "Sottogruppo");
define('ttReport' , "Report");
define('ttCertificates' , "Certificati");
define('ttCertificate' , "Certificato");
define('ttNewGroup' , "Aggiungi gruppo");
define('ttEditGroup' , "Modifica gruppo");
define('ttEditTeacher' , "Modifica docente");
define('ttEditStudent' , "Modifica studente");
define('tteTeacher' , "Esaminatore");
define('tttotals' , "Totale");
define('ttD1s' , "Facili");
define('ttD2s' , "Medie");
define('ttD3s' , "Difficili");
define('ttSelectStudent' , "Elenco studenti");
define('ttSelectTeacher' , "Elenco docenti");
define('ttD3s' , "Difficili");
define('ttCoord' , "Coordinate");
define('ttHelpLog' , "Un file di Log viene creato automaticamente dopo aver modificato una domanda che risulta attualmente assegnata ad un test. Sposta il mouse sull'id di una domanda per vederne la history");
define('ttHelpExams' , "Qui viene visualizzato l'elenco degli esami. Puoi creare un nuovo esame, puoi modificare le impostazioni di un esame, o visualizzare i voti degli studenti.");
define('ttHelpSubject' , "Qui viene visualizzato l'elenco dei corsi di cui sei insegnante. Selezionane uno per visualizzare le domande in esso contenute.");
define('ttNotAvailable' , "Le impostazioni selezionate non consentono di generare un test.");
define('ttStudentDetailCreport' , "Dettaglio studenti");
define('ttSelectGroup' , "Modifica gruppi o sottogruppi");
define('ttConfirmProcedure' , "Vuoi davvero eseguire questa operazione?");
define('ttUserDeleted' , "Utente cancellato correttamente");
define('ttMGroupCreated' , "Gruppo creato correttamente");
define('ttNewSubgroup' , "Nuovo sottogruppo");
define('ttErrorTopic' , "Troppe domande selezionate nei topics");
define('ttAvailable' , "questions available of");
define('ttThereAreNot' , "Non ci sono");
define('ttErrorMax' , "Questo campo non deve essere minore del numero di domande obbligatorie selezionate");
define('ttField' , "Il campo");
define('ttHard' , "Difficile");
define('ttMedium' , "Intermedio");
define('ttEasy' , "Facile");
define('ttMustBeaNumber' , "Deve essere un numero");
define('ttMaxHardReached' , "Numero massimo di domande difficili già raggiunto");
define('ttMaxMediumReached' , "Numero massimo di domande intermedie già raggiunto");
define('ttMaxEasyReached' , "Numero massimo di domande facili già raggiunto");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Cliccando su si, l'esame dello studente verrà automaticamente consegnato al sistema nello stato attuale in cui si trova. Se lo studente sta ancora ancora svolgendo l'esame qualunque sua ulteriore modifica non sarà considerata.");
define('ttProfCert' , "Certificazione delle competenze");
define('ttCertify' , "Viene certificato che");
define('ttSuccess' , "ha superato con successo");
define('ttEvaluation' , "con la valutazione seguente");
define('ttAccreditedTestSite' , "nel test ufficiale di");
define('ttOn' , "a");
define('ttNumQuestionsTopic' , "Numero di domande per ogni topic");
define('ttParamNotSet' , "Parametro mancante");
define('ttNotEnoughQuestions' , "Non ci sono abbastanza domande");
define('ttExamArchivedCertNot' , "Esame archiviato correttamente, i certificati potrebbero non essere stati generati.");
define('ttSendCertificate' , "Invia certificato");
define('ttCertificateAlert' , "Sei sicuro di voler inviare il certificato dell'esame allo studente ? L'operazione non può in alcun modo essere annullata!");
define('ttCertificateScore' , "Lo studente non ha il punteggio minimo per ricevere un certificato!");
define('ttCertificateGenerated' , "Il certificato è stato generato correttamente");
define('ttBut' , "ma");
define('ttAnd' , "e");
define('ttCertificateEmailSended' , "l'email è stata correttamente inviata");
define('ttCertificateGeneratedProblem' , "Il certificato non è stato generato!");
define('ttCertificatePoint' , "Il punteggio dello studente è troppo basso e non può essere emesso un certificato.");
