<?php
define('ttAccountActivation' , "activación de cuenta");
define('ttActive' , "Activo");
define('ttActivate' , "Activar");
define('ttAdd' , "Añadir");
define('ttAddSelectedStudents' , "Añadir estudiantes seleccionados");
define('ttAdministration' , "Administración");
define('ttAdministrator' , "Administrador");
define('ttAdminWelcome' , "Bienvenido al panel de administración.");
define('ttAlias' , "Código ISO 639-1");
define('ttAndExit' , "y salir");
define('ttAnswer' , "Responder");
define('ttAnswers' , "Respuestas");
define('ttArchive' , "Archivo");
define('ttArchived' , "Archivado");
define('ttAssignSubject' , "Asignar Asunto");
define('ttAutomatic' , "Automático");
define('ttAImportComplete' , "Preguntas de importación ya completadas con éxito");
define('ttBasedOn' , "Residencia en");
define('ttBlocked' , "Obstruido");
define('ttBlock' , "Bloquear");
define('ttUnblock' , "Desatascar");
define('ttBonus' , "Prima");
define('ttCancel' , "Cancelar");
define('ttChangeLanguage' , "Cambiar idioma");
define('ttChangeVersion' , "Cambiar la versión de prueba");
define('ttCheck' , "Comprobar...");
define('ttClose' , "Cerrar");
define('ttClosed' , "Cerrado");
define('ttCorrect' , "Correcto");
define('ttConfiguration' , "Configuración");
define('ttConfirm' , "Confirmar");
define('ttConfirmEmail' , "Confirmar correo electrónico");
define('ttConfirmPassword' , "Confirmar contraseña");
define('ttCreate' , "Crear");
define('ttCArchiveExam' , "¿Estás seguro de archivar el examen?");
define('ttCBlockTest' , "¿Estás seguro de bloquear esta prueba?");
define('ttCChangeStatus' , "¿Está seguro de cambiar el estado de la pregunta a _STATUS_?");
define('ttCConfirmTest' , "¿Quieres confirmar el puntaje del examen?");
define('ttCDeleteAnswer' , "¿Estás seguro de eliminar esta respuesta y sus traducciones?");
define('ttCDeleteExam' , "¿Estás seguro de eliminar este examen?");
define('ttCDeleteQuestion' , "¿Estás seguro de eliminar esta pregunta y sus traducciones?");
define('ttCDeleteRoom' , "¿Estás seguro de eliminar esta sala?");
define('ttCDeleteSubject' , "¿Estás seguro de eliminar este tema?");
define('ttCDeleteSettings' , "¿Está seguro de eliminar esta configuración de prueba?");
define('ttCDeleteTopic' , "¿Estás seguro de eliminar este tema?");
define('ttCDiscardEdits' , "Tus cambios se perderán.");
define('ttCDiscardNew' , "El artículo creado se perderá.");
define('ttCRegister' , "¿Estás seguro de registrarte en este examen?");
define('ttCRegisterStudents' , "¿Estás seguro de registrar a estos estudiantes seleccionados en el examen?");
define('ttCRenewPassword' , "Se cambiará la contraseña del examen.");
define('ttCStartExam' , "¿Quieres activar el examen seleccionado?");
define('ttCStartTest' , "¿Quieres comenzar el examen ahora?");
define('ttCStopExam' , "¿Desea desactivar el examen seleccionado?");
define('ttCSubmitTest' , "¿Quieres enviar tu prueba?");
define('ttCTest' , "La contraseña es correcta.");
define('ttCumLaudae' , "cum laudae");
define('ttCUnblockTest' , "¿Estás seguro de desbloquear esta prueba?");
define('ttCUpdateConfigurations' , "¿Está seguro de guardar las nuevas configuraciones del sistema?");
define('ttCUpdateLanguage' , "¿Estás seguro de actualizar archivos de idioma?");
define('ttD1' , "Fácil");
define('ttD2' , "Medio");
define('ttD3' , "Difícil");
define('ttDatabaseConfiguration' , "Configuración de la base de datos");
define('ttDay' , "Día");
define('ttDelete' , "Borrar");
define('ttDescription' , "Descripción");
define('ttDifficulty' , "Dificultad");
define('ttDifficultyQuestions' , "Preguntas por dificultad");
define('ttDistribution' , "Distribución");
define('ttDo' , "Hacer examen");
define('ttDTAnswerInfo' , "Mostrando _TOTAL_ respuestas");
define('ttDTAnswerFiltered' , "(filtrado de _MAX_ respuestas totales)");
define('ttDTAnswerEmpty' , "No hay respuestas para mostrar");
define('ttDTExamInfo' , "Mostrando _TOTAL_ exámenes en progreso");
define('ttDTExamFiltered' , "(filtrado de _MAX_ exámenes totales en curso)");
define('ttDTExamEmpty' , "No hay exámenes para mostrar");
define('ttDTQuestionInfo' , "Mostrando _TOTAL_ preguntas");
define('ttDTQuestionFiltered' , "(filtrado de _MAX_ total de preguntas)");
define('ttDTQuestionEmpty' , "No hay preguntas para mostrar");
define('ttDTRegisteredStudentInfo' , "Mostrando _TOTAL_ alumnos matriculados");
define('ttDTRegisteredStudentFiltered' , "(filtrado de _MAX_ total de estudiantes registrados)");
define('ttDTRegisteredStudentEmpty' , "No hay estudiantes registrados para mostrar");
define('ttDTStudentsInfo' , "Mostrando _TOTAL_ estudiantes");
define('ttDTStudentsFiltered' , "(filtrado de _MAX_ total de estudiantes)");
define('ttDTStudentsEmpty' , "No hay estudiantes para mostrar");
define('ttDTTestInfo' , "Mostrando la prueba _TOTAL_");
define('ttDTTeacherInfo' , "Mostrando _TOTAL_ profesores");
define('ttDTTeacherFiltered' , "(filtrado de _MAX_ total de profesores)");
define('ttDTTeacherEmpty' , "No hay profesor para mostrar");
define('ttDTTestFiltered' , "(filtrado de _MAX_ pruebas totales)");
define('ttDTTestEmpty' , "No hay pruebas para mostrar");
define('ttDone' , "Examen hecho");
define('ttDuration' , "Duración");
define('ttDTsubquestionInfo' , "Sub-preguntas");
define('ttEdit' , "Editar");
define('ttEditableScore' , "Puntaje editable");
define('ttError' , "Error");
define('ttEmail' , "Email");
define('ttEnd' , "Fin");
define('ttEverywhere' , "En todos lados");
define('ttExam' , "Examen");
define('ttExams' , "Examenes");
define('ttExit' , "Salida");
define('ttExtra' , "Extra");
define('ttExamsArchive' , "Archivo");
define('ttExamsInProgress' , "Exámenes en curso");
define('ttETeachers' , "Examinador");
define('ttErrorquestion' , "Informe de error");
define('ttEActivationFails' , "¡La activación falla!");
define('ttEAlreadyRegistered' , "¡El estudiante ya está registrado para este examen!");
define('ttEAnswerInSet' , "La operación no se puede completar.");
define('ttEAnswerNotFound' , "Respuesta no encontrada");
define('ttEAnswers' , "Se produjo un problema con las respuestas.");
define('ttEDatabase' , "¡Error de la base de datos!");
define('ttEDates' , "Las fechas no son correctas!");
define('ttEEditRoomAll' , "'Todo' sala no se puede editar!");
define('ttEEmailAlreadyRegistered' , "¡Correo electrónico ya registrado!");
define('ttEEmailNotRegistered' , "E-mail no registrado!");
define('ttEEmailNotValid' , "El correo electrónico escrito no es válido!");
define('ttEEmailsNotMatch' , "Los dos correos electrónicos no coinciden!");
define('ttEEmptyFields' , "¡Uno o más campos están vacíos!");
define('ttEExamArchived' , "La operación no se puede completar.");
define('ttEExamNotFound' , "Examen no encontrado!");
define('ttEExamNotStarted' , "No se puede iniciar el examen.");
define('ttEExamStarted' , "La operación no se puede completar porque el examen ya está iniciado.");
define('ttEExamWaiting' , "La operación no se puede completar porque el examen nunca se inicia.");
define('ttEExamsNotArchivedDeleteTopic' , "La operación no se puede completar, porque al menos un examen no archivado contiene preguntas de este tema.");
define('ttEExamsNotArchivedEditTestSettings' , "La operación no se puede completar, ya que estas configuraciones se utilizan al menos en un examen no archivado.");
define('ttEExamsNotArchivedDeleteTestSettings' , "La operación no se puede completar, ya que estas configuraciones se utilizan en al menos un examen no archivado");
define('ttEIncorrectField' , "Uno o más campos no son correctos!");
define('ttELogin' , "Correo electrónico y / o contraseña no son correctos!");
define('ttEMainLanguageEmpty' , "El idioma principal del sujeto no puede estar vacío!");
define('ttEMandatoryQuestion' , "Esta es una pregunta obligatoria de la configuración de la prueba '_TESTSETTING_': no ​​se puede eliminar o editar su dificultad o tema.");
define('ttENotAuthorized' , "Su cliente no está autorizado.");
define('ttENoStudentsToRegister' , "Ningún estudiante para registrarse!");
define('ttENoTopicsForSubject' , "No hay tema para este tema!");
define('ttEOldPasswordWrong' , "La contraseña antigua no es correcta!");
define('ttEPassword' , "¡Contraseña incorrecta!");
define('ttEPasswordShort' , "La contraseña es demasiado corta.");
define('ttEPasswordsNotMatch' , "Las dos contraseñas no coinciden!");
define('ttEQuestAnswPicker' , "Error durante la selección de preguntas y respuestas.");
define('ttEQuestionInSet' , "La operación no se puede completar.");
define('ttEQuestionNotFound' , "Pregunta no encontrada!");
define('ttEQuestionType' , "Tipo de pregunta no es correcto!");
define('ttERegFailedQuestions' , "Registro fallido: muy pocas preguntas!");
define('ttERoomAllDelete' , "'Todo' sala no se puede eliminar!");
define('ttERoomUsed' , "La operación no se puede completar.");
define('ttESaveBeforeNew' , "Antes de crear un nuevo elemento, guarde o cancele el ya creado.");
define('ttESelectQuestionType' , "¡Debes seleccionar uno de los tipos de preguntas disponibles!");
define('ttESelectSubject' , "¡Debes seleccionar uno de tus temas!");
define('ttESelectTestSettings' , "Debes seleccionar una de las configuraciones de prueba!");
define('ttESetNotFound' , "Conjunto de preguntas no encontrado!");
define('ttETestAlreadyArchived' , "La operación no se puede completar.");
define('ttETestAlreadySubmitted' , "La operación no se puede completar.");
define('ttETestBlockedSubmitted' , "La operación no se puede completar.");
define('ttETestNotArchived' , "La operación no se puede completar.");
define('ttETestNotFound' , "Prueba no encontrada!");
define('ttETestsNotArchived' , "Algunas pruebas no han sido archivadas!");
define('ttETestSettingDeleteQuestion' , "La operación no se puede completar.");
define('ttETestSettingDeleteTopic' , "La operación no puede ser completada.");
define('ttETimeExpired' , "¡El tiempo disponible ha expirado!");
define('ttETranslationExists' , "¡La traducción del idioma seleccionado ya existe!");
define('ttEUserNotFound' , "¡Usuario no encontrado!");
define('ttEValues' , "¡Algunos valores no son correctos!");
define('ttFalse' , "Falso");
define('ttFinalScore' , "Puntuación final");
define('ttGeneralInformations' , "Información general");
define('ttHours' , "horas");
define('ttHome' , "Casa");
define('ttHomepage' , "Página principal");
define('ttHost' , "Anfitrión");
define('ttHAnswPanel' , "Haga doble clic para editar la respuesta seleccionada.");
define('ttHQuestLanguagesPanel' , "Haga clic para mostrar la traducción de la pregunta seleccionada");
define('ttHQuestPanel' , "Haga un clic para seleccionar y ver la vista previa de las preguntas y haga doble clic para editar la información de las preguntas y respuestas.");
define('ttHQuestPreviewPanel' , "Las respuestas con fondo naranja no están traducidas en el idioma solicitado.");
define('ttHQuestTopicPanel' , "Un solo clic para filtrar preguntas y hacer doble clic para editar la información del tema");
define('ttInfo' , "Información");
define('ttIPEnd' , "IPv4 End");
define('ttIPStart' , "Inicio de IPv4");
define('ttInactive' , "Inactivo");
define('ttImportQM' , "Importar");
define('ttImport' , "Importar QM");
define('ttImportComplete' , "Importación de preguntas completadas exitosamente");
define('ttJoin' , "Unirse");
define('ttLanguage' , "Idioma");
define('ttLanguages' , "Idiomas");
define('ttLogin' , "Iniciar sesión");
define('ttLogo' , "Logo");
define('ttLoginOk' , "Inicio de sesión completo!");
define('ttLogout' , "CERRAR SESIÓN");
define('ttMailLostPassword' , "Para restablecer la contraseña de su cuenta, haga clic en el siguiente enlace: _LINK_ Si no ha solicitado un restablecimiento de contraseña, ignore este correo electrónico.");
define('ttMailCredentials' , "Estimado _USERNAME_, Su contraseña asociada a la cuenta _USEREMAIL_ ha sido modificada de acuerdo con su solicitud.");
define('ttMailNewTeacher' , "Bienvenido a _SYSTEMNAME_.");
define('ttMainLanguage' , "Lenguaje principal");
define('ttManage' , "Gestionar");
define('ttMandatory' , "Obligatorio");
define('ttManual' , "Manual");
define('ttMinutes' , "minutos");
define('ttMyExams' , "Mis exámenes");
define('ttMySettings' , "Mi configuración");
define('ttMySubjects' , "Seleccionar tema");
define('ttMActivation' , "Contraseña correctamente establecida.");
define('ttMAnswerDeleted' , "Respuesta eliminada exitosamente");
define('ttMConfigurationsUpdated' , "Configuraciones del sistema actualizadas exitosamente");
define('ttMConfirm' , "Prueba confirmada y archivada con éxito.");
define('ttMUserCreated' , "Creación completada: se le ha enviado un correo electrónico para completar el registro.");
define('ttMEdit' , "Ediciones guardadas exitosamente");
define('ttMExamArchived' , "Examen archivado con éxito");
define('ttMExamDeleted' , "Examen eliminado con éxito");
define('ttMExamStarted' , "Examen iniciado con éxito");
define('ttMExamStopped' , "Examen detenido exitosamente");
define('ttMLanguageCreated' , "Traducción exitosa creada");
define('ttMLanguageSaved' , "Traducción guardada con éxito");
define('ttMLanguageUpdated' , "Traducción actualizada correctamente");
define('ttMNewAnswer' , "Respuesta creada con éxito");
define('ttMNewQuestion' , "Pregunta creada exitosamente");
define('ttMNewRoom' , "Sala creada con éxito");
define('ttMNewSettings' , "Configuraciones de prueba creadas exitosamente");
define('ttMNewSubject' , "Asunto creado exitosamente");
define('ttMNewTopic' , "Tema creado con éxito");
define('ttMPasswordRenewed' , "Exam's password successfully renewed");
define('ttMQuestionDeleted' , "Question successfully deleted");
define('ttMRegistration' , "You successfully registered on this exam");
define('ttMResetConfirmed' , "Request completed: an email has been sent to you reset your password.<br/>Also check in spam folder too");
define('ttMRoomDeleted' , "Room successfully deleted");
define('ttMSelectLanguage' , "Select the language you want manage");
define('ttMSettingsDeleted' , "Test Settings successfully deleted");
define('ttMStudentsRegistered' , "Students successfully registered on the exam");
define('ttMSubjectDeleted' , "Subject successfully deleted");
define('ttMSubjectQuestions' , "To manage topics and questions, plase select the subject");
define('ttMSubjectSettings' , "To manage exam's settings, please select the subject");
define('ttMTestBlocked' , "Test successfully blocked");
define('ttMTestSubmitted' , "Test successfully submitted");
define('ttMTestUnblocked' , "Test successfully unblocked");
define('ttMTopicDeleted' , "Topic successfully deleted");
define('ttName' , "Name");
define('ttNumberError' , "The value should be an integer or a decimal (ES: 12.5)");
define('ttNegativeScores' , "Negative scores");
define('ttNew' , "New");
define('ttNext' , "Next");
define('ttNewAnswer' , "New Answer");
define('ttNewCredentials' , "New Credentials");
define('ttNewLanguage' , "New Language");
define('ttNewPassword' , "New Password");
define('ttNewQuestion' , "New Question");
define('ttNewRegistration' , "New Registration");
define('ttNewRoom' , "New Room");
define('ttNewTeacher' , "New Teacher");
define('ttNewTestSettings' , "New Settings");
define('ttNewSubject' , "New Subject");
define('ttNewStudent' , "New Student");
define('ttNewTopic' , "New Topic");
define('ttNewUser' , "New User");
define('ttNo' , "No");
define('ttNoAnswers' , "No answers available for this question");
define('ttNoExams' , "No exams available for this subject");
define('ttNoExamInProgress' , "No exam in progress");
define('ttNoInfo' , "There aren't information about this exam");
define('ttNoQuestions' , "No questions available for this topic");
define('ttNoRooms' , "No rooms created: 'All' only available");
define('ttNoSettings' , "No settings available for this subject");
define('ttNoSubjects' , "No subjects available");
define('ttNoTestToCorrect' , "No tests to correct");
define('ttNoUserRegistered' , "No registered users for this exam");
define('ttOldPassword' , "Old Password");
define('ttEssayQuestion' , "Essay question");
define('ttPassword' , "Password");
define('ttPasswordLost' , "Password Lost?");
define('ttPort' , "Port");
define('ttProfile' , "Profile");
define('ttPrepareImportQM' , "Preview");
define('ttQuestion' , "Question");
define('ttQuestionPreview' , "Question Preview");
define('ttQuestions' , "Questions");
define('ttQEc' , "Calculator");
define('ttQEp' , "Periodic Table");
define('ttQTMC' , "Multiple Choice");
define('ttQTMCDescription' , "In a Multiple Choice question the participant selects a single choice from a number of choices to answer the question.");
define('ttQTMR' , "Multiple Response");
define('ttQTMRDescription' , "A Multiple Response question is like a multiple choice, except that instead of being required to make at most one choice, the user is allowed to make one or more than one choice.");
define('ttQTES' , "Essay Question");
define('ttQTESDescription' , "An Essay question lets the participant enter a long, free-range text answer to a question. It's also possible to use this question type to solicit opinions or suggestions on a particular subject.");
define('ttQTYN' , "Yes / No");
define('ttQTYNDescription' , "A Yes/No question is a multiple choice question that asks the participant to give a \"Yes\" or \"No\" answer to a question.");
define('ttQTTF' , "True / False");
define('ttQTTFDescription' , "A True/False question is a Multiple Choice question that asks the participant to give a \"True\" or \"False\" answer to a question.");
define('ttQTNM' , "Numeric");
define('ttQTNMDescription' , "In a Numeric Question, the participant answers by typing in either a whole number or a real number.");
define('ttQTTM' , "Text Match");
define('ttQTTMDescription' , "En una pregunta de concordancia de texto, el participante escribe una sola palabra o unas pocas palabras para indicar su respuesta.");
define('ttQTHS' , "Punto de acceso");
define('ttQTHSDescription' , "Una pregunta de punto de acceso es una pregunta de arrastrar y soltar con solo un área derecha.");
define('ttQTPL' , "Lista desplegable");
define('ttQuesionid' , "ID de la pregunta");
define('ttQuestionNotes' , "Descripción");
define('ttQuestionsend' , "Enviar reporte");
define('ttQuestionreporting' , "Para reportar más preguntas, debe dejar el campo de identificación en blanco.");
define('ttRandom' , "Aleatorio");
define('ttRefresh' , "Refrescar");
define('ttRegister' , "Registro");
define('ttRegistrations' , "Inscripciones");
define('ttRegEnd' , "Cierre de registro");
define('ttRenewPassword' , "Renovar contraseña");
define('ttReset' , "Reiniciar");
define('ttResetPassword' , "Restablecer la contraseña");
define('ttRole' , "Papel");
define('ttRooms' , "Habitaciones");
define('ttSave' , "Salvar");
define('ttSaveAnswerInfo' , "Guardar información de respuesta");
define('ttSaveLanguageFiles' , "Guardar archivos de idioma");
define('ttSaveLanguageXML' , "Guardar archivos de lenguaje XML");
define('ttSaveQuestionInfo' , "Guardar información de la pregunta");
define('ttScore' , "Puntuación");
define('ttScoreFinal' , "Puntuación final");
define('ttScoreTest' , "Resultado de la prueba");
define('ttScoreType' , "Tipo de puntaje");
define('ttScoreMin' , "Puntaje mínimo");
define('ttSelectSubject' , "Seleccione Asunto");
define('ttSelectSubjectBefore' , "Seleccione un tema antes");
define('ttSet' , "Conjunto");
define('ttSetPassword' , "Por favor establezca su contraseña");
define('ttSettings' , "Ajustes");
define('ttShowHide' , "Mostrar ocultar");
define('ttSelectSubQuestion' , "Seleccione una subpregunta");
define('ttSkin' , "Piel");
define('ttStart' , "comienzo");
define('ttStarted' , "Empezado");
define('ttStop' , "Detener");
define('ttStopped' , "Detenido");
define('ttStartTest' , "Prueba de inicio");
define('ttStatus' , "Estado");
define('ttStats' , "Estadísticas");
define('ttStudent' , "Estudiante");
define('ttStudents' , "Estudiantes");
define('ttST10' , "Décimos");
define('ttST30' , "Treinta");
define('ttST100' , "Centésimo");
define('ttSubject' , "Tema");
define('ttSubjects' , "Asignaturas");
define('ttSubmit' , "Enviar");
define('ttSurname' , "Apellido");
define('ttSystem' , "Sistema");
define('ttSystemConfiguration' , "Configuración del sistema");
define('ttSbjVers' , "Versión");
define('ttTeacher' , "Profesor");
define('ttTeachers' , "Maestros");
define('ttTest' , "Prueba");
define('ttTests' , "Pruebas");
define('ttTestToCorrect' , "Pruebas para corregir");
define('ttText' , "Texto");
define('ttTime' , "Hora");
define('ttTimeEnd' , "Fin de tiempo");
define('ttTimeStart' , "Hora de inicio");
define('ttTimeUsed' , "Tiempo utilizado");
define('ttTimeZone' , "Zona horaria");
define('ttTitle' , "Title");
define('ttTopic' , "Topic");
define('ttTopics' , "Topics");
define('ttTopicsAndQuestions' , "Topics and Questions");
define('ttTopicsQuestions' , "Questions per Topics");
define('ttTranslations' , "Translations");
define('ttTrue' , "True");
define('ttType' , "Type");
define('ttUser' , "User");
define('ttUsers' , "Users");
define('ttView' , "View");
define('ttWelcome' , "Welcome");
define('ttWaiting' , "Waiting");
define('ttWarning' , "Warning");
define('ttYes' , "Yes");
define('ttAssesmentOverview' , "Assesment Overview Report");
define('ttDeselectAll' , "Deselect all");
define('ttErrorUserParameter' , "Select a participant detail to continue!");
define('ttQuestionerror' , "Question ID");
define('ttRemove' , "Remove");
define('ttReportCoachingError' , "Select an assessment and a participant to continue");
define('ttReportCoachingError2' , "Select an assessment to continue");
define('ttReportErrorStudent' , "The selected student did not participate in chosen tests");
define('ttReportMainAO' , "Main");
define('ttReportTemplateDeleteFailed' , "Delete failed");
define('ttReportTemplateDelet' , "Template deleted");
define('ttReportTemplateLoaded' , "Template caricato correttamente");
define('ttReportTemplateSaveError' , "Insert a template name without space!");
define('ttReportTemplateSaved' , "Template Saved correctly");
define('ttReportTemplateDuplicateError' , "Template name already exist!");
define('ttReportScoreFilter' , "If you have already selected a participant, now please re-select new one");
define('ttSelectAll' , "Select all");
define('ttQTFB' , "Fill in the blanks");
define('ttQTFB_TEXT' , "Complete the following text with the appropriate words");
define('ttQTFBDescription' , "In a fill in blanks question the participant have to complete the text with the correct answer in the text-field");
define('ttPosterImageVideo' , "Loading Logo");
define('ttWidthVideo' , "Width");
define('ttHeightVideo' , "Height");
define('ttIdVideo' , "Identification Code");
define('ttVideoTypeVideo' , "Video format");
define('ttNumberOfPlaysVideo' , "Max number of plays");
define('ttToolbarVideo' , "Video");
define('ttDialogTitleVideo' , "Video property");
define('ttFakeObjectVideo' , "Video");
define('ttPropertiesVideo' , "Edit video");
define('ttWidthRequiredVideo' , "The width should be set");
define('ttHeightRequiredVideo' , "The height should be set");
define('ttNumberOfPlayRequiredVideo' , "The Max number of plays should be set");
define('ttFallbackTemplateVideo' , "Your browser does not support HTML5 video");
define('ttBrowseVideo' , "Browse server");
define('ttsourceVideo' , "Source video");
define('ttNumberOfPlayAlertVideo' , "You have reached the maximum number of plays your video");
define('ttHelpDefault' , "Information Panel");
define('ttHelpDefaultDescription' , "Press this button to get a description of what you can do");
define('ttHelpQuestion' , "Select a question to read its contents, or double-click to edit");
define('ttHelpADMINNewTeacherDescription' , "Define the account of a new administrator, teacher or examiner");
define('ttHelpADMINNewStudentDescription' , "Define the account of a new student");
define('ttHelpADMINSelLanguageDescription' , "Select a language to manage");
define('ttHelpADMINLanguageDescription' , "Here you can change the localizations of the words used by the system");
define('ttHelpADMINSystemConf' , "Here you can change the EOL settings, be careful");
define('ttHelpADMINRoom' , "Define the rooms where the tests will be carried out");
define('ttHelpADMINImport' , "This screen allows you to import new questions to Question Mark");
define('ttHelpADMINProfile' , "This screen allows you to edit your profile");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttHelpStudent' , "To the left are the available tests, to the right the selected examination details");
define('ttHelpStudentTest' , "You are in the exam screen, answer the questions and submit the test");
define('ttHelpAdminErrorQuestion' , "If you find problems you can report from this page.");
define('ttHelpExamsCorrect' , "Aquí recibe un examen realizado por un estudiante, verifique que la corrección se haya realizado correctamente y luego confirme la votación.");
define('ttHelpExamsSettings' , "En esta pantalla puede definir o cambiar la configuración para usar en exámenes futuros.");
define('ttQTPLDescription' , "El menú desplegable es una pregunta cerrada que permite a los encuestados elegir una opción de respuesta de una lista de opciones presentada en un menú desplegable. Si desea mostrar las opciones de respuesta como botones de opción o casillas de verificación, use la pregunta de opción múltiple");
define('ttQuestionsubPL' , "Sub-preguntas");
define('ttHelpLog' , "Un archivo de registro se creará automáticamente después de cambiar una pregunta ya asignada a una prueba.");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Grupo");
define('ttSubgroup' , "Subgrupo");
define('ttAOreportSaved' , "Todo el informe generado se guardará en el servidor.");
define('ttReport' , "Informe");
define('ttReportAllFinished' , "Todo terminado");
define('ttReportAODescription' , "Si no selecciona evaluaciones específicas, todas las evaluaciones serán analizadas.");
define('ttReportAOWelcome' , "Elija una evaluación y use las pestañas del asistente para filtrar los datos");
define('ttReportAOSelectAssesment' , "Seleccionar evaluaciones para informar");
define('ttReportAssesmentAuthor' , "Autor de la evaluación");
define('ttReportAssessmentInformation' , "Información de evaluación");
define('ttReportAssesmentID' , "ID de evaluación");
define('ttReportAssesmentDateTimeFirst' , "Fecha / hora de la primera toma");
define('ttReportAssesmentDateTimeLast' , "Fecha / Hora de la última toma");
define('ttReportAssesmentLeastTimeFinished' , "Menos tiempo para los acabados.");
define('ttReportAssesmentName' , "Nombre de evaluación");
define('ttReportAssesmentNumberStarted' , "Num.");
define('ttReportAssesmentNumberNotFinished' , "Num.");
define('ttReportAssesmentNumberFinished' , "Num.");
define('ttReportAssesmentMinscoreFinished' , "Puntuación mínima de los finalizados.");
define('ttReportAssesmentMaxcoreFinished' , "Puntaje máximo de los finalizados.");
define('ttReportAssesmentMediumFinished' , "Puntuación media de los acabados.");
define('ttReportAssesmentMediumTimeFinished' , "Tiempo medio tomado para los acabados.");
define('ttReportAssesmentMostTimeFinished' , "La mayoría del tiempo tomado para los acabados.");
define('ttReportAssesmentScore' , "Filtrar por puntaje de evaluaciones");
define('ttReportAssesmentStdDeviation' , "Desviación estándar para los acabados.");
define('ttReportChecked' , "Seleccionado");
define('ttReportCoaching' , "Informe de Coaching");
define('ttReportCWelcome' , "Elige una valoración y un participante.");
define('ttReportCDescription' , "Tienes que filtrar los datos por fechas y, si quieres, también por puntuación");
define('ttReportCoachingDescription' , "Vea los resultados detallados para un participante que toma una evaluación");
define('ttReportCoachingInformation' , "Seleccione una prueba para ver información detallada");
define('ttReportCustomize' , "Personaliza tu informe");
define('ttReportDateInterval' , "Intervalo de fechas");
define('ttReportDateFrom' , "Desde");
define('ttReportDateTaken' , "Fecha que se tendrá");
define('ttReportDateTo' , "a");
define('ttReportErrorDetail' , "Please select a participant to show details");
define('ttReportField' , "Field name");
define('ttReportGraphicalDsiplays' , "Graphical displays");
define('ttReportGraphicHistogram' , "Histogram of assessment scores");
define('ttReportGraphicTopicScore' , "Histogram of topic scores");
define('ttReportGroup' , "Groups");
define('ttReportGroupNotPresent' , "There aren't groups");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filter by minimum score");
define('ttReportMaximumScore' , "Filter by maximum score");
define('ttReportNotFilter' , "Do not use filter");
define('ttReportOrder' , "Order");
define('ttReportPartecipants' , "Participants");
define('ttReportPartecipant' , "Participant");
define('ttReportScheduled' , "Schedule");
define('ttReportScoreBand' , "Filter by score band");
define('ttReportSearch' , "Search...");
define('ttReportSearched' , "Search result");
define('ttReportSelectDetail' , "Select user ID or email of participant selected before");
define('ttReportSelectFilter' , "Select filter");
define('ttReportSelectGroup' , "Select groups filter on");
define('ttReportSelectLetter' , "Letter");
define('ttReportAOSelectPartecipant' , "Select participant");
define('ttReportSelected' , "Selected assessments");
define('ttReportSelectTemplate' , "Select a template");
define('ttReportSelectedGroup' , "Selected groups");
define('ttReportSearchByLetter' , "Search by letter");
define('ttReportStudent' , "Filter on participant");
define('ttReportStudentNotPresent' , "There aren't students");
define('ttReportStudentDetail' , "Filter on participant detail");
define('ttReportTemplateLoad' , "Select a template to load");
define('ttReportTemplateSave' , "Save template as");
define('ttReportTemplateName' , "Insert name");
define('ttReportTimedOut' , "Timed out");
define('ttReportTopicAverageScore' , "Average score");
define('ttReportTopicInformation' , "Topic information");
define('ttReportTopicMaximumScore' , "Maximum score");
define('ttReportTopicMinimumScore' , "Minimum score");
define('ttReportTopicName' , "Topic name");
define('ttReportTopicStandardDeviation' , "Standard Deviation");
define('ttReportTyping' , "Search by typing");
define('ttReportQuestionType' , "Question type");
define('ttReportViewer' , "Report viewer");
define('ttReportViewerDescription' , "View all generated report and manage them");
define('ttStudentDetailCreport' , "Student detail");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Certificates");
define('ttCertificate' , "Certificate");
define('ttNewGroup' , "Add group");
define('ttEditGroup' , "Edit group");
define('ttEditTeacher' , "Edit Teacher");
define('ttEditStudent' , "Edit Student");
define('tteTeacher' , "Examiner");
define('tttotals' , "Total");
define('ttD1s' , "Easy");
define('ttD2s' , "Medium");
define('ttD3s' , "Hard");
define('ttSelectStudent' , "Students list");
define('ttSelectTeacher' , "Teacher list");
define('ttCoord' , "Coordinates");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "The list of exams is displayed here. You can create a new exam, change the exam settings, or view student votes.");
define('ttHelpSubject' , "Here you will see a list of the courses you are teaching. Select one to view the questions contained therein.");
define('ttNotAvailable' , "The selected settings do not allow you to generate a test.");
define('ttSelectGroup' , "Edit groups or subgroups");
define('ttConfirmProcedure' , "Do you really want to do this?");
define('ttUserDeleted' , "User deleted correctly");
define('ttMGroupCreated' , "Group successfully created");
define('ttMSubgroupCreated' , "Subgrupo creado exitosamente");
define('ttNewSubgroup' , "Add subgroup");
define('ttErrorTopic' , "Too much topic questions selected");
define('ttAvailable' , "questions available of");
define('ttThereAreNot' , "There aren't");
define('ttErrorMax' , "This field can't be lesser than the number of selected mandatory questions");
define('ttField' , "The field");
define('ttHard' , "Hard");
define('ttMedium' , "Medium");
define('ttEasy' , "Easy");
define('ttMustBeaNumber' , "Must be a number");
define('ttMaxHardReached' , "Número máximo de preguntas difíciles ya alcanzadas");
define('ttMaxMediumReached' , "Número máximo de preguntas medianas ya alcanzadas");
define('ttMaxEasyReached' , "Número máximo de preguntas fáciles ya alcanzadas");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Si hace clic en el botón Sí, el examen del estudiante se entregará automáticamente al sistema en su estado actual.");
define('ttProfCert' , "Certificado de Competencia");
define('ttCertify' , "Esto es para certificar que");
define('ttSuccess' , "ha pasado con éxito");
define('ttEvaluation' , "con evaluacion");
define('ttAccreditedTestSite' , "en el Sitio de Prueba Acreditado de la");
define('ttOn' , "en");
define('ttNumQuestionsTopic' , "Número de preguntas para cada tema.");
define('ttParamNotSet' , "Parámetros faltantes");
define('ttNotEnoughQuestions' , "No hay suficientes preguntas");
define('ttExamArchivedCertNot' , "El examen está archivado pero no se han generado certificados.");
define('ttSendCertificate' , "Descargar certificado");
define('ttCertificateAlert' , "¿Está seguro de que desea generar y descargar el certificado de examen para el estudiante?");
define('ttCertificateScore' , "El alumno no tiene la puntuación mínima para recibir un certificado.");
define('ttCertificateGenerated' , "El certificado fue generado correctamente.");
define('ttBut' , "pero");
define('ttAnd' , "y");
define('ttCertificateEmailSended' , "el correo electrónico fue enviado con éxito");
define('ttCertificateGeneratedProblem' , "El certificado no fue generado!");
define('ttCertificatePoint' , "El puntaje del estudiante es demasiado bajo y no se puede emitir un certificado.");
define('ttPrivacy1' , "Leo y acepto el");
define('ttPrivacy2' , "Política de privacidad de ECTN");
define('ttPrivacy3' , "Deseo ser informado sobre la posibilidad de obtener un Certificado de Competencia Individual");
define('ttDemoTest' , "Demo test");
