<?php
define('ttAccountActivation' , "Aktiviranje računa");
define('ttActive' , "Aktivno");
define('ttActivate' , "Aktiviraj");
define('ttAdd' , "Dodaj");
define('ttAddSelectedStudents' , "Dodaj izbrane študente");
define('ttAdministration' , "Uprava");
define('ttAdministrator' , "Skrbnik");
define('ttAdminWelcome' , "Dobrodošli na nadzorni plošči. ");
define('ttAlias' , "ISO 639-1");
define('ttAndExit' , "in Izhod");
define('ttAnswer' , "Odgovor");
define('ttAnswers' , "Odgovori");
define('ttArchive' , "Arhiv");
define('ttArchived' , "Arhivirano");
define('ttAssignSubject' , "Dodeli predmet");
define('ttAutomatic' , "Samodejno");
define('ttAImportComplete' , "Vprašanja Uvoz je uspešno zaključen");
define('ttBasedOn' , "Temelji na");
define('ttBlocked' , "Blokiran");
define('ttBlock' , "Blokiraj");
define('ttUnblock' , "Odblokiraj");
define('ttBonus' , "Bonus");
define('ttCancel' , "Prekliči");
define('ttChangeLanguage' , "Spremeni jezik");
define('ttChangeVersion' , "Spremeni preizkusno različico");
define('ttCheck' , "Preverite ...");
define('ttClose' , "Zapri");
define('ttClosed' , "Zaprto");
define('ttCorrect' , "Pravilno");
define('ttConfiguration' , "Konfiguracija");
define('ttConfirm' , "Potrdite");
define('ttConfirmEmail' , "potrdi email");
define('ttConfirmPassword' , "potrdi geslo");
define('ttCreate' , "Ustvari");
define('ttCArchiveExam' , "Ste prepričani, da boste arhivirali izpit? ");
define('ttCBlockTest' , "Ali ste prepričani, da želite blokirati ta test?");
define('ttCChangeStatus' , "Ali ste prepričani, da želite spremeniti stanje vprašanja v _STATUS_?");
define('ttCConfirmTest' , "Ali želite potrditi rezultat testa? ");
define('ttCDeleteAnswer' , "Ali ste prepričani, da želite izbrisati ta odgovor in njegove prevode? ");
define('ttCDeleteExam' , "Ali ste prepričani, da želite izbrisati ta izpit? ");
define('ttCDeleteQuestion' , "Ali ste prepričani, da želite izbrisati to vprašanje in njegove prevode? ");
define('ttCDeleteRoom' , "Ali ste prepričani, da želite izbrisati sobo? ");
define('ttCDeleteSubject' , "Ali ste prepričani, da želite izbrisati to temo? ");
define('ttCDeleteSettings' , "Ali ste prepričani, da želite izbrisati te nastavitve testa? ");
define('ttCDeleteTopic' , "Ali ste prepričani, da želite izbrisati to temo? ");
define('ttCDiscardEdits' , "Vaše spremembe bodo izgubljene. ");
define('ttCDiscardNew' , "Ustvarjen element bo izgubljen. ");
define('ttCRegister' , "Ste prepričani, da se boste prijavili na ta izpit?");
define('ttCRegisterStudents' , "Ali ste prepričani, da boste te izbrane študente registrirali na izpitu?");
define('ttCRenewPassword' , "Geslo za izpit bo spremenjeno. ");
define('ttCStartExam' , "Ali želite aktivirati izbrani izpit?");
define('ttCStartTest' , "Do you want to start the exam now?<br/>Exam password will be required.");
define('ttCStopExam' , "Do you want to deactivate the selected exam?");
define('ttCSubmitTest' , "Do you want to submit your test?<br/>This operation can not be undone! Continue?");
define('ttCTest' , "Password is correct. Your test is ready and will start after your click!");
define('ttCumLaudae' , "cum Laudae");
define('ttCUnblockTest' , "Are you sure to unblock this test?");
define('ttCUpdateConfigurations' , "Are you sure to save the new system configurations?");
define('ttCUpdateLanguage' , "Are you sure to update language files?<br/>This operation can not be undone. Continue?");
define('ttD1' , "Easy");
define('ttD2' , "Medium");
define('ttD3' , "Hard");
define('ttDatabaseConfiguration' , "Konfiguracija baze podatkov");
define('ttDay' , "Dan");
define('ttDelete' , "Izbriši");
define('ttDescription' , "Opis");
define('ttDifficulty' , "Težava");
define('ttDifficultyQuestions' , "Vprašanja glede težavnosti");
define('ttDistribution' , "Distribucija");
define('ttDo' , "Naredite izpit");
define('ttDTAnswerInfo' , "Prikazanih je _TOTAL_ odgovorov");
define('ttDTAnswerFiltered' , "(filtrirano iz vseh odgovorov _MAX_)");
define('ttDTAnswerEmpty' , "Ni odgovorov za prikaz");
define('ttDTExamInfo' , "V teku je _TOTAL_ izpitov");
define('ttDTExamFiltered' , "(filtrira se iz vseh izpitov _MAX_ v teku)");
define('ttDTExamEmpty' , "Ni izpitov za prikaz");
define('ttDTQuestionInfo' , "Prikaz _TOTAL_ vprašanj");
define('ttDTQuestionFiltered' , "(filtrirano iz vseh vprašanj _MAX_)");
define('ttDTQuestionEmpty' , "Ni vprašanj");
define('ttDTRegisteredStudentInfo' , "Prikazanih _TOTAL_ registriranih študentov");
define('ttDTRegisteredStudentFiltered' , "(filtrirano iz vseh registriranih študentov _MAX_)");
define('ttDTRegisteredStudentEmpty' , "Ni prijavljenih študentov za prikaz");
define('ttDTStudentsInfo' , "Prikaz _TOTAL_ študentov");
define('ttDTStudentsFiltered' , "(filtrirano od vseh študentov _MAX_)");
define('ttDTStudentsEmpty' , "Št študentov za prikaz");
define('ttDTTestInfo' , "Prikaz preskusa _TOTAL_");
define('ttDTTeacherInfo' , "Prikaz _TOTAL_ učiteljev");
define('ttDTTeacherFiltered' , "(filtrirano iz vseh učiteljev _MAX_)");
define('ttDTTeacherEmpty' , "Ni učitelja, ki bi ga prikazal");
define('ttDTTestFiltered' , "(filtrirano iz vseh testov _MAX_)");
define('ttDTTestEmpty' , "Ni testov za prikaz");
define('ttDone' , "Izveden izpit");
define('ttDuration' , "Trajanje");
define('ttDTsubquestionInfo' , "Vprašanja");
define('ttEdit' , "Uredi");
define('ttEditableScore' , "Editable Score");
define('ttError' , "Napaka");
define('ttEmail' , "E-naslov");
define('ttEnd' , "Konec");
define('ttEverywhere' , "Povsod");
define('ttExam' , "Izpit");
define('ttExams' , "Izpiti");
define('ttExit' , "Izhod");
define('ttExtra' , "Dodatno");
define('ttExamsArchive' , "Arhiv");
define('ttExamsInProgress' , "Izpiti so v teku");
define('ttETeachers' , "Preiskovalec");
define('ttErrorquestion' , "Prijavi napako");
define('ttEActivationFails' , "Aktivacija ne uspe!");
define('ttEAlreadyRegistered' , "Študent je že prijavljen na ta izpit!");
define('ttEAnswerInSet' , "Operacije ni mogoče dokončati. ");
define('ttEAnswerNotFound' , "Odgovor ni bil najden");
define('ttEAnswers' , "Prišlo je do težav z odgovori. ");
define('ttEDatabase' , "Napaka baze podatkov!");
define('ttEDates' , "Datumi niso pravilni!");
define('ttEEditRoomAll' , "'Vse' sobe ni mogoče urejati!");
define('ttEEmailAlreadyRegistered' , "E-pošta je že registrirana!");
define('ttEEmailNotRegistered' , "E-pošta ni registrirana!");
define('ttEEmailNotValid' , "Vtipkana e-pošta ni veljavna! ");
define('ttEEmailsNotMatch' , "E-poštna sporočila se ne ujemata!");
define('ttEEmptyFields' , "Eno ali več polj je praznih!");
define('ttEExamArchived' , "Operacije ni mogoče dokončati. ");
define('ttEExamNotFound' , "Izpit ni bil najden!");
define('ttEExamNotStarted' , "Ne morete začeti izpita. ");
define('ttEExamStarted' , "Operacije ni mogoče dokončati, ker je izpit že zagnan!");
define('ttEExamWaiting' , "Operacije ni mogoče dokončati, ker se izpit nikoli ne začne!");
define('ttEExamsNotArchivedDeleteTopic' , "Operacije ni mogoče dokončati, ker vsaj en ne arhiviran izpit vsebuje vprašanja iz te teme!");
define('ttEExamsNotArchivedEditTestSettings' , "Operacije ni mogoče dokončati, ker se te nastavitve uporabljajo z vsaj enim ne arhiviranim izpitom.");
define('ttEExamsNotArchivedDeleteTestSettings' , "Operacije ni mogoče dokončati, ker te nastavitve uporablja vsaj en nepovabljen izpit!");
define('ttEIncorrectField' , "Eno ali več polj ni pravilno!");
define('ttELogin' , "E-pošta in / ali geslo nista pravilna!");
define('ttEMainLanguageEmpty' , "Glavni jezik predmeta ne sme biti prazen!");
define('ttEMandatoryQuestion' , "To je obvezno vprašanje pri nastavitvi testa »_TESTSETTING_«: ne morete ga izbrisati ali urediti njegove težave ali teme.");
define('ttENotAuthorized' , "Vaša stranka ni pooblaščena. ");
define('ttENoStudentsToRegister' , "Št študent za registracijo!");
define('ttENoTopicsForSubject' , "Ni teme za to temo! ");
define('ttEOldPasswordWrong' , "Staro geslo ni pravilno!");
define('ttEPassword' , "Napačno geslo!");
define('ttEPasswordShort' , "Geslo je prekratko. ");
define('ttEPasswordsNotMatch' , "Dve gesli se ne ujemata!");
define('ttEQuestAnswPicker' , "Napaka pri izbiranju vprašanj in odgovorov. ");
define('ttEQuestionInSet' , "Operacije ni mogoče dokončati. ");
define('ttEQuestionNotFound' , "Vprašanje ni bilo mogoče najti!");
define('ttEQuestionType' , "Vrsta vprašanja ni pravilna!");
define('ttERegFailedQuestions' , "Registracija ni uspela: premalo vprašanj! ");
define('ttERoomAllDelete' , "\"Vse\" sobe ni mogoče izbrisati!");
define('ttERoomUsed' , "Operacije ni mogoče dokončati. ");
define('ttESaveBeforeNew' , "Pred ustvarjanjem novega elementa shranite ali prekličite že ustvarjeno.");
define('ttESelectQuestionType' , "Izbrati morate eno od razpoložljivih vrst vprašanj!");
define('ttESelectSubject' , "Izbrati morate enega od predmetov!");
define('ttESelectTestSettings' , "Izbrati morate eno od preskusnih nastavitev!");
define('ttESetNotFound' , "Vprašanja niso bila najdena!");
define('ttETestAlreadyArchived' , "Operacije ni mogoče dokončati. ");
define('ttETestAlreadySubmitted' , "Operacije ni mogoče dokončati. ");
define('ttETestBlockedSubmitted' , "Operacije ni mogoče dokončati. ");
define('ttETestNotArchived' , "Operacije ni mogoče dokončati. ");
define('ttETestNotFound' , "Test ni bil najden!");
define('ttETestsNotArchived' , "Nekateri testi niso bili arhivirani! ");
define('ttETestSettingDeleteQuestion' , "Operacije ni mogoče dokončati. ");
define('ttETestSettingDeleteTopic' , "Operacije ni mogoče dokončati. ");
define('ttETimeExpired' , "Razpoložljivi čas je potekel!");
define('ttETranslationExists' , "Prevod izbranega jezika že obstaja!");
define('ttEUserNotFound' , "Uporabnik ni najden!");
define('ttEValues' , "Nekatere vrednosti niso pravilne!");
define('ttFalse' , "Ne drži");
define('ttFinalScore' , "Končni rezultat");
define('ttGeneralInformations' , "Splošne informacije");
define('ttHours' , "ure");
define('ttHome' , "Domov");
define('ttHomepage' , "Domača stran");
define('ttHost' , "Gostiteljica");
define('ttHAnswPanel' , "Dvokliknite, da uredite izbrani odgovor");
define('ttHQuestLanguagesPanel' , "Kliknite, če želite prikazati prevod izbranega vprašanja");
define('ttHQuestPanel' , "Z enim klikom izberite in si oglejte predogled vprašanja ter dvokliknite, če želite urediti vprašanje in odgovoriti na informacije. ");
define('ttHQuestPreviewPanel' , "Odgovori z oranžnim ozadjem se ne prevajajo v zahtevanem jeziku");
define('ttHQuestTopicPanel' , "Z enim klikom za filtriranje vprašanj in z dvojnim klikom uredite informacije o temi");
define('ttInfo' , "Info");
define('ttIPEnd' , "Konec IPv4");
define('ttIPStart' , "Začetek IPv4");
define('ttInactive' , "Neaktivno");
define('ttImportQM' , "Uvozi");
define('ttImport' , "Uvozi QM");
define('ttImportComplete' , "Vprašanja Uvoz je uspešno zaključen");
define('ttJoin' , "Pridruži se");
define('ttLanguage' , "Jezik");
define('ttLanguages' , "Jeziki");
define('ttLogin' , "Vpiši se");
define('ttLogo' , "Logotip");
define('ttLoginOk' , "Prijava je končana!");
define('ttLogout' , "IZPISATI");
define('ttMailLostPassword' , "Če želite ponastaviti geslo računa, kliknite to povezavo: _LINK_ Če niste zahtevali ponastavitve gesla, prezrite to e-poštno sporočilo.");
define('ttMailCredentials' , "Spoštovani, _USERNAME_, geslo, povezano z računom _USEREMAIL_, je bilo spremenjeno glede na vašo zahtevo. ");
define('ttMailNewTeacher' , "Dobrodošli v _SYSTEMNAME_. ");
define('ttMainLanguage' , "Glavni jezik");
define('ttManage' , "Upravljanje");
define('ttMandatory' , "Obvezno");
define('ttManual' , "Priročnik");
define('ttMinutes' , "minut");
define('ttMyExams' , "Moji izpiti");
define('ttMySettings' , "Moje nastavitve");
define('ttMySubjects' , "Izberite predmet");
define('ttMActivation' , "Geslo je uspešno nastavljeno. ");
define('ttMAnswerDeleted' , "Odgovor je bil uspešno izbrisan");
define('ttMConfigurationsUpdated' , "Sistemske konfiguracije so uspešno posodobljene");
define('ttMConfirm' , "Test je bil uspešno potrjen in arhiviran");
define('ttMUserCreated' , "Izdelava je bila dokončana: e-poštno sporočilo vam je bilo poslano, da dokončate registracijo. ");
define('ttMEdit' , "Urejanje je bilo uspešno shranjeno");
define('ttMExamArchived' , "Izpit je uspešno arhiviran");
define('ttMExamDeleted' , "Izpit je bil uspešno izbrisan");
define('ttMExamStarted' , "Izpit se je uspešno začel");
define('ttMExamStopped' , "Izpit je bil uspešno zaustavljen");
define('ttMLanguageCreated' , "Prevajanje je bilo uspešno ustvarjeno");
define('ttMLanguageSaved' , "Prevod je uspešno shranjen");
define('ttMLanguageUpdated' , "Prevajanje je bilo uspešno posodobljeno");
define('ttMNewAnswer' , "Odgovor je bil uspešno ustvarjen");
define('ttMNewQuestion' , "Vprašanje je uspešno ustvarjeno");
define('ttMNewRoom' , "Soba je bila uspešno ustvarjena");
define('ttMNewSettings' , "Nastavitve preizkusa so uspešno ustvarjene");
define('ttMNewSubject' , "Zadeva je bila uspešno ustvarjena");
define('ttMNewTopic' , "Tema je bila uspešno ustvarjena");
define('ttMPasswordRenewed' , "Geslo za izpit uspešno obnovljeno");
define('ttMQuestionDeleted' , "Vprašanje je bilo uspešno izbrisano");
define('ttMRegistration' , "Uspešno ste se prijavili na ta izpit");
define('ttMResetConfirmed' , "Zahteva je končana: e-poštno sporočilo je bilo poslano, da ponastavite geslo. ");
define('ttMRoomDeleted' , "Soba je bila uspešno izbrisana");
define('ttMSelectLanguage' , "Izberite jezik, ki ga želite upravljati");
define('ttMSettingsDeleted' , "Nastavitve testa so bile uspešno izbrisane");
define('ttMStudentsRegistered' , "Študenti so se uspešno prijavili na izpit");
define('ttMSubjectDeleted' , "Zadeva je bila uspešno izbrisana");
define('ttMSubjectQuestions' , "Če želite upravljati teme in vprašanja, izberite predmet");
define('ttMSubjectSettings' , "Če želite upravljati nastavitve izpita, izberite zadevo");
define('ttMTestBlocked' , "Test je bil uspešno blokiran");
define('ttMTestSubmitted' , "Test je bil uspešno poslan");
define('ttMTestUnblocked' , "Preskus je bil uspešno blokiran");
define('ttMTopicDeleted' , "Tema je bila uspešno izbrisana");
define('ttName' , "Ime");
define('ttNumberError' , "Vrednost mora biti celo število ali decimalka (ES: 12.5)");
define('ttNegativeScores' , "Negativne ocene");
define('ttNew' , "Novo");
define('ttNext' , "Naslednji");
define('ttNewAnswer' , "Nov odgovor");
define('ttNewCredentials' , "Nove poverilnice");
define('ttNewLanguage' , "Novi jezik");
define('ttNewPassword' , "novo geslo");
define('ttNewQuestion' , "Novo vprašanje");
define('ttNewRegistration' , "Nova registracija");
define('ttNewRoom' , "Nova soba");
define('ttNewTeacher' , "Novi učitelj");
define('ttNewTestSettings' , "Nove nastavitve");
define('ttNewSubject' , "Nov predmet");
define('ttNewStudent' , "Novi študent");
define('ttNewTopic' , "Nova tema");
define('ttNewUser' , "Nov uporabnik");
define('ttNo' , "Ne");
define('ttNoAnswers' , "Za to vprašanje ni na voljo nobenih odgovorov");
define('ttNoExams' , "Za ta predmet ni na voljo nobenih izpitov");
define('ttNoExamInProgress' , "Izpit ni v teku");
define('ttNoInfo' , "Ni podatkov o tem izpitu");
define('ttNoQuestions' , "Za to temo ni na voljo nobenih vprašanj");
define('ttNoRooms' , "Ni ustvarjenih sob: \"Vse\" je na voljo samo");
define('ttNoSettings' , "Za to temo ni na voljo nobenih nastavitev");
define('ttNoSubjects' , "Na voljo ni nobenih tem");
define('ttNoTestToCorrect' , "Ni testov za popravo");
define('ttNoUserRegistered' , "Za ta izpit ni registriranih uporabnikov");
define('ttOldPassword' , "staro geslo");
define('ttEssayQuestion' , "Esejsko vprašanje");
define('ttPassword' , "Geslo");
define('ttPasswordLost' , "Geslo izgubljeno?");
define('ttPort' , "Pristanišče");
define('ttProfile' , "Profil");
define('ttPrepareImportQM' , "Predogled");
define('ttQuestion' , "Vprašanje");
define('ttQuestionPreview' , "Predogled vprašanja");
define('ttQuestions' , "Vprašanja");
define('ttQEc' , "Kalkulator");
define('ttQEp' , "Periodni sistem");
define('ttQTMC' , "Večkratna izbira");
define('ttQTMCDescription' , "V vprašanju za več izbir udeleženec izbere eno samo izbiro med več izbirami, da odgovori na vprašanje.");
define('ttQTMR' , "Večkratni odziv");
define('ttQTMRDescription' , "Vprašanje več odgovorov je kot večkratna izbira, razen da se uporabniku dovoli, da izbere eno ali več izbir, namesto da bi moral uporabiti največ eno možnost.");
define('ttQTES' , "Vprašanje o eseju");
define('ttQTESDescription' , "Vprašanje o eseju omogoča udeležencu, da vnese dolg, prosti tekstovni odgovor na vprašanje. ");
define('ttQTYN' , "Da / Ne");
define('ttQTYNDescription' , "Vprašanje »da / ne« je vprašanje z več izbirami, ki od udeleženca zahteva, da na vprašanje odgovori z „da“ ali „ne“.");
define('ttQTTF' , "Pravilno napačno");
define('ttQTTFDescription' , "Vprašanje True / False je vprašanje več izbir, ki od udeleženca zahteva, da na vprašanje odgovori z »True« ali »False«.");
define('ttQTNM' , "Številčna");
define('ttQTNMDescription' , "V številskem vprašanju udeleženec odgovori tako, da vnese celo število ali realno število.");
define('ttQTTM' , "Ujemanje besedila");
define('ttQTTMDescription' , "V vprašanju ujemanja besedila udeleženec vnese eno samo besedo ali nekaj besed, da navede svoj odgovor. ");
define('ttQTHS' , "Hotspot");
define('ttQTHSDescription' , "Vprašanje Hotspot je vprašanje povleci in spusti z le enim desnim področjem. ");
define('ttQTPL' , "Povlecite seznam");
define('ttQuesionid' , "ID vprašanja");
define('ttQuestionNotes' , "Opis");
define('ttQuestionsend' , "Pošlji poročilo");
define('ttQuestionreporting' , "Če želite prijaviti več vprašanj, pustite polje ID prazno");
define('ttRandom' , "Naključen");
define('ttRefresh' , "Osveži");
define('ttRegister' , "Register");
define('ttRegistrations' , "Registracije");
define('ttRegEnd' , "Zapiranje registracije");
define('ttRenewPassword' , "Obnovi geslo");
define('ttReset' , "Ponastaviti");
define('ttResetPassword' , "Ponastavitev gesla");
define('ttRole' , "Vloga");
define('ttRooms' , "Sobe");
define('ttSave' , "Shrani");
define('ttSaveAnswerInfo' , "Shrani informacije o odgovoru");
define('ttSaveLanguageFiles' , "Shrani jezikovne datoteke");
define('ttSaveLanguageXML' , "Shrani jezikovne datoteke XML");
define('ttSaveQuestionInfo' , "Shrani informacije o vprašanju");
define('ttScore' , "Ocena");
define('ttScoreFinal' , "Končni rezultat");
define('ttScoreTest' , "Rezultat testa");
define('ttScoreType' , "Vrsta zadetka");
define('ttScoreMin' , "Minimalni rezultat");
define('ttSelectSubject' , "Izberite Zadeva");
define('ttSelectSubjectBefore' , "Pred tem izberite predmet");
define('ttSet' , "Set");
define('ttSetPassword' , "Nastavite geslo");
define('ttSettings' , "Nastavitve");
define('ttShowHide' , "Prikaži / skrij");
define('ttSelectSubQuestion' , "Izberite vprašanje");
define('ttSkin' , "Kožo");
define('ttStart' , "Začni");
define('ttStarted' , "Začelo se je");
define('ttStop' , "Stop");
define('ttStopped' , "Ustavljeno");
define('ttStartTest' , "Začni preskus");
define('ttStatus' , "Stanje");
define('ttStats' , "Statistika");
define('ttStudent' , "Študent");
define('ttStudents' , "Študenti");
define('ttST10' , "Desetine");
define('ttST30' , "Tridesete");
define('ttST100' , "Stotina");
define('ttSubject' , "Predmet");
define('ttSubjects' , "Predmeti");
define('ttSubmit' , "Pošlji");
define('ttSurname' , "Priimek");
define('ttSystem' , "Sistem");
define('ttSystemConfiguration' , "Konfiguracija sistema");
define('ttSbjVers' , "Različica");
define('ttTeacher' , "Učitelj");
define('ttTeachers' , "Učitelji");
define('ttTest' , "Test");
define('ttTests' , "Testi");
define('ttTestToCorrect' , "Preskusi za odpravo");
define('ttText' , "Besedilo");
define('ttTime' , "Čas");
define('ttTimeEnd' , "Časovna omejitev");
define('ttTimeStart' , "Čas začetka");
define('ttTimeUsed' , "Uporabljen čas");
define('ttTimeZone' , "Časovni pas");
define('ttTitle' , "Naslov");
define('ttTopic' , "Tema");
define('ttTopics' , "Teme");
define('ttTopicsAndQuestions' , "Teme in vprašanja");
define('ttTopicsQuestions' , "Vprašanja glede tem");
define('ttTranslations' , "Prevodi");
define('ttTrue' , "Prav");
define('ttType' , "Vrsta");
define('ttUser' , "Uporabnik");
define('ttUsers' , "Uporabniki");
define('ttView' , "Prikaži");
define('ttWelcome' , "Dobrodošli");
define('ttWaiting' , "Čakam");
define('ttWarning' , "Opozorilo");
define('ttYes' , "Da");
define('ttAssesmentOverview' , "Poročilo o pregledu ocene");
define('ttDeselectAll' , "Počistite vse");
define('ttErrorUserParameter' , "Izberite podrobnost udeleženca za nadaljevanje!");
define('ttQuestionerror' , "ID vprašanja");
define('ttRemove' , "Odstraniti");
define('ttReportCoachingError' , "Izberite oceno in udeleženca za nadaljevanje");
define('ttReportCoachingError2' , "Izberite oceno za nadaljevanje");
define('ttReportErrorStudent' , "Izbrani študent ni sodeloval v izbranih testih");
define('ttReportMainAO' , "Main");
define('ttReportTemplateDeleteFailed' , "Brisanje ni uspelo");
define('ttReportTemplateDelet' , "Predloga je izbrisana");
define('ttReportTemplateLoaded' , "Predloga caricato correttamente");
define('ttReportTemplateSaveError' , "Vstavite ime predloge brez presledka!");
define('ttReportTemplateSaved' , "Predloga je pravilno shranjena");
define('ttReportTemplateDuplicateError' , "Ime predloge že obstaja!");
define('ttReportScoreFilter' , "Če ste že izbrali udeleženca, ga znova izberite");
define('ttSelectAll' , "Izberi vse");
define('ttQTFB' , "Izpolnite praznine");
define('ttQTFB_TEXT' , "Izpolnite naslednje besedilo z ustreznimi besedami");
define('ttQTFBDescription' , "V vprašanju za izpolnitev praznine mora udeleženec v besedilnem polju izpolniti besedilo s pravilnim odgovorom");
define('ttPosterImageVideo' , "Nalaganje logotipa");
define('ttWidthVideo' , "Premer");
define('ttHeightVideo' , "Višina");
define('ttIdVideo' , "Identifikacijska koda");
define('ttVideoTypeVideo' , "Oblika videoposnetka");
define('ttNumberOfPlaysVideo' , "Največje število predvajanj");
define('ttToolbarVideo' , "Video");
define('ttDialogTitleVideo' , "Lastnost videoposnetka");
define('ttFakeObjectVideo' , "Video");
define('ttPropertiesVideo' , "Uredi videoposnetek");
define('ttWidthRequiredVideo' , "Nastaviti je treba širino");
define('ttHeightRequiredVideo' , "Nastaviti je treba višino");
define('ttNumberOfPlayRequiredVideo' , "Nastavi se največje število predvajanj");
define('ttFallbackTemplateVideo' , "Vaš brskalnik ne podpira videa HTML5");
define('ttBrowseVideo' , "Brskanje po strežniku");
define('ttsourceVideo' , "Izvorni videoposnetek");
define('ttNumberOfPlayAlertVideo' , "Dosegli ste največje število predvajanj vašega videoposnetka");
define('ttHelpDefault' , "Informacijska plošča");
define('ttHelpDefaultDescription' , "Pritisnite ta gumb, da dobite opis, kaj lahko storite");
define('ttHelpQuestion' , "Izberite vprašanje za branje njegove vsebine ali pa dvokliknite, da ga uredite");
define('ttHelpADMINNewTeacherDescription' , "Določite račun novega administratorja, učitelja ali izpraševalca");
define('ttHelpADMINNewStudentDescription' , "Določite račun novega študenta");
define('ttHelpADMINSelLanguageDescription' , "Izberite jezik, ki ga želite upravljati");
define('ttHelpADMINLanguageDescription' , "Tukaj lahko spremenite lokalizacije besed, ki jih uporablja sistem");
define('ttHelpADMINSystemConf' , "Tukaj lahko spremenite nastavitve EOL, bodite previdni");
define('ttHelpADMINRoom' , "Določite prostore, v katerih se bodo izvajali preskusi");
define('ttHelpADMINImport' , "Ta zaslon vam omogoča uvoz novih vprašanj v vprašanje");
define('ttHelpADMINProfile' , "Ta zaslon vam omogoča urejanje profila");
define('ttHelpReportAreport' , "Ta zaslon vam omogoča, da ustvarite Areport, obvezno morate izbrati vsaj en predmet");
define('ttHelpReportAreportTemplate' , "Izberite, katere informacije lahko dobite v poročilu");
define('ttHelpReportCreport' , "Ta zaslon vam omogoča, da ustvarite Creport, obvezno morate izbrati udeleženca");
define('ttHelpReportCreportlist' , "Izberite pregled za izdelavo poročila");
define('ttHelpStudent' , "Na levi strani so razpoložljivi testi, na desni pa izbrani podrobnosti pregleda");
define('ttHelpStudentTest' , "Na izpitnem zaslonu ste, odgovorite na vprašanja in oddajte test");
define('ttHelpAdminErrorQuestion' , "Če najdete težave, ki jih lahko prijavite na tej strani.");
define('ttHelpExamsCorrect' , "Tukaj prejmete izpit, ki ga opravi študent, preverite, ali je bil popravek pravilno opravljen, in potrdite glasovanje.");
define('ttHelpExamsSettings' , "Na tem zaslonu lahko določite ali spremenite nastavitve za uporabo pri prihodnjih pregledih.");
define('ttQTPLDescription' , "Spustni meni je vprašanje zaprtega tipa, ki anketirancem omogoča, da izberejo eno izbiro odgovora s seznama izbir, ki so prikazane v spustnem meniju.");
define('ttQuestionsubPL' , "Podvprašanja");
define('ttHelpLog' , "Po spremembi vprašanja, ki je že dodeljeno testu, se bo datoteka dnevnika samodejno ustvarila. ");
define('ttErrorSent' , "ACK");
define('ttGroup' , "Skupina");
define('ttSubgroup' , "Podskupina");
define('ttAOreportSaved' , "Vsa ustvarjena poročila bodo shranjena na strežniku. ");
define('ttReport' , "Poročilo");
define('ttReportAllFinished' , "Vse je končano");
define('ttReportAODescription' , "Če ne izberete določenih ocen, bomo analizirali celotno oceno");
define('ttReportAOWelcome' , "Izberite oceno in s karticami čarovnika filtrirajte podatke");
define('ttReportAOSelectAssesment' , "Izberite ocene za poročanje");
define('ttReportAssesmentAuthor' , "Avtor ocene");
define('ttReportAssessmentInformation' , "Informacije o oceni");
define('ttReportAssesmentID' , "ID presoje");
define('ttReportAssesmentDateTimeFirst' , "Prvič posneti datum / čas");
define('ttReportAssesmentDateTimeLast' , "Zadnji dan / ura");
define('ttReportAssesmentLeastTimeFinished' , "Za tiste, ki so končali, je potreben najmanj čas");
define('ttReportAssesmentName' , "Ime ocene");
define('ttReportAssesmentNumberStarted' , "Št. ");
define('ttReportAssesmentNumberNotFinished' , "Št. ");
define('ttReportAssesmentNumberFinished' , "Št. ");
define('ttReportAssesmentMinscoreFinished' , "Minimalno število doseženih");
define('ttReportAssesmentMaxcoreFinished' , "Največje število doseženih rezultatov");
define('ttReportAssesmentMediumFinished' , "Srednje število končanih");
define('ttReportAssesmentMediumTimeFinished' , "Srednji čas, potreben tistim, ki so končali");
define('ttReportAssesmentMostTimeFinished' , "Večina časa, potrebnega za tiste, ki so končali");
define('ttReportAssesmentScore' , "Filtrirajte po ocenah ocen");
define('ttReportAssesmentStdDeviation' , "Standardno odstopanje za končne");
define('ttReportChecked' , "Izbrano");
define('ttReportCoaching' , "Coaching poročilo");
define('ttReportCWelcome' , "Izberite oceno in udeleženca");
define('ttReportCDescription' , "Podatke morate filtrirati po datumih in, če želite, tudi po rezultatih");
define('ttReportCoachingDescription' , "Oglejte si podrobne rezultate za enega udeleženca, ki je sprejel eno oceno");
define('ttReportCoachingInformation' , "Izberite en preskus, da vidite podrobne informacije");
define('ttReportCustomize' , "Prilagodite poročilo");
define('ttReportDateInterval' , "Interval datumov");
define('ttReportDateFrom' , "Od");
define('ttReportDateTaken' , "Datum fotografiranja");
define('ttReportDateTo' , "do");
define('ttReportErrorDetail' , "Izberite udeleženca za prikaz podrobnosti");
define('ttReportField' , "Ime polja");
define('ttReportGraphicalDsiplays' , "Grafični prikazi");
define('ttReportGraphicHistogram' , "Histogram ocenjevalnih točk");
define('ttReportGraphicTopicScore' , "Histogram tematskih točk");
define('ttReportGroup' , "Skupine");
define('ttReportGroupNotPresent' , "Ni skupin");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filtrirajte po minimalnem rezultatu");
define('ttReportMaximumScore' , "Filtrirajte po najvišjem rezultatu");
define('ttReportNotFilter' , "Ne uporabljajte filtra");
define('ttReportOrder' , "Naročilo");
define('ttReportPartecipants' , "Udeleženci");
define('ttReportPartecipant' , "Udeleženec");
define('ttReportScheduled' , "Urnik");
define('ttReportScoreBand' , "Filtrirajte po pasu rezultatov");
define('ttReportSearch' , "Iskanje...");
define('ttReportSearched' , "Rezultat iskanja");
define('ttReportSelectDetail' , "Izberite uporabniško ime ali e-pošto udeleženca, ki ste jo izbrali prej");
define('ttReportSelectFilter' , "Izberite filter");
define('ttReportSelectGroup' , "Izbira skupin vključi");
define('ttReportSelectLetter' , "Pismo");
define('ttReportAOSelectPartecipant' , "Izberite udeleženca");
define('ttReportSelected' , "Izbrane ocene");
define('ttReportSelectTemplate' , "Izberite predlogo");
define('ttReportSelectedGroup' , "Izbrane skupine");
define('ttReportSearchByLetter' , "Iskanje po črki");
define('ttReportStudent' , "Filtrirajte udeleženca");
define('ttReportStudentNotPresent' , "Ni študentov");
define('ttReportStudentDetail' , "Filtrirajte podrobnosti udeleženca");
define('ttReportTemplateLoad' , "Izberite predlogo za nalaganje");
define('ttReportTemplateSave' , "Shrani predlogo kot");
define('ttReportTemplateName' , "Vstavi ime");
define('ttReportTimedOut' , "Časovna omejitev je iztekla");
define('ttReportTopicAverageScore' , "Povprečna ocena");
define('ttReportTopicInformation' , "Informacije o temah");
define('ttReportTopicMaximumScore' , "Največja ocena");
define('ttReportTopicMinimumScore' , "Minimalni rezultat");
define('ttReportTopicName' , "Ime teme");
define('ttReportTopicStandardDeviation' , "Standardni odklon");
define('ttReportTyping' , "Išči s tipkanjem");
define('ttReportQuestionType' , "Vrsta vprašanja");
define('ttReportViewer' , "Pregledovalnik poročil");
define('ttReportViewerDescription' , "Oglejte si vsa ustvarjena poročila in jih upravljajte");
define('ttStudentDetailCreport' , "Podrobnosti študenta");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "Potrdila");
define('ttCertificate' , "Potrdilo");
define('ttNewGroup' , "Dodaj skupino");
define('ttEditGroup' , "Uredi skupino");
define('ttEditTeacher' , "Uredi učitelja");
define('ttEditStudent' , "Uredi študenta");
define('tteTeacher' , "Preizkuševalec");
define('tttotals' , "Skupaj");
define('ttD1s' , "Enostavno");
define('ttD2s' , "Srednje");
define('ttD3s' , "Trdo");
define('ttSelectStudent' , "Seznam študentov");
define('ttSelectTeacher' , "Seznam učiteljev");
define('ttCoord' , "Koordinate");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "Tukaj je prikazan seznam izpitov. ");
define('ttHelpSubject' , "Tu boste videli seznam tečajev, ki jih poučujete. ");
define('ttNotAvailable' , "Izbrane nastavitve vam ne omogočajo ustvarjanja testa.");
define('ttSelectGroup' , "Uredite skupine ali podskupine");
define('ttConfirmProcedure' , "Ali res želite to storiti?");
define('ttUserDeleted' , "Uporabnik je pravilno izbrisal");
define('ttMGroupCreated' , "Skupina je bila uspešno ustvarjena");
define('ttMSubgroupCreated' , "Podskupina je bila uspešno ustvarjena");
define('ttNewSubgroup' , "Dodaj podskupino");
define('ttErrorTopic' , "Izbrano je preveč vprašanj o temi");
define('ttAvailable' , "razpoložljivih vprašanj");
define('ttThereAreNot' , "Ni jih");
define('ttErrorMax' , "To polje ne sme biti manjše od števila izbranih obveznih vprašanj");
define('ttField' , "Polje");
define('ttHard' , "Trdo");
define('ttMedium' , "Srednje");
define('ttEasy' , "Enostavno");
define('ttMustBeaNumber' , "Mora biti številka");
define('ttMaxHardReached' , "Največje število težkih vprašanj je bilo že doseženih");
define('ttMaxMediumReached' , "Največje število srednje velikih vprašanj je bilo že doseženih");
define('ttMaxEasyReached' , "Doseženo je bilo največje število preprostih vprašanj");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Če kliknete gumb Da, se izpit za študenta samodejno dostavi v sistem v njegovem trenutnem stanju. ");
define('ttProfCert' , "Potrdilo o usposobljenosti");
define('ttCertify' , "To je, da potrdi, da");
define('ttSuccess' , "uspešno prestal");
define('ttEvaluation' , "z ocenjevanjem");
define('ttAccreditedTestSite' , "na akreditiranem testnem mestu");
define('ttOn' , "na");
define('ttNumQuestionsTopic' , "Število vprašanj za vsako temo");
define('ttParamNotSet' , "Manjkajoči parametri");
define('ttNotEnoughQuestions' , "Ni dovolj vprašanj");
define('ttExamArchivedCertNot' , "Izpit je arhiviran, vendar potrdila niso bila ustvarjena");
define('ttSendCertificate' , "Prenesite potrdilo");
define('ttCertificateAlert' , "Ali ste prepričani, da želite izdelati in prenesti potrdilo o izpitu za študenta? ");
define('ttCertificateScore' , "Študent nima minimalne ocene za pridobitev certifikata");
define('ttCertificateGenerated' , "Certifikat je bil pravilno ustvarjen");
define('ttBut' , "ampak");
define('ttAnd' , "in");
define('ttCertificateEmailSended' , "e-poštno sporočilo je bilo uspešno poslano");
define('ttCertificateGeneratedProblem' , "Potrdilo ni bilo ustvarjeno!");
define('ttCertificatePoint' , "Študentski rezultat je prenizek in ne more biti izdan certifikat.");
define('ttPrivacy1' , "Prebral sem in sprejemam");
define('ttPrivacy2' , "Pravilnik o zasebnosti ECTN");
define('ttPrivacy3' , "Želim biti obveščen o možnosti pridobitve individualnega spričevala o strokovni usposobljenosti");
