<?php
define('ttAccountActivation' , "activación de cuentaactivación de cuenta");
define('ttActive' , "ActivoActivo");
define('ttActivate' , "ActivarActivar");
define('ttAdd' , "AñadirAñadir");
define('ttAddSelectedStudents' , "Añadir estudiantes seleccionadosAñadir estudiantes seleccionados");
define('ttAdministration' , "AdministraciónAdministración");
define('ttAdministrator' , "AdministradorAdministrador");
define('ttAdminWelcome' , "Bienvenido al panel de administración.Bienvenido al panel de administración.");
define('ttAlias' , "Código ISO 639-1Código ISO 639-1");
define('ttAndExit' , "y saliry salir");
define('ttAnswer' , "ResponderResponder");
define('ttAnswers' , "RespuestasRespuestas");
define('ttArchive' , "ArchivoArchivo");
define('ttArchived' , "ArchivadoArchivado");
define('ttAssignSubject' , "Asignar AsuntoAsignar Asunto");
define('ttAutomatic' , "AutomáticoAutomático");
define('ttAImportComplete' , "Preguntas de importación ya completadas con éxitoPreguntas de importación ya completadas con éxito");
define('ttBasedOn' , "Residencia enResidencia en");
define('ttBlocked' , "ObstruidoObstruido");
define('ttBlock' , "BloquearBloquear");
define('ttUnblock' , "DesatascarDesatascar");
define('ttBonus' , "PrimaPrima");
define('ttCancel' , "CancelarCancelar");
define('ttChangeLanguage' , "Cambiar idiomaCambiar idioma");
define('ttChangeVersion' , "Cambiar la versión de pruebaCambiar la versión de prueba");
define('ttCheck' , "Comprobar...Comprobar...");
define('ttClose' , "CerrarCerrar");
define('ttClosed' , "CerradoCerrado");
define('ttCorrect' , "CorrectoCorrecto");
define('ttConfiguration' , "ConfiguraciónConfiguración");
define('ttConfirm' , "ConfirmarConfirmar");
define('ttConfirmEmail' , "Confirmar correo electrónicoConfirmar correo electrónico");
define('ttConfirmPassword' , "Confirmar contraseñaConfirmar contraseña");
define('ttCreate' , "CrearCrear");
define('ttCArchiveExam' , "¿Estás seguro de archivar el examen?¿Estás seguro de archivar el examen?");
define('ttCBlockTest' , "¿Estás seguro de bloquear esta prueba?¿Estás seguro de bloquear esta prueba?");
define('ttCChangeStatus' , "¿Está seguro de cambiar el estado de la pregunta a _STATUS_?¿Está seguro de cambiar el estado de la pregunta a _STATUS_?");
define('ttCConfirmTest' , "¿Quieres confirmar el puntaje del examen?¿Quieres confirmar el puntaje del examen?");
define('ttCDeleteAnswer' , "¿Estás seguro de eliminar esta respuesta y sus traducciones?¿Estás seguro de eliminar esta respuesta y sus traducciones?");
define('ttCDeleteExam' , "¿Estás seguro de eliminar este examen?¿Estás seguro de eliminar este examen?");
define('ttCDeleteQuestion' , "¿Estás seguro de eliminar esta pregunta y sus traducciones?¿Estás seguro de eliminar esta pregunta y sus traducciones?");
define('ttCDeleteRoom' , "¿Estás seguro de eliminar esta sala?¿Estás seguro de eliminar esta sala?");
define('ttCDeleteSubject' , "¿Estás seguro de eliminar este tema?¿Estás seguro de eliminar este tema?");
define('ttCDeleteSettings' , "¿Está seguro de eliminar esta configuración de prueba?¿Está seguro de eliminar esta configuración de prueba?");
define('ttCDeleteTopic' , "¿Estás seguro de eliminar este tema?¿Estás seguro de eliminar este tema?");
define('ttCDiscardEdits' , "Tus cambios se perderán.Tus cambios se perderán.");
define('ttCDiscardNew' , "El artículo creado se perderá.El artículo creado se perderá.");
define('ttCRegister' , "¿Estás seguro de registrarte en este examen?¿Estás seguro de registrarte en este examen?");
define('ttCRegisterStudents' , "¿Estás seguro de registrar a estos estudiantes seleccionados en el examen?¿Estás seguro de registrar a estos estudiantes seleccionados en el examen?");
define('ttCRenewPassword' , "Se cambiará la contraseña del examen.Se cambiará la contraseña del examen.");
define('ttCStartExam' , "¿Quieres activar el examen seleccionado?¿Quieres activar el examen seleccionado?");
define('ttCStartTest' , "¿Quieres comenzar el examen ahora?¿Quieres comenzar el examen ahora?");
define('ttCStopExam' , "¿Desea desactivar el examen seleccionado?¿Desea desactivar el examen seleccionado?");
define('ttCSubmitTest' , "¿Quieres enviar tu prueba?¿Quieres enviar tu prueba?");
define('ttCTest' , "La contraseña es correcta.La contraseña es correcta.");
define('ttCumLaudae' , "cum laudaecum laudae");
define('ttCUnblockTest' , "¿Estás seguro de desbloquear esta prueba?¿Estás seguro de desbloquear esta prueba?");
define('ttCUpdateConfigurations' , "¿Está seguro de guardar las nuevas configuraciones del sistema?¿Está seguro de guardar las nuevas configuraciones del sistema?");
define('ttCUpdateLanguage' , "¿Estás seguro de actualizar archivos de idioma?¿Estás seguro de actualizar archivos de idioma?");
define('ttD1' , "FácilFácil");
define('ttD2' , "MedioMedio");
define('ttD3' , "DifícilDifícil");
define('ttDatabaseConfiguration' , "Configuración de la base de datosConfiguración de la base de datos");
define('ttDay' , "DíaDía");
define('ttDelete' , "BorrarBorrar");
define('ttDescription' , "DescripciónDescripción");
define('ttDifficulty' , "DificultadDificultad");
define('ttDifficultyQuestions' , "Preguntas por dificultadPreguntas por dificultad");
define('ttDistribution' , "DistribuciónDistribución");
define('ttDo' , "Hacer examenHacer examen");
define('ttDTAnswerInfo' , "Mostrando _TOTAL_ respuestasMostrando _TOTAL_ respuestas");
define('ttDTAnswerFiltered' , "(filtrado de _MAX_ respuestas totales)(filtrado de _MAX_ respuestas totales)");
define('ttDTAnswerEmpty' , "No hay respuestas para mostrarNo hay respuestas para mostrar");
define('ttDTExamInfo' , "Mostrando _TOTAL_ exámenes en progresoMostrando _TOTAL_ exámenes en progreso");
define('ttDTExamFiltered' , "(filtrado de _MAX_ exámenes totales en curso)(filtrado de _MAX_ exámenes totales en curso)");
define('ttDTExamEmpty' , "No hay exámenes para mostrarNo hay exámenes para mostrar");
define('ttDTQuestionInfo' , "Mostrando _TOTAL_ preguntasMostrando _TOTAL_ preguntas");
define('ttDTQuestionFiltered' , "(filtrado de _MAX_ total de preguntas)(filtrado de _MAX_ total de preguntas)");
define('ttDTQuestionEmpty' , "No hay preguntas para mostrarNo hay preguntas para mostrar");
define('ttDTRegisteredStudentInfo' , "Mostrando _TOTAL_ alumnos matriculadosMostrando _TOTAL_ alumnos matriculados");
define('ttDTRegisteredStudentFiltered' , "(filtrado de _MAX_ total de estudiantes registrados)(filtrado de _MAX_ total de estudiantes registrados)");
define('ttDTRegisteredStudentEmpty' , "No hay estudiantes registrados para mostrarNo hay estudiantes registrados para mostrar");
define('ttDTStudentsInfo' , "Mostrando _TOTAL_ estudiantesMostrando _TOTAL_ estudiantes");
define('ttDTStudentsFiltered' , "(filtrado de _MAX_ total de estudiantes)(filtrado de _MAX_ total de estudiantes)");
define('ttDTStudentsEmpty' , "No hay estudiantes para mostrarNo hay estudiantes para mostrar");
define('ttDTTestInfo' , "Mostrando la prueba _TOTAL_Mostrando la prueba _TOTAL_");
define('ttDTTeacherInfo' , "Mostrando _TOTAL_ profesoresMostrando _TOTAL_ profesores");
define('ttDTTeacherFiltered' , "(filtrado de _MAX_ total de profesores)(filtrado de _MAX_ total de profesores)");
define('ttDTTeacherEmpty' , "No hay profesor para mostrarNo hay profesor para mostrar");
define('ttDTTestFiltered' , "(filtrado de _MAX_ pruebas totales)(filtrado de _MAX_ pruebas totales)");
define('ttDTTestEmpty' , "No hay pruebas para mostrarNo hay pruebas para mostrar");
define('ttDone' , "Examen hechoExamen hecho");
define('ttDuration' , "DuraciónDuración");
define('ttDTsubquestionInfo' , "Sub-preguntasSub-preguntas");
define('ttEdit' , "EditarEditar");
define('ttEditableScore' , "Puntaje editablePuntaje editable");
define('ttError' , "ErrorError");
define('ttEmail' , "EmailEmail");
define('ttEnd' , "FinFin");
define('ttEverywhere' , "En todos ladosEn todos lados");
define('ttExam' , "ExamenExamen");
define('ttExams' , "ExamenesExamenes");
define('ttExit' , "SalidaSalida");
define('ttExtra' , "ExtraExtra");
define('ttExamsArchive' , "ArchivoArchivo");
define('ttExamsInProgress' , "Exámenes en cursoExámenes en curso");
define('ttETeachers' , "ExaminadorExaminador");
define('ttErrorquestion' , "Informe de errorInforme de error");
define('ttEActivationFails' , "¡La activación falla!¡La activación falla!");
define('ttEAlreadyRegistered' , "¡El estudiante ya está registrado para este examen!¡El estudiante ya está registrado para este examen!");
define('ttEAnswerInSet' , "La operación no se puede completar.La operación no se puede completar.");
define('ttEAnswerNotFound' , "Respuesta no encontradaRespuesta no encontrada");
define('ttEAnswers' , "Se produjo un problema con las respuestas.Se produjo un problema con las respuestas.");
define('ttEDatabase' , "¡Error de la base de datos!¡Error de la base de datos!");
define('ttEDates' , "Las fechas no son correctas!Las fechas no son correctas!");
define('ttEEditRoomAll' , "'Todo' sala no se puede editar!'Todo' sala no se puede editar!");
define('ttEEmailAlreadyRegistered' , "¡Correo electrónico ya registrado!¡Correo electrónico ya registrado!");
define('ttEEmailNotRegistered' , "E-mail no registrado!E-mail no registrado!");
define('ttEEmailNotValid' , "El correo electrónico escrito no es válido!El correo electrónico escrito no es válido!");
define('ttEEmailsNotMatch' , "Los dos correos electrónicos no coinciden!Los dos correos electrónicos no coinciden!");
define('ttEEmptyFields' , "¡Uno o más campos están vacíos!¡Uno o más campos están vacíos!");
define('ttEExamArchived' , "La operación no se puede completar.La operación no se puede completar.");
define('ttEExamNotFound' , "Examen no encontrado!Examen no encontrado!");
define('ttEExamNotStarted' , "No se puede iniciar el examen.No se puede iniciar el examen.");
define('ttEExamStarted' , "La operación no se puede completar porque el examen ya está iniciado.La operación no se puede completar porque el examen ya está iniciado.");
define('ttEExamWaiting' , "La operación no se puede completar porque el examen nunca se inicia.La operación no se puede completar porque el examen nunca se inicia.");
define('ttEExamsNotArchivedDeleteTopic' , "La operación no se puede completar, porque al menos un examen no archivado contiene preguntas de este tema.La operación no se puede completar, porque al menos un examen no archivado contiene preguntas de este tema.");
define('ttEExamsNotArchivedEditTestSettings' , "La operación no se puede completar, ya que estas configuraciones se utilizan al menos en un examen no archivado.La operación no se puede completar, ya que estas configuraciones se utilizan al menos en un examen no archivado.");
define('ttEExamsNotArchivedDeleteTestSettings' , "La operación no se puede completar, ya que estas configuraciones se utilizan en al menos un examen no archivadoLa operación no se puede completar, ya que estas configuraciones se utilizan en al menos un examen no archivado");
define('ttEIncorrectField' , "Uno o más campos no son correctos!Uno o más campos no son correctos!");
define('ttELogin' , "Correo electrónico y / o contraseña no son correctos!Correo electrónico y / o contraseña no son correctos!");
define('ttEMainLanguageEmpty' , "El idioma principal del sujeto no puede estar vacío!El idioma principal del sujeto no puede estar vacío!");
define('ttEMandatoryQuestion' , "Esta es una pregunta obligatoria de la configuración de la prueba '_TESTSETTING_': no ​​se puede eliminar o editar su dificultad o tema.Esta es una pregunta obligatoria de la configuración de la prueba '_TESTSETTING_': no ​​se puede eliminar o editar su dificultad o tema.");
define('ttENotAuthorized' , "Su cliente no está autorizado.Su cliente no está autorizado.");
define('ttENoStudentsToRegister' , "Ningún estudiante para registrarse!Ningún estudiante para registrarse!");
define('ttENoTopicsForSubject' , "No hay tema para este tema!No hay tema para este tema!");
define('ttEOldPasswordWrong' , "La contraseña antigua no es correcta!La contraseña antigua no es correcta!");
define('ttEPassword' , "¡Contraseña incorrecta!¡Contraseña incorrecta!");
define('ttEPasswordShort' , "La contraseña es demasiado corta.La contraseña es demasiado corta.");
define('ttEPasswordsNotMatch' , "Las dos contraseñas no coinciden!Las dos contraseñas no coinciden!");
define('ttEQuestAnswPicker' , "Error durante la selección de preguntas y respuestas.Error durante la selección de preguntas y respuestas.");
define('ttEQuestionInSet' , "La operación no se puede completar.La operación no se puede completar.");
define('ttEQuestionNotFound' , "Pregunta no encontrada!Pregunta no encontrada!");
define('ttEQuestionType' , "Tipo de pregunta no es correcto!Tipo de pregunta no es correcto!");
define('ttERegFailedQuestions' , "Registro fallido: muy pocas preguntas!Registro fallido: muy pocas preguntas!");
define('ttERoomAllDelete' , "'Todo' sala no se puede eliminar!'Todo' sala no se puede eliminar!");
define('ttERoomUsed' , "La operación no se puede completar.La operación no se puede completar.");
define('ttESaveBeforeNew' , "Antes de crear un nuevo elemento, guarde o cancele el ya creado.Antes de crear un nuevo elemento, guarde o cancele el ya creado.");
define('ttESelectQuestionType' , "¡Debes seleccionar uno de los tipos de preguntas disponibles!¡Debes seleccionar uno de los tipos de preguntas disponibles!");
define('ttESelectSubject' , "¡Debes seleccionar uno de tus temas!¡Debes seleccionar uno de tus temas!");
define('ttESelectTestSettings' , "Debes seleccionar una de las configuraciones de prueba!Debes seleccionar una de las configuraciones de prueba!");
define('ttESetNotFound' , "Conjunto de preguntas no encontrado!Conjunto de preguntas no encontrado!");
define('ttETestAlreadyArchived' , "La operación no se puede completar.La operación no se puede completar.");
define('ttETestAlreadySubmitted' , "La operación no se puede completar.La operación no se puede completar.");
define('ttETestBlockedSubmitted' , "La operación no se puede completar.La operación no se puede completar.");
define('ttETestNotArchived' , "La operación no se puede completar.La operación no se puede completar.");
define('ttETestNotFound' , "Prueba no encontrada!Prueba no encontrada!");
define('ttETestsNotArchived' , "Algunas pruebas no han sido archivadas!Algunas pruebas no han sido archivadas!");
define('ttETestSettingDeleteQuestion' , "La operación no se puede completar.La operación no se puede completar.");
define('ttETestSettingDeleteTopic' , "La operación no puede ser completada.La operación no puede ser completada.");
define('ttETimeExpired' , "¡El tiempo disponible ha expirado!¡El tiempo disponible ha expirado!");
define('ttETranslationExists' , "¡La traducción del idioma seleccionado ya existe!¡La traducción del idioma seleccionado ya existe!");
define('ttEUserNotFound' , "¡Usuario no encontrado!¡Usuario no encontrado!");
define('ttEValues' , "¡Algunos valores no son correctos!¡Algunos valores no son correctos!");
define('ttFalse' , "FalsoFalso");
define('ttFinalScore' , "Puntuación finalPuntuación final");
define('ttGeneralInformations' , "Información generalInformación general");
define('ttHours' , "horashoras");
define('ttHome' , "CasaCasa");
define('ttHomepage' , "Página principalPágina principal");
define('ttHost' , "AnfitriónAnfitrión");
define('ttHAnswPanel' , "Haga doble clic para editar la respuesta seleccionada.Haga doble clic para editar la respuesta seleccionada.");
define('ttHQuestLanguagesPanel' , "Haga clic para mostrar la traducción de la pregunta seleccionadaHaga clic para mostrar la traducción de la pregunta seleccionada");
define('ttHQuestPanel' , "Haga un clic para seleccionar y ver la vista previa de las preguntas y haga doble clic para editar la información de las preguntas y respuestas.Haga un clic para seleccionar y ver la vista previa de las preguntas y haga doble clic para editar la información de las preguntas y respuestas.");
define('ttHQuestPreviewPanel' , "Las respuestas con fondo naranja no están traducidas en el idioma solicitado.Las respuestas con fondo naranja no están traducidas en el idioma solicitado.");
define('ttHQuestTopicPanel' , "Un solo clic para filtrar preguntas y hacer doble clic para editar la información del temaUn solo clic para filtrar preguntas y hacer doble clic para editar la información del tema");
define('ttInfo' , "InformaciónInformación");
define('ttIPEnd' , "IPv4 EndIPv4 End");
define('ttIPStart' , "Inicio de IPv4Inicio de IPv4");
define('ttInactive' , "InactivoInactivo");
define('ttImportQM' , "ImportarImportar");
define('ttImport' , "Importar QMImportar QM");
define('ttImportComplete' , "Importación de preguntas completadas exitosamenteImportación de preguntas completadas exitosamente");
define('ttJoin' , "UnirseUnirse");
define('ttLanguage' , "IdiomaIdioma");
define('ttLanguages' , "IdiomasIdiomas");
define('ttLogin' , "Iniciar sesiónIniciar sesión");
define('ttLogo' , "LogoLogo");
define('ttLoginOk' , "Inicio de sesión completo!Inicio de sesión completo!");
define('ttLogout' , "CERRAR SESIÓNCERRAR SESIÓN");
define('ttMailLostPassword' , "Para restablecer la contraseña de su cuenta, haga clic en el siguiente enlace: _LINK_ Si no ha solicitado un restablecimiento de contraseña, ignore este correo electrónico.Para restablecer la contraseña de su cuenta, haga clic en el siguiente enlace: _LINK_ Si no ha solicitado un restablecimiento de contraseña, ignore este correo electrónico.");
define('ttMailCredentials' , "Estimado _USERNAME_, Su contraseña asociada a la cuenta _USEREMAIL_ ha sido modificada de acuerdo con su solicitud.Estimado _USERNAME_, Su contraseña asociada a la cuenta _USEREMAIL_ ha sido modificada de acuerdo con su solicitud.");
define('ttMailNewTeacher' , "Bienvenido a _SYSTEMNAME_.Bienvenido a _SYSTEMNAME_.");
define('ttMainLanguage' , "Lenguaje principalLenguaje principal");
define('ttManage' , "GestionarGestionar");
define('ttMandatory' , "ObligatorioObligatorio");
define('ttManual' , "ManualManual");
define('ttMinutes' , "minutosminutos");
define('ttMyExams' , "Mis exámenesMis exámenes");
define('ttMySettings' , "Mi configuraciónMi configuración");
define('ttMySubjects' , "Seleccionar temaSeleccionar tema");
define('ttMActivation' , "Contraseña correctamente establecida.Contraseña correctamente establecida.");
define('ttMAnswerDeleted' , "Respuesta eliminada exitosamenteRespuesta eliminada exitosamente");
define('ttMConfigurationsUpdated' , "Configuraciones del sistema actualizadas exitosamenteConfiguraciones del sistema actualizadas exitosamente");
define('ttMConfirm' , "Prueba confirmada y archivada con éxito.Prueba confirmada y archivada con éxito.");
define('ttMUserCreated' , "Creación completada: se le ha enviado un correo electrónico para completar el registro.Creación completada: se le ha enviado un correo electrónico para completar el registro.");
define('ttMEdit' , "Ediciones guardadas exitosamenteEdiciones guardadas exitosamente");
define('ttMExamArchived' , "Examen archivado con éxitoExamen archivado con éxito");
define('ttMExamDeleted' , "Examen eliminado con éxitoExamen eliminado con éxito");
define('ttMExamStarted' , "Examen iniciado con éxitoExamen iniciado con éxito");
define('ttMExamStopped' , "Examen detenido exitosamenteExamen detenido exitosamente");
define('ttMLanguageCreated' , "Traducción exitosa creadaTraducción exitosa creada");
define('ttMLanguageSaved' , "Traducción guardada con éxitoTraducción guardada con éxito");
define('ttMLanguageUpdated' , "Traducción actualizada correctamenteTraducción actualizada correctamente");
define('ttMNewAnswer' , "Respuesta creada con éxitoRespuesta creada con éxito");
define('ttMNewQuestion' , "Pregunta creada exitosamentePregunta creada exitosamente");
define('ttMNewRoom' , "Sala creada con éxitoSala creada con éxito");
define('ttMNewSettings' , "Configuraciones de prueba creadas exitosamenteConfiguraciones de prueba creadas exitosamente");
define('ttMNewSubject' , "Asunto creado exitosamenteAsunto creado exitosamente");
define('ttMNewTopic' , "Tema creado con éxitoTema creado con éxito");
define('ttMPasswordRenewed' , "La contraseña del examen fue renovada exitosamenteLa contraseña del examen fue renovada exitosamente");
define('ttMQuestionDeleted' , "Pregunta eliminada exitosamentePregunta eliminada exitosamente");
define('ttMRegistration' , "Te has registrado correctamente en este examen.Te has registrado correctamente en este examen.");
define('ttMResetConfirmed' , "Solicitud completada: se le ha enviado un correo electrónico para restablecer su contraseña.Solicitud completada: se le ha enviado un correo electrónico para restablecer su contraseña.");
define('ttMRoomDeleted' , "Habitación eliminada exitosamenteHabitación eliminada exitosamente");
define('ttMSelectLanguage' , "Seleccione el idioma que desea gestionarSeleccione el idioma que desea gestionar");
define('ttMSettingsDeleted' , "Configuraciones de prueba eliminadas exitosamenteConfiguraciones de prueba eliminadas exitosamente");
define('ttMStudentsRegistered' , "Estudiantes inscritos con éxito en el examen.Estudiantes inscritos con éxito en el examen.");
define('ttMSubjectDeleted' , "Asunto eliminado con éxitoAsunto eliminado con éxito");
define('ttMSubjectQuestions' , "Para gestionar temas y preguntas, simplemente seleccione el tema.Para gestionar temas y preguntas, simplemente seleccione el tema.");
define('ttMSubjectSettings' , "Para administrar la configuración del examen, seleccione el temaPara administrar la configuración del examen, seleccione el tema");
define('ttMTestBlocked' , "Prueba bloqueada exitosamentePrueba bloqueada exitosamente");
define('ttMTestSubmitted' , "Prueba enviada correctamentePrueba enviada correctamente");
define('ttMTestUnblocked' , "Prueba desbloqueada exitosamentePrueba desbloqueada exitosamente");
define('ttMTopicDeleted' , "Tema eliminado exitosamenteTema eliminado exitosamente");
define('ttName' , "NombreNombre");
define('ttNumberError' , "El valor debe ser un entero o un decimal (ES: 12.5)El valor debe ser un entero o un decimal (ES: 12.5)");
define('ttNegativeScores' , "Puntajes negativosPuntajes negativos");
define('ttNew' , "NuevoNuevo");
define('ttNext' , "SiguienteSiguiente");
define('ttNewAnswer' , "Nueva respuestaNueva respuesta");
define('ttNewCredentials' , "Nuevas credencialesNuevas credenciales");
define('ttNewLanguage' , "Nuevo idiomaNuevo idioma");
define('ttNewPassword' , "Nueva contraseñaNueva contraseña");
define('ttNewQuestion' , "Nueva preguntaNueva pregunta");
define('ttNewRegistration' , "Nuevo registroNuevo registro");
define('ttNewRoom' , "Nuevo cuartoNuevo cuarto");
define('ttNewTeacher' , "Nuevo profesorNuevo profesor");
define('ttNewTestSettings' , "Nuevas ConfiguracionesNuevas Configuraciones");
define('ttNewSubject' , "Nuevo temaNuevo tema");
define('ttNewStudent' , "Estudiante nuevoEstudiante nuevo");
define('ttNewTopic' , "Nuevo temaNuevo tema");
define('ttNewUser' , "Nuevo usuarioNuevo usuario");
define('ttNo' , "NoNo");
define('ttNoAnswers' , "No hay respuestas disponibles para esta preguntaNo hay respuestas disponibles para esta pregunta");
define('ttNoExams' , "No hay exámenes disponibles para esta asignatura.No hay exámenes disponibles para esta asignatura.");
define('ttNoExamInProgress' , "Ningún examen en progresoNingún examen en progreso");
define('ttNoInfo' , "No hay información sobre este examen.No hay información sobre este examen.");
define('ttNoQuestions' , "No hay preguntas disponibles para este temaNo hay preguntas disponibles para este tema");
define('ttNoRooms' , "No hay habitaciones creadas: 'Todos' solo disponiblesNo hay habitaciones creadas: 'Todos' solo disponibles");
define('ttNoSettings' , "No hay configuraciones disponibles para este temaNo hay configuraciones disponibles para este tema");
define('ttNoSubjects' , "No hay asignaturas disponibles.No hay asignaturas disponibles.");
define('ttNoTestToCorrect' , "No hay pruebas para corregirNo hay pruebas para corregir");
define('ttNoUserRegistered' , "No hay usuarios registrados para este examen.No hay usuarios registrados para este examen.");
define('ttOldPassword' , "Contraseña anteriorContraseña anterior");
define('ttEssayQuestion' , "Pregunta de ensayoPregunta de ensayo");
define('ttPassword' , "ContraseñaContraseña");
define('ttPasswordLost' , "Contraseña perdida?Contraseña perdida?");
define('ttPort' , "PuertoPuerto");
define('ttProfile' , "PerfilPerfil");
define('ttPrepareImportQM' , "AvanceAvance");
define('ttQuestion' , "PreguntaPregunta");
define('ttQuestionPreview' , "Vista previa de la preguntaVista previa de la pregunta");
define('ttQuestions' , "PreguntasPreguntas");
define('ttQEc' , "CalculadoraCalculadora");
define('ttQEp' , "Tabla periódicaTabla periódica");
define('ttQTMC' , "Opción multipleOpción multiple");
define('ttQTMCDescription' , "En una pregunta de opción múltiple, el participante selecciona una sola opción de una serie de opciones para responder la pregunta.En una pregunta de opción múltiple, el participante selecciona una sola opción de una serie de opciones para responder la pregunta.");
define('ttQTMR' , "Respuesta múltipleRespuesta múltiple");
define('ttQTMRDescription' , "Una pregunta de respuesta múltiple es como una opción múltiple, excepto que, en lugar de que se requiera hacer una opción, el usuario puede hacer una o más opciones.Una pregunta de respuesta múltiple es como una opción múltiple, excepto que, en lugar de que se requiera hacer una opción, el usuario puede hacer una o más opciones.");
define('ttQTES' , "Pregunta de ensayoPregunta de ensayo");
define('ttQTESDescription' , "Una pregunta de ensayo le permite al participante ingresar una respuesta de texto largo y libre para una pregunta.Una pregunta de ensayo le permite al participante ingresar una respuesta de texto largo y libre para una pregunta.");
define('ttQTYN' , "Si noSi no");
define('ttQTYNDescription' , "Una pregunta de Sí / No es una pregunta de opción múltiple que le pide al participante que responda \"Sí\" o \"No\" a una pregunta.Una pregunta de Sí / No es una pregunta de opción múltiple que le pide al participante que responda \"Sí\" o \"No\" a una pregunta.");
define('ttQTTF' , "Verdadero FalsoVerdadero Falso");
define('ttQTTFDescription' , "Una pregunta de Verdadero / Falso es una pregunta de opción múltiple que le pide al participante que dé una respuesta de \"Verdadero\" o \"Falso\" a una pregunta.Una pregunta de Verdadero / Falso es una pregunta de opción múltiple que le pide al participante que dé una respuesta de \"Verdadero\" o \"Falso\" a una pregunta.");
define('ttQTNM' , "NuméricoNumérico");
define('ttQTNMDescription' , "En una pregunta numérica, el participante responde escribiendo un número entero o un número real.En una pregunta numérica, el participante responde escribiendo un número entero o un número real.");
define('ttQTTM' , "Coincidencia de textoCoincidencia de texto");
define('ttQTTMDescription' , "En una pregunta de concordancia de texto, el participante escribe una sola palabra o unas pocas palabras para indicar su respuesta.En una pregunta de concordancia de texto, el participante escribe una sola palabra o unas pocas palabras para indicar su respuesta.");
define('ttQTHS' , "Punto de accesoPunto de acceso");
define('ttQTHSDescription' , "Una pregunta de punto de acceso es una pregunta de arrastrar y soltar con solo un área derecha.Una pregunta de punto de acceso es una pregunta de arrastrar y soltar con solo un área derecha.");
define('ttQTPL' , "Lista desplegableLista desplegable");
define('ttQuesionid' , "ID de la preguntaID de la pregunta");
define('ttQuestionNotes' , "DescripciónDescripción");
define('ttQuestionsend' , "Enviar reporteEnviar reporte");
define('ttQuestionreporting' , "Para reportar más preguntas, debe dejar el campo de identificación en blanco.Para reportar más preguntas, debe dejar el campo de identificación en blanco.");
define('ttRandom' , "AleatorioAleatorio");
define('ttRefresh' , "RefrescarRefrescar");
define('ttRegister' , "RegistroRegistro");
define('ttRegistrations' , "InscripcionesInscripciones");
define('ttRegEnd' , "Cierre de registroCierre de registro");
define('ttRenewPassword' , "Renovar contraseñaRenovar contraseña");
define('ttReset' , "ReiniciarReiniciar");
define('ttResetPassword' , "Restablecer la contraseñaRestablecer la contraseña");
define('ttRole' , "PapelPapel");
define('ttRooms' , "HabitacionesHabitaciones");
define('ttSave' , "SalvarSalvar");
define('ttSaveAnswerInfo' , "Guardar información de respuestaGuardar información de respuesta");
define('ttSaveLanguageFiles' , "Guardar archivos de idiomaGuardar archivos de idioma");
define('ttSaveLanguageXML' , "Guardar archivos de lenguaje XMLGuardar archivos de lenguaje XML");
define('ttSaveQuestionInfo' , "Guardar información de la preguntaGuardar información de la pregunta");
define('ttScore' , "PuntuaciónPuntuación");
define('ttScoreFinal' , "Puntuación finalPuntuación final");
define('ttScoreTest' , "Resultado de la pruebaResultado de la prueba");
define('ttScoreType' , "Tipo de puntajeTipo de puntaje");
define('ttScoreMin' , "Puntaje mínimoPuntaje mínimo");
define('ttSelectSubject' , "Seleccione AsuntoSeleccione Asunto");
define('ttSelectSubjectBefore' , "Seleccione un tema antesSeleccione un tema antes");
define('ttSet' , "ConjuntoConjunto");
define('ttSetPassword' , "Por favor establezca su contraseñaPor favor establezca su contraseña");
define('ttSettings' , "AjustesAjustes");
define('ttShowHide' , "Mostrar ocultarMostrar ocultar");
define('ttSelectSubQuestion' , "Seleccione una subpreguntaSeleccione una subpregunta");
define('ttSkin' , "PielPiel");
define('ttStart' , "comienzocomienzo");
define('ttStarted' , "EmpezadoEmpezado");
define('ttStop' , "DetenerDetener");
define('ttStopped' , "DetenidoDetenido");
define('ttStartTest' , "Prueba de inicioPrueba de inicio");
define('ttStatus' , "EstadoEstado");
define('ttStats' , "EstadísticasEstadísticas");
define('ttStudent' , "EstudianteEstudiante");
define('ttStudents' , "EstudiantesEstudiantes");
define('ttST10' , "DécimosDécimos");
define('ttST30' , "TreintaTreinta");
define('ttST100' , "CentésimoCentésimo");
define('ttSubject' , "TemaTema");
define('ttSubjects' , "AsignaturasAsignaturas");
define('ttSubmit' , "EnviarEnviar");
define('ttSurname' , "ApellidoApellido");
define('ttSystem' , "SistemaSistema");
define('ttSystemConfiguration' , "Configuración del sistemaConfiguración del sistema");
define('ttSbjVers' , "VersiónVersión");
define('ttTeacher' , "ProfesorProfesor");
define('ttTeachers' , "MaestrosMaestros");
define('ttTest' , "PruebaPrueba");
define('ttTests' , "PruebasPruebas");
define('ttTestToCorrect' , "Pruebas para corregirPruebas para corregir");
define('ttText' , "TextoTexto");
define('ttTime' , "HoraHora");
define('ttTimeEnd' , "Fin de tiempoFin de tiempo");
define('ttTimeStart' , "Hora de inicioHora de inicio");
define('ttTimeUsed' , "Tiempo utilizadoTiempo utilizado");
define('ttTimeZone' , "Zona horariaZona horaria");
define('ttTitle' , "TítuloTítulo");
define('ttTopic' , "TemaTema");
define('ttTopics' , "Los temasLos temas");
define('ttTopicsAndQuestions' , "Temas y preguntasTemas y preguntas");
define('ttTopicsQuestions' , "Preguntas por temasPreguntas por temas");
define('ttTranslations' , "TraduccionesTraducciones");
define('ttTrue' , "CiertoCierto");
define('ttType' , "TipoTipo");
define('ttUser' , "UsuarioUsuario");
define('ttUsers' , "UsuariosUsuarios");
define('ttView' , "VerVer");
define('ttWelcome' , "BienvenidoBienvenido");
define('ttWaiting' , "EsperandoEsperando");
define('ttWarning' , "AdvertenciaAdvertencia");
define('ttYes' , "SíSí");
define('ttAssesmentOverview' , "Informe general de evaluaciónInforme general de evaluación");
define('ttDeselectAll' , "Deseleccionar todoDeseleccionar todo");
define('ttErrorUserParameter' , "Seleccione un detalle del participante para continuar!Seleccione un detalle del participante para continuar!");
define('ttQuestionerror' , "ID de la preguntaID de la pregunta");
define('ttRemove' , "retirarretirar");
define('ttReportCoachingError' , "Seleccione una evaluación y un participante para continuar.Seleccione una evaluación y un participante para continuar.");
define('ttReportCoachingError2' , "Seleccione una evaluación para continuarSeleccione una evaluación para continuar");
define('ttReportErrorStudent' , "El alumno seleccionado no participó en las pruebas elegidas.El alumno seleccionado no participó en las pruebas elegidas.");
define('ttReportMainAO' , "PrincipalPrincipal");
define('ttReportTemplateDeleteFailed' , "Eliminación fallidaEliminación fallida");
define('ttReportTemplateDelet' , "Plantilla eliminadaPlantilla eliminada");
define('ttReportTemplateLoaded' , "Plantilla de caricato correttamentePlantilla de caricato correttamente");
define('ttReportTemplateSaveError' , "Inserte un nombre de plantilla sin espacio!Inserte un nombre de plantilla sin espacio!");
define('ttReportTemplateSaved' , "Plantilla guardada correctamentePlantilla guardada correctamente");
define('ttReportTemplateDuplicateError' , "El nombre de la plantilla ya existe!El nombre de la plantilla ya existe!");
define('ttReportScoreFilter' , "Si ya ha seleccionado un participante, ahora vuelva a seleccionar uno nuevoSi ya ha seleccionado un participante, ahora vuelva a seleccionar uno nuevo");
define('ttSelectAll' , "Seleccionar todoSeleccionar todo");
define('ttQTFB' , "Rellenar los espacios en blancoRellenar los espacios en blanco");
define('ttQTFB_TEXT' , "Complete el siguiente texto con las palabras apropiadasComplete el siguiente texto con las palabras apropiadas");
define('ttQTFBDescription' , "En una pregunta para completar los espacios en blanco, el participante debe completar el texto con la respuesta correcta en el campo de textoEn una pregunta para completar los espacios en blanco, el participante debe completar el texto con la respuesta correcta en el campo de texto");
define('ttPosterImageVideo' , "Cargando LogoCargando Logo");
define('ttWidthVideo' , "AnchuraAnchura");
define('ttHeightVideo' , "AlturaAltura");
define('ttIdVideo' , "Código de identificaciónCódigo de identificación");
define('ttVideoTypeVideo' , "Formato de videoFormato de video");
define('ttNumberOfPlaysVideo' , "Número máximo de jugadasNúmero máximo de jugadas");
define('ttToolbarVideo' , "VídeoVídeo");
define('ttDialogTitleVideo' , "Propiedad de videoPropiedad de video");
define('ttFakeObjectVideo' , "VídeoVídeo");
define('ttPropertiesVideo' , "Editar videoEditar video");
define('ttWidthRequiredVideo' , "El ancho debe ser establecidoEl ancho debe ser establecido");
define('ttHeightRequiredVideo' , "La altura debe ser establecidaLa altura debe ser establecida");
define('ttNumberOfPlayRequiredVideo' , "El número máximo de jugadas debe ser establecidoEl número máximo de jugadas debe ser establecido");
define('ttFallbackTemplateVideo' , "Su navegador no soporta video HTML5Su navegador no soporta video HTML5");
define('ttBrowseVideo' , "Buscar servidorBuscar servidor");
define('ttsourceVideo' , "Fuente de videoFuente de video");
define('ttNumberOfPlayAlertVideo' , "Has alcanzado el número máximo de reproducciones de tu video.Has alcanzado el número máximo de reproducciones de tu video.");
define('ttHelpDefault' , "Panel de informacionPanel de informacion");
define('ttHelpDefaultDescription' , "Presiona este botón para obtener una descripción de lo que puedes hacerPresiona este botón para obtener una descripción de lo que puedes hacer");
define('ttHelpQuestion' , "Seleccione una pregunta para leer su contenido, o haga doble clic para editarSeleccione una pregunta para leer su contenido, o haga doble clic para editar");
define('ttHelpADMINNewTeacherDescription' , "Definir la cuenta de un nuevo administrador, profesor o examinador.Definir la cuenta de un nuevo administrador, profesor o examinador.");
define('ttHelpADMINNewStudentDescription' , "Definir la cuenta de un nuevo alumno.Definir la cuenta de un nuevo alumno.");
define('ttHelpADMINSelLanguageDescription' , "Seleccione un idioma para administrarSeleccione un idioma para administrar");
define('ttHelpADMINLanguageDescription' , "Aquí puede cambiar las localizaciones de las palabras utilizadas por el sistema.Aquí puede cambiar las localizaciones de las palabras utilizadas por el sistema.");
define('ttHelpADMINSystemConf' , "Aquí puede cambiar la configuración de EOL, tenga cuidadoAquí puede cambiar la configuración de EOL, tenga cuidado");
define('ttHelpADMINRoom' , "Definir las salas donde se realizarán las pruebas.Definir las salas donde se realizarán las pruebas.");
define('ttHelpADMINImport' , "Esta pantalla le permite importar nuevas preguntas a un signo de interrogación.Esta pantalla le permite importar nuevas preguntas a un signo de interrogación.");
define('ttHelpADMINProfile' , "Esta pantalla te permite editar tu perfil.Esta pantalla te permite editar tu perfil.");
define('ttHelpReportAreport' , "Esta pantalla le permite crear un Areport, es obligatorio seleccionar al menos un temaEsta pantalla le permite crear un Areport, es obligatorio seleccionar al menos un tema");
define('ttHelpReportAreportTemplate' , "Seleccione qué información puede obtener en el InformeSeleccione qué información puede obtener en el Informe");
define('ttHelpReportCreport' , "Esta pantalla le permite crear un Creport, es obligatorio seleccionar un participanteEsta pantalla le permite crear un Creport, es obligatorio seleccionar un participante");
define('ttHelpReportCreportlist' , "Seleccione el examen para crear el informe.Seleccione el examen para crear el informe.");
define('ttHelpStudent' , "A la izquierda están las pruebas disponibles, a la derecha los detalles del examen seleccionadoA la izquierda están las pruebas disponibles, a la derecha los detalles del examen seleccionado");
define('ttHelpStudentTest' , "Estás en la pantalla de examen, responde las preguntas y envía la pruebaEstás en la pantalla de examen, responde las preguntas y envía la prueba");
define('ttHelpAdminErrorQuestion' , "Si encuentra problemas puede informar desde esta página.Si encuentra problemas puede informar desde esta página.");
define('ttHelpExamsCorrect' , "Aquí recibe un examen realizado por un estudiante, verifique que la corrección se haya realizado correctamente y luego confirme la votación.Aquí recibe un examen realizado por un estudiante, verifique que la corrección se haya realizado correctamente y luego confirme la votación.");
define('ttHelpExamsSettings' , "En esta pantalla puede definir o cambiar la configuración para usar en exámenes futuros.En esta pantalla puede definir o cambiar la configuración para usar en exámenes futuros.");
define('ttQTPLDescription' , "El menú desplegable es una pregunta cerrada que permite a los encuestados elegir una opción de respuesta de una lista de opciones presentada en un menú desplegable. Si desea mostrar las opciones de respuesta como botones de opción o casillas de verificación, use la pregunta de opción múltipleEl menú desplegable es una pregunta cerrada que permite a los encuestados elegir una opción de respuesta de una lista de opciones presentada en un menú desplegable. Si desea mostrar las opciones de respuesta como botones de opción o casillas de verificación, use la pregunta de opción múltiple");
define('ttQuestionsubPL' , "Sub-preguntasSub-preguntas");
define('ttHelpLog' , "Un archivo de registro se creará automáticamente después de cambiar una pregunta ya asignada a una prueba.Un archivo de registro se creará automáticamente después de cambiar una pregunta ya asignada a una prueba.");
define('ttErrorSent' , "ACKACK");
define('ttGroup' , "GrupoGrupo");
define('ttSubgroup' , "SubgrupoSubgrupo");
define('ttAOreportSaved' , "Todo el informe generado se guardará en el servidor.Todo el informe generado se guardará en el servidor.");
define('ttReport' , "InformeInforme");
define('ttReportAllFinished' , "Todo terminadoTodo terminado");
define('ttReportAODescription' , "Si no selecciona evaluaciones específicas, todas las evaluaciones serán analizadas.Si no selecciona evaluaciones específicas, todas las evaluaciones serán analizadas.");
define('ttReportAOWelcome' , "Elija una evaluación y use las pestañas del asistente para filtrar los datosElija una evaluación y use las pestañas del asistente para filtrar los datos");
define('ttReportAOSelectAssesment' , "Seleccionar evaluaciones para informarSeleccionar evaluaciones para informar");
define('ttReportAssesmentAuthor' , "Autor de la evaluaciónAutor de la evaluación");
define('ttReportAssessmentInformation' , "Información de evaluaciónInformación de evaluación");
define('ttReportAssesmentID' , "ID de evaluaciónID de evaluación");
define('ttReportAssesmentDateTimeFirst' , "Fecha / hora de la primera tomaFecha / hora de la primera toma");
define('ttReportAssesmentDateTimeLast' , "Fecha / Hora de la última tomaFecha / Hora de la última toma");
define('ttReportAssesmentLeastTimeFinished' , "Menos tiempo para los acabados.Menos tiempo para los acabados.");
define('ttReportAssesmentName' , "Nombre de evaluaciónNombre de evaluación");
define('ttReportAssesmentNumberStarted' , "Num.Num.");
define('ttReportAssesmentNumberNotFinished' , "Num.Num.");
define('ttReportAssesmentNumberFinished' , "Num.Num.");
define('ttReportAssesmentMinscoreFinished' , "Puntuación mínima de los finalizados.Puntuación mínima de los finalizados.");
define('ttReportAssesmentMaxcoreFinished' , "Puntaje máximo de los finalizados.Puntaje máximo de los finalizados.");
define('ttReportAssesmentMediumFinished' , "Puntuación media de los acabados.Puntuación media de los acabados.");
define('ttReportAssesmentMediumTimeFinished' , "Tiempo medio tomado para los acabados.Tiempo medio tomado para los acabados.");
define('ttReportAssesmentMostTimeFinished' , "La mayoría del tiempo tomado para los acabados.La mayoría del tiempo tomado para los acabados.");
define('ttReportAssesmentScore' , "Filtrar por puntaje de evaluacionesFiltrar por puntaje de evaluaciones");
define('ttReportAssesmentStdDeviation' , "Desviación estándar para los acabados.Desviación estándar para los acabados.");
define('ttReportChecked' , "SeleccionadoSeleccionado");
define('ttReportCoaching' , "Informe de CoachingInforme de Coaching");
define('ttReportCWelcome' , "Elige una valoración y un participante.Elige una valoración y un participante.");
define('ttReportCDescription' , "Tienes que filtrar los datos por fechas y, si quieres, también por puntuaciónTienes que filtrar los datos por fechas y, si quieres, también por puntuación");
define('ttReportCoachingDescription' , "Vea los resultados detallados para un participante que toma una evaluaciónVea los resultados detallados para un participante que toma una evaluación");
define('ttReportCoachingInformation' , "Seleccione una prueba para ver información detalladaSeleccione una prueba para ver información detallada");
define('ttReportCustomize' , "Personaliza tu informePersonaliza tu informe");
define('ttReportDateInterval' , "Intervalo de fechasIntervalo de fechas");
define('ttReportDateFrom' , "DesdeDesde");
define('ttReportDateTaken' , "Fecha que se tendráFecha que se tendrá");
define('ttReportDateTo' , "aa");
define('ttReportErrorDetail' , "Por favor seleccione un participante para mostrar detallesPor favor seleccione un participante para mostrar detalles");
define('ttReportField' , "Nombre del campoNombre del campo");
define('ttReportGraphicalDsiplays' , "Pantallas gráficasPantallas gráficas");
define('ttReportGraphicHistogram' , "Histograma de puntajes de evaluación.Histograma de puntajes de evaluación.");
define('ttReportGraphicTopicScore' , "Histograma de las puntuaciones del temaHistograma de las puntuaciones del tema");
define('ttReportGroup' , "Los gruposLos grupos");
define('ttReportGroupNotPresent' , "No hay gruposNo hay grupos");
define('ttReportMainAO' , "Main");
define('ttReportMinimumScore' , "Filtrar por puntuación mínimaFiltrar por puntuación mínima");
define('ttReportMaximumScore' , "Filtrar por puntuación máximaFiltrar por puntuación máxima");
define('ttReportNotFilter' , "No utilizar filtroNo utilizar filtro");
define('ttReportOrder' , "OrdenOrden");
define('ttReportPartecipants' , "ParticipantesParticipantes");
define('ttReportPartecipant' , "PartícipePartícipe");
define('ttReportScheduled' , "ProgramarProgramar");
define('ttReportScoreBand' , "Filtrar por banda de puntuaciónFiltrar por banda de puntuación");
define('ttReportSearch' , "Buscar...Buscar...");
define('ttReportSearched' , "Resultado de búsquedaResultado de búsqueda");
define('ttReportSelectDetail' , "Seleccione la identificación de usuario o correo electrónico del participante seleccionado antesSeleccione la identificación de usuario o correo electrónico del participante seleccionado antes");
define('ttReportSelectFilter' , "Seleccionar filtroSeleccionar filtro");
define('ttReportSelectGroup' , "Seleccionar grupos filtrar enSeleccionar grupos filtrar en");
define('ttReportSelectLetter' , "CartaCarta");
define('ttReportAOSelectPartecipant' , "Seleccionar participanteSeleccionar participante");
define('ttReportSelected' , "Evaluaciones seleccionadasEvaluaciones seleccionadas");
define('ttReportSelectTemplate' , "Seleccione una plantillaSeleccione una plantilla");
define('ttReportSelectedGroup' , "Grupos seleccionadosGrupos seleccionados");
define('ttReportSearchByLetter' , "Buscar por letraBuscar por letra");
define('ttReportStudent' , "Filtrar en participanteFiltrar en participante");
define('ttReportStudentNotPresent' , "No hay estudiantesNo hay estudiantes");
define('ttReportStudentDetail' , "Filtrar en detalle de participanteFiltrar en detalle de participante");
define('ttReportTemplateLoad' , "Seleccione una plantilla para cargarSeleccione una plantilla para cargar");
define('ttReportTemplateSave' , "Guardar plantilla comoGuardar plantilla como");
define('ttReportTemplateName' , "Insertar nombreInsertar nombre");
define('ttReportTimedOut' , "DesconectadoDesconectado");
define('ttReportTopicAverageScore' , "Puntuación mediaPuntuación media");
define('ttReportTopicInformation' , "Información del temaInformación del tema");
define('ttReportTopicMaximumScore' , "Puntuación máximaPuntuación máxima");
define('ttReportTopicMinimumScore' , "Puntaje mínimoPuntaje mínimo");
define('ttReportTopicName' , "Nombre del temaNombre del tema");
define('ttReportTopicStandardDeviation' , "Desviación estándarDesviación estándar");
define('ttReportTyping' , "Buscar escribiendoBuscar escribiendo");
define('ttReportQuestionType' , "Tipo de preguntaTipo de pregunta");
define('ttReportViewer' , "Visor de informesVisor de informes");
define('ttReportViewerDescription' , "Ver todos los informes generados y gestionarlosVer todos los informes generados y gestionarlos");
define('ttStudentDetailCreport' , "Detalle del estudianteDetalle del estudiante");
define('ttErrorquestion' , "Reporting incorrect question");
define('ttHelpReportAreport' , "This screen allows you to create an Areport, it is obligatory to select at least one subject");
define('ttHelpReportAreportTemplate' , "Select what information you can get in the Report");
define('ttHelpReportCreport' , "This screen allows you to create a Creport, it is obligatory to select a participant");
define('ttHelpReportCreportlist' , "Select the exam to create the Report");
define('ttCertificates' , "CertificadosCertificados");
define('ttCertificate' , "CertificadoCertificado");
define('ttNewGroup' , "Añadir grupoAñadir grupo");
define('ttEditGroup' , "Editar grupoEditar grupo");
define('ttEditTeacher' , "Profesor de ediciónProfesor de edición");
define('ttEditStudent' , "Editar estudianteEditar estudiante");
define('tteTeacher' , "ExaminadorExaminador");
define('tttotals' , "TotalTotal");
define('ttD1s' , "FácilFácil");
define('ttD2s' , "MedioMedio");
define('ttD3s' , "DifícilDifícil");
define('ttSelectStudent' , "Lista de estudiantesLista de estudiantes");
define('ttSelectTeacher' , "Lista de profesoresLista de profesores");
define('ttCoord' , "CoordenadasCoordenadas");
define('ttHelpLog' , "A Log file will be automatically created after changing a question already assigned to a test. Move the mouse on a question's id to see its history");
define('ttHelpExams' , "La lista de exámenes se muestra aquí.La lista de exámenes se muestra aquí.");
define('ttHelpSubject' , "Aquí podrás ver una lista de los cursos que estás impartiendo.Aquí podrás ver una lista de los cursos que estás impartiendo.");
define('ttNotAvailable' , "La configuración seleccionada no le permite generar una prueba.La configuración seleccionada no le permite generar una prueba.");
define('ttSelectGroup' , "Editar grupos o subgruposEditar grupos o subgrupos");
define('ttConfirmProcedure' , "¿Realmente quieres hacer esto?¿Realmente quieres hacer esto?");
define('ttUserDeleted' , "Usuario eliminado correctamenteUsuario eliminado correctamente");
define('ttMGroupCreated' , "Grupo creado exitosamenteGrupo creado exitosamente");
define('ttMSubgroupCreated' , "Subgrupo creado exitosamenteSubgrupo creado exitosamente");
define('ttNewSubgroup' , "Añadir subgrupoAñadir subgrupo");
define('ttErrorTopic' , "Demasiadas preguntas de tema seleccionadasDemasiadas preguntas de tema seleccionadas");
define('ttAvailable' , "preguntas disponibles depreguntas disponibles de");
define('ttThereAreNot' , "No hayNo hay");
define('ttErrorMax' , "Este campo no puede ser menor que el número de preguntas obligatorias seleccionadasEste campo no puede ser menor que el número de preguntas obligatorias seleccionadas");
define('ttField' , "El campoEl campo");
define('ttHard' , "DifícilDifícil");
define('ttMedium' , "MedioMedio");
define('ttEasy' , "FácilFácil");
define('ttMustBeaNumber' , "Tiene que ser un númeroTiene que ser un número");
define('ttMaxHardReached' , "Número máximo de preguntas difíciles ya alcanzadasNúmero máximo de preguntas difíciles ya alcanzadas");
define('ttMaxMediumReached' , "Número máximo de preguntas medianas ya alcanzadasNúmero máximo de preguntas medianas ya alcanzadas");
define('ttMaxEasyReached' , "Número máximo de preguntas fáciles ya alcanzadasNúmero máximo de preguntas fáciles ya alcanzadas");
define('ttMSubgroupCreated' , "Sottogruppo creato correttamente");
define('ttTeacherSubmitStudentExam' , "Si hace clic en el botón Sí, el examen del estudiante se entregará automáticamente al sistema en su estado actual.Si hace clic en el botón Sí, el examen del estudiante se entregará automáticamente al sistema en su estado actual.");
define('ttProfCert' , "Certificado de CompetenciaCertificado de Competencia");
define('ttCertify' , "Esto es para certificar queEsto es para certificar que");
define('ttSuccess' , "ha pasado con éxitoha pasado con éxito");
define('ttEvaluation' , "con evaluacioncon evaluacion");
define('ttAccreditedTestSite' , "en el Sitio de Prueba Acreditado de laen el Sitio de Prueba Acreditado de la");
define('ttOn' , "enen");
define('ttNumQuestionsTopic' , "Número de preguntas para cada tema.Número de preguntas para cada tema.");
define('ttParamNotSet' , "Parámetros faltantesParámetros faltantes");
define('ttNotEnoughQuestions' , "No hay suficientes preguntasNo hay suficientes preguntas");
define('ttExamArchivedCertNot' , "El examen está archivado pero no se han generado certificados.El examen está archivado pero no se han generado certificados.");
define('ttSendCertificate' , "Descargar certificadoDescargar certificado");
define('ttCertificateAlert' , "¿Está seguro de que desea generar y descargar el certificado de examen para el estudiante?¿Está seguro de que desea generar y descargar el certificado de examen para el estudiante?");
define('ttCertificateScore' , "El alumno no tiene la puntuación mínima para recibir un certificado.El alumno no tiene la puntuación mínima para recibir un certificado.");
define('ttCertificateGenerated' , "El certificado fue generado correctamente.El certificado fue generado correctamente.");
define('ttBut' , "peropero");
define('ttAnd' , "yy");
define('ttCertificateEmailSended' , "el correo electrónico fue enviado con éxitoel correo electrónico fue enviado con éxito");
define('ttCertificateGeneratedProblem' , "El certificado no fue generado!El certificado no fue generado!");
define('ttCertificatePoint' , "El puntaje del estudiante es demasiado bajo y no se puede emitir un certificado.El puntaje del estudiante es demasiado bajo y no se puede emitir un certificado.");
define('ttPrivacy1' , "Leo y acepto elLeo y acepto el");
define('ttPrivacy2' , "Política de privacidad de ECTNPolítica de privacidad de ECTN");
define('ttPrivacy3' , "Deseo ser informado sobre la posibilidad de obtener un Certificado de Competencia IndividualDeseo ser informado sobre la posibilidad de obtener un Certificado de Competencia Individual");
